Filetype refactoring
kaist-cp/rv6 pull request #211
Opened 2020-09-14 11:38 UTC by kimjungwow

코멘트 작성 후 ping 드리겠습니다.

2020-09-14 11:40 UTC, kimjungwow commented on kernel-rs/src/file.rs
>      pub readable: bool,
struct File의 **read/writable**를 2개의 bool대신 bitflags을 이용할까요?

2020-09-14 11:40 UTC, kimjungwow commented on kernel-rs/src/file.rs
>      pub unsafe fn stat(&mut self, addr: usize) -> i32 {
`stat()`는 `sys_fstat()`에서만 참조되며, syscall은 usize를 리턴하는 방식입니다. 따라서 `stat()`은 0 혹은 -1을 리턴하는 함수이지만, 리턴 타입을 Result로 바꾸지 않고 i32로 유지했습니다.

2020-09-14 11:40 UTC, kimjungwow commented on kernel-rs/src/file.rs
> +        match &mut self.typ {
self.typ에 대하여 match를 사용할 때, self.typ 내부 value를 바꾸는 경우 &mut self.typ을 사용합니다. `write()`의 match도 같습니다.

2020-09-14 11:40 UTC, kimjungwow commented
@efenniht ping

2020-09-14 13:53 UTC, coolofficials commented on kernel-rs/src/file.rs
>      pub readable: bool,
bitflag를 사용해서 두가지 status를 하나로 합친다는 의미시군요? 큰 차이가 없을 것 같은데 개인적으로는 bool이 더 읽기 편합니다.. 혹시 바꾸는 것의 장점이 무엇이 더 있나요?

2020-09-15 01:51 UTC, kimjungwow commented on kernel-rs/src/file.rs
>      pub readable: bool,
@coolofficials UNIX가 동작하는 방식 (파일의 permission을 다루는 방식)과 유사하게 만들기 위함입니다. `elf.rs`와 `fcntl.rs`에서 bitflags를 사용하는 것과 같은 맥락으로 이해하시면 될 것 같습니다

2020-09-15 03:59 UTC, coolofficials commented on kernel-rs/src/file.rs
>      pub readable: bool,
@kimjungwow UNIX-like 하게 하는 목적이라면 저는 괜찮을 것 같습니다.

2020-09-15 15:11 UTC, efenniht requested changes
고생하셨습니다 :clap: 몇 가지 수정 부탁드립니다.

2020-09-15 15:11 UTC, efenniht commented on kernel-rs/src/file.rs
> +                while i < n {
무조건 `bytes_to_write` 만큼 읽는 것이 확실하므로,
```suggestion
                for i in (0..n).step_by(max) {
```
이런 식으로 functional 하게 작성할 수 있을 듯 해요. 그리고 `i`에 좀 더 설명적인 이름을 붙여주시기를 부탁드립니다.

2020-09-15 15:11 UTC, efenniht commented on kernel-rs/src/file.rs
> +                Filetype::PIPE { mut pipe } => pipe.close(self.writable),
이제 drop 을 통해 `File` 이 죽는 시점을 lexical하게 아니까, `AllocatedPipe::close` 가 by-value 로 `self` 를 받을 수 있도록 바꿀 수 있을 것 같습니다.

2020-09-15 15:11 UTC, efenniht commented on kernel-rs/src/file.rs
> +}
다른 파일도 그러네요...

2020-09-15 16:54 UTC, kimjungwow commented on kernel-rs/src/console.rs
> +const CONSOLE: usize = 1;
https://github.com/kaist-cp/rv6/pull/211/commits/334207580696637bfc48b27043fbeabdf15e1c6f

2020-09-15 16:55 UTC, kimjungwow commented on kernel-rs/src/file.rs
> +}
https://github.com/kaist-cp/rv6/pull/211/commits/202f23575ba049c9d824dcdac52dd7121f183064

2020-09-15 17:17 UTC, kimjungwow commented on kernel-rs/src/file.rs
>  pub struct File {
1. https://github.com/kaist-cp/rv6/pull/211/commits/f206ec5fa84153cb9fcf7e752c60057a1e62e0c6

2020-09-15 17:17 UTC, kimjungwow commented on kernel-rs/src/file.rs
> -#[derive(Copy, Clone, PartialEq)]
https://github.com/kaist-cp/rv6/pull/211/commits/b20a1f360ba7668888f952a168ae4252cf064710

2020-09-15 17:19 UTC, kimjungwow commented on kernel-rs/src/file.rs
>  pub enum Filetype {
1. convention : https://github.com/kaist-cp/rv6/pull/211/commits/95fb56d25f3fda257193badccd156a92329d0abe
2. `None`은 `File::zeroed()`로 File을 만들 때 사용되며, `File::zeroed()`는 `RcFile::alloc()`에서 호출됩니다. `RcFile::alloc()`에서 어떤 타입으로 파일을 alloc할지 인자를 통해 전달하면 `None`을 없앨 수 있습니다.

2020-09-15 17:19 UTC, kimjungwow commented on kernel-rs/src/file.rs
> +                        break;
https://github.com/kaist-cp/rv6/pull/211/commits/6c4fdf12f5246dd461a51679adcb60caf421486a

2020-09-16 06:30 UTC, efenniht commented on kernel-rs/src/console.rs
> +const CONSOLE: usize = 1;
앗... 제 말씀은 여기서의 1은 특별한 값이 const 로 선언하되, DEVSW 에서의 index 이므로 이에 맞게 이름을 지어야 한다는 뜻이었습니다.

2020-09-16 06:31 UTC, efenniht commented on kernel-rs/src/file.rs
>  pub enum Filetype {
그렇다면 `RcFile::alloc()` 이 `File` 값을 받아야 하겠네요. 그렇게 수정할 수 있을까요?

2020-09-16 10:16 UTC, kimjungwow commented on kernel-rs/src/file.rs
> +        match &mut self.typ {
@efenniht 

FileType이 Inode인 경우에만 Inode의 lock으로 보호하는 것 아닌가요? `read, write`는 Inode에 대해서만 lock을 쥐고 `off` 필드를 변경하고, `stat`에서는 Inode의 lock을 쥐지만 수정은 하지 않는 것으로 보입니다. 혹시 `match &mut self.typ`를 사용하는 것이 좋지 않은 방법인가요?

2020-09-16 11:43 UTC, kimjungwow commented on kernel-rs/src/console.rs
> +const CONSOLE: usize = 1;
https://github.com/kaist-cp/rv6/pull/211/commits/2eeaf5f313c60790094b576417fde5eeb34a031e

2020-09-16 18:47 UTC, kimjungwow commented on kernel-rs/src/file.rs
> +                while i < n {
https://github.com/kaist-cp/rv6/pull/211/commits/192e38cb7911c76b3ac036b92e91b4016e075769

2020-09-16 18:48 UTC, kimjungwow commented on kernel-rs/src/file.rs
>  pub struct File {
2. https://github.com/kaist-cp/rv6/pull/211/commits/ea45f618f57a78977581019aa79a655d2506597d https://github.com/kaist-cp/rv6/pull/211/commits/f47defc29c2d9b44a5e9832450c161240174a174 https://github.com/kaist-cp/rv6/pull/211/commits/5f0f81a944f5cf7b981faa38c90798c934c235ff

2020-09-16 19:13 UTC, kimjungwow commented on kernel-rs/src/file.rs
>  pub struct File {
2 https://github.com/kaist-cp/rv6/pull/211/commits/8383b4b749f0549722018ce1ee2a257f2de60213

2020-09-16 19:13 UTC, kimjungwow commented on kernel-rs/src/file.rs
>  pub enum Filetype {
https://github.com/kaist-cp/rv6/pull/211/commits/8383b4b749f0549722018ce1ee2a257f2de60213

2020-09-17 04:57 UTC, efenniht commented on kernel-rs/src/file.rs
> +        match &mut self.typ {
- `match &mut self.typ` 이 잘못되었다기 보다는 `read`, `write`, `stat` 함수가 `&mut self` 를 받는 게 실제 의미와 다르다는 뜻입니다. `&mut self` 는 `File` 에 대한 접근을 할 때 다른 스레드에서는 `File` 에 접근할 수 없다는 뜻인데, `File` 자체에 걸린 락이 없어서 그렇게 되지는 않습니다.
 - 그럼에도 불구하고 `&self` 로 바꿀 수 없는 이유는, 말씀하신 대로 `off` 이 `Inode` 의 락에 의해 보호되어 있는 중에 수정되기 때문입니다. 이게 굉장히 tricky 한데 `off` 는 file 별로 있는 field 이고 여러 개의 파일이 동시에 한 inode를 가리킬 수 있어서 `off` 를 inode 에 집어넣을 수 없습니다. 그렇다고 락을 file에서 들고 있을 수도 없구요. :thinking: 어떻게 리팩토링하는 게 좋을까요? @jeehoonkang

2020-09-17 04:59 UTC, efenniht commented on kernel-rs/src/pipe.rs
> +        .ok_or(())?;
이렇게 하면 `RcFile::alloc` 이 실패했을 때 `Pipe` 를 할당한 메모리가 leak 되지 않을까요?

2020-09-17 06:45 UTC, kimjungwow commented on kernel-rs/src/pipe.rs
> +        .ok_or(())?;
https://github.com/kaist-cp/rv6/pull/211/commits/72c85898b869960efdfd6346e672438a5dbc806a

이 수정이 f0과 f1 모두 alloc이 실패한 경우도 잘 다룬다고 생각합니다.

2020-09-17 07:29 UTC, kimjungwow commented on kernel-rs/src/file.rs
> +                Filetype::PIPE { mut pipe } => pipe.close(self.writable),
https://github.com/kaist-cp/rv6/pull/211/commits/e9a4a208960eccf7c94e4ca9ad61d6bab89b671e

2020-09-17 07:29 UTC, kimjungwow commented on kernel-rs/src/file.rs
> +                if *major < 0 || *major as usize >= NDEV || DEVSW[*major as usize].write.is_none() {
https://github.com/kaist-cp/rv6/pull/211/commits/c896704074536bff813f5e2f3d4f93766f875e5e

2020-09-17 07:30 UTC, kimjungwow commented on kernel-rs/src/file.rs
> +                if *major < 0 || *major as usize >= NDEV || DEVSW[*major as usize].read.is_none() {
https://github.com/kaist-cp/rv6/pull/211/commits/c896704074536bff813f5e2f3d4f93766f875e5e

2020-09-17 07:32 UTC, kimjungwow commented on kernel-rs/src/file.rs
>      pub unsafe fn stat(&mut self, addr: usize) -> i32 {
https://github.com/kaist-cp/rv6/pull/211/commits/6c362710f2d417b489cf961ac4ed85ac69e70bcf

2020-09-17 07:45 UTC, kimjungwow commented on kernel-rs/src/file.rs
> +                if *major < 0 || *major as usize >= NDEV || DEVSW[*major as usize].read.is_none() {
Inode와 DInode의 major/minor도 u16으로 변경해서, 위 주석의 위치를 바꿨습니다. https://github.com/kaist-cp/rv6/pull/211/commits/8c73e6623bae2bae3a5ce452a07ee038b2f9818f

2020-09-17 08:59 UTC, kimjungwow commented
@efenniht 
https://github.com/kaist-cp/rv6/pull/211#discussion_r489970751 빼고 다 수정하였습니다. 이상이 없다면 코멘트는 새 이슈로 남기고 다음 PR에서 다뤄도 좋겠습니다 :)

2020-09-17 10:53 UTC, efenniht requested changes

2020-09-17 10:53 UTC, efenniht commented on kernel-rs/src/fs.rs
> +    major: u16,
`Dinode` 는 disk 에 저장되는 inode entry 이므로, 여기를 수정하면 disk 를 만드는 `mkfs` 코드도 unsigned integer 를 사용하도록 고쳐야 합니다.

2020-09-17 10:53 UTC, efenniht commented on kernel-rs/src/pipe.rs
> +        .or_else(|| {
`ok_or_else` 로 합쳐서 쓸 수 있습니다.

2020-09-17 10:53 UTC, efenniht commented on kernel-rs/src/pipe.rs
> +            drop(&f0);
- `drop(&f0)` 는 아무 일도 안 일어납니다.
 - `drop(f0)` 로 바꾸면 되는데, 어차피 `f0` 는 return 할 때 저절로 drop 되므로 굳이 작성하지 않아도 됩니다.
 - 그리고 여기서 `drop(f0)` 를 하면, 이미 `kfree` 로 `Pipe` 의 메모리가 해제된 상태에서, `f0` 의 destructor `File::drop` 이 호출되고, 거기서 `AllocatedPipe::close` 를 호출하므로 use-after-free 가 발생합니다. :boom:
 - 이걸 깔끔하게 해결하려면 file과 pipe 의 메모리 allocation을 가장 위에서 다 해치우고, 실제 값을 allocation 에 write 하는 작업을 뒤에서 몰아서 하는 건데요. 그러려면 uninitialized allocation 을 타입으로 나타내야 하겠습니다.
 - 그런데 이건 지금 PR 을 벗어나는 이야기인 것 같습니다. 결론은, 죄송합니다만, :sob: 원래 구현으로 돌아가서 `RcFile::alloc` 에서는 `FileType::None` 으로 값을 초기화하고, `File::init` 같은 걸 만들어서 이걸로 초기화하도록 합시다. ㅠㅠ

2020-09-17 10:53 UTC, efenniht commented on kernel-rs/src/pipe.rs
> +    unsafe fn try_write(&mut self, addr: usize, n: u32) -> Result<usize, ()> {
어차피 `sys_write`에서 변환을 하니까 `n` 도 `usize`가 되는 게 맞을까요? 인자는 `u32` 인데 return은 `usize` 라서 두 타입을 맞춰주는 게 좋을 것 같습니다.

2020-09-17 10:53 UTC, efenniht commented on kernel-rs/src/sysfile.rs
> +    let f = if (*ip).typ as i32 == T_DEVICE {
이 if 문에서 리턴하는 값에 공통된 부분이 많습니다. 하나로 묶는 게 좋겠습니다.

2020-09-17 10:53 UTC, efenniht commented on kernel-rs/src/sysfile.rs
> +    let minor = u16::try_from(ok_or!(argint(2), return usize::MAX)).unwrap_or(NDEV as u16);
major 랑 minor 는 그냥 `as` 로 convert하는 게 맞는 것 같습니다.
 - 음수였던 값이 overflow 되어서 아주 큰 양수가 된다고 해도, DEVSW를 접근할 수 있는 index가 되는 것은 아닙니다.
 - 그리고 이 값은 Dinode 의 field 에 저장되므로, disk 로 저장되어 외부에서 읽을 수 있습니다. 현실적으로 xv6 disk를 다른 곳에서 읽을 이유가 없긴 하지만, 그래도 semantics를 지키기 위해서 값을 그대로 가져가는 것이 좋겠습니다.

2020-09-17 10:53 UTC, efenniht commented on kernel-rs/src/file.rs
> +    pub unsafe fn stat(&mut self, addr: usize) -> Result<usize, ()> {
이 함수는 성공했을 때 리턴하는 값이 하나이므로 리턴 타입은 `Result<(), ()>` 로 하는 게 더 좋아 보입니다.

2020-09-17 10:55 UTC, efenniht commented
@kimjungwow ping

2020-09-19 13:51 UTC, kimjungwow commented on kernel-rs/src/file.rs
> +    pub unsafe fn stat(&mut self, addr: usize) -> Result<usize, ()> {
https://github.com/kaist-cp/rv6/pull/211/commits/65a17ce241e6b42f015f22e2e8c7e298ce9c61fc

2020-09-19 13:51 UTC, kimjungwow commented on kernel-rs/src/console.rs
> +        let fresh2 = &mut (*DEVSW.as_mut_ptr().add(CONSOLE_IN_DEVSW)).read;
https://github.com/kaist-cp/rv6/pull/211/commits/cd4bd3c2e77b8229ee16bfe33c6f745e759c2d7a

2020-09-19 15:29 UTC, kimjungwow commented on kernel-rs/src/sysfile.rs
> +    let minor = u16::try_from(ok_or!(argint(2), return usize::MAX)).unwrap_or(NDEV as u16);
https://github.com/kaist-cp/rv6/pull/211/commits/c7be213a9a6ede9614911806398189cf376caebf

2020-09-19 16:16 UTC, kimjungwow commented on kernel-rs/src/sysfile.rs
> +    let f = if (*ip).typ as i32 == T_DEVICE {
우선 정확히 아래와 같은 if문들을 합쳤습니다. https://github.com/kaist-cp/rv6/pull/211/commits/5d886963b2e146f82febba3b5173819f7f99b6fe
```Rust
(*ip).unlockput();
end_op();
return usize::MAX;
```

2020-09-19 18:20 UTC, kimjungwow commented on kernel-rs/src/pipe.rs
> +    unsafe fn try_write(&mut self, addr: usize, n: u32) -> Result<usize, ()> {
https://github.com/kaist-cp/rv6/pull/211/commits/fe7cb8808544a788f9dcf4066f85bddca730ba0b

2020-09-19 18:20 UTC, kimjungwow commented on kernel-rs/src/pipe.rs
> +            drop(&f0);
https://github.com/kaist-cp/rv6/pull/211/commits/6c27e1930548a707ef1330e50b21b2fda1b0fd33

2020-09-19 18:20 UTC, kimjungwow commented on kernel-rs/src/pipe.rs
> +        .or_else(|| {
https://github.com/kaist-cp/rv6/pull/211/commits/6c27e1930548a707ef1330e50b21b2fda1b0fd33 수정 후 해당사항 없습니다

2020-09-19 18:23 UTC, kimjungwow commented on kernel-rs/src/fs.rs
> +    major: u16,
`mkfs` 코드를 확인하는 것은 별도의 이슈로 다루면 좋겠습니다. Dinode의 minor/major는 i16으로 다시 수정하고, 이슈 개설하겠습니다.

2020-09-19 18:25 UTC, kimjungwow commented on kernel-rs/src/fs.rs
> +    major: u16,
#216

2020-09-19 18:26 UTC, kimjungwow commented on kernel-rs/src/fs.rs
> +    major: u16,
https://github.com/kaist-cp/rv6/pull/211/commits/c752be73eefa3a0574bedf9024b4ba110a0a88f1

2020-09-19 18:28 UTC, kimjungwow commented
@efenniht 리뷰 감사드립니다! ping

2020-09-20 09:50 UTC, efenniht requested changes
고생하셨습니다... 거의 다 왔습니다!

2020-09-20 09:50 UTC, efenniht commented on kernel-rs/src/pipe.rs
> +    pub unsafe fn close(self, writable: bool) {
- 의미를 생각했을 때, 이 함수는 `self` 를 받는 게 맞습니다. close 이후의 pipe는 접근할 수 없어야 합니다.
 - 그러나 그 경우 File 의 drop 에서 호출하기가 애매하네요. (drop 은 `&mut self` 를 받으므로) 지금은 `AllocatedPipe` 가 `Copy` 이어서 되고 있습니다.
 - 제 생각에는 `AllocatedPipe` 가 `Copy` 인 것이 더 시급히 고쳐야 할 (더 실수하기 쉬운) 부분인 것 같습니다. 왜냐면, `close` 는 unsafe 이어서 프로그래머가 고민하고 쓸 수 있지만, `Copy` 는 safe Rust 에서도 부를 수 있기 때문입니다.

그래서 `close` 는 아직은 `&mut self` 를 받도록 하되 `AllocatedPipe` 에서 `#[derive(Copy, Clone)]` 을 제거해야 할 것 같습니다.

2020-09-20 09:50 UTC, efenniht commented on kernel-rs/src/pipe.rs
> +        let mut f0 = RcFile::alloc(true, false).ok_or_else(|| {
Rust에서 아무 것도 리턴하지 않는 것은 `()` 를 리턴하는 것과 같습니다. `kfree` 가 그런 함수이므로,
```suggestion
        let mut f0 = RcFile::alloc(true, false).ok_or_else(|| kfree(ptr as _))?;
```

2020-09-20 09:50 UTC, efenniht commented on kernel-rs/src/sysfile.rs
> +    (*f).stat(st).map_or_else(|_| usize::MAX, |_| 0)
- Closure 안에 있는 게 cost 가 있는 연산이 아니므로, `map_or` 를 쓰는 게 더 깔끔하게 보입니다.
 - 그런데 `map_or` 는 error 가 첫 번째 인자로 오네요.. 위의 문장과 순서가 달라 실수하기 쉬우므로, 다음처럼 하는 게 좋겠습니다:
```suggestion
    ok_or!((*f).stat(st), return usize::MAX);
    0
```

2020-09-20 09:50 UTC, efenniht commented on kernel-rs/src/sysfile.rs
> +    if (!omode.contains(FcntlFlags::O_CREATE)
- https://github.com/kaist-cp/rv6/pull/211#discussion_r490138570 이 comment 에서 제 의도는 `File` 의 readable & writable field 와 `RcFile::alloc(File::new(...))` call 이 중복되었다는 것이었습니다. 
 - 이렇게 return point를 묶으면 실패하는 이유와 프로그래머의 의도를 파악하기 힘드므로 `(*ip).unlockput(); end_op(); return usize::MAX;` 는 중복되더라도 원래대로 두는 것이 좋겠습니다.
 - 이러한 중복은 scopeguard 를 쓰거나 Drop 에서 이 작업을 해주는 다른 타입을 만들어서 해결해야 하는데, 그것은 이 PR 의 scope 을 벗어납니다.

2020-09-21 02:08 UTC, efenniht commented on kernel-rs/src/file.rs
> +        match &mut self.typ {
이 PR 에서는 일단 File 의 메소드가 `&mut self` 를 받도록 합시다. 이 문제는 #218 에 남겨두었습니다.

2020-09-22 07:29 UTC, kimjungwow commented on kernel-rs/src/file.rs
> +                    Some(dev.read.expect("non-null function pointer")(1, addr, n) as usize)
https://github.com/kaist-cp/rv6/pull/211/commits/f34dba2fd3677874bb25423d5915364eceb1756b

2020-09-22 07:29 UTC, kimjungwow commented on kernel-rs/src/pipe.rs
> +        let mut f0 = RcFile::alloc(true, false).ok_or_else(|| {
https://github.com/kaist-cp/rv6/pull/211/commits/012fc469f533ba8197c5ecb8e58c47035701d442

2020-09-22 07:29 UTC, kimjungwow commented on kernel-rs/src/sysfile.rs
> +    (*f).stat(st).map_or_else(|_| usize::MAX, |_| 0)
https://github.com/kaist-cp/rv6/pull/211/commits/ad6dc6bc031da3c43079506f566b1bfe0c38ee5a

2020-09-22 08:01 UTC, kimjungwow commented on kernel-rs/src/pipe.rs
> +    pub unsafe fn close(self, writable: bool) {
말씀하신대로 `AllocatedPipe`의 `close`는 `File`의 `drop`에서 호출하는데, `AllocatedPipe`의 `close`가 `&self`가 아닌 `&mut self`를 받아야하는 이유가 있나요? `Pipe`의 `close`도 현재 `&self`를 사용합니다.

2020-09-22 08:25 UTC, kimjungwow commented on kernel-rs/src/sysfile.rs
> +    if (!omode.contains(FcntlFlags::O_CREATE)
1. https://github.com/kaist-cp/rv6/blob/8c73e6623bae2bae3a5ce452a07ee038b2f9818f/kernel-rs/src/sysfile.rs 이전 코드의 290번째 줄에서, `(*ip.typ)`가 Device냐 Inode냐에 따라 if문이 나뉘는데 그 안에 중복된 내용이 많다는 말씀이었군요.. 지금은 `RcFile::alloc`이 readable & writable field를 받고, typ필드는 밑에서 따로 채워주기 때문에 말씀하신 중복은 해결된 것으로 보입니다! :)
2. https://github.com/kaist-cp/rv6/pull/211/commits/cb1d03cbedacd2a03ef7bdedaf4c1bea97b31e5e return point를 다시 원래대로 나눴습니다.
3. 중복 제거 : #220 이슈 만들엇습니다.

2020-09-22 08:25 UTC, efenniht commented on kernel-rs/src/pipe.rs
> +    pub unsafe fn close(self, writable: bool) {
- `Pipe::close` 는 내부적으로 lock 을 걸기 때문에 `&self` 를 받아도 됩니다.
 - `AllocatedPipe::close` 는 `Pipe::close` 를 호출하는 것 + 추가로 내부 `ptr` 을 필요한 경우 `kfree` 하는 것 두 가지 일을 합니다. 따라서 `AllocatedPipe` 의 shared reference 가 두 개 이상 존재하고 있으면 double free 나 use-after-free 가 발생할 수 있습니다.
 - 물론 `&mut self` 를 받아도 이 문제를 완전히 해결할 수는 없습니다 (close 를 호출하고 나서 다시 빌리면 되므로.) 또한 `unsafe` 이므로 안전성 체크는 프로그래머가 어차피 해야 합니다.
 - 하지만 최선의 방법 (`self` 를 받아서 safe하게 만드는 것) 이 아니어도 이 방법은 프로그래머가 덜 실수하도록 만들 수 있습니다. ([`ManuallyDrop::drop`](https://doc.rust-lang.org/stable/std/mem/struct.ManuallyDrop.html#method.drop) 이 unsafe 이지만 `&mut self` 를 받는 것과 비슷합니다.)

2020-09-22 08:33 UTC, kimjungwow commented on kernel-rs/src/pipe.rs
> +    pub unsafe fn close(self, writable: bool) {
설명 감사합니다! https://github.com/kaist-cp/rv6/pull/211/commits/2e4eac5e8552bbb7d86b75e604f3da4264586ff2

2020-09-22 08:33 UTC, kimjungwow commented
@efenniht ping

2020-09-22 08:43 UTC, efenniht commented
제가 테스트해보니까 부팅 중에 panic 이 일어나는 데 @kimjungwow 님은 어떠신가요?

2020-09-22 08:48 UTC, kimjungwow commented
> 제가 테스트해보니까 부팅 중에 panic 이 일어나는 데 @kimjungwow 님은 어떠신가요?

저는 잘 부팅됩니다.. 제가 기존에 수정하던 디렉토리 외에도, gibhub cli와 스크립트를 각각 이용하여 이 PR의 코드를 받은 뒤 둘 다 확인했는데 잘 부팅됩니다.. @efenniht

2020-09-22 08:53 UTC, efenniht commented
> > 제가 테스트해보니까 부팅 중에 panic 이 일어나는 데 @kimjungwow 님은 어떠신가요?
> 
> 저는 잘 부팅됩니다.. 제가 기존에 수정하던 디렉토리 외에도, gibhub cli와 스크립트를 각각 이용하여 이 PR의 코드를 받은 뒤 둘 다 확인했는데 잘 부팅됩니다.. @efenniht

아 qemu version이 5.1 로 업데이트되어 있었습니다. 5.0으로 내리니 정상 동작하네요.

2020-09-22 08:54 UTC, efenniht approved these changes

2020-09-22 08:54 UTC, merged