Refactor vm.rs - pagetable struct
kaist-cp/rv6 pull request #212
Opened 2020-09-14 13:35 UTC by anemoneflower

- all usertest passed
- cargo fmt done
---
- subissue of #195
- vm.rs의 포인터로 되어 있는 `KERNEL_PAGETABLE`을 `PageTableEntry`, `RawPageTable`, `PageTable` struct의 구조로 재구성하였습니다.
---
1. 현재 temp로 되어 있는 `walk_temp`와 같은 함수들을 'walk'대신 사용할 수 있도록 다른 파일에도 수정된 struct 적용
2. 가능한 함수들을 각 struct의 method로 수정
한 후에 merge 가능한 pr로 돌리겠습니다.

2020-09-14 13:42 UTC, jeehoonkang requested changes
오랜만에...

2020-09-14 13:42 UTC, jeehoonkang commented on kernel-rs/src/riscv.rs
> +pub const PTESIZE: usize = PGSIZE / mem::size_of::<PageTableEntry>();
아울러 PageTableEntry와 다른 파일에 정의되어있는게 다소 의아합니다. 지금 서로 circular dependency가 있는 것 같은데 가능하면 해소하면 좋겠습니다.

2020-09-14 13:42 UTC, jeehoonkang commented on kernel-rs/src/vm.rs
> +    pub unsafe fn as_page(&self) -> &Page {
이 API들을 safe하게 감쌀 순 있을가요?

2020-09-14 13:42 UTC, jeehoonkang commented on kernel-rs/src/vm.rs
> +            ptr::write_bytes(page as *mut libc::CVoid, 0, PGSIZE);
cvoid 없이 할 수 있는 방법이 있을까요?

2020-09-14 13:42 UTC, jeehoonkang commented on kernel-rs/src/vm.rs
> +    pub fn into_page(self) -> *mut RawPageTable {
`into_raw`가 더 나은 이름일 것 같아요.

2020-09-14 13:42 UTC, jeehoonkang commented on kernel-rs/src/vm.rs
> +        panic!("`PageTableEntry` should not be dropped.");
pte가 어덯게 사라지는지 간단히 document하면 좋겠습니다 주석우로..

2020-09-14 13:42 UTC, jeehoonkang commented on kernel-rs/src/vm.rs
>  /*
Rust-style comment로 바꿉시다

2020-09-14 13:42 UTC, jeehoonkang commented on kernel-rs/src/vm.rs
> +    pub const unsafe fn raw() -> Self {
이름이 이상합니다.  `fn null()`?  아울러 PageTable이 null이라면 method invocation들이 다 error일텐데 이 함수를 노출하는게 다소 이상합니다.

2020-09-14 13:42 UTC, jeehoonkang commented on kernel-rs/src/vm.rs
> +/// Assumes va is page aligned.
주석에서 "assume"이라고 되어잇는게 있고 "assumes"라고ㅕ 되어있는게 있는데 가능하면 통일 부탁드려요

2020-09-14 13:42 UTC, jeehoonkang commented on kernel-rs/src/vm.rs
> +/// Assumes va is page aligned.
저는 Rust compiler 컨벤션에 따라 "Assumes"라고 하ㅅ길 선호합니다

2020-09-15 15:30 UTC, efenniht commented on kernel-rs/src/vm.rs
> +    let pte_op = walk_temp(&mut KERNEL_PAGETABLE, va, 0);
```suggestion
    let pte = walk_temp(&mut KERNEL_PAGETABLE, va, 0).filter(|pte| pte.is_valid()).expect("kvmpa");
```

2020-09-15 15:31 UTC, efenniht commented on kernel-rs/src/vm.rs
> +        let pte_op = walk_temp(pagetable, a, 1);
```suggestion
        let pte = walk_temp(pagetable, a, 1).filter(|pte| !pte.is_valid()).expect("remap");
```

2020-09-16 16:44 UTC, efenniht commented on kernel-rs/src/vm.rs
> +    pub unsafe fn as_page(&self) -> &Page {
제 생각에
 -  `as_page` 는 쉽게 됩니다.
 -  `as_table` 는 현재 PTE 가 어느 레벨의 page table 의 entry 인지를 알아야 합니다. 0 은 leaf node 라서 안 되고, 1, 2 는 됩니다. 이걸 const generics 또는 typenum 같은 crate 을 이용하여 zero cost 로 할 수 있을까요?

2020-09-19 07:42 UTC, efenniht requested changes
review 대로 수정하면 usertests 통과합니다. :laughing:

2020-09-19 07:42 UTC, efenniht commented on kernel-rs/src/exec.rs
> +    let mut pagetable = &mut PageTable::raw();
이 라인 삭제하고 `exec` 내에서 `pagetable` 접근하는 코드 `pt` 로 바꾸어야 합니다.

2020-09-19 07:42 UTC, efenniht commented on kernel-rs/src/vm.rs
> +    if pte.check_flag(PTE_U as usize) {
```suggestion
    if !pte.check_flag(PTE_U as usize) {
```

2020-09-19 07:42 UTC, efenniht commented on kernel-rs/src/vm.rs
> +        let pte = walk_temp(pagetable, a, 1).filter(|pte| !pte.check_flag(PTE_V)).expect("remap");
이 부분 제가 잘못 생각했는데 `walk_temp` 가 `None` 을 return 하면 panic 하지 않고 false 를 리턴해야 하더라구요. 이런 식으로 수정하면 됩니다:

```rust
let pte = some_or!(walk_temp(pagetable, a, 1), return false);
if pte.check_flag(PTE_V) {
    panic!("remap");
}
```

2020-09-21 08:13 UTC, anemoneflower commented on kernel-rs/src/vm.rs
> +    pub const unsafe fn raw() -> Self {
allocate되기 전의 `proc`이나 initialize되기 전의 `KERNEL_PAGETABLE`에 초기화값으로 지정하기 위해서 만든 함수입니다. 혹시 다른 방법이 있을까요?
(함수 이름은 `null()`로 수정했습니다:) )

2020-09-21 08:51 UTC, anemoneflower commented on kernel-rs/src/vm.rs
> +            ptr::write_bytes(page as *mut libc::CVoid, 0, PGSIZE);
이 부분은 좀더 고민해 봐야 할 것 같습니다..ㅠㅠ

2020-09-21 08:55 UTC, anemoneflower commented
* all usertest passed
* cargo fmt done
 
* subissue of #195
* vm.rs의 포인터로 되어 있는 `KERNEL_PAGETABLE`을 `PageTableEntry`, `RawPageTable`, `PageTable` struct의 구조로 재구성하였습니다.
 
> 1. 현재 temp로 되어 있는 `walk_temp`와 같은 함수들을 'walk'대신 사용할 수 있도록 다른 파일에도 수정된 struct 적용
> 2. 가능한 함수들을 각 struct의 method로 수정

완료했습니다.

---

merge이후 #195의 남은 subissue
- physical address / kernel virtual address / user virtual addrsss type 만들어서 copyin/out refactoring
진행할 예정입니다.

2020-09-21 15:28 UTC, coolofficials reviewed
일단 저는 proc.rs만 확인했는데 제 pr과 conflict는 없을 것 같습니다 :) (있다 해도 아주 minor한 issue일 것 같습니다.) 정말 고생하셨습니다!

2020-09-22 05:58 UTC, efenniht requested changes
수고하셨습니다. 몇 가지 큰 refactoring point 가 있습니다.
 - kernel page table vs user process page table 의 메서드 분리하기
 - `PageTable::init` 대신 `PageTable::new` 로 변경하고 `PageTable::null` 은 삭제
 - `PageTableEntry` 가 하위 page 를 소유하지 않을 수 있음. ex) trampoline 소유권 모델링 생각해보기

2020-09-22 05:58 UTC, efenniht commented on kernel-rs/src/proc.rs
> +            if sz.is_err() {
```suggestion
            sz.unwrap_or(-1)
```

2020-09-22 05:58 UTC, efenniht commented on kernel-rs/src/proc.rs
>  pub unsafe fn either_copyout(user_dst: i32, dst: usize, src: *mut libc::CVoid, len: usize) -> i32 {
이 함수도 `Result<(), ()>` 를 리턴하는 것이 어떨까요?

2020-09-22 05:58 UTC, efenniht commented on kernel-rs/src/trap.rs
> +    let satp: usize = make_satp((*p).pagetable.ptr as usize);
`PageTable::as_raw(&self) -> *mut RawPageTable` method 를 만들고 `ptr` 은 public 하게 노출하지 않는게 좋겠습니다.

2020-09-22 05:58 UTC, efenniht commented on kernel-rs/src/vm.rs
> +    unsafe fn from_raw(inner: PteT) -> Self {
이 함수를 어디서 사용하나요?

2020-09-22 05:58 UTC, efenniht commented on kernel-rs/src/vm.rs
> +    fn set_invalid(&mut self, flag: usize) {
- `set_valid` -> `set_flag` 로 바꿉시다.
 - `set_invalid` -> `clear_flag`

2020-09-22 05:58 UTC, efenniht commented on kernel-rs/src/vm.rs
> +const PTSIZE: usize = PGSIZE / mem::size_of::<PageTableEntry>();
`SIZE` 는 바이트 단위 크기로 혼동할 여지가 있습니다. `PTE_PER_PAGE_TABLE` ? 좋은 이름이 있을 것 같은데 영어란 어렵네요 ㅠㅠ

2020-09-22 05:58 UTC, efenniht commented on kernel-rs/src/vm.rs
> +    pub unsafe fn walkaddr(&mut self, va: usize) -> usize {
"Can only be used to look up user pages" 이 말을 타입으로 나타내면 좋겠습니다. Type parameter 를 page table에 넣으면 되지 않을까요?

2020-09-22 05:58 UTC, efenniht commented on kernel-rs/src/vm.rs
> +    pub unsafe fn walkaddr(&mut self, va: usize) -> usize {
그리고 이 함수는 실패하면 0을 리턴하는 데 `Option<usize>` 가 더 좋겠습니다. (`Option<NonZeroUsize>` 가 더 정확한데 이것은 나중에...)

2020-09-22 05:58 UTC, efenniht commented on kernel-rs/src/vm.rs
> +    pub unsafe fn mappages(&mut self, va: usize, size: usize, mut pa: usize, perm: i32) -> bool {
마찬가지로 `Result<(), ()>` 를 리턴하는 게 좋겠습니다.

2020-09-22 05:58 UTC, efenniht commented on kernel-rs/src/vm.rs
> +    pub unsafe fn mappages(&mut self, va: usize, size: usize, mut pa: usize, perm: i32) -> bool {
그리고 이 함수는 `PageTable` 의 method 가 되는 게 더 올바를 수 있습니다.

2020-09-22 05:58 UTC, efenniht commented on kernel-rs/src/vm.rs
> +    pub unsafe fn uvmunmap(&mut self, va: usize, size: usize, do_free: i32) {
`uvm` 으로 시작하는 메서드들은 user process page table 에서만 쓸 수 있습니다. 이것도 타입으로 나타내는 게 어떨까요?

2020-09-22 05:58 UTC, efenniht commented on kernel-rs/src/vm.rs
> +            let pte = pte_op.unwrap();
```suggestion
            let pte = walk(self, a, 0).expect("uvmunmap: walk");
```
일반적으로 `unwrap` 은 피하는 것이 좋습니다.

2020-09-22 05:58 UTC, efenniht commented on kernel-rs/src/vm.rs
> +    pub unsafe fn uvmalloc(&mut self, mut oldsz: usize, newsz: usize) -> Result<usize, ()> {
이 함수는 성공하는 경우 new size 이외의 다른 값을 리턴하는 것이 아니므로 그냥 `Result<(), ()>` 를 리턴하는 게 좋겠습니다.

2020-09-22 05:58 UTC, efenniht commented on kernel-rs/src/vm.rs
> +            new = scopeguard::ScopeGuard::into_inner(new_ptable);
`use scopeguard::ScopeGuard;` 추가해 주세요..
```suggestion
            new = ScopeGuard::into_inner(new_ptable);
```

2020-09-22 05:58 UTC, efenniht commented on kernel-rs/src/vm.rs
> +        pte_op.unwrap().set_invalid(PTE_U as usize)
위와 마찬가지로 `expect` 를 사용하면 됩니다.

2020-09-22 05:58 UTC, efenniht commented on kernel-rs/src/vm.rs
> +        mut src: *mut u8,
인자가 `&[u8]` 이면 더 좋을 것 같은데, 그렇게 리팩토링해도 호출하는 쪽에서 잘 부를 수 있는 지 확인해 주세요.

2020-09-22 05:58 UTC, efenniht commented on kernel-rs/src/vm.rs
>  pub unsafe fn kvminit() {
커널 페이지 테이블을 초기화하고 소유하는 MemoryManager 가 있는 게 좋겠습니다. 이것은 다음 PR 에서...

2020-09-23 01:43 UTC, coolofficials commented
rebase가 잘못되어 있습니다..!
`git reset --hard cb0cac6` 하시고
`git rebase 8c9de67` 이후에 conflict 날 때마다 resolve(그냥 incoming change 누르시면 됩니다) 하시고
수정한 파일들 `git add` 까지만 한 이후 `git rebase --continue` 계속 진행하시면 됩니다.
그 이후에 `git push` (또는 `git push --force-with-lease` 하시면 됩니다.

2020-09-23 02:10 UTC, anemoneflower commented
> rebase가 잘못되어 있습니다..!
> `git reset --hard cb0cac6` 하시고
> `git rebase 8c9de67` 이후에 conflict 날 때마다 resolve(그냥 incoming change 누르시면 됩니다) 하시고
> 수정한 파일들 `git add` 까지만 한 이후 `git rebase --continue` 계속 진행하시면 됩니다.
> 그 이후에 `git push` (또는 `git push --force-with-lease`) 하시면 됩니다 :)

어느 지점에서 문제인지 설명해 주실 수 있을까요?

2020-09-23 02:17 UTC, coolofficials commented
https://github.com/kaist-cp/rv6/pull/212#issuecomment-697079155

현재 commit list 보시면 `1657693`~`cb0cac6`의 기존 commit 위에 `29b43be`~`8c9de67`의 upstream/riscv commit이 쌓여있고, 다시 기존의 commit과 같은 내용 `427eab7`~`e468883`이 쌓여 있는 상태입니다.

rebase를 하는 목적은 working tree(linegraph)가 한 줄로 깔끔하게 이어지도록 하는 것인데, `git log --all --decorate --oneline --graph` command를 통해 linegraph 확인하실 수 있습니다.

https://github.com/kaist-cp/rv6/pull/194#issuecomment-687125514
https://github.com/kaist-cp/rv6/pull/214#issuecomment-696680401

2020-09-25 04:11 UTC, anemoneflower commented on kernel-rs/src/vm.rs
> +    pub unsafe fn uvmalloc(&mut self, mut oldsz: usize, newsz: usize) -> Result<usize, ()> {
https://github.com/kaist-cp/rv6/blob/c56f42418196c169063fcda4b82319fceb501e8c/kernel-rs/src/vm.rs#L199-L202
위의 경우 `oldsz`를 리턴하기도 합니다!

2020-09-25 12:04 UTC, anemoneflower commented on kernel-rs/src/vm.rs
> +const PTSIZE: usize = PGSIZE / mem::size_of::<PageTableEntry>();
PTE_PER_PT 로 수정했습니다..!

2020-09-25 12:28 UTC, anemoneflower commented on kernel-rs/src/vm.rs
> +    pub unsafe fn uvmunmap(&mut self, va: usize, size: usize, do_free: i32) {
다음 PR에서 진행할 예정이므로 resolve하겠습니다!

2020-09-26 15:21 UTC, anemoneflower commented on kernel-rs/src/proc.rs
> +            if sz.is_err() {
해당하는 type이 `usize` 인데 `-1`이 `i32`라서 `unwrap_or`사용시 에러가 납니다. `map_or`와 같은 다른 방법도 시도해 봤는데 혹시 `unwrap_or`말고 `unwrap`을 사용하지 않는 해결책이 있을까요?
(rebase를 해서 생긴 차이인것 같기도 합니다...)

2020-09-26 16:10 UTC, anemoneflower commented on kernel-rs/src/proc.rs
> +            if sz.is_err() {
`ok_or!`로 해결했습니다.

2020-09-26 16:21 UTC, anemoneflower commented on kernel-rs/src/vm.rs
> +    pub unsafe fn walkaddr(&mut self, va: usize) -> usize {
> "Can only be used to look up user pages" 이 말을 타입으로 나타내면 좋겠습니다. Type parameter 를 page table에 넣으면 되지 않을까요?

이부분은 TODO로 남기고 앞서 논의했던 것처럼 다음 pr에서 user/kernel pagetable 따로 구분할 때 적용하겠습니다!

2020-09-27 07:11 UTC, efenniht commented on kernel-rs/src/vm.rs
> +    pub unsafe fn uvmalloc(&mut self, mut oldsz: usize, newsz: usize) -> Result<usize, ()> {
그렇다면 원래대로 `Result<usize, ()>` 를 리턴하면 될 것 같습니다 :smiley:

2020-09-27 07:25 UTC, anemoneflower commented on kernel-rs/src/vm.rs
> +        mut src: *mut u8,
Todo 남기고 resolve하겠습니다!

2020-09-27 07:39 UTC, efenniht commented on kernel-rs/src/vm.rs
> +        mut src: *mut u8,
#226

2020-09-27 08:20 UTC, efenniht requested changes
구조를 뜯어고치다 보니까 PR 이 엄청 커지네요.. :open_mouth: 다른 디테일은 이후에 수정하되, `walk` 와 `walk` 를 부르는 함수는 모두 `PageTable` 의 메서드가 되는 것이 더 자연스러울 것 같습니다.

2020-09-27 08:20 UTC, efenniht commented on kernel-rs/src/vm.rs
> +        let pte = some_or!(walk(self, va, 0), return None);
```suggestion
        let pte = walk(self, va, 0)?;
```

2020-09-27 08:20 UTC, efenniht commented on kernel-rs/src/vm.rs
> +            let pte = &mut self[i];
```suggestion
        for pte in &mut self.inner {
```

2020-09-27 08:20 UTC, efenniht commented on kernel-rs/src/vm.rs
> +        ptr::write_bytes(mem as *mut libc::CVoid, 0, PGSIZE);
```suggestion
        ptr::write_bytes(mem, 0, PGSIZE);
```
`u8` 과 `CVoid` 모두 동일한 크기 (1바이트) 입니다.

2020-09-27 08:20 UTC, efenniht commented on kernel-rs/src/vm.rs
> +        unsafe { &*(pte2pa(self.inner) as *const Page) }
다시 생각해보니까 PTE 가 invalid 하면 이 함수도 unsound 할 수 있군요... 이 함수도 `unsafe` 로 마킹해두어야 할 것 같습니다.

2020-09-27 08:20 UTC, efenniht commented on kernel-rs/src/vm.rs
> +unsafe fn walk(
이 함수는 `PageTable` 의 method 가 될 수 있지 않나요?

2020-09-27 08:23 UTC, coolofficials commented on kernel-rs/src/proc.rs
> +    if !(*p).pagetable.assume_init_mut().is_null() {
@efenniht @anemoneflower 확인했습니다.

2020-09-27 15:32 UTC, efenniht approved these changes

2020-09-27 15:32 UTC, merged