[subissue of #204] Create ProcessPool & implement methods.
kaist-cp/rv6 pull request #214
Opened 2020-09-16 10:10 UTC by coolofficials

- make / usertests / hart message / fmt
- 기존에 PROC으로 나타내던 Process들의 pool을 ProcessPool type으로 변경하고 global PROCPOOL을 선언.
- 해당하는 함수들을 ProcessPool의 method로 implement

@efenniht 
- wait의 경우 Proc을 refactoring 하면서 조금 더 생각해봐야 할 것 같습니다.

- Proc, Cpu, Context 등에 대한 수정을 진행하도록 하겠습니다.

2020-09-16 11:04 UTC, kimjungwow reviewed
커밋을 잘 드러내는 커밋 메시지들을 사용해주셔서 리뷰하기 수월했습니다. 감사합니다.
ProcessPool의 ownership은 시원님께서 고민하신 방향에 적극 동의합니다.
함수명들 위주로 코멘트를 남겼는데, 다른 분들께서 수정할 필요가 없다 생각하시면 넘기셔도 좋습니다. :)

2020-09-16 11:04 UTC, kimjungwow commented on kernel-rs/src/proc.rs
> +    pub unsafe fn debug(&mut self) {
참고 : `debug`의 이전 이름인 `procdump`는 Windows에서 사용되는 command-line application인데, `debug()`와는 역할이 좀 다릅니다.
https://en.wikipedia.org/wiki/ProcDump

2020-09-16 11:04 UTC, kimjungwow commented on kernel-rs/src/proc.rs
> +#[no_mangle]
비록 예외가 있긴 하지만, 리눅스 커널의 `start_kernel`을 보면 대체로 `***init()`와 같이 사용하는 것으로 보입니다. (핀토스에서도 그랬던 것으로 기억합니다).
https://elixir.bootlin.com/linux/latest/source/init/main.c#L832
`init_process_pool`을 사용하신 특별한 이유가 없다면, `***init()`와 같이 `init`이 뒤쪽으로 오는 함수명을 사용하시면 어떨까요?

2020-09-16 11:15 UTC, coolofficials reviewed
@kimjungwow 리뷰 감사합니다! 각 항목 별로 한 분만 의견을 더 주시면 바로 수정하도록 하겠습니다!

2020-09-16 11:15 UTC, coolofficials commented on kernel-rs/src/proc.rs
> +/// Process pool type containing & managing whole processes.
서술하는 문장이라서 그렇게 했습니다. 어느게 좋을까요? 다른 분들 의견 더 들어보고 결정하겠습니다.

2020-09-16 11:15 UTC, coolofficials commented on kernel-rs/src/proc.rs
> +    unsafe fn init_parent(&mut self, p: *mut Proc) {
아까 @efenniht 님과 얘기할 때 `reparent`라는 이름만 보고 함수 내용 파악이 수월하지 않았던 것 같아서 parent를 초기화한다는 의미로 init_parent로 변경했습니다. `deparent`? 등도 괜찮을 것 같습니다.

2020-09-16 11:15 UTC, coolofficials commented on kernel-rs/src/proc.rs
> +    pub unsafe fn kill_process(&mut self, pid: i32) -> i32 {
`kill_process`라고 한 이유는 해당 메소드가 `ProcessPool` 내부에 특정 `pid`를 가지는 `Proc` 하나를 kill 하기 때문입니다. 말씀하신대로 어차피 `pid`를 parameter로 가진다면 `kill`도 충분할 것 같습니다. 의견 듣고 결정하겠습니다!

2020-09-16 11:15 UTC, coolofficials commented on kernel-rs/src/proc.rs
> +    pub fn wakeup_pool(&mut self, targetchannel: &WaitChannel) {
@kimjungwow `wakeup_pool`을 `WaitChannel`의 메소드인 `wakeup`에서 호출하는 방식으로 ownership을 표현했습니다.

2020-09-16 11:15 UTC, coolofficials commented on kernel-rs/src/proc.rs
> +    pub unsafe fn debug(&mut self) {
이 부분은 procdump또는 dump로 수정하는게 좋을 것 같다는 생각이 드네요. 이것도 다른 분 의견 하나만 더 듣고 수정하겠습니다!

2020-09-16 11:15 UTC, coolofficials commented on kernel-rs/src/proc.rs
> +#[no_mangle]
저도 수정하면서 통일성 측면에서 그게 좋겠다고 생각했었습니다. process_pool_init()정도로 수정하겠습니다.

2020-09-16 11:32 UTC, coolofficials commented on kernel-rs/src/proc.rs
> +    pub unsafe fn kill_process(&mut self, pid: i32) -> i32 {
설명을 잘못 드린 것 같은데 해당 함수 내부에 Proc에 implement 할 kill method를 call하게 될 것 같아서 이렇게 두었습니다!

2020-09-16 11:37 UTC, kimjungwow commented on kernel-rs/src/proc.rs
> +    pub unsafe fn kill_process(&mut self, pid: i32) -> i32 {
> 설명을 잘못 드린 것 같은데 해당 함수 내부에 Proc에 implement 할 kill method를 call하게 될 것 같아서 이렇게 두었습니다!

이 `kill_process()`외에도 `impl Proc` 안에 `kill()` 함수가 생긴다는 말씀이신가요?

2020-09-16 11:39 UTC, coolofficials commented on kernel-rs/src/proc.rs
> +    pub unsafe fn kill_process(&mut self, pid: i32) -> i32 {
@kimjungwow 네 맞습니다!

2020-09-16 16:39 UTC, efenniht requested changes
수고하셨습니다. 작업하신 내용을 보니까 `ProcessPool` 의 많은 API 가 `Proc` 과 밀접하게 연결되어 있어서, 둘을 함께 리팩토링하는 게 좋을 것 같습니다. 이 PR 에서는 `ProcessPool` 에서 하는 일 중 `Proc` 의 메서드로 옮길 수 있는 것들을 실제로 옮기는 것까지 하도록 합시다. 그리고 다음 PR 에서 `Proc` struct 가 들고 있는 field를 정리하는 게 좋겠습니다.

2020-09-16 16:39 UTC, efenniht commented on kernel-rs/src/proc.rs
> +static mut INITPROC: *mut Proc = ptr::null_mut();
`INITPROC` 은 `ProcessPool` 에 넣을 수 없나요?

2020-09-16 16:39 UTC, efenniht commented on kernel-rs/src/proc.rs
> +    unsafe fn alloc_proc(&mut self) -> *mut Proc {
이 함수는 alloc 의 대상이 proc인 것이 확실하므로 그냥 이름을 `alloc` 으로 하는 게 명확해 보입니다. 다른 함수들도 마찬가지입니다.

2020-09-16 16:39 UTC, efenniht commented on kernel-rs/src/proc.rs
> +    unsafe fn alloc_proc(&mut self) -> *mut Proc {
그리고 실패할 수 있는 함수니까 `Result<*mut Proc, ()>` 을 리턴하도록 리팩토링해 주세요. (#203) 이것도 다른 함수에도 적용 부탁드립니다.

2020-09-16 16:39 UTC, efenniht commented on kernel-rs/src/proc.rs
> +    pub unsafe fn kill_process(&mut self, pid: i32) -> i32 {
제 생각에도 `kill` 로 충분한 것 같습니다. Receiver의 타입이 다르기 때문에...

2020-09-16 16:39 UTC, efenniht commented on kernel-rs/src/proc.rs
> +    unsafe fn alloc_proc(&mut self) -> *mut Proc {
마지막으로 `ProcessPool` 은 락으로 보호되지 않고 내부의 shared data만 lock 을 거므로, `ProcessPool` 의 메서드들은 `&self` 를 받아야 합니다. (init 제외)

2020-09-16 16:39 UTC, efenniht commented on kernel-rs/src/proc.rs
> +    pub fn wakeup_pool(&mut self, targetchannel: &WaitChannel) {
- 변수는 `target_channel` 처럼 쓰는 게 convention입니다. (https://rust-lang.github.io/api-guidelines/naming.html#casing-conforms-to-rfc-430-c-case)
 - 그리고 이건 제 취향인데, 타입에 이미 이 변수가 waitchannel인 것이 드러나므로 변수 이름에는 그 정보를 중복해서 나타낼 필요가 없는 것 같습니다. 이건 @coolofficials 님께서 더 좋은 쪽으로 결정해주세요...

2020-09-16 16:39 UTC, efenniht commented on kernel-rs/src/proc.rs
> +    fn run_processes(&mut self, c: *mut Cpu) {
이 함수가 safe한 이유는 무엇인가요?

2020-09-16 17:26 UTC, coolofficials commented on kernel-rs/src/proc.rs
> +    pub fn wakeup_pool(&mut self, targetchannel: &WaitChannel) {
@efenniht target으로 변경하는 방식을 말씀하시는 것인가요?

2020-09-17 05:04 UTC, efenniht commented on kernel-rs/src/proc.rs
> +    pub fn wakeup_pool(&mut self, targetchannel: &WaitChannel) {
네 그렇게 쓰는 것을 제안드렸습니다.

2020-09-21 05:55 UTC, coolofficials commented on kernel-rs/src/proc.rs
> +    unsafe fn alloc_proc(&mut self) -> *mut Proc {
https://github.com/kaist-cp/rv6/pull/214#discussion_r489569370 해당 comment는 Proc을 Spinlock을 감싼 이후 진행하겠습니다. #204 에 명시.

2020-09-21 06:05 UTC, coolofficials commented on kernel-rs/src/proc.rs
> +        PROCPOOL.run_processes(c);
@efenniht 상욱 님. 해당 review는 run_processes method 내부의 swtch function call 부분을 scheduler의 method로 변경하면 되는 부분일까요? 그 위까지는 Procstate를 변경하는 code이기 때문에 review 해주신대로면 ProcessPool의 메소드로 두는 것이 맞는 것 같습니다.

run_processes를 call_scheduler 또는 run_scheduler 정도로 변경하고 추후 scheduler implement하면서 추가적으로(Scheduler를 해당 메소드가 변수로 받는 방식으로) 변경하도록 하겠습니다.

2020-09-21 06:16 UTC, coolofficials commented on kernel-rs/src/proc.rs
> +        PROCPOOL.run_processes(c);
위에서 생각을 잘못했는데 https://github.com/skyzh/core-os-riscv/blob/master/kernel/src/process/schedule.rs 처럼 사용하는 것이 좋을 것 같습니다. 현재 PR에서는 원래의 상태로 변경하도록 하겠습니다.

2020-09-21 06:47 UTC, coolofficials commented on kernel-rs/src/proc.rs
> +    }
kill은 현재 sysproc의 sys_kill에서만 사용하고 이 함수는 usize를 return하고 있습니다. 그리고 이 메소드도 Result를 return해야하는지 의문입니다. 제 생각에는 syscall.rs refactoring에서 Result type으로 변경하는 것이 맞다고 판단됩니다.

2020-09-21 07:14 UTC, coolofficials commented on kernel-rs/src/proc.rs
> +    unsafe fn alloc_proc(&mut self) -> *mut Proc {
https://github.com/kaist-cp/rv6/pull/214#discussion_r489557242 확인 결과 현재 PR에서는 alloc만 변경해도 될 것 같습니다.

2020-09-21 07:30 UTC, coolofficials commented on kernel-rs/src/proc.rs
> +static mut INITPROC: *mut Proc = ptr::null_mut();
일단 넣었습니다. 원래는 userinit이나 exit 함수가 PROCSYS가 올바르게 선언되지 않은 상태에서도 global INITPROC의 존재로 인해 문제 없이 돌아가는 구조였으나, 이제는 PROCSYS: ProcessSystem이 선언되면 해당 PROCSYS의 initial_proc을 INITPROC으로 사용합니다. 제 생각에는 원래 구조보다 현재 수정된 구조가 더 올바른 semantic이라고 생각됩니다. (동시에 돌아가는 ProcessSystem이 하나이기 때문에..)

2020-09-22 03:24 UTC, coolofficials commented
@efenniht 

현재 PR에서 진행해야할 사항 중

exit_current > CPU refactoring, Proc Spinlock 이후
alloc > Proc Spinlock으로 감싼 이후

마저 진행하도록 하겠습니다.
제가 보기에는 현재 PR에서 진행할 부분은 여기까지인 것 같습니다.

- usertests all passed
- fmt

이어서 Proc Spinlock으로 감싸는 것을 우선적으로 진행해야할 것 같습니다.
- Proc에 Spinlock으로 감싸야하는 field와 아닌 field가 나뉘어 있는데, 일단은 전체를 Spinlock으로 감싼 이후 method들을 정리하고 나서 field 정리를 진행하는 것이 더 좋은 방법이 아닐까 생각이 듭니다.

2020-09-22 03:33 UTC, coolofficials reviewed
`wakeup`이 여러 struct들에 나뉘어 구현이 되어 있습니다.
이러한 패턴이 더 많이 있을텐데, 올바른 추상화를 생각해야합니다.

개인적으로는 sleep과 wakeup이 WaitChannel의 메소드가 되는 것의 장점을 잘 파악하지 못하겠습니다. @kimjungwow @efenniht 혹시 어떠한 장점들이 있을까요?


다른 thread로부터 channel로 notify를 보내서 관리하는 mental model이 이유였군요? 좋은 것 같습니다. 
하지만 sleep은 current process이 특정 channel에 잠들도록 하는 추상화가 더 좋지 않을까요?

2020-09-22 03:33 UTC, coolofficials commented on kernel-rs/src/proc.rs
> +        self.initial_proc = p;
이 부분 때문에 추후에 Spinlock으로 Proc을 감싸더라도 이 메소드는 &mut self를 받아야 할 것 같습니다.

2020-09-22 06:39 UTC, efenniht requested changes
:carrot: 거의 다 온 것 같습니다!

2020-09-22 06:39 UTC, efenniht commented on kernel-rs/src/proc.rs
> +    unsafe fn kill(&mut self) {
safe 이어도 되지 않을까요?

2020-09-22 06:39 UTC, efenniht commented on kernel-rs/src/proc.rs
> +                    return Ok(ptr::null_mut());
이 경우에 `Ok` 를 리턴하는 이유는 무엇인가요?

2020-09-22 06:39 UTC, efenniht commented on kernel-rs/src/proc.rs
> +        };
기존의 코드는 이 시점에서 `alloc` 이 절대 실패하지 않을 것이라고 가정하고 진행합니다. 실제로 그러므로 버그가 아니긴 한데, 첫 init 시점에서 error 가 나지 않는 것을 타입으로 보장하는 것은 어렵습니다.

비록 런타임 체크가 조금 더 들어가지만, 이 코드는 부팅 시 단 한 번만 호출되므로 `expect` 를 호출하도록 합시다.
```suggestion
        let mut p = self.alloc().expect("user_proc_init");
```

2020-09-22 06:39 UTC, efenniht commented on kernel-rs/src/proc.rs
> +            .wakeup_proc(PROCSYS.initial_proc);
```suggestion
            .wakeup_proc(self.initial_proc);
```

2020-09-22 06:39 UTC, efenniht commented on kernel-rs/src/proc.rs
> +        };
아 이게 `self.alloc()` 이 `Ok(ptr::null_mut())` 일 수도 있네요.. null 이면 무조건 `Err` 가 되도록 위에서 수정하는 게 좋겠습니다.

2020-09-22 06:39 UTC, efenniht commented on kernel-rs/src/proc.rs
>      let p = myproc();
제 생각에 `exit_current` 가 ProcessSystem 의 메서드이면 `fork` 와 `wait` 도 그렇지 않을 이유가 없다고 생각하는데요. 둘이 다른 이유가 무엇인가요?

2020-09-22 07:02 UTC, coolofficials reviewed
@efenniht 상욱님, review address 했습니다. 코멘트 남긴 부분들(alloc return 관련) 검토해주시면 마저 address 하겠습니다.

- wait, fork 같은 경우에도 Proc을 Spinlock으로 감싼 이후에 진행하는 것이 좋을 것 같아서 두었습니다.
- kill, wait, fork의 return -1 등은 syscall refactoring의 영역인 것 같아서 Result로 변경하지 않았습니다.

이제 크게 Proc 관련해서 가능한 다음 단계가

1. Spinlock으로 Proc을 감싸고 나서 가능한 logic 수정.
2. *mut Proc을 AllocatedProc으로 수정.

위의 두가지가 independent 하게 진행 가능할 것 같고, 그 이후에 Cpu, Scheduler, Context, Trapframe 등의 수정 이후에 추가로 생겨날 point들이 있을 것 같습니다.

2020-09-22 07:04 UTC, coolofficials commented on kernel-rs/src/proc.rs
> +                    return Ok(ptr::null_mut());
처음에는 Err(NullProc) 등으로 return 하고자 했습니다.

2020-09-22 08:00 UTC, efenniht commented on kernel-rs/src/proc.rs
> +                    return Ok(ptr::null_mut());
`p.tf.is_null()` 은 trapframe 의 할당에 실패하였다는 의미인 것 같습니다. (`tf` 는 raw pointer) 그 경우에는 allocate 을 실패한 것이므로 `Err` 를 리턴하는 게 맞지 않을까요?

2020-09-22 08:06 UTC, efenniht commented on kernel-rs/src/proc.rs
>      let p = myproc();
네, 세 함수 모두 유사한 일을 하는 것으로 보입니다. (본인 Context를 조작하기 위해서 ProcessSystem 을 접근.) 먼저 ProcessSystem 으로 다 옮기는 게 좋을 것 같습니다.

2020-09-22 08:09 UTC, coolofficials commented on kernel-rs/src/proc.rs
> +                    return Ok(ptr::null_mut());
아 그런 의미군요... 차후에 trapframe refactoring 시에 더 변경될 수 있을 것 같습니다. 일단 Err return 하겠습니다.

2020-09-22 08:19 UTC, coolofficials commented
merge 준비된 것 같습니다.

2020-09-22 08:31 UTC, efenniht commented on kernel-rs/src/proc.rs
> +    NullTrapFrame,
- `TrapFrame` 의 내용이 올바르지 않은 게 아니라, `TrapFrame` 을 저장하는 _메모리_ 할당이 실패한 것이므로 `OutOfMemory` 같은 이름이 좋겠습니다.
 - 그런데 이 Error type 을 실제로 구별해야 할 이유가 있는 건가요?

2020-09-22 11:03 UTC, coolofficials commented on kernel-rs/src/proc.rs
> +    NullTrapFrame,
특별한 이유는 없어서 그냥 Err(())로 변경하겠습니다.

2020-09-22 12:10 UTC, coolofficials commented
@efenniht rebase 조금 힘들었지만 잘 된 것 같습니다 :)
Err를 그냥 Err(())로 변경했습니다.

cargo fmt / usertests passed

2020-09-22 17:28 UTC, efenniht requested changes
제가 메세지에 답을 드리기 전에 해결하셨군요..!! 고생하셨습니다. 아주 작은 것만 수정 부탁드립니다.

2020-09-22 17:28 UTC, efenniht commented on kernel-rs/src/proc.rs
> +        }
```suggestion
        let mut np = self.alloc()?;
```

2020-09-22 23:46 UTC, coolofficials commented on kernel-rs/src/proc.rs
> +        }
@efenniht 제시해주신 수정은 -1을 return 하는 logic과 다른 것 같습니다.

2020-09-22 23:56 UTC, coolofficials commented on kernel-rs/src/proc.rs
>  use core::str;
str 같은 경우는 dump에서 사용하고 있습니다.

2020-09-23 00:07 UTC, coolofficials commented on kernel-rs/src/proc.rs
> +        }
logic 수정은 syscall 쪽 refactoring인 것 같아서 현재 PR 범위가 아닌 것 같습니다.

2020-09-23 02:29 UTC, efenniht commented on kernel-rs/src/proc.rs
> +        }
그렇군요.. 그러면 ok_or을 쓰는 것은 어떨까요?

2020-09-23 02:45 UTC, efenniht commented on kernel-rs/src/proc.rs
> +        (*self).cwd = ptr::null_mut();
417번째 줄에 하나 남아있습니다 ;)

2020-09-23 02:45 UTC, efenniht commented on kernel-rs/src/proc.rs
> +        (*self).cwd = ptr::null_mut();
417번째 줄에 하나 남아있습니다 ;)

2020-09-23 02:45 UTC, efenniht commented on kernel-rs/src/proc.rs
> +        (*self).cwd = ptr::null_mut();
417번째 줄에 하나 남아있습니다 ;)

2020-09-23 02:45 UTC, efenniht commented on kernel-rs/src/proc.rs
> +        (*self).cwd = ptr::null_mut();
417번째 줄에 하나 남아있습니다 ;)

2020-09-23 02:45 UTC, efenniht commented on kernel-rs/src/proc.rs
> +        (*self).cwd = ptr::null_mut();
417번째 줄에 하나 남아있습니다 ;)

2020-09-23 02:45 UTC, efenniht commented on kernel-rs/src/proc.rs
> +        (*self).cwd = ptr::null_mut();
417번째 줄에 하나 남아있습니다 ;)

2020-09-23 02:58 UTC, coolofficials commented on kernel-rs/src/proc.rs
> +        (*self).cwd = ptr::null_mut();
앗... 확인했습니다...

2020-09-23 02:59 UTC, efenniht commented on kernel-rs/src/proc.rs
> +        (*self).cwd = ptr::null_mut();
죄송합니다 폰에서 막 눌렀더니 댓글이 엄청 많이 달렸네요 :disappointed:

2020-09-23 03:02 UTC, efenniht commented on kernel-rs/src/proc.rs
>  use core::str;
아 타입 말고 모듈 `core::str` 는 자동으로 import 가 안 되는군요 :open_mouth:

2020-09-23 03:33 UTC, coolofficials commented on kernel-rs/src/proc.rs
> +        }
반영했습니다!

2020-09-23 03:33 UTC, coolofficials commented on kernel-rs/src/proc.rs
> +        (*self).cwd = ptr::null_mut();
반영했습니다..!

2020-09-23 04:28 UTC, efenniht approved these changes

2020-09-23 04:29 UTC, merged