DRAFT : Use SleeplockWIP<Inode> (related to #218)
kaist-cp/rv6 pull request #228
Opened 2020-09-28 08:35 UTC by kimjungwow

- 현재 부팅시 `panicked at 'Inode::lock: no type', src/fs.rs:488:17`에서 패닉이 걸립니다. 상욱님과 공유하기 위한 Draft PR입니다.
- 아래와 같이 struct Inode를 리팩토링했습니다. 이유는
  - Inode의 Sleeplock이 보호하는 대상을 명확히 하고
  - Inode의 Sleeplock을 쥔 상태에서 호출되는 함수는 `impl InodeGuard<'_>`에서 다루기 위함입니다.
```Rust
pub struct InodeGuard<'a> {
    pub guard: SleepLockGuard<'a, InodeInner>,
    pub ptr: *mut Inode,
}
pub struct InodeInner {
    /// copy of disk inode
    pub typ: i16,
    pub major: u16,
    pub minor: u16,
    pub nlink: i16,
    pub size: u32,
    pub addrs: [u32; 13],
}

/// in-memory copy of an inode
pub struct Inode {
    /// Device number
    pub dev: u32,

    /// Inode number
    pub inum: u32,

    /// Reference count
    pub ref_0: i32,

    /// inode has been read from disk?
    pub valid: i32,

    // pub inner: InodeInner,
    pub inner: SleeplockWIP<InodeInner>,
}
```

2020-09-28 12:17 UTC, efenniht commented on kernel-rs/src/exec.rs
>      end_op();
이 라인 삭제하시고 `rm fs.img` 하시면 부팅은 정상적으로 됩니다.

2020-09-28 12:18 UTC, efenniht commented
@kimjungwow ping

2020-09-28 12:32 UTC, kimjungwow commented on kernel-rs/src/exec.rs
>      end_op();
`drop(ip_inodeguard);` 말씀이신가요? 지우고 `rm fs.img`후 `make qemu`하면 아직
`panicked at 'log_write outside of trans', src/log.rs:253:9` 패닉이 뜨네요..

2020-09-28 12:38 UTC, kimjungwow commented on kernel-rs/src/exec.rs
>      end_op();
`end_op()`도 지워보았습니다.. `drop(ip_inodeguard)`만 남기고요

2020-09-28 12:45 UTC, kimjungwow commented
@efenniht ping 감사합니다! :) ping

2020-09-28 12:48 UTC, efenniht commented on kernel-rs/src/exec.rs
>      end_op();
`drop(ip_inodeguard)` 는 남기고, `end_op()` 는 지우고, `fs.img` 지운 다음에 다시 실행하면 되지 않나요?

2020-09-28 12:52 UTC, kimjungwow commented on kernel-rs/src/exec.rs
>      end_op();
@efenniht 
- 네, 말씀하신대로 `drop(ip_inodeguard);`는 남기고,  그 밑의 `end_op();`는 지우고 `rm fs.img` 후 `make qemu`해도 같은 오류가 뜹니다.. `rm fs.img`대신 `make clean`해도 마찬가지입니다. 이 PR 기준으로 `end_op()`를 지운것 외에 변경사항은 없습니다.
- 저도 `end_op()`를 지워야 한다는 것은 이해했습니다

2020-09-28 15:36 UTC, efenniht reviewed
아 제가 한 가지 빼먹었는데, `put` 함수에서도 수정해야 합니다.

2020-09-28 15:36 UTC, efenniht commented on kernel-rs/src/fs.rs
> +        // && (*self).inner.nlink as i32 == 0
여기서 삭제된 조건을 체크해야 합니다.

2020-09-28 15:36 UTC, efenniht commented on kernel-rs/src/fs.rs
> +
```suggestion
            if inodeguard.guard.nlink != 0 {
                self.ref_0 -= 1;
                return;
            }
```
이런 식으로 할 수 있습니다.

2020-09-28 15:59 UTC, kimjungwow commented
@efenniht 아직 리팩토링이 끝나지 않았는데 조건을 삭제한 것이 문제였군요.. 감사합니다! 리팩토링을 더 진행한 후 리뷰 요청드리겠습니다 :)

2020-10-05 16:56 UTC, kimjungwow commented
@efenniht 상욱님, 리뷰 요청드립니다!

- Done
  - Inode를 Sleeplock으로 감싸며, `lock()` 실행 시 `InodeGuard`를 리턴한다. `InodeGuard`는 Inode의 valid 필드도 접근/수정해야 해서 InodeGuard의 ptr 필드는 `*mut Inode`이다.
    - Inode의 sleeplock을 쥔 상태에서만 실행되는 함수들은 `impl InodeGuard`로 옮김
  - struct field의 타입 / 함수의 리턴 타입을 적절히 변경
  - Inode 관련 함수 중 실패할 때 -1을 리턴하는 함수가 Result를 리턴하도록 변경 (sysfile.rs 제외)
    - 불필요한 if 문 대신`map_or()`, `?` 연산자 등을 적절히 사용
- To do
  - 불필요한 wrapping 대신 +-*/% 연산자 사용
  - `InodeGuard`에 꼭 `ptr : *mut Inode`가 있어야 하는지 고민하기 : valid 필드를 InodeInner에 넣는 등의 방법으로 해결할 수 있을지 고민하기
  - #218, #224, #231

2020-10-06 07:32 UTC, efenniht requested changes
고생하셨습니다 ㅠ 굉장히 많은 변경을 하셨네요.

이번 PR에서는 `InodeGuard` 가 1) 정확히 어떤 의미를 가지는 지 파악하고, 2) 이를 돕기 위해서 좋은 API를 만드는 것이 핵심인 것 같습니다. 관련하여 코멘트를 남겼습니다.

2020-10-06 07:32 UTC, efenniht commented on kernel-rs/src/file.rs
> +pub struct InodeGuard<'a> {
마지막으로 `InodeGuard` 가 `InodeInner` 의 `Deref`를 구현하는 게 어떨까요?

2020-10-06 07:32 UTC, efenniht commented on kernel-rs/src/fs.rs
> +    pub unsafe fn dirlink(&mut self, name: &FileName, inum: u32) -> bool {
`Result<(), ()>` 를 리턴하는 것이 어떨까요?

2020-10-06 07:32 UTC, efenniht commented on kernel-rs/src/fs.rs
> +        while (off as u32) < self.guard.size {
`step_by` 함수를 이용하여 for 문으로 만들 수 있습니다.

2020-10-06 07:32 UTC, efenniht commented on kernel-rs/src/fs.rs
> +                .map_or(true, |v| v != ::core::mem::size_of::<Dirent>())
마찬가지로 정리할 수 있습니다.

2020-10-06 07:32 UTC, efenniht commented on kernel-rs/src/fs.rs
> +            .map_or(true, |v| v != ::core::mem::size_of::<Dirent>())
마찬가지로 정리할 수 있습니다.

2020-10-06 07:32 UTC, efenniht commented on kernel-rs/src/fs.rs
> +                .map_or(true, |v| v != ::core::mem::size_of::<Dirent>())
또한 `if xx { panic!("..."); }` 은 `assert!(xx, "...");` 로 쓸 수 있습니다.

2020-10-06 07:32 UTC, efenniht commented on kernel-rs/src/fs.rs
> +                dst = (dst).wrapping_add(m as usize)
```suggestion
                tot = tot.wrapping_add(m);
                off = off.wrapping_add(m);
                dst = dst.wrapping_add(m as usize)
```

2020-10-06 07:32 UTC, efenniht commented on kernel-rs/src/fs.rs
> +                src = (src).wrapping_add(m as usize)
```suggestion
                tot = tot.wrapping_add(m);
                off = off.wrapping_add(m);
                src = src.wrapping_add(m as usize)
```

2020-10-06 07:32 UTC, efenniht commented on kernel-rs/src/fs.rs
> +                .map_or(true, |v| v != ::core::mem::size_of::<Dirent>())
마찬가지로 정리할 수 있습니다.

2020-10-06 07:32 UTC, efenniht commented on kernel-rs/src/fs.rs
> +    pub unsafe fn dirlookup(&mut self, name: &FileName, poff: *mut u32) -> Result<*mut Inode, ()> {
poff 를 같이 리턴하는 게 더 직관적인 것 같습니다: `Result<(*mut Inode, u32), ()>`

2020-10-06 07:32 UTC, efenniht commented on kernel-rs/src/fs.rs
> +        while off < self.guard.size {
마찬가지로 `step_by` 를 사용할 수 있습니다.

2020-10-06 07:32 UTC, efenniht commented on kernel-rs/src/fs.rs
> +    drop(inode);
제 생각에 이 함수에서 굳이 drop 을 강조해서 적을 필요는 없을 것 같습니다.

2020-10-06 07:32 UTC, efenniht commented on kernel-rs/src/sleeplock.rs
> +    // TODO: transient measure
이 todo 는 이제 resolve 되었습니다!

2020-10-06 07:32 UTC, efenniht commented on kernel-rs/src/sysfile.rs
> +        while (off as u32) < self.guard.size {
마찬가지로 step_by 함수를 사용할 수 있습니다.

2020-10-06 07:32 UTC, efenniht commented on kernel-rs/src/sysfile.rs
> +                .map_or(true, |v| v != mem::size_of::<Dirent>())
마찬가지로 정리할 수 있습니다.

2020-10-06 07:32 UTC, efenniht commented on kernel-rs/src/sysfile.rs
> +                    .map_or(true, |v| v != mem::size_of::<Dirent>())
마찬가지로 정리할 수 있습니다.

2020-10-06 07:32 UTC, efenniht commented on kernel-rs/src/sysfile.rs
> +        ip.unwrap()
```suggestion
        ok_or!(create(path, T_FILE, 0, 0), {
            end_op();
            return usize::MAX;
        })
```
아래에도 unwrap 이 많은 데 unwrap 을 가능하면 피하는 것이 좋겠습니다.

2020-10-06 10:13 UTC, kimjungwow commented on kernel-rs/src/exec.rs
>      }
if 문의 || 대신 &&가 맞는 것 같습니다. 그렇게 수정하겠습니다!

2020-10-06 10:47 UTC, kimjungwow commented on kernel-rs/src/exec.rs
>      }
https://github.com/kaist-cp/rv6/pull/228/commits/324388ff35f0fe31b44c586c09d5e670c3f0fc68

2020-10-06 10:47 UTC, kimjungwow commented on kernel-rs/src/exec.rs
> +            .map_or(true, |v| v != ::core::mem::size_of::<ProgHdr>())
https://github.com/kaist-cp/rv6/pull/228/commits/324388ff35f0fe31b44c586c09d5e670c3f0fc68

2020-10-06 10:48 UTC, kimjungwow commented on kernel-rs/src/exec.rs
>              *sz = sz_op.unwrap();
https://github.com/kaist-cp/rv6/pull/228/commits/324388ff35f0fe31b44c586c09d5e670c3f0fc68

2020-10-06 10:48 UTC, kimjungwow commented on kernel-rs/src/exec.rs
> +    *sz = sz_op?;
https://github.com/kaist-cp/rv6/pull/228/commits/324388ff35f0fe31b44c586c09d5e670c3f0fc68

2020-10-06 10:48 UTC, kimjungwow commented on kernel-rs/src/exec.rs
> +                .map_or(true, |v| v as u32 != n)
https://github.com/kaist-cp/rv6/pull/228/commits/324388ff35f0fe31b44c586c09d5e670c3f0fc68

2020-10-06 10:48 UTC, kimjungwow commented on kernel-rs/src/file.rs
> +                })?;
https://github.com/kaist-cp/rv6/pull/228/commits/324388ff35f0fe31b44c586c09d5e670c3f0fc68

2020-10-06 10:48 UTC, kimjungwow commented on kernel-rs/src/fs.rs
> +                .map_or(true, |v| v != ::core::mem::size_of::<Dirent>())
https://github.com/kaist-cp/rv6/pull/228/commits/324388ff35f0fe31b44c586c09d5e670c3f0fc68

2020-10-06 10:48 UTC, kimjungwow commented on kernel-rs/src/fs.rs
> +            .map_or(true, |v| v != ::core::mem::size_of::<Dirent>())
https://github.com/kaist-cp/rv6/pull/228/commits/324388ff35f0fe31b44c586c09d5e670c3f0fc68

2020-10-06 10:48 UTC, kimjungwow commented on kernel-rs/src/fs.rs
> +                dst = (dst).wrapping_add(m as usize)
https://github.com/kaist-cp/rv6/pull/228/commits/324388ff35f0fe31b44c586c09d5e670c3f0fc68

2020-10-06 10:48 UTC, kimjungwow commented on kernel-rs/src/fs.rs
> +                .map_or(true, |v| v != ::core::mem::size_of::<Dirent>())
https://github.com/kaist-cp/rv6/pull/228/commits/324388ff35f0fe31b44c586c09d5e670c3f0fc68

2020-10-06 10:48 UTC, kimjungwow commented on kernel-rs/src/fs.rs
> +    drop(inode);
https://github.com/kaist-cp/rv6/pull/228/commits/324388ff35f0fe31b44c586c09d5e670c3f0fc68

2020-10-06 10:49 UTC, kimjungwow commented on kernel-rs/src/sleeplock.rs
> +    // TODO: transient measure
https://github.com/kaist-cp/rv6/pull/228/commits/324388ff35f0fe31b44c586c09d5e670c3f0fc68

2020-10-06 10:49 UTC, kimjungwow commented on kernel-rs/src/sysfile.rs
> +                    .map_or(true, |v| v != mem::size_of::<Dirent>())
https://github.com/kaist-cp/rv6/pull/228/commits/324388ff35f0fe31b44c586c09d5e670c3f0fc68

2020-10-06 10:53 UTC, kimjungwow commented on kernel-rs/src/sysfile.rs
> +                .map_or(true, |v| v != mem::size_of::<Dirent>())
https://github.com/kaist-cp/rv6/pull/228/commits/324388ff35f0fe31b44c586c09d5e670c3f0fc68

2020-10-06 10:53 UTC, kimjungwow commented on kernel-rs/src/fs.rs
> +                src = (src).wrapping_add(m as usize)
https://github.com/kaist-cp/rv6/pull/228/commits/324388ff35f0fe31b44c586c09d5e670c3f0fc68

2020-10-06 11:01 UTC, kimjungwow commented on kernel-rs/src/sysfile.rs
> +        ip.unwrap()
https://github.com/kaist-cp/rv6/pull/228/commits/c3041f1cef95a9ceeeabf130b986f5434871eda4

2020-10-06 11:10 UTC, kimjungwow commented on kernel-rs/src/fs.rs
> +    pub unsafe fn dirlink(&mut self, name: &FileName, inum: u32) -> bool {
https://github.com/kaist-cp/rv6/pull/228/commits/1890579d9c9f4cf6d3e4e120e7aaf6a183379ac1

2020-10-06 11:15 UTC, kimjungwow commented on kernel-rs/src/fs.rs
> +        while (off as u32) < self.guard.size {
여기서는 `off`가 밑에 `write()`에서 쓰이는데 마찬가지로 `step_by`를 사용해야할까요?

2020-10-06 11:30 UTC, kimjungwow commented on kernel-rs/src/sysfile.rs
> +        while (off as u32) < self.guard.size {
https://github.com/kaist-cp/rv6/pull/228/commits/e3fe75071b881608a9a2e2fb8812a2f03a8fc0f0

2020-10-06 11:31 UTC, kimjungwow commented on kernel-rs/src/fs.rs
> +        while off < self.guard.size {
https://github.com/kaist-cp/rv6/pull/228/commits/e3fe75071b881608a9a2e2fb8812a2f03a8fc0f0

2020-10-06 11:53 UTC, kimjungwow commented on kernel-rs/src/fs.rs
> +    pub unsafe fn dirlookup(&mut self, name: &FileName, poff: *mut u32) -> Result<*mut Inode, ()> {
https://github.com/kaist-cp/rv6/pull/228/commits/c08be76e3945c53b2c084c70afed944e3a658b66

2020-10-06 11:58 UTC, kimjungwow commented on kernel-rs/src/exec.rs
> +    unsafe fn loadseg(
https://github.com/kaist-cp/rv6/pull/228/commits/f0484937c8cef6f6575481450efc632bd7665b1c

2020-10-06 11:59 UTC, kimjungwow commented on kernel-rs/src/fs.rs
> +    pub unsafe fn stati(&self, mut st: *mut Stat) {
https://github.com/kaist-cp/rv6/pull/228/commits/78ec19e691428ff43696423c43f26727a92ce9a0

2020-10-06 12:02 UTC, efenniht commented on kernel-rs/src/fs.rs
> +        while (off as u32) < self.guard.size {
앗.. 그러면 그대로 두는 것이 좋겠습니다.

2020-10-06 16:16 UTC, kimjungwow commented on kernel-rs/src/file.rs
> +                        })?;
https://github.com/kaist-cp/rv6/pull/228/commits/782e575379bf013ca123614e7a177ec12cc7c0d7

2020-10-07 04:51 UTC, kimjungwow commented on kernel-rs/src/file.rs
> +pub struct InodeGuard<'a> {
## 수정중

> 그리고 이 타입과 Inode 관련 타입 & 메서드는 다른 파일로 옮기는 것이 좋겠습니다 (다음 PR에서?)

https://github.com/kaist-cp/rv6/pull/228/commits/422cf10cacfa419e54a620f37a2a3af04477d3f7 (TODO 작성)

> 마지막으로 InodeGuard 가 InodeInner 의 Deref를 구현하는 게 어떨까요?

https://github.com/kaist-cp/rv6/pull/228/commits/f60f8a6dfbd40a0a99e78363b3bcb4d613f1f149

2020-10-07 04:52 UTC, kimjungwow commented on kernel-rs/src/exec.rs
> +    };
https://github.com/kaist-cp/rv6/pull/228/commits/ba693e2aa15d5ce444596049ce6b58199daeafba

ptr를 `lock()`의 인자로 전달하지 않으면 이상하게 usertests가 fourfiles에서 넘어가지 않아서, 우선은 ptr을 인자로 전달하게 했습니다..

2020-10-07 08:58 UTC, kimjungwow commented on kernel-rs/src/fs.rs
> +    pub unsafe fn unlock(self) {
https://github.com/kaist-cp/rv6/pull/228/commits/1dd2dc64523e623eb0848dd74af56bb04f78b5e9

2020-10-07 09:02 UTC, kimjungwow commented on kernel-rs/src/exec.rs
> +    };
https://github.com/kaist-cp/rv6/pull/228/commits/f0dce1a563cc2164c7b1dc42ffd45a343d0a3b3b

2020-10-07 10:01 UTC, kimjungwow commented
@efenniht 리뷰 요청드립니다! 참고 : https://github.com/kaist-cp/rv6/pull/228#discussion_r500736029

2020-10-07 12:13 UTC, efenniht commented
고생하셨습니다. 디테일한 리뷰는 내일 하도록 하겠습니다. 코드를 훑어 보았는데 다음과 같이 수정할 수 있을 것 같습니다:

 - `InodeGuard::unlockput()` 의 인자 `ptr`을 생략하기 (`Inode::put()` 이 `&self` 를 받는 것이 옳다고 생각합니다.)
 - `Inode` 의 `valid` 필드를 `InodeInner` 에 집어넣기 (`valid` 는 lock 이 걸려있거나 ref==1 이라서 uniqueness 가 보장된 상태에서만 접근하는 하는 필드인 것 같습니다.)

2020-10-08 04:18 UTC, kimjungwow commented
> `InodeGuard::unlockput()` 의 인자 `ptr`을 생략하기 (`Inode::put()` 이 `&self` 를 받는 것이 옳다고 생각합니다.)

`Inode::put()`의 `self.ref_0 -= 1;`가 있어서, `&self`를 받으려면 `ref_0` 필드도 리팩토링해야 할 것 같습니다! 이 PR에서 진행할까요?

2020-10-08 08:29 UTC, efenniht commented
> > `InodeGuard::unlockput()` 의 인자 `ptr`을 생략하기 (`Inode::put()` 이 `&self` 를 받는 것이 옳다고 생각합니다.)
> 
> `Inode::put()`의 `self.ref_0 -= 1;`가 있어서, `&self`를 받으려면 `ref_0` 필드도 리팩토링해야 할 것 같습니다! 이 PR에서 진행할까요?

그러면 너무 일이 커질 것 같습니다. 아주 나쁜 코드지만 `*(&self.ref_0 as *const _ as *mut _) -= 1` 같은 짓을 해야할 것 같습니다 :sob:

2020-10-08 09:01 UTC, efenniht requested changes
고생하셨습니다 :carrot:

2020-10-08 12:53 UTC, kimjungwow commented on kernel-rs/src/file.rs
> +                drop(ip);
https://github.com/kaist-cp/rv6/pull/228/commits/24c58f1e47c8bc330aa9ce4668df02b490fc0703

2020-10-08 12:53 UTC, kimjungwow commented on kernel-rs/src/fs.rs
> +        (*st).dev = self.ptr.dev as i32;
https://github.com/kaist-cp/rv6/pull/228/commits/24c58f1e47c8bc330aa9ce4668df02b490fc0703

2020-10-08 12:53 UTC, kimjungwow commented on kernel-rs/src/fs.rs
> +    pub unsafe fn stati(&self, st: &mut Stat) {
https://github.com/kaist-cp/rv6/pull/228/commits/24c58f1e47c8bc330aa9ce4668df02b490fc0703

2020-10-08 12:53 UTC, kimjungwow commented on kernel-rs/src/fs.rs
> +        );
https://github.com/kaist-cp/rv6/pull/228/commits/24c58f1e47c8bc330aa9ce4668df02b490fc0703

2020-10-08 12:53 UTC, kimjungwow commented on kernel-rs/src/fs.rs
> +            );
https://github.com/kaist-cp/rv6/pull/228/commits/24c58f1e47c8bc330aa9ce4668df02b490fc0703

2020-10-08 12:54 UTC, kimjungwow commented on kernel-rs/src/fs.rs
>          );
https://github.com/kaist-cp/rv6/pull/228/commits/24c58f1e47c8bc330aa9ce4668df02b490fc0703

2020-10-08 12:54 UTC, kimjungwow commented on kernel-rs/src/fs.rs
> +        assert!(self.typ == T_DIR, "dirlookup not DIR");
https://github.com/kaist-cp/rv6/pull/228/commits/24c58f1e47c8bc330aa9ce4668df02b490fc0703

2020-10-08 12:54 UTC, kimjungwow commented on kernel-rs/src/fs.rs
> +    // (@kimjungwow) lock() receives `ptr` because usertest halts at `fourfiles` when `ptr` isn't given.
https://github.com/kaist-cp/rv6/pull/228/commits/24c58f1e47c8bc330aa9ce4668df02b490fc0703

2020-10-08 12:54 UTC, kimjungwow commented on kernel-rs/src/fs.rs
> +            );
https://github.com/kaist-cp/rv6/pull/228/commits/24c58f1e47c8bc330aa9ce4668df02b490fc0703

2020-10-08 12:54 UTC, kimjungwow commented on kernel-rs/src/fs.rs
> +        let inode_ptr = &*self;
https://github.com/kaist-cp/rv6/pull/228/commits/24c58f1e47c8bc330aa9ce4668df02b490fc0703

2020-10-08 12:55 UTC, kimjungwow commented on kernel-rs/src/fs.rs
> +            assert!(guard.typ != 0, "Inode::lock: no type");
https://github.com/kaist-cp/rv6/pull/228/commits/24c58f1e47c8bc330aa9ce4668df02b490fc0703

2020-10-08 12:55 UTC, kimjungwow commented on kernel-rs/src/fs.rs
> +            let mut ip = (*self).lock();
https://github.com/kaist-cp/rv6/pull/228/commits/24c58f1e47c8bc330aa9ce4668df02b490fc0703

2020-10-08 12:55 UTC, kimjungwow commented on kernel-rs/src/fs.rs
> +    assert!(SB.magic == FSMAGIC, "invalid file system");
https://github.com/kaist-cp/rv6/pull/228/commits/24c58f1e47c8bc330aa9ce4668df02b490fc0703

2020-10-08 12:55 UTC, kimjungwow commented on kernel-rs/src/fs.rs
> +    );
https://github.com/kaist-cp/rv6/pull/228/commits/24c58f1e47c8bc330aa9ce4668df02b490fc0703

2020-10-08 12:55 UTC, kimjungwow commented on kernel-rs/src/sysfile.rs
> +            );
https://github.com/kaist-cp/rv6/pull/228/commits/24c58f1e47c8bc330aa9ce4668df02b490fc0703

2020-10-08 12:55 UTC, kimjungwow commented on kernel-rs/src/sysfile.rs
> +                );
https://github.com/kaist-cp/rv6/pull/228/commits/24c58f1e47c8bc330aa9ce4668df02b490fc0703

2020-10-08 12:55 UTC, kimjungwow commented on kernel-rs/src/sysfile.rs
> +    assert!(dp.dirlink(&name, (*ptr2).inum).is_ok(), "create: dirlink");
https://github.com/kaist-cp/rv6/pull/228/commits/24c58f1e47c8bc330aa9ce4668df02b490fc0703

2020-10-08 12:55 UTC, kimjungwow commented on kernel-rs/src/sysfile.rs
> +        );
https://github.com/kaist-cp/rv6/pull/228/commits/24c58f1e47c8bc330aa9ce4668df02b490fc0703

2020-10-08 12:55 UTC, kimjungwow commented on kernel-rs/src/sysfile.rs
> +    let (ptr, name) = ok_or!(path.nameiparent(), return Err(()));
https://github.com/kaist-cp/rv6/pull/228/commits/24c58f1e47c8bc330aa9ce4668df02b490fc0703

2020-10-12 05:56 UTC, kimjungwow commented on kernel-rs/src/file.rs
>      pub addrs: [u32; 13],
https://github.com/kaist-cp/rv6/pull/228/commits/fac127f3de36d112e30cea7f89b86c228f718911

`as_ref().unwrap()` 대신 `match` 가 더 적절하다면 다시 변경하겠습니다! @efenniht

2020-10-12 06:14 UTC, kimjungwow commented on kernel-rs/src/fs.rs
> +            );
https://github.com/kaist-cp/rv6/pull/228/commits/a995317b983290e91310895602e65691e6e98fa9

`read_entry()`라는 method를 만들어서 중복되는 코드를 줄였는데 괜찮을까요? 
`InodeGuard::read()`에서 `off` 값을 `self.size`와도 비교하고, overflow가 발생하는지도 확인하기 때문에 `*mut Dirent` 자체에 `mem::size_of::<Dirent>()`를 계속 더해가는 것은 부적절하다고 판단했습니다.

2020-10-12 06:19 UTC, kimjungwow commented
@efenniht 상욱님! 말씀하시는 내용들 반영하였습니다 :)

2020-10-12 06:23 UTC, kimjungwow commented on kernel-rs/src/file.rs
> +pub struct InodeGuard<'a> {
https://github.com/kaist-cp/rv6/pull/228/commits/2228015038bac439524d9ba6fe89d5a9c3c24fc7

2020-10-15 09:50 UTC, efenniht requested changes
늦어서 죄송합니다 :sob: 이 PR 은 아래 내용만 수정해주시면 머지하겠습니다. 다음 PR 에서 Inode Cache 와 RcFile 의 Inode 버전 타입을 만들면 좋겠습니다.

2020-10-15 09:50 UTC, efenniht commented on kernel-rs/src/sysfile.rs
> +unsafe fn create(path: &Path, typ: i16, major: u16, minor: u16) -> Result<InodeGuard<'static>, ()> {
여기서 리턴하는 lifetime 은 `'static` 이면 위험한데 lockguard 를 리턴하는 자체가 별로 좋지 않은 행위이므로 이것도 일단 기록만 해 두고 다음 PR 에서 수정하는 것이 좋겠습니다.

2020-10-15 09:50 UTC, efenniht commented on kernel-rs/src/sysfile.rs
> +            ip: *(&ip.ptr as *const _ as *mut _),
```suggestion
            ip: ip.ptr as *const _ as *mut _,
```
그리고 이 함수 위의 `clippy::allow(..)` 를 제거할 수 있습니다.

2020-10-15 09:50 UTC, efenniht commented on kernel-rs/src/file.rs
>      pub addrs: [u32; 13],
죄송합니다만 Option<InodeInner> 로 바꾸었을 때 더 코드가 복잡해지고 딱히 safety 측면에서 더 좋아지는 것은 아닌 것 같습니다. 원래 valid=false 이면 다른 field 가 init되어있지 않기 때문에 이렇게 말씀드렸는데 이 값을 읽는 게 UB 는 아니네요... 원래대로 valid field 를 가지는 것이 좋을 것 같습니다.. 죄송합니다..

2020-10-15 10:48 UTC, kimjungwow commented on kernel-rs/src/file.rs
>      pub addrs: [u32; 13],
https://github.com/kaist-cp/rv6/pull/228/commits/2aa14b4546edfa2a07160b0b95d7e3a745b3eff2

2020-10-15 10:48 UTC, kimjungwow commented on kernel-rs/src/sysfile.rs
> +            ip: *(&ip.ptr as *const _ as *mut _),
https://github.com/kaist-cp/rv6/pull/228/commits/2aa14b4546edfa2a07160b0b95d7e3a745b3eff2
https://github.com/kaist-cp/rv6/pull/228/commits/8e8875f320cf64b909cc98933d11de7364fa8007

2020-10-15 10:49 UTC, kimjungwow commented on kernel-rs/src/sysfile.rs
> +unsafe fn create(path: &Path, typ: i16, major: u16, minor: u16) -> Result<InodeGuard<'static>, ()> {
https://github.com/kaist-cp/rv6/pull/228/commits/8e8875f320cf64b909cc98933d11de7364fa8007

2020-10-15 10:49 UTC, kimjungwow commented on kernel-rs/src/fs.rs
> +    fn read_entry(&mut self, ip: &mut InodeGuard<'_>, off: u32, panic_msg: &'static str) {
https://github.com/kaist-cp/rv6/pull/228/commits/8e8875f320cf64b909cc98933d11de7364fa8007

2020-10-15 10:49 UTC, kimjungwow commented on kernel-rs/src/fs.rs
> +pub const DIRENTSIZE: usize = mem::size_of::<Dirent>();
https://github.com/kaist-cp/rv6/pull/228/commits/4ed64e1b806aa8dbaceabbedcec1a18b7ee819b7

2020-10-15 10:49 UTC, kimjungwow commented on kernel-rs/src/fs.rs
> +        if !self.inner.get_mut_unchecked().is_some() {
https://github.com/kaist-cp/rv6/pull/228/commits/2aa14b4546edfa2a07160b0b95d7e3a745b3eff2

2020-10-15 10:49 UTC, kimjungwow commented on kernel-rs/src/fs.rs
> +        InodeGuard::new(guard, &*self)
https://github.com/kaist-cp/rv6/pull/228/commits/2aa14b4546edfa2a07160b0b95d7e3a745b3eff2

2020-10-15 11:33 UTC, kimjungwow commented
@efenniht 바쁘신데 리뷰해주셔서 감사합니다!!! 👍😁

2020-10-15 17:09 UTC, efenniht requested changes

2020-10-15 17:09 UTC, efenniht commented on kernel-rs/src/file.rs
> +pub struct InodeGuard<'a> {
여기 주석만 바꾸어 주시길 부탁드립니다 🥺

2020-10-15 17:09 UTC, efenniht commented on kernel-rs/src/fs.rs
> +        if !self.inner.get_mut_unchecked().valid {
여기서 `get_mut_unchecked()` 안 쓰고 `guard.valid` 로 쓸 수 있을 것 같습니다.

2020-10-15 18:18 UTC, kimjungwow commented
@efenniht ping

2020-10-15 19:40 UTC, efenniht approved these changes

2020-10-15 19:40 UTC, merged