[sub pr from #226, #195] vm.rs refactoring
kaist-cp/rv6 pull request #252
Opened 2020-10-27 08:17 UTC by anemoneflower

진행상황 공유 및 1차 pr merge를 위해 draft를 올립니다. (rebase를 진행했는데 conflict가 많이 발생해서 남은 부분을 merge 하고 진행하는 것이 좋을 것 같습니다.)

---
현재 진행한 부분은 다음과 같습니다.
- `Virtual Addr` trait과 'PAddr', `KVAddr`, `UVAddr` struct를 통해 address type을 구분했습니다.
  - `either_copyin`, `either_copyout`함수에 `Virtual Addr`을 적용했습니다.
  - pagetable 관련 함수들에도 바뀐 구조를 적용했습니다.
---
아직 진행하지 않은 부분은 이렇습니다.
- `uvmcopy`에서 `pa` 말고 `u8`의 slice를 복사하도록 수정하는 방안 고민
- `copyin`함수가 `*mut u8`대신 `&[u8]`을 사용하도록 수정

2020-10-27 08:20 UTC, anemoneflower commented on kernel-rs/src/console.rs
> +    unsafe fn read<A: VirtualAddr + Copy>(
`dst` 때문에 임시로 Copy를 사용했습니다. Copy를 remove하는 방법에 대한 조언을 구합니다.

2020-10-27 08:21 UTC, anemoneflower reviewed
Copy 사용에 대한 질문입니다.

2020-10-27 08:21 UTC, anemoneflower commented on kernel-rs/src/fs/inode.rs
> +    pub unsafe fn read<A: VirtualAddr + Copy>(
`dst` 때문에 임시로 Copy를 사용했습니다. Copy를 remove하는 방법에 대한 조언을 구합니다.

2020-10-27 08:21 UTC, anemoneflower commented on kernel-rs/src/fs/inode.rs
> +    pub unsafe fn write<A: VirtualAddr + Copy>(
`src` 때문에 임시로 Copy를 사용했습니다. Copy를 remove하는 방법에 대한 조언을 구합니다.

2020-10-27 18:09 UTC, jeehoonkang requested changes

2020-10-27 18:09 UTC, jeehoonkang commented on kernel-rs/src/vm.rs
> +pub trait VirtualAddr {
KVAddr, UVAddr을 아우르는 trait이서 VAddr이 어떨까 합니다.

2020-10-27 18:09 UTC, jeehoonkang commented on kernel-rs/src/proc.rs
> +pub unsafe fn either_copyin<A: VirtualAddr>(dst: *mut u8, src: A, len: usize) -> Result<(), ()> {
- 이렇게 간단하면 굳이 정의할 필요가?
- 원래 로직은 좀 복잡해보이는데 이렇게 간단히 만들 수 있는지 궁금합니다.

2020-10-27 18:09 UTC, jeehoonkang commented on kernel-rs/src/console.rs
> +    unsafe fn write<A: VirtualAddr>(&mut self, src: A, n: i32) {
src가 kernel/user addr 모두 가능한가요?

2020-10-27 18:09 UTC, jeehoonkang commented on kernel-rs/src/console.rs
> +    unsafe fn read<A: VirtualAddr + Copy>(
VirtualAddr에 Clone + Copy를 요구하면 어떨까 합니다.

2020-10-27 18:09 UTC, jeehoonkang commented on kernel-rs/src/console.rs
>  unsafe fn consolewrite(user_src: i32, src: usize, n: i32) -> i32 {
하는김에 boolean으로 바꿉시다 user_src

2020-10-27 18:09 UTC, jeehoonkang commented on kernel-rs/src/fs/inode.rs
> +    pub unsafe fn read<A: VirtualAddr + Copy>(
같은 종류의 코멘트는 한번만 달아도 됩니다.

2020-10-27 18:09 UTC, jeehoonkang commented on kernel-rs/src/pipe.rs
> +                .copyout(UVAddr::wrap(addr.wrapping_add(i)), &ch, 1usize)
"wrap": 혹시 이런 경우에 자주 쓰이는 단어인지 궁금합니다  new()가 아닌 이유는?

2020-10-27 18:09 UTC, jeehoonkang commented on kernel-rs/src/vm.rs
> +    pub unsafe fn walkaddr(&mut self, va: A) -> Option<usize> {
혹시 메소드 구현 순서를 바꾼 이유가 있나요?

2020-10-27 18:09 UTC, jeehoonkang commented on kernel-rs/src/vm.rs
> +    pa + off
why?

2020-10-28 02:17 UTC, coolofficials reviewed
https://github.com/kaist-cp/rv6/issues/195#issuecomment-703481936 의 논의도 반영하고 계신 것 같은데, 세부 사항에 대해 한 번 공유가 되면 좋을 것 같습니다:)

2020-10-28 02:17 UTC, coolofficials commented on kernel-rs/src/console.rs
>  unsafe fn consolewrite(user_src: i32, src: usize, n: i32) -> i32 {
교수님, 해당 내용 관련해서 https://github.com/kaist-cp/rv6/issues/195#issuecomment-703481936 와 같은 논의가 있었습니다. 논의에 대한 교수님의 의견이 궁금합니다.

2020-10-28 02:17 UTC, coolofficials commented on kernel-rs/src/console.rs
> +    unsafe fn write<A: VirtualAddr>(&mut self, src: A, n: i32) {
저는 user address만 가능한 것으로 알고 있습니다. 아마 https://github.com/kaist-cp/rv6/issues/195#issuecomment-703481936 의 논의에 대해 반영하고자 하셨던 것 같습니다.

2020-10-28 11:08 UTC, anemoneflower commented on kernel-rs/src/console.rs
> +    unsafe fn write<A: VirtualAddr>(&mut self, src: A, n: i32) {
기존 코드를 보고 `VirtualAddr`을 사용했습니다. `UVAddr`로 수정했습니다!

2020-10-29 23:10 UTC, anemoneflower commented on kernel-rs/src/proc.rs
> +pub unsafe fn either_copyin<A: VirtualAddr>(dst: *mut u8, src: A, len: usize) -> Result<(), ()> {
proc.rs의 `either_copyin`, `either_copyout`의 함수에 정의되어 있던 내용을 vm.rs의 `VAddr`에서 `KVAddr`과 `UVAddr`의 경우로 나누어 구현했습니다.

https://github.com/kaist-cp/rv6/blob/f47fff4b5b276c9a36abc632803c574cb2bb35ad/kernel-rs/src/vm.rs#L144-L153

https://github.com/kaist-cp/rv6/blob/f47fff4b5b276c9a36abc632803c574cb2bb35ad/kernel-rs/src/vm.rs#L168-L183

2020-10-29 23:12 UTC, anemoneflower commented on kernel-rs/src/pipe.rs
> +                .copyout(UVAddr::wrap(addr.wrapping_add(i)), &ch, 1usize)
`new()`로 수정했습니다!

2020-10-29 23:26 UTC, anemoneflower commented on kernel-rs/src/vm.rs
> +    pub unsafe fn walkaddr(&mut self, va: A) -> Option<usize> {
RawPageTable에서 `walk`를 사용하는 메소드를 `PageTable`로 옮겼습니다.

2020-10-29 23:32 UTC, anemoneflower commented on kernel-rs/src/vm.rs
> +    pa + off
address를 다루는 부분이라서 overflow가 나는 것이 옳지 않기 때문에 `wrapping_add`대신 `+`를 사용하도록 수정했습니다.

2020-10-30 04:38 UTC, jeehoonkang requested changes

2020-10-30 04:38 UTC, jeehoonkang commented on kernel-rs/src/console.rs
> +                dst.update(dst.value() + 1);
굳이 update 메소드를 안만들어도 될거같아요  원래 있던대로가 좋아보입니다.

2020-10-30 04:38 UTC, jeehoonkang commented on kernel-rs/src/console.rs
> +unsafe fn consolewrite(user_src: bool, src: usize, n: i32) -> i32 {
uvaddr만 받도록 수정해도 되나요?

2020-10-30 04:38 UTC, jeehoonkang commented on kernel-rs/src/console.rs
> +unsafe fn consoleread(user_dst: bool, dst: usize, n: i32) -> i32 {
위와 마찬가지

2020-10-30 04:38 UTC, jeehoonkang commented on kernel-rs/src/exec.rs
> +        let bytes_read = ip.read(KVAddr::new(pa), offset.wrapping_add(i), n)?;
음 잘은 모르겠지만 이걸 보면 kernal address만 지원하는게 맞지 않나 합니다.

2020-10-30 04:38 UTC, jeehoonkang commented on kernel-rs/src/proc.rs
> +pub unsafe fn either_copyout<A: VAddr>(dst: A, src: &[u8]) -> Result<(), ()> {
그냥 없애도 될거같아요

2020-10-30 04:38 UTC, jeehoonkang commented on kernel-rs/src/proc.rs
> +pub unsafe fn either_copyin<A: VAddr>(dst: *mut u8, src: A, len: usize) -> Result<(), ()> {
ditto

2020-10-30 04:38 UTC, jeehoonkang commented on kernel-rs/src/vm.rs
> +    pub const fn wrap(value: usize) -> Self {
new?

2020-10-30 04:38 UTC, jeehoonkang commented on kernel-rs/src/vm.rs
> +    pub const fn value(self) -> usize {
제 생각에
- Addr 관련 struct를 모두 clone, copy로 하고
- 이 함수의 이름을 into_usize로 만든느게 좋겠ㅅ븐디ㅏ

2020-10-30 04:38 UTC, jeehoonkang commented on kernel-rs/src/vm.rs
> +    fn update(&mut self, new: usize);
이건 그냥 없는게 좋겠습니다.

2020-10-30 06:52 UTC, anemoneflower commented on kernel-rs/src/vm.rs
> +    fn update(&mut self, new: usize);
`VAddr` 내부의 `usize`를 변경하기 위해서 `update`대신에 `add`를 implement 했습니다.

2020-10-30 07:02 UTC, anemoneflower commented on kernel-rs/src/exec.rs
> +        let bytes_read = ip.read(KVAddr::new(pa), offset.wrapping_add(i), n)?;
file.rs에서 `UVAddr`을 사용하고 있습니다.

https://github.com/kaist-cp/rv6/blob/08b59ef6476f2f2b6334b435d670671ceec39a4b/kernel-rs/src/file.rs#L109

2020-10-30 07:23 UTC, jeehoonkang commented on kernel-rs/src/exec.rs
> +        let bytes_read = ip.read(KVAddr::new(pa), offset.wrapping_add(i), n)?;
아 아뇨 loadseg 함수에서 kvaddr만 지원하는게 어떠냐는 의견이었습니다.

2020-10-30 08:29 UTC, anemoneflower commented on kernel-rs/src/exec.rs
> +        let bytes_read = ip.read(KVAddr::new(pa), offset.wrapping_add(i), n)?;
https://github.com/kaist-cp/rv6/blob/4c4221c7b911e00548cb1efe6eed5bcfcab3dff2/kernel-rs/src/exec.rs#L77

`loadseg`에 사용되는 `pt`가 `PageTable<UVAddr>`이기 때문에 

https://github.com/kaist-cp/rv6/blob/4c4221c7b911e00548cb1efe6eed5bcfcab3dff2/kernel-rs/src/exec.rs#L41

`UVAddr`을 사용하도록 수정했습니다.

2020-10-30 08:44 UTC, jeehoonkang approved these changes
- Draft인데 머지해도 되나요?
- usize로 address 표현하던거 모두 PAddr/KVAddr/UVAddr로 변경했는지 확인 부탁드려요.

2020-10-30 10:47 UTC, anemoneflower commented
확인 후 rebase까지 완료했습니다.

2020-10-30 12:44 UTC, merged