[minor issue from #271] inode.rs -> mod.rs dependency
kaist-cp/rv6 pull request #277
Opened 2020-11-13 06:16 UTC by anemoneflower

- minor한 depencency입니다.

---

- mod.rs에 있던 `bzero`, `balloc`, `bfree`는 inode에서만 사용되기 때문에 inode.rs로 옮겼습니다.
- mod.rs에 있던 IPB를 inode.rs에서 정의하고, Dinode를 private하게 바꿨습니다.

2020-11-13 06:22 UTC, jeehoonkang requested changes

2020-11-13 06:22 UTC, jeehoonkang commented on kernel-rs/src/fs/inode.rs
> +    let mut bp = Disk::read(dev as u32, bno as u32);
이 부분에서 read 말고 buf만 얻어와도 될까요? @kimjungwow

2020-11-13 06:22 UTC, jeehoonkang commented on kernel-rs/src/fs/inode.rs
> +/// Blocks.
주석이 좀 이상한 것 같습니다.

2020-11-13 06:22 UTC, jeehoonkang commented on kernel-rs/src/fs/inode.rs
> +    let mut bp = Disk::read(dev as u32, bno as u32);
또한 이거는 왜 여기로 옮겼는지 궁금합니다.  balloc도..

2020-11-13 06:22 UTC, anemoneflower commented
<img width="659" alt="inode-mod" src="https://user-images.githubusercontent.com/31069340/99035839-d3f79280-25c3-11eb-8dba-af251baa94ab.PNG">

수정내용이 반영되면, mod.rs와 inod.rs사이의 (변수를 제외한) dependency는 `InodeGuard`와 `Dirent`만 남습니다.

2020-11-13 06:26 UTC, anemoneflower commented on kernel-rs/src/fs/inode.rs
> +    let mut bp = Disk::read(dev as u32, bno as u32);
balloc, bzero, bfree를 inode.rs에서만 사용하기 때문에 inode.rs로 옮겼습니다.

2020-11-13 12:13 UTC, jeehoonkang requested changes
지금 그래프의 엣지를 줄이는 것에 집중하기보다는 각 메서드의 의미에 대해 생각하고 리팩토링하는게 좋겠습니다.

2020-11-13 12:13 UTC, jeehoonkang commented on kernel-rs/src/fs/inode.rs
> +                bp.deref_mut_inner().data[(bi / 8) as usize] =
이 PR이랑 상관 없이면 `... |= m;` 이렇게도 되나요?

2020-11-13 12:13 UTC, jeehoonkang commented on kernel-rs/src/fs/inode.rs
> +    let mut bp = Disk::read(dev as u32, bno as u32);
음 제 느낌에 disk에 있어야 하는 것 같다는 인상이 들었습니다.  어떻게 보시나요?

@kimjungwow 정우님도 의견 부탁드려요.

2020-11-13 13:13 UTC, coolofficials commented on kernel-rs/src/fs/inode.rs
> +    let mut bp = Disk::read(dev as u32, bno as u32);
제 생각에는 Edge를 줄이는게 중요한 요소가 아니라면, 의미적으로는 Log에 있는 것이 좋을 것 같습니다. `balloc`, `bfree`도 마찬가지라고 생각합니다.

2020-11-17 08:30 UTC, anemoneflower commented on kernel-rs/src/fs/inode.rs
> +    let mut bp = Disk::read(dev as u32, bno as u32);
저도 의미적으로보면 disk에 있는 것이 맞다고 생각합니다.

2020-11-17 08:40 UTC, anemoneflower commented on kernel-rs/src/fs/inode.rs
> +                bp.deref_mut_inner().data[(bi / 8) as usize] =
`bp.deref_mut_inner().data[(bi / 8) as usize]`가 `u8` type이고 `m`은 `i32`라서 안되는 듯 합니다.

2020-11-17 08:51 UTC, kimjungwow reviewed
리뷰가 늦어 죄송합니다!! @anemoneflower

2020-11-17 08:51 UTC, kimjungwow commented on kernel-rs/src/fs/inode.rs
> +    let mut bp = Disk::read(dev as u32, bno as u32);
> 이 부분에서 read 말고 buf만 얻어와도 될까요?

**`Disk::read()`를 사용해야 한다고 생각합니다.** 2개의 프로세스가 같은 file descriptor에 write를 실행할 때 offset이 공유되는지를 판단하는 sharedfd usertest 때문에 `bzero()`에서는 `BufUnlocked::new(dev as u32, bno as u32).lock()`이 아닌 `Disk::read(dev as u32, bno as u32);`로 `bp`를 가져와야 할 것 같습니다.
 
> 음 제 느낌에 disk에 있어야 하는 것 같다는 인상이 들었습니다. 어떻게 보시나요?

**`balloc, bzero, bfree`는 disk에 있는 것이 맞다고 생각합니다.** 세 함수 모두 주체가 Disk로 보입니다. bfree는 Disk를 update하는 것으로 이해했습니다.

2020-11-17 08:51 UTC, kimjungwow commented on kernel-rs/src/fs/inode.rs
> +    let mut bp = Disk::read(dev as u32, bno as u32);
`bzero()`의 `dev, bno`도 `i32`에서 `u32`로 바뀌어야 할 것 같습니다 @anemoneflower

2020-11-17 10:28 UTC, kimjungwow commented
개인 일정 마치고 (오늘 안에) 리뷰 내용을 보충한 뒤 핑드리겠습니다!

2020-11-17 17:16 UTC, kimjungwow requested changes
제 코멘트를 보충하고자 다시 리뷰 올립니다! 😎

- `balloc()`
  - Disk에 있는 block 중 새로운 disk block을 할당해주는 함수이기 때문에 Disk가 주체라고 생각합니다. 
- `bzero()`
  - `balloc()`에서 Disk의 block 중 bitmap bit이 zero인 block을 찾은 뒤, `bzero()`는 `bread()`를 통해 해당하는 disk block의 the latest content를 가져옵니다. 이 후 해당 block을 zeroize해주고 (나중에 몰아서) Disk에 반영시키고자 `log_write()`를 실행합니다. 결국 Disk의 block을 새로운 내용으로 바꾸기 위한 작업이기 때문에 Disk가 `bzero()`의 주체라고 생각합니다.
- `bfree()`
  - `bzero()`와 비슷하게 block의 bitmap bit을 0으로 만든 뒤, (나중에 몰아서) Disk에 적용하고자 `log_write()`를 실행합니다. 마찬가지로 Disk의 block을 새로운 내용으로 바꾸기 위한 작업이기 때문에 Disk가 `bfree()`의 주체라고 생각합니다.

> 음... block을 zeroing 하는 것도 일종의 logging이라고 생각했는데, 어떻게 생각하시나요?

block이 내용을 zero로 만들거나 (`bzero()`) bitmap bit을 0으로 만드는 (`bfree()`) 행위 : block을 수정하는 행위는 logging의 일부보다는 Disk가 주체인 행위라고 생각합니다.
차후에 몰아서 on-disk file system을 수정하기 위해 `log_write()`를 실행하는 것은 logging이라고 생각합니다.
block을 zeroing하는 것의 궁극적인 목표가 결국 log에 적어두기 위한 것이 아닌, 그 이후에 Disk를 수정하기 위한 것이기 때문입니다.

2020-11-17 17:16 UTC, kimjungwow commented on kernel-rs/src/fs/inode.rs
> +        (bp.deref_mut_inner().data[(bi / 8) as usize] as i32 & !m) as u8;
```suggestion
    bp.deref_mut_inner().data[(bi / 8) as usize] &= (!m) as u8;
```

2020-11-17 17:58 UTC, efenniht commented on kernel-rs/src/fs/inode.rs
> +                    (bp.deref_mut_inner().data[(bi / 8) as usize] as i32 | m) as u8; // Mark block in use.
FYI... https://lib.rs/crates/bitvec

2020-11-17 18:02 UTC, coolofficials commented
https://github.com/kaist-cp/rv6/pull/277#pullrequestreview-532563148
@kimjungwow 님의 답변에 대한 생각입니다.

1) `Log`의 존재의미를 명확하게 할 필요가 있다고 생각합니다.
- Logging의 역할은 `Disk`에 쓸 내용들을 모아뒀다가 `commit`이 일어날 때 `write_log` 함수를 통해 `Disk`에 적는 것으로 알고 있습니다. "결국 `Disk`의 `block`을 새로운 내용으로 바꾸기 위한 작업이기 때문에 `Disk`가 `bzero()`의 주체라고 생각합니다." 라는 내용만으로 `bzero`가 `Disk`의 일부여야 한다고 주장하기에는, `Log`의 존재 의미가 퇴색된다고 생각합니다.

2) 만약 `bzero`, `bfree` 등의 함수를 `Disk`로 옮긴다면 `Disk`<->`Log`의 Acyclic graph 구성을 위해서 너무 많은 cost가 발생할 것 같습니다.
- `bzero`와 `bfree` 모두 `log_write` 함수를 사용하고 있고, 이 부분은 개발자의 의도가 강하게 담긴 부분이라고 생각합니다.
- `Log`의 `read/write_head`, `install_trans`, `write_log` 등의 내부에서 `Disk`의 `read/write` function을 사용하고 있습니다. `write_log`는 `Disk`로 옮겨도 의미가 퇴색되지 않는 method라고 생각하지만, 다른 method들은 `Log`에 존재하는 것이 옳다고 생각됩니다.
- 이를 해소하기 위해서는 logic 단계에서의 수정이 필요해 개발자의 의도를 유지하면서 수정하기가 까다롭다고 생각합니다.

3) @jeehoonkang 근본적으로 Acyclic한 dependency를 만드는 것이 얼마나 큰 의의를 갖는지 여쭤보고 싶습니다.

4) `block`이라는 type을 새로 분리하면 더 나은 추상화 및 dependency를 해소하는데 도움을 줄 수도 있다고 생각하는데, 어떻게 생각하시나요?

2020-11-17 18:11 UTC, jeehoonkang commented
- dependency: module별로 safety reasoning을 하기 위해 dependency를 적절하게 끊는게 중요합니다.  끊지 못하면 inter-dependency가 있는 모든 모듈을 한꺼번에 reasoning해야 하므로 매우 어려울 것으로 생각합니다.

- bzero: 저도 bzero, balloc, ...은 disk라기보다는 logging 혹은 그 상위 layer인 것 같습니다.  시원님이 말씀하신 것과 같은 이유입니다.

2020-11-18 02:42 UTC, jeehoonkang commented
이 문제와 관련하여 #279 에서 제 아이디어를 실험해보고 있습니다.

2020-11-20 12:16 UTC, anemoneflower commented
- `balloc()`, `bzero()`, `bfree()`에 관한 내용은 #279 merge로 해결될 예정이라서 해당 내용인 commit 0238372는 revert 했습니다.
- 현재 PR에서 수정된 코드는 `Dinode`를 private하게 바꾸는 부분과 https://github.com/kaist-cp/rv6/pull/277#discussion_r525308104 수정사항에 대한 부분입니다.

2020-11-20 12:18 UTC, jeehoonkang requested changes
이거 conflict이 많이 생길 것 같은데 그냥 여기 있는 수정사항을 (commit 하나로) #279 에 올리면 어떨까 합니다.

2020-11-20 12:18 UTC, jeehoonkang commented on kernel-rs/src/fs/mod.rs
> +    bp.deref_mut_inner().data[(bi / 8) as usize] &= (!m) as u8;
!(m as u8) 인게 더 가독성이 좋을 것 같아요.

2020-11-20 12:21 UTC, coolofficials commented on kernel-rs/src/fs/mod.rs
> +unsafe fn bzero(dev: u32, bno: u32) {
dev랑 bno가 usize가 아니라 u32인 이유가 무엇인가요?

2020-11-20 12:51 UTC, anemoneflower commented on kernel-rs/src/fs/mod.rs
> +unsafe fn bzero(dev: u32, bno: u32) {
```c
static struct buf*
bget(uint dev, uint blockno)
```
두 변수는 xv6에서 `uint`로 사용되고 있습니다. 덧붙이자면, `usize`로 사용해도 무관하지만 두 변수는 plain number이기 때문에 `u32`를 사용하는게 더 좋은 방향이라고 생각합니다. (FYI..(?) https://stackoverflow.com/questions/29592256/whats-the-difference-between-usize-and-u32/29592369#29592369)

2020-11-20 12:58 UTC, anemoneflower commented
#279에 현재 pr내용 추가합니다!

2020-11-20 13:24 UTC, closed without merging