Merge mit pdos [4] (related to #261)
kaist-cp/rv6 pull request #281
Opened 2020-11-19 04:22 UTC by kimjungwow

### Rust 코드에 반영되었는지 한 번 더 확인 후 리뷰 요청 드리겠습니다 (related to #261 )

- [ ] https://github.com/mit-pdos/xv6-riscv/commit/db0f092ae44f85db450718588c2deea080c27d0e: fix printf() in interrupts
  - Uart::putc_sync() 생성 + Uart::putc()의 bool 타입 인자 제거 -> Rust 반영 완료
- [ ] https://github.com/mit-pdos/xv6-riscv/commit/050a69610afee9884bc3df27215d0d5534743975 : defines for UART register bits
  - `uart.c`에서 하드 코딩된 값을 사용하는 대신, define으로 설정함 -> `uart.rs`에 반영 완료  
- [ ] https://github.com/mit-pdos/xv6-riscv/commit/6c3099d31401dfb76204c276572b7a34caad9b44 : Change tf -> trapframe in a few comments
  - `trampoline.S`에만 적용되어 Rust 해당 사항 없음  
- [ ] https://github.com/mit-pdos/xv6-riscv/commit/8b9b7999376f67f45cf9efde675d418841a264ce : modify each page in usertests countfree()
  - `vm.c`의 `walk(), freewalk()`에서 static 제거 -> Rust는 해당 사항 없음 (pub 함수도 아님)
- [ ] https://github.com/mit-pdos/xv6-riscv/commit/f01b1a8b71b8e0e8d7564a475a31c4e951463874 : test pointer checking in copyin, copyout, copyinstr
  - `usertests.c` 변경 : Rust 해당 사항 없음
  - `copyin` usertest를 통과하기 위해 `File::write, InodeGuard::write`도 차후의 PR (https://github.com/mit-pdos/xv6-riscv/commit/5e392531c07966fd8a6bee50e3e357c553fb2a2f)을 따라 미리 변경
- [ ] https://github.com/mit-pdos/xv6-riscv/commit/354adfdafc3993771f58236771e213016ff9aed8 : streamline copyin/copyout code in usertests
  - console, inode, pipe의 read/write에서 에러 있을 때 return value 관련 버그 수정..
- [ ] https://github.com/mit-pdos/xv6-riscv/commit/234391b6bf4d4809930300c1637403987c273461 : test copyinstr()'s handling of the terminating null
  - `usertests.c` 변경 : Rust 해당 사항 없음
- [ ] https://github.com/mit-pdos/xv6-riscv/commit/6cb6764bb1778b8c4f92680295f928fec074e3d7 : test string system call arguments that cross over the end of the last…
  - `usertests.c` 변경 : Rust 해당 사항 없음   
- [ ] https://github.com/kaist-cp/rv6/commit/aa902bbcbced258aa1c996422df26f5a01429975 : [All usertests passed] To pass usertest copyin
  - copyin usertest 통과하기 위해 차후의 xv6-riscv commit을 미리 반영함 (주석도 적었습니다)
- [ ] https://github.com/mit-pdos/xv6-riscv/commit/897f6f34ddf2b45f7ef0e2474691f28cb6c9c0bd : yet another toolchain name
  - xv6-riscv에서 merge하는 과정 : Rust에 이미 적용 완료
- [ ] https://github.com/mit-pdos/xv6-riscv/commit/b62d4d412bf36eb445dd05cf80762ba8837de6ce : more grind
  - xv6-riscv에서 merge하는 과정 : Rust에 이미 적용 완료
- [ ] https://github.com/mit-pdos/xv6-riscv/commit/672217ae2a3d68b73b2229ab368979ef7790e28a : allow more files 
  - xv6-riscv에서 merge하는 과정 : Rust에 이미 적용 완료
- [ ] https://github.com/mit-pdos/xv6-riscv/commit/af9eb9114c2f8700d4315eaa1e2d637c2aaaf210 : make "echo hello > x" truncate file x.
  - xv6-riscv에서 merge하는 과정 : Rust에 이미 적용 완료
- [ ] https://github.com/mit-pdos/xv6-riscv/commit/82981fab6bbd36dc0ff24201a11d365c4a2c6b1d : drop QEMUEXTRA
  - xv6-riscv에서 merge하는 과정 : Rust에 이미 적용 완료
- [ ] https://github.com/mit-pdos/xv6-riscv/commit/5494c9170587b17c9d749e19753fa3e7fb6958b9 : rename p->tf to p->trapframe, for consistency with p->context
  - xv6-riscv에서 merge하는 과정 : Rust에 이미 적용 완료
- [ ] https://github.com/mit-pdos/xv6-riscv/commit/1e72d5ca087985938589ce509ace4914039860d3 : cpu->scheduler -> cpu->context to reduce confusion
  - xv6-riscv에서 merge하는 과정 : Rust에 이미 적용 완료   
- [ ] https://github.com/mit-pdos/xv6-riscv/commit/27057bc9b467db64a3de600f27d6fa3239a04c88 : interrupt-driven uart output, hopefully a nice example for teaching.
  - xv6-riscv에서 merge하는 과정 : Rust에 이미 적용 완료   
- [ ] https://github.com/mit-pdos/xv6-riscv/commit/0f50e9527c68168c8114a38b211a8744e3bd2473 : fix printf() in interrupts
  - xv6-riscv에서 merge하는 과정 : Rust에 이미 적용 완료   
- [ ] https://github.com/mit-pdos/xv6-riscv/commit/2ae9c8e2722282d9a619c1745d845fb5d862c518 : defines for UART register bits
  - xv6-riscv에서 merge하는 과정 : Rust에 이미 적용 완료   
- [ ] https://github.com/mit-pdos/xv6-riscv/commit/7f35d7a14efe56905d340a0e318f01c7c514320d : modify each page in usertests countfree()
  - xv6-riscv에서 merge하는 과정 : Rust에 이미 적용 완료   
- [ ] https://github.com/mit-pdos/xv6-riscv/commit/1f555198d61d1c447e874ae7e5a0868513822023 : Change tf -> trapframe in a few comments
  - `trampoline.S` 내 주석의 `tf`를 `trapframe`으로 변경 : Rust 해당 사항 없음

2020-11-19 06:44 UTC, jeehoonkang requested changes

2020-11-19 06:44 UTC, jeehoonkang commented on kernel-rs/src/file.rs
> +                // TODO(@kimjungwow) : To pass copyin() usertest,
혹시 이 TODO에 대해 더 설명 부탁드립니다.

2020-11-19 06:44 UTC, jeehoonkang commented on kernel-rs/src/file.rs
> +                    if r? != bytes_to_write as usize {
물음표는 위에서 `let r = ...` 할때 하는게 더 좋겠습니다.

2020-11-19 06:44 UTC, jeehoonkang commented on kernel-rs/src/pipe.rs
> -        for i in 0..n {
그냥 for로 하고 나중에 n을 리턴하면 안되나요?

2020-11-19 06:44 UTC, jeehoonkang commented on kernel-rs/src/uart.rs
> +const IER_TX_ENABLE: u8 = 1 << 0;
Bitflag면 bitflags! 를 사용하는게 어떨가 합니다.

2020-11-19 06:44 UTC, jeehoonkang commented on kernel-rs/src/uart.rs
> +        unsafe {
위에 엔터 하나 넣어주는게 더 가독성이 높을 것 같습니다.

2020-11-19 12:29 UTC, kimjungwow commented on kernel-rs/src/file.rs
> +                // TODO(@kimjungwow) : To pass copyin() usertest,
- 이 PR에서 새롭게 반영한 `copyin()`이라는 usertest가 있는데, 이 PR에서 다룬 commit만으로는 `copyin()`을 통과하지 못합니다. 따라서 mit-pdos의 더 나중 (2020/11/5) 커밋을 미리 반영하였다는 의미였습니다. 
- 2020/11/5 커밋까지 upstream 따라잡기가 순조롭게 진행되면 이 코멘트는 지우겠습니다.
- 위 내용을 담도록 코멘트도 수정하였습니다.

https://github.com/kaist-cp/rv6/pull/281/commits/e6f6b46f40c1f93d6ef211097140c201b4f14278

2020-11-19 12:29 UTC, kimjungwow commented on kernel-rs/src/pipe.rs
> -        for i in 0..n {
https://github.com/kaist-cp/rv6/pull/281/commits/e6f6b46f40c1f93d6ef211097140c201b4f14278

2020-11-19 12:30 UTC, kimjungwow commented on kernel-rs/src/uart.rs
> +        unsafe {
` while LSR.read() & LSR_TX_IDLE == 0 {}`
`THR.write(c as u8);`
`unsafe {..`
세 줄 모두 역할이 달라서 사이사이에 엔터를 넣었습니다!
https://github.com/kaist-cp/rv6/pull/281/commits/e6f6b46f40c1f93d6ef211097140c201b4f14278

2020-11-19 12:30 UTC, kimjungwow commented on kernel-rs/src/file.rs
> +                    if r? != bytes_to_write as usize {
https://github.com/kaist-cp/rv6/pull/281/commits/e6f6b46f40c1f93d6ef211097140c201b4f14278

2020-11-19 12:41 UTC, kimjungwow commented on kernel-rs/src/uart.rs
> +const IER_TX_ENABLE: u8 = 1 << 0;
### 이 PR에서 `uart.rs`에 추가한 const들은 bitflags를 사용하기 껄끄러울 것 같습니다 😥 @jeehoonkang 
- write 시 **비트 별로 적는 것이 아닌** `ptr::write_volatile()`을 사용합니다. (`bitflags::insert()`와 다른 의미로 이해했습니다)
- 이 const 변수들은 `UART0`에 임의의 수를 더해 얻어지는 `*mut u8` 주소에 있는 값을 읽고 쓰는 용도입니다. 
  - (`UartCtrlRegs::read(), write()` 할 때 사용되지만, `UartCtrlRegs`의 값을 읽고 쓰는 것이 아니어서 bitflags를 사용하기 애매합니다.) 
https://github.com/kaist-cp/rv6/blob/237d4bebb50a09e465001071583cad81cfdea4cd/kernel-rs/src/uart.rs#L39-L46
- `Uart::init()`에서 아직 하드코딩된 값을 write하는 경우가 있습니다.

2020-11-19 12:43 UTC, coolofficials commented
@kimjungwow 정우님 혹시 uartputc sync를 사용함에 있어서 ctrl+P 결과가 제대로 출력되거나 하지는 않나요?

2020-11-19 13:44 UTC, jeehoonkang requested changes

2020-11-19 13:44 UTC, jeehoonkang commented on kernel-rs/src/uart.rs
> +const IER_TX_ENABLE: u8 = 1 << 0;
- 넵 알겠습니다.
- 혹시 enum은 가능한가요.

2020-11-20 01:10 UTC, kimjungwow commented
> 정우님 혹시 uartputc sync를 사용함에 있어서 ctrl+P 결과가 제대로 출력되거나 하지는 않나요?

@coolofficials 이 PR에서는 아직 ctrl+P 결과가 출력되지는 않습니다. 하지만 (논의가 진행 중인) #282 에서 변경한 내용들을 적용하면 정상적으로 출력됩니다!

2020-11-20 01:32 UTC, kimjungwow commented on kernel-rs/src/uart.rs
> +const IER_TX_ENABLE: u8 = 1 << 0;
@jeehoonkang 교수님, enum이 가능하긴 한데 좋은 코드는 아닌 것 같습니다.

- `IER_TX_ENABLE, FCR_FIFO_CLEAR, LSR_RX_READ`는 모두 같은 값 (1)을 가져, enum 안에 모두 넣을 수는 없습니다.
- 아래와 같이 같은 enum으로 취급할 수 있긴 합니다.. enum과 const의 명명법이 달라서 아래와 같이 명명했는데, 가독성을 조금 포기하고 통일성을 주려면 `IERTXENABLE, FCRFIFIOCLEAR, LSRRXREAD`로 하면 될 것 같습니다!
```Rust
enum UartRegBits {
    IerTxEnable= 1 << 0;
    생략
}

impl UartRegBtis {
    const FCR_FIFO_CLEAR:UartRegBits = UartRegBits::IerTxEnable;
    const LSR_RX_READ:UartRegBits = UartRegBits::IerTxEnable;
}
```

2020-11-20 02:43 UTC, jeehoonkang commented on kernel-rs/src/uart.rs
> +const IER_TX_ENABLE: u8 = 1 << 0;
음.. 일반적으로 이 상수들에 어떤 structure가 있는지 제가 이해하지 못해서 조언드리기 어려울 것 같은데요, 정우님이 생각하시기에 structure가 가장 잘 드러나는 방식으로 리팩토링해주시면 감사하겠습니다.

2020-11-20 13:36 UTC, kimjungwow commented on kernel-rs/src/uart.rs
> +const IER_TX_ENABLE: u8 = 1 << 0;
1. 리팩토링 전처럼 const 변수들을 그대로 사용하는 것은 적절치 않고
2. 해당 const 상수들 중 같은 값을 갖는 상수들이 있고
3. `UartCtrlRegs::write(self, v: u8)`의 `v`가 하드코딩된 값 혹은 임의의 값이 주어지기 때문에

`UartRegBits::bits()` 함수를 만들었습니다!

https://github.com/kaist-cp/rv6/pull/281/commits/bf5fe7c2dd9ee05114f8ea0b856e5568519202da

2020-11-20 14:23 UTC, jeehoonkang commented
이거랑 #285 중에 뭘 먼저 머지하는게 좋을까요?  정우님이 판단해주세요.

2020-11-20 14:24 UTC, kimjungwow commented
> 이거랑 #285 중에 뭘 먼저 머지하는게 좋을까요? 정우님이 판단해주세요.

이 PR (#281 )을 먼저 머지하면 좋겠습니다! 😀 감사합니다.

2020-11-20 14:25 UTC, jeehoonkang commented
넵 알겠습니다.  수정해주시고 리뷰 재요청 해주세요

2020-11-20 16:39 UTC, kimjungwow commented
수정은 다 되었고, CI 통과하기를 기다리고 있었습니다! 리뷰 요청드립니다. 😊 @jeehoonkang

2020-11-20 16:41 UTC, merged

2020-11-21 03:36 UTC, coolofficials commented
@kimjungwow Uart::putc_sync의 존재 이유가 kernel이 initialize 되지 않아도 print를 할 수 있게 하기 위함인가요? 이 경우 어제 논의했던 console struct의 design이 아니라 다른 방향을 가져야할 것 같아서 문의드립니다.

2020-11-23 01:39 UTC, kimjungwow commented
@coolofficials 

> `Uart::putc`와 `Uart::putc_sync`의 차이점에 대해서 혹시 설명해주실 수 있나요??

- 두 함수의 차이는 interrupt 사용 여부입니다. `Uart::putc_sync()`는 interrupt 사용하지만, `Uart::putc()`는 interrupt를 사용하지 않고 output buffer가 꽉 찬 경우 `sleep()`으로 block합니다.

> `Uart::putc`는 현재 사용처가 안 보이고, `Uart::putc_sync`로 전부 변경된 것 같은데, `Uart::putc_sync` 함수는 self를 받지 않아서 소유권이 모호합니다.

- `Uart::putc`는 `Console::write()`에서 사용됩니다 (78번째 줄)
https://github.com/kaist-cp/rv6/blob/53d87f7a060f4ba33ee79fc3dd8395492e5df258/kernel-rs/src/console.rs#L72-L81
- #287 의 관점에서 보면 소유권이 모호하다고 볼 수 있음에 동의합니다
 
> `Uart::putc_sync`의 존재 이유가 kernel이 initialize 되지 않아도 print를 할 수 있게 하기 위함인가요? 이 경우 어제 논의했던 console struct의 design이 아니라 다른 방향을 가져야할 것 같아서 문의드립니다. `Kernel`이 `Uart`를 소유하면 안 될 것 같아서요.

- `Uart::putc_sync`의 존재 이유는 xv6의 의도(`uartputc_sync`)를 반영하기 위함입니다. https://github.com/mit-pdos/xv6-riscv/commit/db0f092ae44f85db450718588c2deea080c27d0e
- `Kernel`이 `Uart`를 소유하면 안 되는 이유가 궁금합니다!

2020-11-23 01:41 UTC, kimjungwow commented
@coolofficials #188 에서 논의를 이어가도 될까요? 😁

2020-11-23 01:42 UTC, coolofficials commented
> @coolofficials
> 
> > `Uart::putc`와 `Uart::putc_sync`의 차이점에 대해서 혹시 설명해주실 수 있나요??
> 
> * 두 함수의 차이는 interrupt 사용 여부입니다. `Uart::putc_sync()`는 interrupt 사용하지만, `Uart::putc()`는 interrupt를 사용하지 않고 output buffer가 꽉 찬 경우 `sleep()`으로 block합니다.
> 
> > `Uart::putc`는 현재 사용처가 안 보이고, `Uart::putc_sync`로 전부 변경된 것 같은데, `Uart::putc_sync` 함수는 self를 받지 않아서 소유권이 모호합니다.
> 
> * `Uart::putc`는 `Console::write()`에서 사용됩니다 (78번째 줄)
>   https://github.com/kaist-cp/rv6/blob/53d87f7a060f4ba33ee79fc3dd8395492e5df258/kernel-rs/src/console.rs#L72-L81
> * #287 의 관점에서 보면 소유권이 모호하다고 볼 수 있음에 동의합니다
> 
> > `Uart::putc_sync`의 존재 이유가 kernel이 initialize 되지 않아도 print를 할 수 있게 하기 위함인가요? 이 경우 어제 논의했던 console struct의 design이 아니라 다른 방향을 가져야할 것 같아서 문의드립니다. `Kernel`이 `Uart`를 소유하면 안 될 것 같아서요.
> 
> * `Uart::putc_sync`의 존재 이유는 xv6의 의도(`uartputc_sync`)를 반영하기 위함입니다. [mit-pdos/xv6-riscv@db0f092](https://github.com/mit-pdos/xv6-riscv/commit/db0f092ae44f85db450718588c2deea080c27d0e)
> * `Kernel`이 `Uart`를 소유하면 안 되는 이유가 궁금합니다!

@kimjungwow 아 제가 저 당시 생각 정리가 좀 덜 되어 여쭤본건데, xv6 코드를 읽고 의도를 파악하여 #286 에 담아봤습니다. 리뷰 부탁드려요 👍