[Closes #243, Updated from #276] Fix: Procdump & Sleepablelock
kaist-cp/rv6 pull request #282
Opened 2020-11-19 09:20 UTC by coolofficials

#Closes #243 
#Updated from #276 

xv6의 구현과 달리 lock을 하나만 잡도록 한 상태로 bug를 고쳤습니다. https://github.com/kaist-cp/rv6/pull/276#issuecomment-730200985
1. `ProcessSystem::dump` 내에서 출력할 때 Null character 이전까지만 출력하도록 수정. https://github.com/kaist-cp/rv6/pull/276#issuecomment-727167934
2. `Sleepablelock`이 holding 중이지 않을 때만 acquire 하고, holding 중일 때만 release 하도록 수정. 
- `RawSpinlock`을 수정하는 것은 xv6의 intention을 바꾸는 작업이라고 생각하여 `Sleepablelock`에서만 일단 수정을 했습니다.
- `Spinlock`도 수정이 필요할까요?

2020-11-19 13:41 UTC, jeehoonkang requested changes

2020-11-19 13:41 UTC, jeehoonkang commented on kernel-rs/src/proc.rs
> +            let mut name = [0; 16];
- 16이 magic이라 혹시 다르게 구현할 수 있을지 궁금합니다.
- strcpy 같은걸 사용할 수도 있나요?

2020-11-19 13:41 UTC, jeehoonkang commented on kernel-rs/src/proc.rs
> +            let mut name = [0; 16];
아니면 str::from_utf8 대신에 0을 recognize하는걸 사용할 수 있으면 좋겠습니다.

2020-11-19 13:41 UTC, jeehoonkang commented on kernel-rs/src/sleepablelock.rs
> +        if !self.lock.holding() {
이렇게 하면 안됩니다.  두 쓰레드가 holding인지 체크해서 모두 holding이 아니라고 판단한 후에, 둘 모두 acquire를 실행할 수도 있습니다.

2020-11-19 14:04 UTC, coolofficials commented on kernel-rs/src/sleepablelock.rs
> +        if !self.lock.holding() {
reentrantlock과 같은 구현을 하면 어떨까요?
reference counting을 통해 thread가 lock을 이미 holding 중일 때만 lock을 여러번 더 acquire 할 수 있게 해주는 구현입니다.

혹은 그냥 `RawSpinlock`의 `acquire`가 `holding`이 true일 때 panic 하지 않고 return 하는 방법도 있을 것 같습니다.

2020-11-19 14:05 UTC, jeehoonkang commented on kernel-rs/src/sleepablelock.rs
> +        if !self.lock.holding() {
reentrant lock: 이렇게 가면 xv6의 의도를 좀 바꾸는거라서 더 강한 이유가 필요합니다.  어느 지점에서 reentrancy가 필요한지 검토해주시고 의견 남겨주세요.

2020-11-19 14:12 UTC, jeehoonkang commented on kernel-rs/src/sleepablelock.rs
> +        if !self.lock.holding() {
아 https://github.com/kaist-cp/rv6/pull/276#issuecomment-730200985 이게 이유겠군요.. 읽어보고 다시 연락드리겠습니다.

2020-11-19 14:31 UTC, coolofficials commented on kernel-rs/src/sleepablelock.rs
> +        if !self.lock.holding() {
reentrancy가 필요한 부분은 cons.lock과 pr.lock을 합치는 경우 외에는 없는 것 같습니다.
reentrancy를 구현하지 않으면서 두 lock을 합치는 좋은 방법이 있을까요?

제가 이해하기로는 현재 구현의 문제가 if !self.lock.holding()을 확인한 뒤 acquire를 하기 전에 다른 thread가 !self.lock.holding()을 확인하는 경우인데, 이 부분을 atomic 하게 수정하는 방법은 없을까요?

release의 경우는 holding을 체크하는 것이 문제가 없는 것 같은데(lock이 unique 하니까) 제 생각이 맞나요?

2020-11-20 02:26 UTC, coolofficials commented
교수님과 면담 결과 Printer를 분리하여 사용하는 것으로 결론이 났습니다. 다시 #276 에서 이어가겠습니다.

2020-11-20 02:26 UTC, closed without merging