[#closes 243] Procdump debug & Refactor console struct.
kaist-cp/rv6 pull request #286
Opened 2020-11-21 18:52 UTC by coolofficials

#276 의 논의가 너무 길어지고 conflict가 많이 생겨서 새롭게 PR을 작성합니다.

- `Processsystem::dump` 출력 시 null character recognizing 문제 해결.
- 지난 주 팀 미팅에서 논의한대로 `Console / Printer / Uart`의 Ownership을 정돈했습니다.

기존의 `Console` Struct를 `Terminal`이라는 임시 이름으로 변경하고 다음과 같이 struct Console을 만들어 정리했습니다.
```
struct Console {
    terminal: Sleepablelock<Terminal>,
    printer: Spinlock<Terminal>,
    uart: Uart,
}
```

2020-11-21 19:09 UTC, coolofficials commented on kernel-rs/src/console.rs
> +    _padding: u8,
padding necessary?

2020-11-21 19:09 UTC, coolofficials commented on kernel-rs/src/console.rs
> +pub struct Terminal {
better naming?

2020-11-21 19:09 UTC, coolofficials commented on kernel-rs/src/console.rs
> +    kernel().console.uart.init();
xv6의 consoleinit 의도를 따라가기 위한 수정입니다.

2020-11-21 19:09 UTC, coolofficials commented on kernel-rs/src/kernel.rs
> +            unsafe { self.console.printer.get_mut_unchecked().write_fmt(args) }
write_fmt printer가 kernel() 함수를 부르고 있어서 소유권이 꼬이는 것 같습니다.

2020-11-21 19:27 UTC, coolofficials commented on kernel-rs/src/console.rs
> +    unsafe fn terminalwrite(&self, src: UVAddr, n: i32) -> i32 {
`terminalwrite/read/intr` 함수들의 소유를 `struct Terminal`로 옮기는 편이 좋을까요?
그 경우 `intr`는 `putc`를 사용하고 있어서 `kernel()`을 부르게 됩니다.

2020-11-21 19:27 UTC, coolofficials commented on kernel-rs/src/console.rs
> +            m if m == ctrl('P') => unsafe {
해당 block만 unsafe 하다고 판단했습니다. 나머지 block은 `Console::putc->Uart::putc_sync->UartCtrlRegs::read`로 safety가 reduce 됩니다.

2020-11-21 19:38 UTC, coolofficials commented on kernel-rs/src/console.rs
> +    unsafe fn write(&self, src: UVAddr, n: i32) -> i32 {
`write/read/intr` 함수들의 소유를 `struct Terminal`로 옮기는 편이 좋을까요?
그 경우 `intr`는 `putc`를 사용하고 있어서 `kernel()`을 부르게 됩니다.

2020-11-21 19:57 UTC, coolofficials commented on kernel-rs/src/console.rs
> +    kernel().console.uart.init();
`consoleinit/read/write/intr` 등이 kernel()을 부르지 않도록 수정은 힘들까요? Devsw와의 연결을 refactoring 할 방법을 생각해보면 좋을 것 같습니다.

2020-11-22 14:15 UTC, jeehoonkang requested changes
감사합니다.. 다만 제가 console, terminal, printer, uart 사이의 관계에 대해 잘 파악하기 어렵습니다. 혹시 주석으로 얘네들이 뭐 하는건지 남겨주시면 감사하겠습니다.

아울러 원래 xv6의 의도를 100% 반영하는지, 아니면 좀 바뀐 부분이 있는지 궁금합니다.

2020-11-22 14:15 UTC, jeehoonkang commented on kernel-rs/src/uart.rs
> +    pub fn putc_sync(&self, c: i32) {
&mut self가 아니라 &self 인 이유는?

2020-11-22 14:27 UTC, coolofficials commented on kernel-rs/src/uart.rs
> +    pub fn putc_sync(&self, c: i32) {
`struct Uart(Self)`에 대한 어떠한 수정도, 접근도 없기 때문에 mutable reference가 아니라고 생각했습니다.
- 함수는 register에 직접 접근하고 있습니다.
- `putc`와 달리 interrupt disable를 통해 synchronize 합니다.
- 직접적인 접근이 없음에도 `&self`를 준 이유는 유일한 Uart를 통해서만 이 함수를 부를 수 있도록 하기 위함입니다.

2020-11-22 14:35 UTC, coolofficials commented on kernel-rs/src/uart.rs
> +    pub fn putc_sync(&self, c: i32) {
제 생각에는 `struct Uart`가 `UartCtrlReg`에 대한 소유권을 갖도록 수정하는게 좋을 것 같은데, 해당 수정을 진행하게 된다면 reference를 다시 생각해봐야 합니다.

- 별도의 이슈에서 `UartCtrlRegs`를 `Uart`가 소유하는 것이 옳은지 논의하겠습니다.

2020-11-22 16:14 UTC, coolofficials commented
@jeehoonkang 
말씀하신 부분 Commentation 완료했습니다. 별도의 issue로 분리해야하는 discussion들 address 했습니다. Discussion들 확인하고 resolve 해주시면 감사하겠습니다.

> "아울러 원래 xv6의 의도를 100% 반영하는지, 아니면 좀 바뀐 부분이 있는지 궁금합니다."

결론적으로 말하자면 의도를 100% 반영한다고 생각합니다.
xv6가 의도한대로 `Uart`의 uniqueness, `Printer`와 `Console(현 Terminal)`의 분리를 확실히 표현해주는 추상화라고 생각합니다.

결국 세 struct가 전부 User와 interact 하는 Console device와 관련된 interface라는 점에서도 의미를 더욱 명확히 표현하고 있다고 생각합니다.

2020-11-22 18:26 UTC, coolofficials commented on kernel-rs/src/console.rs
> +            kernel().console.putc(c as _);
`impl Write for Console`로 변경하고 `kernel()`의 사용을 줄여야할지 논의가 필요합니다.
Printer의 역할을 표현하기 위해서는 현 상태의 구현이 옳다고 생각합니다.

`impl Write for Console`로 변경한다면 `Kernel::printer_write_fmt`의 구현을 변경해야합니다.

2020-11-23 06:50 UTC, anemoneflower commented on kernel-rs/src/console.rs
> +    unsafe fn write(&self, src: UVAddr, n: i32) -> i32 {
- 수정한다면, `write`도 `uart`를 사용하고 있어서 `kernel()`을 불러야 할 것 같습니다.
- 아래 `Printer::Write`과 같은 정책을 사용하는 것이 좋다고 생각합니다. (둘 다 각자 소유 / 다 `Console`이 소유)

2020-11-23 06:50 UTC, anemoneflower commented on kernel-rs/src/console.rs
> +    kernel().console.uart.init();
`consoleinit`함수 대신 `struct Console`에 `init`메소드를 만드는 것은 어떨까요?

2020-11-23 06:59 UTC, coolofficials commented on kernel-rs/src/console.rs
> +    kernel().console.uart.init();
@anemoneflower `Console::init`으로 만드는 것은 괜찮은 방법일 수 있을 것 같습니다. `consoleinit(&mut KERNEL.devsw)` 대신 `KERNEL.console.init(KERNEL.devsw)`을 호출하는 방향으로 수정이 가능할 것 같습니다.

`read/write/intr`에 대해서는 어떻게 생각하시나요?

2020-11-23 07:01 UTC, coolofficials commented on kernel-rs/src/console.rs
> +    unsafe fn write(&self, src: UVAddr, n: i32) -> i32 {
@anemoneflower 소유권 표현 상으로는 kernel()을 부르더라도 Terminal으로 이동하는 것이 좋다는 말씀이시죠?

2020-11-23 07:17 UTC, anemoneflower commented on kernel-rs/src/console.rs
> +    unsafe fn write(&self, src: UVAddr, n: i32) -> i32 {
소유권만 보면 `Terminal`과 `Printer`가 각각 소유하는 것이 맞는 것 같습니다. 그런데, 코드 구조 상으로는 `Console`이 다 소유하는 것이 더 깔끔해 보입니다.. `Printer`와 `Terminal`이 `Console`에서만 사용되기 때문에 `Console`의 소유로 남겨도 괜찮을 것 같은데, 다른 분들의 의견은 어떠신가요?

2020-11-23 08:30 UTC, kimjungwow reviewed
수고하셨습니다! 저는 ownership 위주로 고민해봤습니다 👍👍

2020-11-23 08:30 UTC, kimjungwow commented on kernel-rs/src/console.rs
> +    _padding: u8,
`Printer`는 `WaitChannel`과 달리 1개만 생기고, 혹시 여러 개가 생길 때 주소가 같아도 문제가 없다고 생각해서.. `_padding`이 없어도 될 것 같습니다. 다른 분들의 의견도 궁금합니다 😊

2020-11-23 08:30 UTC, kimjungwow commented on kernel-rs/src/console.rs
> +    unsafe fn write(&self, src: UVAddr, n: i32) -> i32 {
저는 ownership을 중점적으로 생각해 `Terminal`과 `Printer`가 각각 소유하면 좋겠습니다! 추가로 아래의 현재 kaist-cp/rv6의 구현처럼, `write/read/intr`을 실행하기 전 `consoleread/consolewrite/consoleintr`에서 `lock()`을 실행하면 소유권을 더욱 명확히 나타낼 수 있다고 생각합니다!
https://github.com/kaist-cp/rv6/blob/53d87f7a060f4ba33ee79fc3dd8395492e5df258/kernel-rs/src/console.rs#L201-L204

2020-11-23 08:30 UTC, kimjungwow commented on kernel-rs/src/console.rs
> +    kernel().console.uart.init();
* consoleinit함수 대신 struct Console에 init메소드를 만드는 것은 어떨까요?

좋습니다!

* read/write/intr에 대해서는 어떻게 생각하시나요?

현재 PR의 `consoleread/consolewrite/consoleintr`을 `Console::read, Console::write, Console::intr`로 바꾸고, 
현재 PR의 `Console::read, Console::write, Console::intr`를 `Terminal::read, Terminal::write, Terminal::intr`로 바꾸면 어떨까요? 
(`Console::read/write/intr`에서는 단순히 `self.terminal.lock()` 실행 후 `Terminal::read/write/intr`를 실행하는 방식입니다.) 
Ownership을 중심으로 생각하면 이 방법이 명확히 Kernel->Console->Terminal을 표현하는 것 같긴 한데, 불필요한 추상화일 수도 있을 것 같습니다

2020-11-23 08:30 UTC, kimjungwow commented on kernel-rs/src/console.rs
> +            kernel().console.putc(c as _);
저는 `impl Write for Console`로 변경하는게 좋다고 생각합니다. 
`kernel()` 사용을 줄일 수 있는 것도 좋고,  
`Kernel::printer_write_fmt`에서 `Kernel`은 `Console` 안의 `Printer`를 바로 접근하는 것보다 
`Kernel` 바로 아래에 있는 `Console`에 접근하도록 `Kernel::console_write_fmt`로 바꾸는 것이 좋다고 생각하기 때문입니다! 😄

2020-11-23 08:30 UTC, kimjungwow commented on kernel-rs/src/proc.rs
> +    /// Page table.
https://github.com/mit-pdos/xv6-riscv/blob/231c08dc5e5e39a6fafda832e6935beb38ef3887/kernel/proc.h#L102
xv6의 주석을 de9db75b63c1c67b82dc244274479919c7aa8d5d 에서 반영한 내용이었습니다. 주석을 다시 `User page table`로 하면 어떨까요?

2020-11-23 08:30 UTC, kimjungwow commented on kernel-rs/src/proc.rs
> +            let mut name = [0; MAXPROCNAME];
xv6와 다른 내용이니 null character recognizing를 해결하기 위한 코드라고 주석을 적으면 좋겠습니다!

2020-11-23 08:33 UTC, coolofficials commented on kernel-rs/src/console.rs
> +    kernel().console.uart.init();
@kimjungwow `consoleread/consolewrite`의 경우는 Devsw에서 syscall과 link 하기 위해 필요한 함수입니다. #288 
kernel()을 부르는 것이 괜찮다면 저도 read write intr가 Terminal의 소유가 되어야 한다고 생각합니다.

2020-11-23 08:35 UTC, anemoneflower commented on kernel-rs/src/console.rs
> +    _padding: u8,
저도 정우님의 생각에 동의합니다.

2020-11-23 08:35 UTC, coolofficials commented on kernel-rs/src/proc.rs
> +    /// Page table.
이전 PR에서 복사하면서 잘못 옮겨간 부분이네요! 수정하겠습니다.

2020-11-23 08:43 UTC, coolofficials commented on kernel-rs/src/console.rs
> +    unsafe fn write(&self, src: UVAddr, n: i32) -> i32 {
@jeehoonkang 교수님, 현재 논점이 global function `kernel()`의 사용을 지양하는 것과 ownership을 조금 더 세분화하는 것 중에 선택하는 것입니다. 교수님의 의견이 궁금합니다.

2020-11-23 08:50 UTC, coolofficials commented on kernel-rs/src/console.rs
> +    _padding: u8,
@jeehoonkang ZST의 사용을 지양해야하는지 여쭤보고 싶습니다. `Printer`는 trait inherit과 lock을 통한 synchronization만을 위해 존재합니다.

2020-11-23 10:22 UTC, coolofficials commented on kernel-rs/src/console.rs
> +            kernel().console.putc(c as _);
저는 의미론적으로는 Printer가 해당 함수의 owner가 되는 것이 좋다고 생각합니다.
kernel()을 사용하더라도 ownership을 가지는 방향으로 나머지 부분을 수정한다면 이 함수는 그대로 두는 것이 좋겠습니다.

2020-11-23 10:23 UTC, coolofficials commented on kernel-rs/src/console.rs
> +    _padding: u8,
이 코멘트에 대해서는 padding이 없는 방향으로 수정을 진행하겠습니다.

2020-11-23 11:01 UTC, coolofficials commented
@jeehoonkang ping

2020-11-23 11:03 UTC, coolofficials commented on kernel-rs/src/console.rs
> +    unsafe fn write(&self, src: UVAddr, n: i32) -> i32 {
@kimjungwow https://github.com/kaist-cp/rv6/pull/286#discussion_r528535734

2020-11-23 11:11 UTC, coolofficials commented
@efenniht https://github.com/kaist-cp/rv6/pull/186#discussion_r480039643 이 부분에 대한 refactoring도 진행된 것 같은데, 확인 부탁드립니다.

2020-11-23 11:50 UTC, jeehoonkang requested changes
일반적으로 이 PR이 달성하고자하는 바를 잘 모르겠습니다.

2020-11-23 11:50 UTC, jeehoonkang commented on kernel-rs/src/console.rs
> +    pub fn putc(&self, c: i32) {
여전히 이게 &self인게 이해가 잘 안갑니다.  여러 thread가 동시에 putc를 부르면 어떻게 되나요?

2020-11-23 11:50 UTC, jeehoonkang commented on kernel-rs/src/console.rs
> +    unsafe fn write(&self, src: UVAddr, n: i32) -> i32 {
같은 질문을 드리고자 하는데 왜 &self로 해도 안전한가요? 여러 쓰레드가 동시 접근해도 문제가 안생기나요?

2020-11-23 11:50 UTC, jeehoonkang commented on kernel-rs/src/console.rs
> +        terminal.read(dst, n)
이렇게 terminal로 바로 보내는 함수들이 많다면, console이라는 abstraction이 틀린 걸지도 모르겠습니다. 어떻게 보시나요?

2020-11-23 11:50 UTC, jeehoonkang commented on kernel-rs/src/console.rs
> +            kernel().console.uart.putc(c[0] as i32);
저는 이건 잘못된 디자인이라고 생각합니다. uart의 소유권에 대한 명확한 정립이 먼저 필요한 것 같아요.

2020-11-23 11:50 UTC, jeehoonkang commented on kernel-rs/src/console.rs
> +            m if m == ctrl('P') => unsafe {
이 block은 왜 unsafe한가요?

2020-11-23 22:22 UTC, coolofficials reviewed
putc의 multithread 접근에 대해서 조금 더 생각해보겠습니다.

2020-11-23 22:22 UTC, coolofficials commented on kernel-rs/src/console.rs
> +            m if m == ctrl('P') => unsafe {
`ProcessSystem::dump->`p.info.get_mut_unchecked()'를 통해 ProcInfo에 접근합니다.
dump의 unsafe block을 특정지어서 safety를 reduce 해봤습니다.
safety에 대해서 미팅 때 여쭤보겠습니다.

2020-11-23 22:22 UTC, coolofficials commented on kernel-rs/src/console.rs
> +        terminal.read(dst, n)
console이라는 abstraction을 만든 이유가 uart의 ownership을 분명히하고자 하는 것인데, 이런식으로 terminal을 부르는게 그 의미를 담지 못하는 것 같습니다. b2c26c4b360e71d8feb448c90b9a988f1d0c29e3 에서는 console의 uart를 이용하는 방식이었는데, 해당 디자인에서는 console abstraction의 존재 의미를 잘 살리고 있다고 생각하여 role back 하겠습니다.

2020-11-23 22:22 UTC, coolofficials commented on kernel-rs/src/console.rs
> +            kernel().console.uart.putc(c[0] as i32);
생각해봤는데, 이러한 디자인을 사용하는 것이 잘못된 것이 맞는 것 같습니다. 이번 PR의 목적 중 하나가 uart의 소유권을 console이 가지도록 하는 것인데, 이렇게 사용하면 의미가 퇴색되는 것 같습니다.

 b2c26c4 에서처럼 uart의 소유권을 console이 지니도록 하여 console의 존재 의미를 살리는 방식으로 role back 하겠습니다.

2020-11-23 22:34 UTC, coolofficials commented on kernel-rs/src/console.rs
> +    pub fn putc(&self, c: i32) {
생각해봤는데, 명확히 어떤 문제가 생기는지 reasoning이 잘 안됩니다. 면담 때 이런 경우에 어떻게 reasoning 할 수 있는지 가르침을 청해도 될까요?

2020-11-26 13:38 UTC, coolofficials commented
우선 procdump debugging만 하는 정도에서 PR을 마무리하고 console/printer/uart refactoring은 추후에 별도의 issue로 다루기로 해서 close합니다.

2020-11-26 13:38 UTC, closed without merging