Inode::read requires neither mutation nor buf alloc.
kaist-cp/rv6 pull request #292
Opened 2020-11-25 06:25 UTC by efenniht

#280 은 버그가 아님을 보이고, bmap 의 행동을 좀 더 명확하게 바꾼 PR입니다.

 - `Inode::read` 는 offset 과 amount 를 항상 파일 크기 이내가 되도록 사전 체크를 합니다.
 - 한편 `Inode` 의 API 는 파일 크기를 변경해야 하는 경우 항상 그 크기를 커버하는 버퍼를 할당하도록 되어 있습니다.
 - 따라서 `Inode::read` 가 부르는 `bmap` 은 그 내부에서 `balloc` 을 절대 부르지 않습니다.
 - 이를 코드를 보고 명확히 알 수 있도록 기존의 `bmap` 은 `bmap_or_alloc` 으로 이름을 바꾸고, `balloc` 을 호출하지 않는 `bmap` 을 따로 만들었습니다.
 - `Inode::read` 는 이제 `bmap` 을 호출하고, 그 경우에도 usertest 를 통과합니다.

Closes #280

2020-11-25 06:28 UTC, jeehoonkang requested changes

2020-11-25 06:28 UTC, jeehoonkang commented on kernel-rs/src/fs/inode.rs
> +    fn bmap(&self, bn: usize) -> u32 {
로직이 많이 겹치는데 bmap_or_alloc에서 bmap을 부른다던지 하는 방식으로 구현할 수도 있을까요?

2020-11-25 06:43 UTC, efenniht commented on kernel-rs/src/fs/inode.rs
> +    fn bmap(&self, bn: usize) -> u32 {
구두로 한 논의를 이슈로 만들었습니다: #293

2020-12-10 13:35 UTC, jeehoonkang commented
Manually merged: https://github.com/kaist-cp/rv6/commit/e583a9f23c29ca7330aa43b495f13bb100cef2e0

2020-12-10 13:35 UTC, closed without merging