[Closes #243] Procdump_Debug
kaist-cp/rv6 pull request #297
Opened 2020-11-30 16:17 UTC by coolofficials

- closes #243 

주요 변경점은 다음과 같습니다.
- ProcessSystem::dump 에서 null_character recognization을 못하는 문제 해결.
- Print 시에 Console lock을 acquire 하던 문제 해결.
  - xv6의 의도를 따라 `println`을 위한 별도의 `struct Printer`를 다시 만들었습니다.
- Console이 uart를 포함한 상태로 lock을 쥐던 문제 해결.
  - xv6의 의도를 따라 Console이 Console lock의 영향을 받지 않도록 수정했습니다.
  - 임시로 Kernel이 Unique한 Uart를 소유하도록 변경했습니다.

추후 별도의 이슈에서 Uart, Console, Printer의 relationship을 정확히 파악하여 refactoring을 진행해야 합니다.

2020-11-30 16:23 UTC, coolofficials commented
@jeehoonkang 교수님 리뷰 부탁드립니다.

일전에 미팅 때 구두로 논의했던 것처럼 procdump만 debugging 하는 단계에서 PR을 마무리하고 Console-Uart-Printer refactoring은 이슈 #298 로 분리했습니다.

2020-11-30 18:26 UTC, jeehoonkang requested changes

2020-11-30 18:26 UTC, jeehoonkang commented on kernel-rs/src/proc.rs
> +            let mut count = 0;
좀 멋을 부린다면...

```rust
let length = p.name.iter().position(|c| c == 0).unwrap_or(p.name.len());
...
str::from_utf8(p.name[0..length]).unwrap_or("???")
```

2020-11-30 19:27 UTC, coolofficials reviewed
@jeehoonkang 리뷰 반영했습니다!

2020-11-30 19:27 UTC, coolofficials commented on kernel-rs/src/proc.rs
> +            let mut count = 0;
멋있는 것 같습니다. 반영했습니다.

2020-11-30 20:17 UTC, jeehoonkang commented
ci 돌면 머지하겠습니다.  ci 성공하면 noti 주세요.

2020-11-30 21:08 UTC, coolofficials commented
@jeehoonkang CI 통과했습니다. 앞으로도 모든 리뷰 요청 핑은 CI 확인 이후에 드리도록 할까요?

2020-12-01 02:03 UTC, anemoneflower approved these changes

2020-12-01 04:10 UTC, merged