[Closes #261] Merge mit pdos [8]
kaist-cp/rv6 pull request #301
Opened 2020-12-04 04:34 UTC by kimjungwow

#### 12/4 기준 가장 최근 커밋까지 반영했습니다. CI 통과 + 내용 정리 + Rust 코드에 반영되었는지 확인 후 리뷰 요청 드리겠습니다.

- closes #261

2020-12-04 05:18 UTC, coolofficials approved these changes
고생 많으셨습니다:)

2020-12-04 05:18 UTC, coolofficials commented on kernel-rs/src/console.rs
> +    kernel().console.get_mut_unchecked().write(src, n)
혹시 lock을 안 잡는 이유를 임시 코멘트로 남길 수 있을까요?

2020-12-04 05:18 UTC, coolofficials commented on kernel-rs/src/proc.rs
> +    kernel::{kernel, KERNEL},
#300 전에 임시로 사용하는거죠?

2020-12-04 08:02 UTC, kimjungwow commented on kernel-rs/src/console.rs
> +    kernel().console.get_mut_unchecked().write(src, n)
https://github.com/kaist-cp/rv6/pull/301/commits/96a961cec2517e6f12114a8f0452d9f5b45d25f9
임시 코멘트 남겼습니다!

2020-12-04 08:07 UTC, kimjungwow commented on kernel-rs/src/proc.rs
> +    kernel::{kernel, KERNEL},
#300 과는 큰 관련은 없어 보입니다. 이 PR에서는 upstream 따라잡기를 마무리하는 것을 우선적으로 생각하고, #267 에 적어두겠습니다 👍

2020-12-04 08:44 UTC, coolofficials commented on kernel-rs/src/proc.rs
> +    kernel::{kernel, KERNEL},
아 그리고 아까 CI fail 했었던 것 같습니다!

2020-12-04 09:05 UTC, kimjungwow commented on kernel-rs/src/proc.rs
> +    kernel::{kernel, KERNEL},
@coolofficials 저도 확인했었습니다 😂 로컬에서는 계속 통과했었는데 이상하네요.. 지금은 통과했네요 ㅋㅋ

2020-12-04 09:06 UTC, kimjungwow commented
@jeehoonkang 교수님, 리뷰 요청드립니다. 2020/12/4 기준 mit-pdos의 모든 커밋을 반영했습니다!

2020-12-04 10:04 UTC, kimjungwow commented
CI가 통과한 것으로 확인했었는데.. 다시 실패로 떠서 확인 중입니다.
- 로컬에서는 계속 통과하는데 CI에서는 twochildren에서 계속 멈추네요..

2020-12-04 10:57 UTC, kimjungwow commented
![Imgur](https://imgur.com/us6iAh2.png)

여러 번 코멘트를 달아 죄송합니다. CI가 통과한 것을 다시 확인했습니다. 교수님, 리뷰 부탁드립니다!

2020-12-04 12:29 UTC, jeehoonkang requested changes

2020-12-04 12:29 UTC, jeehoonkang commented on kernel-rs/src/kernel.rs
> +pub static mut KERNEL: Kernel = Kernel::zero();
되도록 pub을 없애고싶긴 합니다.  TODO 남겨주세요.

2020-12-04 12:29 UTC, jeehoonkang commented on kernel-rs/src/proc.rs
> -        if lk != (*p).info.raw() as *mut RawSpinlock {
이 로직이 빠진게 재밌네요.  혹시 자세한 이야기를 좀더 해주실 수 있으신가요?

2020-12-05 05:09 UTC, kimjungwow commented on kernel-rs/src/kernel.rs
> +pub static mut KERNEL: Kernel = Kernel::zero();
https://github.com/kaist-cp/rv6/pull/301/commits/0af7578debde7efab4e20083f49976f4ebcdbbdb TODO 남겼습니다!

2020-12-05 05:46 UTC, kimjungwow commented on kernel-rs/src/proc.rs
> -        if lk != (*p).info.raw() as *mut RawSpinlock {
이 로직이 빠진 것 역시 `proc.parent`를 보호하는 `wait_lock`이 생긴 것과 관련이 있습니다.

- 이 PR 이전에 **`proc.c:sleep()` 내에서 `if lk != (*p).info.raw() as *mut RawSpinlock`를 따졌던 이유는, `proc.c:wait()`만을 위한 것으로 보입니다.** xv6에서 `sleep(void *chan, struct spinlock *lk)`의 `lk`를 `proc.lock`으로 `sleep()`을 실행한 경우는 `proc.c:wait()` (의 마지막 부분) 밖에 없기 때문입니다!
  - `if lk != (*p).info.raw() as *mut RawSpinlock`가 거짓이 될 수 있던 부분은 `wait()`에서 `sleep()`을 실행한 경우 밖에 없다는 의미입니다.
- 이 PR 이전에는 `proc.c:wait()`에서 `p->lock`을 쥔 상태로 (`p=myproc()`)
  - exited children이 있는지 for loop을 돌며 확인하고, (`np.parent==p`면 `np`는 `p`의 child라고 판단합니다)
  - children이 있지만 아직 exited children이 없다면 `sleep(p, &p->lock);` 합니다.
  - 이 때 `p->lock`을 이미 쥔 상태이기 때문에, 또 `acquire(&p->lock);`을 하지 않기 위해 `if lk != (*p).info.raw() as *mut RawSpinlock`를 따져주었습니다.

- 하지만 `wait()`에서 `proc.parent`를 접근하기 때문에, **`proc.c:wait()`는 `p->lock`이 아닌 `wait_lock`을 쥔 상태로 실행되도록 바뀌었습니다.** https://github.com/mit-pdos/xv6-riscv/commit/8d4fbc6e2a4c8373453f2e1380bb8c6ca8d334c0
  - 그에 따라 `proc.c:wait()`의 마지막에 `sleep()`을 실행할 때 **`sleep(p, &p->lock);`이 아닌 `sleep(p, &wait_lock);`로 실행합니다.**
  - `lk`를 `proc.lock`으로 설정하며 `sleep()`을 실행하는 경우가 모두 없어졌습니다. 즉, `if lk != (*p).info.raw() as *mut RawSpinlock`가 항상 참이기 때문에 말씀하신 로직이 빠지게 되었습니다!

2020-12-05 08:10 UTC, merged