Change Disk::read/write into Sleepablelock<Disk>'s methods (related to #271)
kaist-cp/rv6 pull request #302
Opened 2020-12-09 08:31 UTC by kimjungwow

#### Disk::read(), Disk::write()를 impl Sleepablelock<Disk>로 만들었습니다. 어떤 Disk에 대해 read/write 하는지 명확히 드러내고, dependency를 줄일 수 있습니다. 하지만 kernel() 호출이 잦아지기 때문에, 이 PR의 장단점중 어떤 것을 우선시할지 정해야 합니다.

- 이 PR처럼 수정한 이유
  - **`Disk::read(), Disk::write()` 형태로 사용하는 것은 어느 `struct Disk`에 대해 read, write하는지 명확히 드러내지 못한다고 판단했습니다.**
    - `Disk::read(), write()` 내부에서 `kernel().disk`를 사용하기 때문에 + xv6에서는 한 개의 `struct Disk`만 사용되기 때문에, `struct Kernel` 안에 있는 `struct Disk`에 대해 read write를 하는 것은 맞습니다.
    - 하지만 `(&kernel().disk).read()`, `(&kernel().disk).write()` 형태로 사용해야 어떤 Disk에 대해 읽고 쓰는지를 잘 드러낼 수 있다고 생각합니다.
    - 비슷한 맥락으로는 `begin_transaction()`이 있습니다. `begin_transaction()`도 `kernel().fs().begin_transaction();` 형태로 호출합니다. ( `begin_transaction()` 내부에서 `kernel().fs()`를 호출하지 않습니다)
  - **dependency 제거 #271**
    - 이 PR이 적용되면 `log.rs, inode.rs, mod.rs`가 `Disk`를 필요로 하지 않게 됩니다.
- 고민해볼 점
  - `kernel()` 호출이 잦아집니다.
    - 기존의 `Disk::read(), write()` 내부에서도 `kernel()`을 실행하기 때문에, 관점에 따라 글로벌 함수 `kernel()`을 `Disk::read()`를 실행하기 전에 호출하느냐 `Disk::read()` 내부에서 호출하느냐의 차이라 생각할 수도 있습니다.
    - 하지만 `Disk::read()`에서 `buf.deref_inner().valid==true`인 경우에는 `kernel()`을 호출할 필요가 없지만, 이 PR이 적용되면 항상 `kernel()`을 호출하게 됩니다.
https://github.com/kaist-cp/rv6/blob/6e98bf60bce864648a93cef4b2184103b608a96c/kernel-rs/src/virtio_disk.rs#L223-L234
  - `Sleepablelock<Disk>`의 메소드로 만드는 것이 적절한가?
    - proc.rs의 ProcGuard처럼 Disk를 보호하는 sleepablelock을 잡았음을 보장하는 `DiskGuard` 같은 것을 만들까 고민해보았습니다.
    - `Proc`과 달리 `Disk`는 `Sleepablelock`에 의해 보호받아야 하기 때문에 + `Proc` 처럼 서로 다른 필드를 보호하는 여러 개의 lock이 필요 없어서 우선은 `Sleepablelock<Disk>`의 메소드로 만들었습니다.
- **저는 "이 PR처럼 수정한 이유"에 적은 내용이 더 중요하다고 판단해서 이와 같은 PR을 올렸습니다.** 다른 분들의 의견도 궁급합니다.

2020-12-09 08:37 UTC, coolofficials commented on kernel-rs/src/fs/inode.rs
> +        let mut bp = (&kernel().disk).read(self.dev, kernel().fs().superblock.iblock(self.inum));
이렇게 수정하는 목적이 dependency 제거 외에 다른 부분은 없는거죠?
이렇게 하는 것이 disk->inode dependency를 disk->kernel->inode로 변경한 느낌이라 dependency를 줄이는 refactoring인지 의문입니다.

추가로 제가 동시성을 하기 전이라 정확히 모르는 것 같은데 update가 &self를 받아야 하는 이유가 무엇인가요? 여러 thread가 접근을 동시에 할 수 있나요?

2020-12-09 08:42 UTC, kimjungwow commented on kernel-rs/src/fs/inode.rs
> +        let mut bp = (&kernel().disk).read(self.dev, kernel().fs().superblock.iblock(self.inum));
@coolofficials 

* 이렇게 수정하는 목적이 dependency 제거 외에 다른 부분은 없는거죠?

`Disk::read(), Disk::write()` 형태로 사용하는 것은 어느 `struct Disk`에 대해 read, write하는지 명확히 드러내지 못한다고 판단한 것이 더욱 큰 이유입니다! 자세한 내용은 본문의 "이 PR처럼 수정한 이유"의 첫 항목을 참고해주세요 😁

* 추가로 제가 동시성을 하기 전이라 정확히 모르는 것 같은데 update가 &self를 받아야 하는 이유가 무엇인가요? 여러 thread가 접근을 동시에 할 수 있나요?

update가 &mut self를 받도록 변경하는 것이 좋다고 생각하시는 건가요? 어떤 이유이신지 여쭙고 싶습니다 😃

2020-12-09 09:06 UTC, coolofficials commented on kernel-rs/src/fs/inode.rs
> +        let mut bp = (&kernel().disk).read(self.dev, kernel().fs().superblock.iblock(self.inum));
"update가 &mut self를 받도록 변경하는 것이 좋다고 생각하시는 건가요? 어떤 이유이신지 여쭙고 싶습니다 😃"
update를 하는 사이에 다른 thread가 접근하는 것이 옳지 않은 것 같아서 그렇습니다. 다른 method들은 `&mut self`인 것이 많은데 update가 `&self`인 특별한 이유가 있는지 여쭤본건데, 혹시 이전에 이미 논의가 진행되었었나요?

2020-12-09 09:06 UTC, coolofficials commented on kernel-rs/src/fs/inode.rs
> +        let mut bp = (&kernel().disk).read(self.dev, kernel().fs().superblock.iblock(self.inum));
"Disk::read(), Disk::write() 형태로 사용하는 것은 어느 struct Disk에 대해 read, write하는지 명확히 드러내지 못한다고 판단한 것이 더욱 큰 이유입니다! 자세한 내용은 본문의 "이 PR처럼 수정한 이유"의 첫 항목을 참고해주세요"

console refactoring 때랑 비슷한 부분이 있는 것 같습니다. 그때도 kernel이 console을 유일하게 소유하지만 kernel()을 이용해서 console을 부르는 것이 좋지 않은 방향이라는 피드백을 받았는데, disk와 console이 어떤 차이점을 가져서 kernel()을 부르는 것이 좋은지 궁금합니다.

2020-12-09 15:11 UTC, kimjungwow commented
#303 에 적은 것처럼 로컬에서는 통과하지만 Travis CI에서는 통과하지 못하고 있습니다. 
Travis CI 빌드 시도를 위해 Draft로 변경하지 않은 채로 두고 있습니다.
통과한 후 교수님께 리뷰를 요청드리겠습니다.

2020-12-10 09:51 UTC, kimjungwow commented
@jeehoonkang  교수님, 리뷰 요청 드립니다! 😀
이 PR에서는 `Disk::read/write`가 어떤 `struct Disk`에 대해 read/write하는지 명확히 드러내고, #271 의 dependency를 줄이고자 시도했습니다

2020-12-10 12:06 UTC, jeehoonkang requested changes

2020-12-10 12:06 UTC, jeehoonkang commented on kernel-rs/src/fs/inode.rs
> +        let mut bp = (&kernel().disk).read(self.dev, kernel().fs().superblock.iblock(self.inum));
- `kernel.disk`를 참조하던 코드가 Disk에 있던게 더 상위 레벨로 옮겨진 것이라 보입니다.
- 저는 맞는 방향의 refactoring이라고 생각합니다.  이렇게 더 상위로 상위로 올려서 결국에 없애는게 목적입니다.

2020-12-10 12:06 UTC, merged

2020-12-10 12:32 UTC, coolofficials commented on kernel-rs/src/fs/inode.rs
> +        let mut bp = (&kernel().disk).read(self.dev, kernel().fs().superblock.iblock(self.inum));
교수님, "상위로 상위로 올려서 결국에 없애는게 목적"이라는 말씀을 정확하게 이해하지 못하겠습니다.
Global 함수 `kernel()`을 사용하는 method들의 경우 상위로 올려서 없애려면 `struct Kernel`이 해당 method를 가지도록 해야하는건가요? (가령 `fn diskwrite(&mut self, ..., ...)`의 형태로...)

2020-12-10 12:43 UTC, jeehoonkang commented on kernel-rs/src/fs/inode.rs
> +        let mut bp = (&kernel().disk).read(self.dev, kernel().fs().superblock.iblock(self.inum));
네 그런 셈입니다.

2020-12-10 12:45 UTC, coolofficials commented on kernel-rs/src/fs/inode.rs
> +        let mut bp = (&kernel().disk).read(self.dev, kernel().fs().superblock.iblock(self.inum));
답변 감사합니다!