Remove tag
kaist-cp/rv6 pull request #306
Opened 2020-12-10 14:46 UTC by jeehoonkang

- 지저분한 tag가 있었는데 모두 없앴습니다.
- kernel()을 되도록 적게 사용하자는 제안과 관련이 있습니다.  kernel()이 사용되는 지점을 점점 더 상위 레벨로 올려서 나중에는 없에버리는게 목표입니다.

2020-12-21 13:49 UTC, coolofficials requested changes
변경 사항 확인했습니다!

2020-12-21 13:49 UTC, coolofficials commented on kernel-rs/src/file.rs
> +            ArrayArena::new(array_const_fn_init![ftable_entry; 100]),
교수님 100이라는 Magic Number가 NFILE이 되는 것이 좋을 것 같습니다.

2020-12-21 13:49 UTC, coolofficials commented on kernel-rs/src/fs/inode.rs
> +            ArrayArena::new(array_const_fn_init![itable_entry; 50]),
이것도 50 대신 NINODE를 사용하는 것이 좋을 듯 합니다.

2020-12-22 01:25 UTC, jeehoonkang commented on kernel-rs/src/file.rs
> +            ArrayArena::new(array_const_fn_init![ftable_entry; 100]),
감사합니다. @kimjungwow @anemoneflower 두분도 의견 주시면 한꺼번에 반영하겠습니다

2020-12-22 03:28 UTC, kimjungwow reviewed
변경 사항 확인했습니다! `kernel` 사용을 줄이기 위한 리팩토링 방향을 계속 고민해봐야 할 것 같습니다.

2020-12-22 03:28 UTC, kimjungwow commented on kernel-rs/src/bio.rs
> +            MruArena::new(array_const_fn_init![bcache_entry; 30]),
30을 `NBUF`로 바꾸면 좋겠습니다!

https://github.com/kaist-cp/rv6/blob/d28972066b059796b1ebb80afccd3407cdcb4c01/kernel/bio.c#L26-L34

2020-12-22 03:28 UTC, kimjungwow commented on kernel-rs/src/bio.rs
> +        unsafe { Rc::from_unchecked(&kernel().bcache, inner) }
```suggestion
        unsafe { Rc::from_unchecked(self, inner) }
```
https://github.com/kaist-cp/rv6/pull/306/commits/94b584f9466505b07c5bfaf0792da5325a4be4c6 과 같은 맥락으로, #267  관련 수정 제안입니다.

2020-12-22 03:28 UTC, kimjungwow commented on kernel-rs/src/bio.rs
> +        Some(unsafe { Rc::from_unchecked(&kernel().bcache, inner) })
```suggestion
        Some(unsafe { Rc::from_unchecked(self, inner) })
```

2020-12-22 03:28 UTC, kimjungwow commented on kernel-rs/src/bio.rs
> +    pub fn buf(&self, dev: u32, blockno: u32) -> BufUnlocked<'_> {
`get_inode()`처럼 이 함수도 `get_buf()`로 하면 어떨까요?

2020-12-22 06:24 UTC, anemoneflower approved these changes

2020-12-22 12:59 UTC, jeehoonkang commented
Superceded by #310

2020-12-22 12:59 UTC, closed without merging