[Closes #265, #311] Intrusive doubly linked list
kaist-cp/rv6 pull request #313
Opened 2021-01-05 11:46 UTC by travis1829

미리 draft를 올립니다.
* Closes https://github.com/kaist-cp/rv6/issues/265, https://github.com/kaist-cp/rv6/issues/311.

- raw pointer가 바깥으로 노출되지 않는 간단한 list.rs를 만든 후 이걸로 arena.rs을 수정했습니다.
- 항상 ListEntry를 init()한 후에만 member function을 쓴다고 가정하면, arena.rs에서 unsafe로 표기해야되는 부분이 조금 줄어듭니다.
- 다만, arena.rs도 그렇고 list.rs도 그렇고, new()만 하고 init()은 안 한 상태에서 member function을 쓰면 에러가 생기는데, 이런점에 대해서는 unsafe로 표기가 안 되어 있습니다. (참고로, new()가 const 함수이기 때문에 그렇다고 init()을 new()안에 넣을 수도 없습니다.) unsafe로 바꿔거나 구현을 바꿔어야 할까요?

2021-01-05 12:38 UTC, coolofficials requested changes
Draft 상태인거죠? Draft로 변경해주시는게 좋을 것 같습니다.

2021-01-05 12:38 UTC, coolofficials commented on kernel-rs/src/list.rs
> +}
마지막에 empty line 추가해주세요

2021-01-05 12:38 UTC, coolofficials commented on kernel-rs/src/trap.rs
> +            // TODO(@travis1829): this is a temporary fix just to circumvent the
너무 작은거기는 하지만 해당 PR에서는 #265 만 다루는게 좋지 않을까요? 서로 연관 없는 하나의 PR은 하나의 issue 또는 연관성 있는 issue들만 다루는게 좋아서요.

2021-01-06 06:00 UTC, coolofficials approved these changes

2021-01-06 07:34 UTC, travis1829 commented
@jeehoonkang 교수님 review 부탁드립니다.

2021-01-06 08:13 UTC, closed without merging

2021-01-06 08:18 UTC, travis1829 commented
Continued at https://github.com/kaist-cp/rv6/pull/316