[Closes #300] Acquire global lock "wait_lock" before accessing parent field
kaist-cp/rv6 pull request #318
Opened 2021-01-07 11:31 UTC by travis1829

* Closes https://github.com/kaist-cp/rv6/issues/300
* 현재 @anemoneflower 님께서 이미 procGuard관련 refactoring을 하시는걸로 알고 있어서, 최대한 겹치지 않게 parent field 관련된 부분만 한번 시험적으로 변경해봤습니다.

# 변경사항
* parent field만을 위한 type 및 API를 만들려다가, 최대한 깔끔하게 하기 위해서 **Spinlock과 매우 비슷한 GlobalSpinlock을 만들었습니다.**
* GlobalSpinlock은 Spinlock과 거의 비슷하나(거의 대부분의 코드를 복사 붙여넣었습니다), 유일한 차이점은 Spinlock은 Spinlock 하나당 RawSpinlock하나를 own하지만, **GlobalSpinlock은 RawSpinlock을 own하지 않고 외부의 global한 RawSpinlock을 가르키는 raw pointer를 갖습니다.**
* **GlobalSpinlockGuard**를 얻기 위해서는 **GlobalSpinlock::lock()** 를 하거나, 동일한 RawSpinlock을 이용하는 다른 GlobalSpinlock으로부터 이미 획득한 GlobalSpinlockGuard를 이용하여 **GlobalSpinlock::lock_with_guard()** 를 하면 됩니다. (spinlock.rs 참고). 굳이 atomic instruction을 다시할 필요가 없도록 하기 위해 이런 API를 추가했습니다.
* ProcInfo의 **parent field**를 Proc안으로 옮긴 후, access하기 위해서는 먼저 **GlobalSpinlock**를 거쳐가야 하도록 바꿨습니다.
* 다만, ProcInfo의 lock을 acquire한 상태에서 wait_lock을 확보하려고 하면 순서가 잘못되었으므로 deadlock이 생길 수 있는 것 같은데, 이걸 방지하는 코드는 아직 없습니다.

# 추가 변경/확인사항
* **proc.rs의 sleep, sleep_sleepable 함수에 버그가 있어서 수정했습니다.** 기존에는 ***const SleepableLock-> usize -> *const RawSpinlock**의 순서로 잘못된 형변환을 합니다. 수정후에는 raw() 함수가 곧바로 ***const RawSpinlock**을 리턴합니다. 어차피 Spinlock/SleepableLock의 가장 첫번째 field가 **lock: RawSpinlock**이여서 지금까지 오류는 안 일어난 것 같습니다.
* Spinlock::reacquire_after()는 arena.rs의 reacquire_after에서만 쓰이는데, 정작 arena.rs의 reacquire_after는 아무데서도 사용되지 않습니다. 일단 놔뒀습니다만, 불필요하다면 지우는 것도 좋을 것 같습니다.
* Spinlock::raw()는 어디에서도 사용되지 않습니다.
* array! macro는 array_const_fn_init과 달리, function pointer가 아니라 그냥 closure도 사용 가능하므로, 불필요한 코드를 삭제했습니다.

2021-01-07 12:43 UTC, jeehoonkang commented on kernel-rs/src/spinlock.rs
> +pub struct GlobalSpinlock<T> {
재밌는 아이디어인 것 같습니다.

- 혹시 `GlobalSpinlock<'s, T>` 와 같이 정의해서 lock pointer의 scope을 `'s`로 지정할 수 있나요? 아마 대부분 `'static`을 쓸 것 같긴 한데 그래도 더 systematic하게 lifetime을 지정할 수 있을 것 같아서 질문드립니다.
- 아울러 `GlobalSpinlock::new(&spinlock, data)` 이런 식으로 만들 수도 있을까요?
- 이름: "Global"의 의미가 잘 와닿지 않는 것 같습니다. 혹시 다른 단어 고민해보실래요?

2021-01-07 12:43 UTC, jeehoonkang commented on kernel-rs/src/spinlock.rs
> +    pub fn lock_with_guard<'s>(
음 이 함수가 잘 이해가 안갑니다. 혹시 어떤 motivation인가요?

2021-01-07 12:43 UTC, jeehoonkang commented on kernel-rs/src/proc.rs
> +            parent_guard = pp.parent.lock_with_guard(parent_guard);
이 코드를 좀더 자세히 설명해주시겠어요?

2021-01-08 01:18 UTC, travis1829 commented on kernel-rs/src/spinlock.rs
> +pub struct GlobalSpinlock<T> {
* 당연히 가능합니다. 애초에, 처음에는 교수님 말씀처럼 `GlobalSpinlock<'s, T>`도 해보고 `'static`도 이미 해봤는데, 이러면 proc.rs에서 lifetime을 표시해야되는 부분이 생기는게 싫어서 그냥 간단하게 raw pointer를 사용하도록 바꿨었습니다. 다만, raw pointer는 dangling ref이 가능하니까, **교수님 말씀대로 바꿔보겠습니다!**
* `GlobalSpinlock::new(&rawspinlock, data)`도 가능은 하며, 처음에는 그렇게 시도했습니다. 
	* 다만, 이러면 const fn안에서 쓸 수 없는 것 같아 `GlobalSpinlock::zero()`와 `GlobalSpinlock::init()`로 나눴습니다. 자세히 말씀드리자면, ProcessSystem::zero()가 문제입니다. `ProcessSystem::process_pool` 배열을 초기화할때, `GlobalSpinlock::new(&rawspinlock, data)`이 아직 만들지도 않은 `ProcessSystem::wait_lock`을 reference 해야해서 안 되는것 같습니다.  다만, 이건 그냥 제가 Rust를 잘 몰라서 실수한 것일 수도 있으므로, **한번 다시 확인해보겠습니다.**
	* 다른 방법으로는, `wait_lock`을 static 변수로 정의해서 사용하는 것인데, const fn안에서는 static 변수를 reference할 수 없도록 되어있더군요.
* **이름에 대해서는 좀 더 생각해보겠습니다!**

2021-01-08 01:18 UTC, travis1829 commented on kernel-rs/src/spinlock.rs
> +    pub fn lock_with_guard<'s>(
* 기존 xv6에서 global lock인 `wait_lock`를 사용하는 경우는 2가지입니다. 
	1. 딱 한개의 `Proc`의 parent field를 access하고 싶을 때.
	2. **모든 `Proc`들을 iterate하면서 각각의 parent field를 access 하고 싶을 때.**
* 이때, i.의 경우는 한번만 `lock()`을 하면 되지만, ii.의 경우 `lock_with_guard()`가 없다면, `lock()`했다가 풀었다가를 계속 반복해야 됩니다. **(즉, 내부적으로는 동일한 `RawSpinlock`을 계속 `acquire`했다가 `release`했다가를 반복합니다)**
* 그래서, ii.의 경우 어차피 동일한 RawSpinlock인데 의미없는 atomic instruction을 너무 낭비한다고 생각하여, 처음에만 `GlobalSpinlock::lock()`을 하고서 guard를 획득한 후 이후부터는 그냥 이전의 guard를 consume해서 다른 `GlobalSpinlock`의 guard로 변환하면서 진행하면 훨씬 효율적일것 같아 이렇게 했습니다. **즉, RawSpinlock을 acquire한 상태를 계속해서 지속하면서, guard가 reference하는 data만 계속 변경합니다.**
* 즉, guard를 획득하는 방법이 두가지입니다.
	* **GlobalSpinlock::lock()**
	* **GlobalSpinlock::lock_with_guard() 에 이전에 획득한 guard를 삽입**
https://github.com/kaist-cp/rv6/blob/c50a2d8c52a7932bd56a0d01ede5b8e1cb09ee89/kernel-rs/src/proc.rs#L722-L728
* 보시면, 처음 L722에서만 lock()을 하고, 첫번째 guard를 획득한 이후부터는 L728에서처럼 이전에 얻은 parent_guard를 `lock_with_guard()`에 넣어서 다음 parent_guard를 얻습니다.
* 다만, 이제와서 보니 조금 비직관적이긴 한 것 같습니다.
* 다른 방법으로는, 모든 parent field들을 하나의 collection으로 모은 후 그 collection 하나만 일반적인 Spinlock으로 감쌀수도 있겠지만, 이러면 특정 Proc의 parent를 찾기위해서는 그 collection을 탐색해야 해서 runtime 비용이 발생합니다.

2021-01-08 01:19 UTC, travis1829 commented on kernel-rs/src/proc.rs
> +            parent_guard = pp.parent.lock_with_guard(parent_guard);
위에서 설명한 `lock_with_guard`의 또다른 사용예입니다. 
* 기존에는 `reparent()`를 call하기 전에는 이미 `wait_lock`을 쥔 상태라고 그냥 가정했습니다.
* 변경 후에는,
1. `reparent()`의 caller가 먼저 `parent_guard`를 하나 제공해줍니다.
2. `reparent()` 내부에서는 모든 `Proc`들을 iterate하면서, `lock_with_guard()`를 이용하여 기존의 `parent_guard`를 계속 다른 `Proc::parent`에 대한 guard로 변경한 후 deref합니다. 이런 식으로 `wait_lock`을 acquire한 상태를 계속 지속합니다.
3. `reparent()`가 끝난 후에는 parent_guard를 리턴하여, `reparent()`이 끝난 후에도 `wait_lock`을 acquire한 상태가 계속되도록 합니다.
https://github.com/kaist-cp/rv6/blob/c50a2d8c52a7932bd56a0d01ede5b8e1cb09ee89/kernel-rs/src/proc.rs#L585-L602

2021-01-08 01:19 UTC, travis1829 commented
사실, 더 효율적인 방법들도 있는 것 같습니다만, 최대한 기존 proc.rs를 변경하지 않으면서 refactoring을 해보고 싶어서 이렇게 해봤습니다. 다만, GlobalSpinlock이라는 새로운 type을 써야되는게 아쉽지만, 사실 거의 대부분의 코드는 Spinlock이랑 같습니다.

2021-01-08 08:09 UTC, travis1829 commented
### 교수님 말씀대로 `GlobalSpinlock`의 API를 바꿔보았습니다.
* `GlobalSpinlock::zero()`와 `GlobalSpinlock::init()`을 없앤 후 `GlobalSpinlock::new()`를 추가했습니다.
* `GlobalSpinlock`은 이제 `*mut RawSpinlock`이 아닌 `&'static RawSpinlock`을 가집니다. (`'static`을 쓰지 않고 `GlobalSpinlock<'s, T>`형태로 쓰려면 rv6 소스 코드에서 매우 많은 부분에 lifetime parameter를 추가해야됩니다. 사소하긴 하지만, 쓸데없이 신경써야되는 부분이 많이 생기는 것 같아 오늘 sync up에서 이렇게 결정했습니다.)
이렇게 하니` GlobalSpinlock`의 API가 훨씬 깔끔하고 unsafe도 줄어들었습니다.

### 다만, `Proc::parent`을 `GlobalSpinlock<*mut Proc>` type -> `Option<GlobalSpinlock<*mut Proc>>` type으로 바꿨습니다.
* 처음에는 `Proc::parent`을 `None`으로 초기화 한 후, `procinit()`에서 `Some(GlobalSpinlock::new(&procs.wait_lock, ptr::null_mut()))`으로 바꿉니다.
* 이렇게 하는 이유는, `GlobalSpinlock::new(**&wait_lock**, ptr::null_mut())`을 `const fn`에서는 사용할 수 없기 때문입니다. (정확히는, `&wait_lock`을 refer할 방법이 없는 것 같습니다.)
* 다른 방법으로는 `MaybeUninit`을 쓸 수 있겠으나, 이러면 불필요한 unsafe 코드가 생깁니다. 또, `mem::zeroed()`는 const fn에서는 사용할 수 없습니다.

혹시 이런 상황에서 보통 어떻게 하는지 의견을 제시해 주실 수 있으신가요? 구글링 해도 잘 모르겠어서 부득이하게 여러분께 문의드립니다.

2021-01-08 14:17 UTC, jeehoonkang requested changes

2021-01-08 14:17 UTC, jeehoonkang commented on kernel-rs/src/spinlock.rs
> +        if self.lock as *const _ != guard.lock.lock as *const _ {
- `assert!`를 쓰면 좋겠습니다.
- 이 체크가 runtime cost가 들어가긴 하겠네요. rv6에서 비용을 더 쓴다고 comment로 명시하면 좋을 것 같습니ㅏㄷ.

2021-01-08 14:17 UTC, jeehoonkang commented on kernel-rs/src/spinlock.rs
> +    pub fn lock_with_guard<'s>(
좀 다른 아이디어로- spinlock을 잡아서 guard를 가지고 있으면, 그 spinlock을 가리키는 global spinlock의 데이타를 접근할 수 있도록 API를 설계할 수도 있을 것 같습니다. 그러면 guard를 다시 얻을 필요 없이 하나의 guard를 이용해서 여러 global spinlock data에 접근할 수 있을 것 같아요. 다만 이 경우도 lock이 같은지 여부를 runtime에 체크해야 합니다.

2021-01-08 14:17 UTC, jeehoonkang commented on kernel-rs/src/spinlock.rs
> +pub struct GlobalSpinlock<T> {
이름: `SpinlockProtected` 정도가 어떨까 합니다.

2021-01-08 14:17 UTC, jeehoonkang commented on kernel-rs/src/proc.rs
> +            parent_guard = pp.parent.assume_init_ref().lock_with_guard(parent_guard);
`parent.assume_init_ref()`들이 모두 안전한지 잘 모르겠습니다.

2021-01-08 14:31 UTC, travis1829 commented on kernel-rs/src/proc.rs
> +            parent_guard = pp.parent.assume_init_ref().lock_with_guard(parent_guard);
* `Proc::parent`들은 proc.rs의 `procinit()`에서 initialize되는데, `procinit()` 함수는 `kernel_main()`에서 실행됩니다. (kernel.rs:225).
* 가장 첫번째 userprocess인 init은 그 이후에 만들어집니다. (kernel.rs:246). 그리고 init은 애초에 parent process이 없으므로 `Proc::parent` field를 access할 일이 없습니다.
https://github.com/kaist-cp/rv6/blob/2ab9e34eaa5329fb50654553c0545897114b44c4/kernel-rs/src/kernel.rs#L225-L247
* 그러므로, 아마도 안전할 것 같긴 합니다만, 그래도 좀 더 확인은 해보겠습니다.

2021-01-09 12:40 UTC, travis1829 commented
* ### `lock_with_guard()`를 없애고 `get_mut()`로 대체했습니다.
`get_mut()`는 input으로 주어진 `&'s SpinlockProtectedGuard`를 체크한 후 `&'s T`를 리턴합니다. lifetime을 명시했기 때문에, 주어진 `SpinlockProtectedGuard`를 outlive하는 일은 일어나지 않습니다. (즉, `RawSpinlock`을 release한 이후에도 data를 refer할 수는 없습니다.)
* ### `freeproc()` 함수의 unsound한 부분을 변경했습니다.
기존의 경우, **xv6과 rv6 모두, `wait_lock`을 acquire하지도 않은 상태에서 `freeproc()` 함수에서 `Proc`의 parent field을 null pointer로 write하는 경우가 있었습니다.** 그럼에도 xv6/rv6에서 문제가 일어나지 않았던 이유는, `wait_lock`을 acquire하지 않은 상태에서 `freeproc()`을 부르는 경우에는 항상 Proc의 parent field가 이미 null pointer이였기 때문입니다. (즉, 사실 parent filed를 write할 필요가 어차피 없었습니다) 이 부분을 좀 더 명시적으로 나타내기 위해서, parent field를 write하고 싶은 경우에는 `freeproc()` 함수에게 `SpinlockProtectedGuard`를 제공해야 하도록 바꿨습니다.

2021-01-10 13:35 UTC, jeehoonkang requested changes

2021-01-10 13:35 UTC, jeehoonkang commented on kernel-rs/src/proc.rs
> +unsafe fn freeproc(mut p: ProcGuard, parent_guard: Option<SpinlockProtectedGuard<'_, *mut Proc>>) {
음 혹시 이 변경이 왜 필요한지 궁금합니다. 복잡해보여서요

2021-01-10 13:35 UTC, jeehoonkang commented on kernel-rs/src/proc.rs
> +        p.parent
혹시 maybeuninit을 없애려고 한다면 변경이 필요할까요?

2021-01-10 13:35 UTC, jeehoonkang commented on kernel-rs/src/spinlock.rs
> +pub struct SpinlockProtectedGuard<'s, T> {
이거 대신에 `SpinlockGuard<()>`를 사용하면 되지 않을까 합니다. 코드를 보니 한 lock을 잡고 여러 spinlockprotected에서 사용하는게 눈에 보이던데, 그럴려면 guard가 spinlockprotected를 refer하지 않는게 맞아보여서요

2021-01-10 14:00 UTC, travis1829 commented on kernel-rs/src/proc.rs
> +unsafe fn freeproc(mut p: ProcGuard, parent_guard: Option<SpinlockProtectedGuard<'_, *mut Proc>>) {
위에서 설명한대로 입니다!
(https://github.com/kaist-cp/rv6/pull/318#issuecomment-757144626 의 두번째 부분)

혹시 제가 설명이 부족했거나, 아니면 다른 방법을 사용하는게 더 나을까요?

2021-01-10 14:00 UTC, travis1829 commented on kernel-rs/src/proc.rs
> +        p.parent
`p.parent`이 `MaybeUninit<SpinlockProtected<*mut Proc>>`이 아니라 그냥 `SpinlockProtected<*mut Proc>`이였으면 좋겠다는 말씀이신가요? 저도 `p.parent`를 굳이 나중에 여기서 initialization하지 않고 `Proc::zero()`에서 처음부터 initialization된 상태로 만들 수 있으면 좋을 것 같은데, 문제는 `Proc::zero()`는 const fn인데 const fn에서는 `SpinlockProtected::new(&procs.wait_lock, ptr::null_mut())`를 사용할 수가 없는 것 같습니다. (자세히 말씀드리자면, `proc.wait_lock`을 reference할 수 없습니다.)

2021-01-10 14:19 UTC, jeehoonkang commented on kernel-rs/src/proc.rs
> +unsafe fn freeproc(mut p: ProcGuard, parent_guard: Option<SpinlockProtectedGuard<'_, *mut Proc>>) {
설명한 부분을 코드에 주석으로 적어주시면 감사하겠습니다-

2021-01-10 14:20 UTC, jeehoonkang commented on kernel-rs/src/proc.rs
> +        p.parent
이 이야기를 maybeuninit을 정의한 곳에 적어주는게 좋겠습니다. 어쩔수 없었다는 설명이 있어야할 것 같아서요

2021-01-11 08:25 UTC, travis1829 commented on kernel-rs/src/spinlock.rs
> +pub struct SpinlockProtectedGuard<'s, T> {
혹시 `SpinlockProtectedGuard<'s, T>`를 변경하자는 뜻이신가요, 아니면 `SpinlockProtectedGuard<'s, T>`라는 새로운 type을 굳이 만들지 말고 이미 있는 `SpinlockGuard<'s, T>`를 `Spinlock`와 `SpinlockProtected`가 공유하도록 하자는 뜻이신가요?

저는 전자로 이해하고 작업했는데, 혹시 후자라면 말씀해주세요.
(다만, 후자의 경우, 어떤 `SpinlockGuard`는 deref이 가능하고 어떤 `SpinlockGuard`는 deref이 불가능한게 조금 비직관적일 수 있어, 지금처럼 type을 명시적으로 2개로 나누는것도 괜찮을 것 같습니다. 또, `SpinlockGuard`는 `& RawSpinlock`이 아니라 `& Spinlock`을 저장하므로, `SpinlockGuard`의 구조를 바꿔야 될 것 같습니다.)

2021-01-11 08:25 UTC, travis1829 commented
이제 `SpinlockProtected`의 data를 access하고 싶으면, 무조건 `SpinlockProtected::get_mut()`를 이용해야됩니다. (즉, `SpinlockProtectedGuard`는 더 이상 `deref`, `deref_mut` trait을 가지고 있지 않습니다.)

참고: 사실 이것 말고도 proc.rs와 spinlock.rs에서 바꿔야 될 부분이 꽤 있는 것 같은데, 이 PR이 너무 늘어지는 것 같아 일단은 이 정도에서 끊었습니다.

2021-01-11 12:17 UTC, jeehoonkang commented on kernel-rs/src/spinlock.rs
> +pub struct SpinlockProtectedGuard<'s, T> {
@travis1829 음 제가 약간 너무 하이레벨에서 의견을 드리는 것 같은데, 제가 위에서 드린 코멘트중에 마지막 문장만 보고 수정해주시면 어떨가 합니다.

2021-01-11 12:25 UTC, travis1829 commented on kernel-rs/src/spinlock.rs
> +pub struct SpinlockProtectedGuard<'s, T> {
일단, 이번 https://github.com/kaist-cp/rv6/pull/318/commits/f9c57e88f8cd928d1f8c744368962622c688777c 에서 그 내용을 반영하기는 했습니다! (더 이상 `SpinlockProtectedGuard`가 `SpinlockProtected`을 refer하지 않습니다. 다만, drop할때 `RawSpinlock`을 release하기는 해야되므로 그 대신 `RawSpinlock`을 refer합니다.)
그리고 https://github.com/kaist-cp/rv6/pull/318#issuecomment-757706057 에 나와있듯이, 이제 `SpinlockProtectedGuard`가 `SpinlockProtected`를 refer하지 않으므로 더 이상 `deref`, `deref_mut` trait을 impl하지 않습니다.

2021-01-11 12:49 UTC, jeehoonkang commented
bors r+

2021-01-11 12:56 UTC, merged

2021-01-12 08:13 UTC, efenniht reviewed
Proc 관련 코드는 이후에도 더 리팩토링하겠지만, 코드를 보다가 unsound한 곳이 있어서 리뷰를 남깁니다:

2021-01-12 08:14 UTC, jeehoonkang commented on kernel-rs/src/spinlock.rs
> +    pub fn get_mut<'s>(&self, guard: &'s SpinlockProtectedGuard<'s>) -> &'s mut T {
새 이슈로 남겨주세여