[Closes #328] Remove FsTransaction from InodeGuard
kaist-cp/rv6 pull request #329
Opened 2021-01-12 14:42 UTC by Medowhill

Closes #328

* `InodeGuard`의 `tx: &FsTransaction` 필드를 없애고 `InodeGuard`의 메서드 중 `FsTransaction`이 필요한 메서드만 명시적으로 `FsTransaction`을 인자로 받도록 수정했습니다.
* `exec.rs`의 `exec`와 `sysfile.rs`의 `sys_chdir`은 `FsTransaction`을 사용하지는 않지만 할당되어 있던 inode를 해제할 수 있기 때문에 `begin_transaction`을 호출합니다. 이는 기존 C 코드에서 `begin_op`를 호출하는 것에 합치합니다. 반면, `file.rs`의 `read`는 더 이상 `begin_transaction`을 호출하지 않으며 이 역시 기존 C 코드에서 `begin_op`를 호출하지 않는 것에 합치합니다.

2021-01-12 14:55 UTC, jeehoonkang requested changes

2021-01-12 14:55 UTC, jeehoonkang commented on kernel-rs/src/exec.rs
> +        let _tx = self.file_system.begin_transaction();
이 tx는 어디서 필요한가요?

2021-01-12 14:55 UTC, jeehoonkang commented on kernel-rs/src/fs/inode.rs
> -    tx: &'a FsTransaction<'a>,
이렇게 되면 inode guard를 만든 이후에 fs transaction을 만들 수도 있지 않나요? 그래도 safe한지 확인 부탁드립니ㅏㄷ.

2021-01-12 14:55 UTC, jeehoonkang commented on kernel-rs/src/fs/inode.rs
> +                addr = unsafe { tx_opt.unwrap().balloc(self.dev) };
혹시 tx_opt.unwrap()을 하지 않도록 만들 수도 있을까요? unwrap이 다소 의아해서 질문드립니다

2021-01-12 14:55 UTC, jeehoonkang commented on kernel-rs/src/sysfile.rs
> +        let _tx = self.file_system.begin_transaction();
이 tx는 어디서 필요한가요?

2021-01-12 15:05 UTC, Medowhill commented on kernel-rs/src/exec.rs
> +        let _tx = self.file_system.begin_transaction();
`namei`에서 호출한 `namex`에서 inode가 drop될 수 있고 `namei`이 성공하면 그 결과로 얻은 `ptr`이 `exec`가 끝날 때 drop됩니다. 그러면 `Inode`의 `finalize`가 호출되고 그 안에서 디스크에 쓰기가 일어날 수 있습니다. `finalize`에서는 `begin_transaction`을 하지 않으므로 `finalize`가 호출될 수 있다면 미리 `begin_transaction`을 호출해 주어야 합니다. 이는 xv6에서 `iput`을 호출할 수 있는 모든 함수는 그 전에 `begin_op`를 호출해야 하는 것과 같은 논리입니다.

2021-01-12 15:07 UTC, jeehoonkang commented on kernel-rs/src/exec.rs
> +        let _tx = self.file_system.begin_transaction();
만일 그렇다면 inode가 drop될 때 transaction이 열려있어야 하므로 inode가 (혹은 inode guard가) fs transaction의 reference를 들고있는게 더 나은 디자인인 것처럼 느껴지는데요, 혹시 어떻게 생각하시나요?

2021-01-12 15:09 UTC, Medowhill commented on kernel-rs/src/sysfile.rs
> +        let _tx = self.file_system.begin_transaction();
309 줄에서 `data.cwd = Some(ptr);`를 통해 기존에 `data.cwd`에 저장되어 있던 현재 디렉토리의 inode가 drop됩니다. 그 후는 `exec.rs`에 대한 설명과 동일합니다. 만약 저 줄이 없으면 `usertests`의 `iput` 테스트에서 커널 패닉이 발생합니다.

2021-01-12 15:11 UTC, Medowhill commented on kernel-rs/src/fs/inode.rs
> +                addr = unsafe { tx_opt.unwrap().balloc(self.dev) };
`tx_opt`가 `None`인 경우는 기존의 `assert!(...)`가 실패하는 경우와 동일하므로, 만약 `tx_opt`가 `None`이라면 패닉을 발생시켜야 합니다. 그렇기 때문에 그냥 `unwrap`을 사용해도 무방하다고 판단했습니다.

2021-01-12 15:19 UTC, Medowhill commented on kernel-rs/src/fs/inode.rs
> -    tx: &'a FsTransaction<'a>,
`InodeGuard`가 만들어지는 곳은 `Inode`의 `lock` 메서드인데 이 메서드에서 디스크에 쓰는 작업을 하지 않으므로 `FsTransaction`이 없는 상태로 `InodeGuard`를 만들어도 안전할 것 같습니다.

2021-01-12 15:23 UTC, Medowhill commented on kernel-rs/src/exec.rs
> +        let _tx = self.file_system.begin_transaction();
`Inode`를 만들 때 `FsTransaction`을 만들고 `Inode`가 drop될 때에서야 그 transaction이 끝난다면, 한 프로세스가 파일을 연 뒤에 아무 작업도 하지 않고 그냥 파일을 연 채로 계속 가만히 있기만 해도 transaction이 계속 열려 있어야 하므로 파일 시스템에 일어난 어떤 변화도 디스크에 기록되지 않을 것 같습니다. 이것이 바람직한 변화 방향인지 잘 모르겠습니다.

2021-01-12 15:25 UTC, jeehoonkang commented on kernel-rs/src/exec.rs
> +        let _tx = self.file_system.begin_transaction();
@Medowhill 이 PR에 대해서는 이제 (온라인) 미팅에서 얘기하는게 더 효율적일 것 같습니다. 혹시 내일 11시 이후에 잠깐 만날 수 있나요? 제 일정은 다음과 같고 https://cp.kaist.ac.kr/jeehoon.kang/#calendar 미팅은 google calendar에서 (meet 포함해서) 재민님이 초대해주세요

2021-01-12 15:32 UTC, Medowhill commented on kernel-rs/src/exec.rs
> +        let _tx = self.file_system.begin_transaction();
네. 미팅 만들고 초대 보내 드렸습니다.

2021-01-13 07:07 UTC, efenniht commented on kernel-rs/src/fs/inode.rs
> +            // we cannot begin a new transaction here becuase beginning of a
becuase -> because

2021-01-13 07:13 UTC, Medowhill commented
`let _tx = self.file_system.begin_transaction();`이 필요한 4 곳에 그 이유에 대한 설명을 주석으로 추가했습니다. 해당 문제는 #290 에서 다룰 예정입니다.

2021-01-14 01:10 UTC, jeehoonkang requested changes
사소한거 하나만 하고 머지하겠습니다.  @efenniht comment 하나만 반영하면 r+ 해주시겠어요?

2021-01-14 01:10 UTC, jeehoonkang commented on kernel-rs/src/fs/inode.rs
> +                addr = unsafe { tx_opt.unwrap().balloc(self.dev) };
tx_opt.expect("bmap: out of range").... 로 바꿔주실 수 있나요? unwrap을 쓴 다른 곳도 마찬가지입니다.

2021-01-14 03:13 UTC, Medowhill commented on kernel-rs/src/fs/inode.rs
> +                addr = unsafe { tx_opt.unwrap().balloc(self.dev) };
수정했습니다.

2021-01-14 03:14 UTC, jeehoonkang commented
bors r+

2021-01-14 03:25 UTC, merged