[Closes https://github.com/kaist-cp/rv6/issues/295] Replace freeproc(), proc_freepagetable() with ProcGuard::drop(), PageTable<UVAddr>::drop()
kaist-cp/rv6 pull request #330
Opened 2021-01-13 10:26 UTC by travis1829

* Closes https://github.com/kaist-cp/rv6/issues/295

1번
* **이제 `freeproc()`을 직접 call해야되는 경우는 `ProcessSystem::wait()`에서 `ZOMBIE` 상태의 child process을 reap하고 싶을 때 뿐입니다.** 그 외에는 `Process`의 `state`가 `STARTING1`인 경우, `ProcGuard::drop()`할때 알아서 call됩니다.
* `freeproc()`은 이제 `ProcGuard`의 method 중 하나입니다.
* 추가로, `STARTING1`과 `STARTING2`라는 새로운 state를 추가했습니다. 굳이 2개나 추가한 이유는 `ProcessSystem::fork()`때문입니다. (아래 코드의 주석 참고. 아주 잠깐동안 `ProcGuard`이 drop되는 부분이 있습니다.).
	* `ProcessSystem::fork()`을 시작하자마자 `wait_lock`을 acquire하도록 변경한다면 굳이 2개일 필요가 없어지지만, 이러면 critical section의 길이가 길어지고 xv6이랑 약간 달라지는 것 같아 일단은 놔뒀습니다.

2번
* **proc_freepagetable을 `PageTable<UVAddr>::drop()`로 대체**했고, 지저분한 부분들을 조금 정리했습니다.(proc_freepagetable은 더 이상 사용되진 않지만 일단 놔뒀습니다.)
* 이를 위해, `PageTable`에 `num_usr_pages`라는 field를 추가했습니다. (`ProcData::sz`는 그대로 놔뒀습니다.)
* 다만, **`Drop` trait을 추가했다는 뜻이 아니라 그냥 `drop()`라는 함수를 추가했다는 뜻입니다.**
	* `Drop` trait을 추가하면 좋을텐데, 현재 Rust에서는 특정 generic type만을 위한 Drop을 만들수가 없어서 이렇게까지 밖에 하지 못했습니다. 혹시 다른 방법이 있으면 말씀해주시면 감사하겠습니다. @jeehoonkang @efenniht

2021-01-14 00:58 UTC, jeehoonkang requested changes
오늘 가능한 이른 시간에 15분 미팅 잡아주세요

2021-01-14 00:58 UTC, jeehoonkang commented on kernel-rs/src/vm.rs
> +    pub unsafe fn drop(&mut self) {
함수 이름을 다르게 하는게 어떨까 합니다. Drop::drop이랑 헷갈려서요

2021-01-14 00:58 UTC, jeehoonkang commented on kernel-rs/src/exec.rs
> +        let mut ptable_guard = scopeguard::guard((pt, sz), |(mut pt, _)| {
sz는 더이상 사용되지 않나요? 그렇다면 왜?

2021-01-14 00:58 UTC, jeehoonkang commented on kernel-rs/src/proc.rs
> +    STARTING1,
xv6에는 없는 state이 추가되는거죠? 원래 USED의 의미는 무엇이었는지 설명해주시고, STARTING1, STARTING2의 의미가 무엇인지 코드에 주석으로 남겨주시면 좋겠습니다.

좀더 논의가 필요해보이는데 오늘중 가능한 이른 시간에 15분 미팅 잡아주세요

2021-01-14 00:58 UTC, jeehoonkang commented on kernel-rs/src/proc.rs
> +    unsafe fn freeproc(&mut self, parent_guard: Option<SpinlockProtectedGuard<'_>>) {
`mut self`가 아니라 `&mut self`를 받는 까닭은? freeproc한 이후에도 guard가 남아있는게 이상해서요

2021-01-14 00:58 UTC, jeehoonkang commented on kernel-rs/src/proc.rs
> +            if self.deref_info().state == Procstate::STARTING1 {
어떤 코드인지 궁금합니다.

2021-01-14 00:58 UTC, jeehoonkang commented on kernel-rs/src/proc.rs
> +        pagetable.drop();
걍 drop이면 이 줄이 없어도 되나요?

2021-01-14 00:58 UTC, jeehoonkang commented on kernel-rs/src/proc.rs
> +        pagetable.drop();
uvmfree가 있다면 kvmfree도 있나요? 둘다 drop으로 통합되는 건가요?

2021-01-14 00:58 UTC, jeehoonkang commented on kernel-rs/src/vm.rs
> +    num_usr_pages: usize,
설명을 주석으로 남겨주세요

2021-01-14 00:58 UTC, jeehoonkang commented on kernel-rs/src/vm.rs
> +impl Drop for PageTable<UVAddr> {
필요 없으면 없애는게 어떨가 합니다.

2021-01-14 00:58 UTC, jeehoonkang commented on kernel-rs/src/vm.rs
> +    pub unsafe fn drop(&mut self) {
Drop::drop으로 못하는 이유를 적어주셨는데 제가 이해를 못해서... 미팅에서 알려주세요

2021-01-14 00:58 UTC, jeehoonkang commented on kernel-rs/src/vm.rs
> +    pub unsafe fn drop(&mut self) {
이  함수가 하던 일이 원래 다른 함수에 있던 건가요?

2021-01-14 01:18 UTC, travis1829 commented on kernel-rs/src/exec.rs
> +        let mut ptable_guard = scopeguard::guard((pt, sz), |(mut pt, _)| {
* 기존에는: `sz`를 보고서 pagetable `pt`에 몇개의 user process page가 들어있는지를 계산해야되므로 `sz`를 알려줘야 했습니다.
	* 참고: `sz`는 `ProcData::sz`에서 온 걸로, process가 사용하고 있는 메모리의 크기를 byte 단위로 나타냅니다.
* 변경 후: `PageTable::num_usr_pages`에 이미 user process page의 숫자를 저장하므로, 더 이상 `sz`를 알려줄 필요가 없습니다.

2021-01-14 01:24 UTC, travis1829 commented on kernel-rs/src/proc.rs
> +    STARTING1,
* USED는 `processpool`에서 이 slot은 다른 `Proc`에 의해 사용되고 있지만, 현재 이 `Proc`은 아직 initialization이 완료되지 않은 상태임을 나타내는 state입니다.
* STARTING1은 USED와 거의 같습니다. 다만, 이름만 다를 뿐입니다.
* STARTING2는 이 `Proc`의 initalization이 거의 완료된 상태임을 나타내며, `STARTING1`과는 다르게 `ProcGuard`이 drop되더라도 `Proc`이 free되지 않습니다.
* 미팅에서 더 자세히 말씀드리겠습니다!

2021-01-14 01:25 UTC, travis1829 commented on kernel-rs/src/proc.rs
> +    unsafe fn freeproc(&mut self, parent_guard: Option<SpinlockProtectedGuard<'_>>) {
교수님 말씀이 맞는 것 같습니다! 바꿔보도록 하겠습니다!

2021-01-14 01:27 UTC, travis1829 commented on kernel-rs/src/proc.rs
> +            if self.deref_info().state == Procstate::STARTING1 {
https://github.com/kaist-cp/rv6/pull/291#discussion_r530407640 을 보면, 1번에 **"ProcGuard::drop()에서 Procstate가 UNUSED 인 경우 freeproc()을 실행하도록 리팩토링하면 좋겠습니다."** 라는 내용이 나와있습니다.
이 부분을 구현한 내용입니다. 다만, `UNUSED`인 경우 freeproc()을 실행하는게 아니라, STARTING1인 경우 freeproc()을 실행하는 것 뿐입니다.

2021-01-14 01:30 UTC, travis1829 commented on kernel-rs/src/proc.rs
> +        pagetable.drop();
kvmfree는 없습니다. 그리고 아직 확실하지는 않지만, 애초에 `PageTable<KVAddr>`이 drop되는 경우 자체가 없는 것으로 보입니다. (즉 kvmfree는 필요하지 않으며, pagetable이 drop되는 경우는 `PageTable<UVAddr>` type 뿐인 것으로 보입니다.)

2021-01-14 01:34 UTC, travis1829 commented on kernel-rs/src/vm.rs
> +    pub unsafe fn drop(&mut self) {
* 이 함수가 하는 일은 원래는 `proc_freepagetable()`이 하던 일이었습니다!
* 다만, 그 외에도 `proc_pagetable`이 `PageTable`을 만들다가 실패하는 경우, 미완성된 `PageTable`을 cleanup하는 작업도 추가로 합니다.

2021-01-16 09:14 UTC, travis1829 commented
이 PR의 Merge 자체는 홍재민님의 PR(https://github.com/kaist-cp/rv6/pull/334)이 끝난 후 할 예정이지만, 그 이전에 먼저 지금까지의 변경사항을 draft PR으로 공개하면 좋을 것 같아 일단 이렇게 올립니다.
* `Procstate` 중에서 STARTING1, STARTING2를 없앴고 USED를 다시 부활시켰습니다.
* `PageTable<A: VAddr>`을 trait으로 변경한 후, **`PageTable<UVAddr>` -> `UserPageTable`로 `PageTable<KVAddr>` -> `KernelPageTable`** 로 바꿨습니다.
	* 굳이 이렇게 한 이유는, 적어도 지금의 Rust에서는 특정 Generic 또는 Struct만을 위한 impl Drop을 할 수가 없는 것으로 보여서입니다. 이렇게 명확하게 두 개의 struct로 나누면 각각을 위한 Drop을 구현할 수 있습니다.
* `ProcData::sz` field를 `UserPageTable::sz`로 옮겼습니다.
	* 추가로, `UserPageTable::sz`는 외부에서는 Read-Only입니다. 즉, **`UserPageTable::uvm*`류의 함수들이 알아서 `UserPageTable::sz`를 update해주므로, 더 이상 외부에서 update을 직접 해야할 필요가 없습니다.** 이를 통해, 코드가 좀 더 깔끔해지는 부작용도 생긴 것 같습니다.

2021-01-16 09:15 UTC, travis1829 commented
이 PR의 Merge 자체는 홍재민님의 PR(https://github.com/kaist-cp/rv6/pull/334)이 끝난 후 할 예정이지만, 그 이전에 먼저 지금까지의 변경사항을 draft PR으로 공개하면 좋을 것 같아 일단 이렇게 올립니다.
* `Procstate` 중에서 STARTING1, STARTING2를 없앴고 USED를 다시 부활시켰습니다.
* `PageTable<A: VAddr>`을 trait으로 변경한 후, **`PageTable<UVAddr>` -> `UserPageTable`로 `PageTable<KVAddr>` -> `KernelPageTable`** 로 바꿨습니다.
	* 굳이 이렇게 한 이유는, 적어도 지금의 Rust에서는 특정 Generic 또는 Struct만을 위한 impl Drop을 할 수가 없는 것으로 보여서입니다. 이렇게 명확하게 두 개의 struct로 나누면 각각을 위한 Drop을 구현할 수 있습니다.
* `ProcData::sz` field를 `UserPageTable::sz`로 옮겼습니다.
	* 추가로, `UserPageTable::sz`는 외부에서는 Read-Only입니다. 즉, **`UserPageTable::uvm*`류의 함수들이 알아서 `UserPageTable::sz`를 update해주므로, 더 이상 외부에서 update을 직접 해야할 필요가 없습니다.** 이를 통해, 코드가 좀 더 깔끔해지는 부작용도 생긴 것 같습니다.

2021-01-16 09:46 UTC, efenniht commented
Draft 지만 메타적인 몇 가지만 말씀드리겠습니다:
 - #334 이후에 머지하실 계획이라면 #334 위로 rebase 해 주세요. #334 에서 PageTable 의 API가 많이 바뀔 것 같으니 이를 고려하시는 것이 좋겠습니다.
 - Rebase 하실 때 merge commit 은 제거해 주세요.

2021-01-18 01:45 UTC, jeehoonkang requested changes

2021-01-18 01:45 UTC, jeehoonkang commented on kernel-rs/src/vm.rs
> +    sz: usize,
- 이 field가 생긴 것 같은데- 이 sz가 virtual memory를 0번지부터 sz번지까지 쓴다는 의미인가요?
- 제 느낌에 kernel/user용으로 새로운 struct를 만드는게 다소 복잡해보이는데 PageTable 하나로만 쓸 수 있으면 더 좋겠는데, sz가 kernel page table에도 들어있어도 되나요?

2021-01-18 03:18 UTC, travis1829 commented on kernel-rs/src/vm.rs
> +    sz: usize,
* 네 맞습니다!
* 일단, KernelPageTable에서는 sz field를 사용하지 않습니다. 다만, 들어있어도 상관은 없을 듯 합니다.

2021-01-18 07:30 UTC, Medowhill commented on kernel-rs/src/vm.rs
> +    sz: usize,
또한, `sz` 필드를 페이지 테이블 쪽에 추가한다면, 이후에 추가할 `MemoryManager`의 필드로 만드는 쪽이 자연스러워 보입니다. `PageTable` 자체는 그냥 자료 구조이고, `MemoryManager`가 invariant를 유지하면서 프로세스의 페이지 테이블이 올바른 상태이도록 관리하기 때문입니다. 그렇게 하면 `MemoryManager`는 유저 페이지 테이블만을 관리하므로 커널 페이지 테이블에 `sz`를 추가할 필요도 없습니다.

_Originally posted by @Medowhill in https://github.com/kaist-cp/rv6/issues/295#issuecomment-762043565_

2021-01-18 07:33 UTC, travis1829 commented on kernel-rs/src/vm.rs
> +    sz: usize,
참고: `sz` field는 다시 `ProcData`로 옮길 예정입니다!

2021-01-18 15:33 UTC, travis1829 commented
원래는 #334가 끝나면 다시 PR을 만들 생각이었으나, 현재 또 새로운 PR이 생겼으므로 (https://github.com/kaist-cp/rv6/pull/342 이랑 https://github.com/kaist-cp/rv6/pull/343) 이게 끝난후 새롭게 PR을 만들겠습니다. 그 전에, `PageTable<A>::Drop`을 어떤식으로 구현할 예정인지를 보여드리기 위해 draft PR을 또 업데이트했습니다.
* `PageTable<A>::Drop`을 추가했습니다. 참고로, 이제는 직접 pagetable을 재귀적으로 탐색하면서 `kernel().free()`로 page를 free시키므로, **`sz`나 `num_usr_pages`같은 추가정보가 필요없습니다.** 또, **`PageTable<KVAddr>::drop()`와 `PageTable<UVAddr>::drop()`이 거의 똑같습니다.** (즉, `PageTable<KVAddr>::drop()`또한 간접적으로 구현해봤습니다.)
* `VAddr` trait에 `need_free()`라는 함수를 추가했습니다. 어떤 page들은 직접 `kernel().free()`를 해야되고 (예: user virtual address 0 ~ sz), 어떤 page들은 `kernel().free()`를 하면 안되는데 (예: TRAPFRAME, TRAMPOLINE), 이걸 구분해주는 boolean 함수입니다. (`Drop`할때 사용됩니다.)
* 다만, 현재 `KVAddr::need_free()`는 항상 false를 리턴하는데, 이 부분은 나중에 kernel virtualization이나 multi kernel등을 어떻게 할 건지를 구상하고서 memory layout을 결정한 후 변경하면 될 것 같습니다.

2021-01-18 19:09 UTC, jeehoonkang commented
- 이 PR에서 계속 이어나가면 좋겠습니다. rebase 해서 리뷰 후 머지합시다.
- pagetable::drop: 네 좋습니다
- dead code: 새로운 코드로 대체된거죠?

2021-01-19 00:28 UTC, travis1829 commented
> * dead code: 새로운 코드로 대체된거죠?
예, 맞습니다!(`PageTable::Drop`와 `PageTable::freewalk()`로 대체되었습니다.)

2021-01-19 03:57 UTC, travis1829 commented on kernel-rs/src/proc.rs
> +    unsafe fn freeproc(&mut self, parent_guard: Option<SpinlockProtectedGuard<'_>>) {
EDIT: drop의 signature가 `fn drop(&mut self)`이므로 이렇게 바꾸게 되면 `drop()`안에서는 `freeproc()`을 사용할 수가 없게 되는 것 같습니다. 그렇다고 `freeproc()`의 내용을 전부 `drop()`안으로 옮길수도 없으므로 (이러면 zombie process을 reap하는게 좀 복잡해집니다), 일단은 이렇게 놔뒀습니다.

2021-01-19 03:57 UTC, travis1829 commented on kernel-rs/src/proc.rs
> +            if self.deref_info().state == Procstate::STARTING1 {
EDIT: STARTING1은 USED로 변경었습니다!

2021-01-19 03:58 UTC, travis1829 commented
제일 최신 PR (https://github.com/kaist-cp/rv6/pull/343) 이후로 rebase했습니다.

2021-01-19 04:40 UTC, jeehoonkang requested changes

2021-01-19 04:40 UTC, jeehoonkang commented on kernel-rs/src/exec.rs
> +        let mut ptable_guard = scopeguard::guard((pt, sz), |(_, _)| {});
이렇게 되면 아예 guard를 없애면 될 것 같습니다.

2021-01-19 04:40 UTC, jeehoonkang commented on kernel-rs/src/exec.rs
> -            proc_freepagetable(oldpagetable, oldsz);
old page table이 free되는 위치가 위로 올라간 것 같은데 (L237) 그래도 괜찮나요? 확인 부탁드려요

2021-01-19 04:40 UTC, jeehoonkang commented on kernel-rs/src/proc.rs
> +    unsafe fn freeproc(&mut self, parent_guard: Option<SpinlockProtectedGuard<'_>>) {
이름이 약간 어색한 것 같은데 "free"는 메모리까지 정리하는 것처럼 느껴져서요. finalize clear 이런 식으로 다른 단어를 쓰는게 어떨까 합니다.

2021-01-19 04:40 UTC, jeehoonkang commented on kernel-rs/src/proc.rs
> +            if self.deref_info().state == Procstate::USED && (*self.data.get()).sz == 0 {
이 condition이 약간 arbitrary 해보이는데 적어도 주석이 있는게 좋겠습니다.

2021-01-19 04:40 UTC, jeehoonkang commented on kernel-rs/src/vm.rs
> +                Self::freewalk(&mut *self.ptr, 2, &mut [0, 0, 0]);
"2"가 매직으로 보이는데 주석이 있으면 좋겠습니다.

2021-01-19 04:48 UTC, travis1829 commented on kernel-rs/src/proc.rs
> +            if self.deref_info().state == Procstate::USED && (*self.data.get()).sz == 0 {
> 이름이 약간 어색한 것 같은데 "free"는 메모리까지 정리하는 것처럼 느껴져서요. finalize clear 이런 식으로 다른 단어를 쓰는게 어떨까 합니다.

`freeproc()`이 원래 xv6에도 있던 함수고 하는 일도 rv6과 거의 똑같아서 이름을 그대로 두었습니다. 다만, 제 생각에도 그냥 `clearproc()`으로 이름을 바꾸는게 좋을 것 같아, 그렇게 하겠습니다.

2021-01-19 04:50 UTC, travis1829 commented on kernel-rs/src/exec.rs
> -            proc_freepagetable(oldpagetable, oldsz);
위로 올라간게 맞습니다! 일단 L237 이후로는 옛날 pagetable을 더 이상 참조할 일이 없으므로 문제는 없을 것 같습니다!

2021-01-19 04:52 UTC, travis1829 commented on kernel-rs/src/proc.rs
> +    unsafe fn freeproc(&mut self, parent_guard: Option<SpinlockProtectedGuard<'_>>) {
`freeproc()`이 원래 xv6에도 있던 함수고 하는 일도 rv6과 거의 똑같아서 이름을 그대로 두었습니다. 다만, 제 생각에도 그냥 `clearproc()`으로 이름을 바꾸는게 좋을 것 같아, 그렇게 하겠습니다.

2021-01-19 05:23 UTC, Medowhill commented on kernel-rs/src/vm.rs
> +impl<A: VAddr> Drop for PageTable<A> {
조금 전 @travis1829 님과 온라인 미팅을 했습니다. `PageTable`의 할당을 해제할 때 `sz`를 인자로 받지 않도록 수정한 것에 대해서는 이제 이해가 됐습니다.

다만, `Page`가 `free`될 때는 `Kmem`의 linked list로 돌아가야 하고, 이를 위해 현재는 전역 함수인 `kernel`을 호출하고 있습니다. #267 에서 언급한 것처럼 `kernel`의 호출은 최소화해야 합니다. 이 문제를 해결하려면 `Page`를 `free`하는 함수가 모두 명시적으로 `Kmem`을 인자로 받고, 인자로 받은 `Kmem`에 `Page`를 돌려 주어야 합니다. 이렇게 구현을 수정하기 위해서는, Rust에서는 `drop`이 인자를 받을 수 없으므로 `Drop` 트레잇을 구현해 `PageTable`이 자동으로 `drop`되게 하는 것은 포기해야 합니다. 그 대신, `PageTable`을 `free`하는 함수가 `Kmem`을 인자로 받고 항상 `PageTable`을 명시적으로 `free`해야 합니다. 따라서 이 PR에서 제안한 자동 `drop`은 다시 사라지게 될 것 같습니다.

그래서 일단 이 PR에서는 `PageTable`을 자동으로 `drop`하기 보다는 기존처럼 명시적으로 `free`하도록 그대로 두고, 다음 중 어느 것을 택할지 별도의 이슈로 의논하면 좋을 것 같습니다.

1. 전역 함수 사용을 줄이는 대신 `PageTable`을 명시적으로 `free`
2. 전역 함수 `kernel`을 계속 사용하는 대신 `PageTable`을 자동으로 `drop`

@jeehoonkang 교수님께서는 어떻게 생각하시나요?

2021-01-19 05:43 UTC, jeehoonkang commented on kernel-rs/src/vm.rs
> +impl<A: VAddr> Drop for PageTable<A> {
저는 일단 2로 가는게 좋겠습니다. 아래와 같은 이유로 page table에 drop을 구현할 수 있는게 더 큰 이득이라고 생각하고, KERNEL.kmem을 refer하는 문제는 이슈 레이징 하고 다음에 해결하는걸 제안합니다.

이유: 다른 거의 모든 system programming에서, heap object가 어떤 allocator로부터 할당되었는지 암시적으로 가정합니다. 우리도 암시적으로 KERNEL.kmem으로부터 heap object들이 할당되었다고 일단 암시적으로 가정해도 괜찮다고 생각합니다.

예상되는 문제: 다만 이런 경우 말씀하신 것처럼 KERNEL에 대한 dependency를 끊을 수가 없는데요, 이 문제는 사실 이 이슈와 별개로 존재하는 문제인 것 같습니다. 특히 multi-kernel design을 상상한다면 (여러 kernel이 공존) allocator를 공유한다면 kmem이 kernel 밖에 있는게 자연스러운 디자인이 됩니다. 따라서 이 문제는 다른 이슈에서 논의하는게 좋겠습니다.

2021-01-19 05:49 UTC, travis1829 commented
* 교수님께서 말씀하신 변경사항을 적용했습니다.
* 또, 일단은 교수님께서 https://github.com/kaist-cp/rv6/pull/330#discussion_r559926318 에서 말씀하신대로 `Drop` trait 자체는 그냥 놔뒀습니다. (다만, 혹시라도 나중에 없애고 싶다면, 그냥 `impl Drop` 부분을 지운 후 PageTable<A>::free_walk()을 직접 부르는 형식으로 바꾸면 됩니다.)

2021-01-19 05:56 UTC, Medowhill commented on kernel-rs/src/vm.rs
> +impl<A: VAddr> Drop for PageTable<A> {
네. 알겠습니다. 별도 이슈로 만들어 두었습니다. #344

2021-01-19 06:02 UTC, jeehoonkang requested changes
사소한거만 해주시면 머지하겠습니다.

2021-01-19 06:02 UTC, jeehoonkang commented on kernel-rs/src/exec.rs
> +        let sz1 = pt.alloc(sz, sz.wrapping_add(2usize.wrapping_mul(PGSIZE)))?;
ditto

2021-01-19 06:02 UTC, jeehoonkang commented on kernel-rs/src/proc.rs
> +    unsafe fn clear_proc(&mut self, parent_guard: Option<SpinlockProtectedGuard<'_>>) {
- procguard의 method이므로 fn clear여도 괜찮을 것 같은데 어떻게 보시나요?
- unsafe function이면 # Safety doc이 있는게 좋겠습니다.

2021-01-19 06:28 UTC, travis1829 commented on kernel-rs/src/proc.rs
> +    unsafe fn clear_proc(&mut self, parent_guard: Option<SpinlockProtectedGuard<'_>>) {
* `fn clear()`이 더 나은 것 같습니다!
* 이제보니, 굳이 unsafe함수일 필요는 없을 것 같습니다. (즉, unsafe한 부분들이 `clear()`내에서 신경써야되는 부분들이지, caller가 신경써야 되는 부분들은 아닌 것 같습니다.)

2021-01-19 06:29 UTC, travis1829 commented
* `sz1` 변수를 아예 없애버렸습니다. (원래 xv6에 있던 변수인데, rv6로 옮기면서 그대로 남았던 것 같습니다.)
* `unsafe fn clear_proc()` -> `fn clear()`로 바꿨습니다.
	* unsafe한 부분에 관해서는, `Proc::data`는 `Proc::zero()`에서 이미 initialized된 상태이고, `Proc::parent`을 `assume_init_mut()`해도 되는 이유는 https://github.com/kaist-cp/rv6/pull/318#discussion_r553976148 에서 언급하였습니다. 그러므로 `fn clear()`의 caller입장에서는 `ProcGuard`를 `Proc::lock()`으로 얻은게 맞다면 따로 신경써야 되는 부분은 없는 듯 합니다.
	* (굳이 신경써야 되는 부분을 찾자면, `ProcData::pagetable`이 drop되었으므로 이후 init하기 전까지는 사용해서는 안된다는 것 정도입니다.)

2021-01-19 06:32 UTC, jeehoonkang requested changes
미안한데 하나만 더 합시다. 반영되면 바로 머지하겠ㅅ브니다.

2021-01-19 06:32 UTC, jeehoonkang commented on kernel-rs/src/exec.rs
> +        let mut sz: usize;
아래  sz=0 하는 곳으로 옮깁시다.

2021-01-19 06:35 UTC, jeehoonkang commented
bors r+

2021-01-19 06:41 UTC, merged