Sysfile refactoring (related to #154)
kaist-cp/rv6 pull request #331
Opened 2021-01-13 15:12 UTC by anemoneflower

- related to #154
- stat.rs의 `T_NONE`, `T_DIR`, `T_FILE`, `T_DEVICE` 를 enum으로 묶어서 `IFileType`으로 만들었습니다.
  - `Inode`, `Dinode` 에 있는 `major`, `minor`는 `T_DEVICE`에만 쓰이기 때문에 `IFileType::T_DEVICE`에 추가했습니다.
- inode.rs의 `get_inode`에서 쓰이는 `find_or_alloc`은 alloc할 때 Array의 처음 empty만 필요로 하기 때문에 `break`를 추가했습니다.

2021-01-13 15:46 UTC, anemoneflower commented
- 코드를 살펴보다 바로 고쳐서 issue 남기는 것을 깜박했습니다..
- 이전 이슈를 보니 #231 에서 관련된 논의가 있었던 것 같은데 혹시 #231 이 적용되지 않은 이유가 있었나요?

2021-01-13 17:42 UTC, efenniht requested changes
몇 가지만 고쳐주시길 부탁드립니다 😃

2021-01-13 17:42 UTC, efenniht commented on kernel-rs/src/fs/inode.rs
> +    typ: IFileType,
`Dinode` 는 disk 에 쓰는 데이터이므로 `IFileType` 을 그대로 사용하면 디스크에 쓰이는 내용이 달라질 수 있습니다.

2021-01-13 17:42 UTC, efenniht commented on kernel-rs/src/stat.rs
> +    pub typ: IFileType,
마찬가지로 `Stat` 도 C FFI 를 따라야 합니다. 이 줄도 원래대로 바꾸고 `Stat` 정의에 `#[repr(C)]` 를 붙여주세요.

2021-01-14 04:35 UTC, anemoneflower reviewed
수정했습니다.
- Stat에 #[repr(C)] 추가
- InodeType에 #[repr(i16)] 추가
- major, minor 원래대로 유지

2021-01-14 04:35 UTC, anemoneflower commented on kernel-rs/src/fs/inode.rs
> +    typ: IFileType,
major, minor를 살리고 InodeType에 #[repr(i16)]을 추가했습니다.

2021-01-14 05:43 UTC, jeehoonkang commented
conflict만 해결하면 머지할게요

bors r+

2021-01-14 06:03 UTC, anemoneflower commented
`DInode`에는 `major`, `minor`를 남기고, `InodeInner`에서는 `major`, `minor`를 `InodeType::Device` 만 소유하고 있는 방향으로 추가 수정 중입니다.
```rust
#[derive(Copy, Clone, PartialEq, Debug)]
#[repr(i16)]
pub enum InodeType {
    None,
    Dir,
    File,
    Device { major: u16, minor: u16 },
}

#[derive(Copy, Clone, PartialEq, Debug)]
#[repr(i16)]
pub enum DInodeType {
    None,
    Dir,
    File,
    Device,
}
```

2021-01-14 06:44 UTC, anemoneflower commented
- `InodeType`과 `DInodeType`을 분리했습니다. (https://github.com/kaist-cp/rv6/pull/331#issuecomment-759947279)
- rebase 완료했습니다.

2021-01-14 10:45 UTC, efenniht commented
bors r+

2021-01-14 10:55 UTC, merged