[closes #332] split sys_* functions into fetch part and helper function
kaist-cp/rv6 pull request #333
Opened 2021-01-14 13:05 UTC by anemoneflower

- closes #332

---

주요 변경점입니다.

- `sys_*` 함수 중에서 https://github.com/kaist-cp/rv6/issues/332#issuecomment-759912575 에서 말씀하신 의도를 만족할 수 있는 부분만 분리했습니다. (내부 코드가 짧은 함수들은 그대로 유지)
  - `sys_*` 함수들이 call하는 함수들은 `Result` type을 return 하도록 변경했습니다.
  - `sys_exec`의 경우에는 `Kernel::exec`가 이미 기능을 하고 있다고 생각해서 변경하지 않았습니다.
- `fetchaddr` 도 `Result`를 return 합니다.
- `fdalloc`이 `Result<i32, Self>` 대신 `Result<i32, ()>`를 return 합니다.

---

#### `sys_*` 함수가 `usize`대신 `Result`를 리턴하는 것은 어떤지 궁금합니다.
  https://github.com/kaist-cp/rv6/blob/f5f6a8f4ddc3e45a17feeaf529ec7f8f835e993e/kernel-rs/src/syscall.rs#L115
  - 여기서 `ok_or!`등을 사용해서 `usize`로 변환하는 방향입니다.

2021-01-14 13:55 UTC, jeehoonkang requested changes

2021-01-14 13:55 UTC, jeehoonkang commented on kernel-rs/src/syscall.rs
> +pub unsafe fn fetchaddr(addr: UVAddr, ip: *mut usize) -> Result<(), ()> {
return type의 의미를 주석으로 설명 부탁드려요

2021-01-14 13:55 UTC, jeehoonkang commented on kernel-rs/src/sysfile.rs
> -    unsafe fn fdalloc(self) -> Result<i32, Self> {
혹시 바꾼 이유는? 혹시라도 fdalloc에 실패하면 다시 rcfile을 쓸 수 도 있지 않나요?

2021-01-14 13:55 UTC, jeehoonkang commented on kernel-rs/src/sysfile.rs
> +    unsafe fn link(&self, oldname: &CStr, newname: &CStr) -> Result<usize, ()> {
전 그냥 sys_link에 놔두는게 좋을 것 같습니다... 이렇게 빼는 이득이 있나요?

2021-01-14 13:55 UTC, jeehoonkang commented on kernel-rs/src/sysfile.rs
> +            ok_or!(
if ....is_err() { break } 로 합시다.

2021-01-14 14:15 UTC, efenniht commented on kernel-rs/src/sysfile.rs
> +    unsafe fn link(&self, oldname: &CStr, newname: &CStr) -> Result<usize, ()> {
제가 이렇게 하는 걸 제안드렸는데요,
 - `sys_link` 와 달리 `link` 는 safe function 으로 만들 수 있어 보이기 때문이고,
 - `Result` 타입을 리턴하면 `?` operator 로 더 보기 좋게 리팩토링할 수 있기 때문입니다.

그런데 지금 보니까 굉장히 짧은 함수들도 많고, 모든 `sys_*` 함수들의 실패시 리턴 값이 `usize::MAX` 라서 서윤님 말씀대로 `sys_*` 함수가 `Result` 를 리턴하는 걸로 리팩토링하는 것도 가능해 보입니다.

2021-01-14 14:23 UTC, jeehoonkang commented on kernel-rs/src/sysfile.rs
> +    unsafe fn link(&self, oldname: &CStr, newname: &CStr) -> Result<usize, ()> {
- `sys_*`를 result로 리턴하는건 좋아보입니다. ok = 0, err = error code 이런 식으로 규정하면 깔끔하게 될거같아요
- safe/unsafe: 혹시 link로 빼면 unsafe를 뗄 수 있는 까닭은 무엇인가요?

2021-01-15 02:01 UTC, efenniht commented on kernel-rs/src/sysfile.rs
> +    unsafe fn link(&self, oldname: &CStr, newname: &CStr) -> Result<usize, ()> {
- safe/unsafe: `argraw` 가 unsafe 할 것 같아서 그렇게 말씀드렸는데 다시 보니까 `ExecutionGuard` 비슷한 걸 만들어서 인자로 주면 safe 할 것 같습니다.

그럼에도 불구하고 저는 이 함수들을 다른 메서드로 빼는 게 좋아 보이는 데 `Kernel` struct 의 public & Rust-idiomatic method 로서 `link`, `unlink` 등이 따로 있고 이것을 user level 과 연결해주는 다리가 `sys_*` 가 되는 게 맞다고 생각합니다. 그 방향이 `Kernel` 을 더 modular 하게 만들 수 있지 않을까요?

2021-01-15 02:22 UTC, jeehoonkang commented on kernel-rs/src/sysfile.rs
> +    unsafe fn link(&self, oldname: &CStr, newname: &CStr) -> Result<usize, ()> {
@efenniht 님 말씀대로 한번 가보기로 합시다. 상욱님이 이 PR 리드해주시겠어요? 머지 직전에 저한테 zulip mention 주시면 제가 머지할게요

2021-01-15 03:06 UTC, efenniht commented on kernel-rs/src/sysfile.rs
> +    unsafe fn link(&self, oldname: &CStr, newname: &CStr) -> Result<usize, ()> {
네 알겠습니다. 별개로 저도 bors r+ 할 수 있는 권한이 있는 것 같습니다.

2021-01-15 05:19 UTC, anemoneflower commented on kernel-rs/src/sysfile.rs
> -    unsafe fn fdalloc(self) -> Result<i32, Self> {
`fdalloc`을 사용하는 함수들에서 `fdalloc`이 실패하는 경우 다시 시도하지 않고 에러를 리턴하기 때문에 `Self`를 리턴하지 않아도 된다고 생각했습니다.
https://github.com/kaist-cp/rv6/blob/4b0b0701aa7a7d1d3c458cb51a1a8ad7408c13ed/kernel-rs/src/sysfile.rs#L111
https://github.com/kaist-cp/rv6/blob/4b0b0701aa7a7d1d3c458cb51a1a8ad7408c13ed/kernel-rs/src/sysfile.rs#L266
https://github.com/kaist-cp/rv6/blob/4b0b0701aa7a7d1d3c458cb51a1a8ad7408c13ed/kernel-rs/src/sysfile.rs#L375-L379

2021-01-15 08:51 UTC, efenniht requested changes
고생하셨습니다. 몇 가지 수정 부탁드립니다.

2021-01-15 08:51 UTC, efenniht commented on kernel-rs/src/sysfile.rs
> +    unsafe fn pipe(&self, fdarray: usize) -> Result<usize, ()> {
`fdarray` 의 타입은 `UVAddr` 이 되는 것이 좋겠습니다. 낮에는 file descirptor 의 array 를 리턴하는 게 어떨까라고 말씀드렸는데, 굳이 그럴 필요는 없을 것 같습니다.

2021-01-15 13:11 UTC, jeehoonkang requested changes

2021-01-15 13:11 UTC, jeehoonkang commented on kernel-rs/src/pipe.rs
> +        let f0 = ok_or!(
ok_or! 하지 말고 alloc_file(...).map_err(|e| ...)? 라고 하는게 더 좋을 것 같습니다. 아래 등 다른 곳도 마찬가지

2021-01-15 13:11 UTC, jeehoonkang commented on kernel-rs/src/proc.rs
> +    pub fn kill(&self, pid: i32) -> Result<(), ()> {
ok, err의 의미를 method의 주석으로 써주면 좋겠습니다. 가능하면 다른 곳도 마찬가지

2021-01-15 13:11 UTC, jeehoonkang commented on kernel-rs/src/syscall.rs
> +/// Returns Ok(ip) on success, Err(()) on error.
ip = ?

2021-01-15 13:11 UTC, jeehoonkang commented on kernel-rs/src/sysfile.rs
> -    unsafe fn fdalloc(self) -> Result<i32, Self> {
그렇긴 한데 나중에 어떻게 바뀔지 모르니 self를 그냥 리턴하는게 좋을 것 같습니다.

2021-01-15 13:11 UTC, jeehoonkang commented on kernel-rs/src/sysfile.rs
> +            data.open_files[fd0 as usize] = None;
일단 data에 써놓고 bail out 하는 경우 되돌리는 패턴인데 혹시 더 refactoring할 수 있을 여지가 있을지 고민해보세요.
꼭 이 PR에서 안해도 됩니다 그런 경우 이슈로 남겨주세요

2021-01-15 13:11 UTC, jeehoonkang commented on kernel-rs/src/sysfile.rs
> +    pub unsafe fn sys_exec(&self) -> Result<usize, ()> {
얘는 exec으로 안뺀 이유는?

2021-01-15 13:11 UTC, jeehoonkang commented on kernel-rs/src/sysproc.rs
> +    pub unsafe fn sys_exit(&self) -> Result<usize, ()> {
sys_* 함수들의 return value의 의미는 무엇인가요?

2021-01-18 08:39 UTC, anemoneflower commented on kernel-rs/src/sysfile.rs
> +    pub unsafe fn sys_exec(&self) -> Result<usize, ()> {
`sys_exec`의 경우에는 `Kernel::exec`가 이미 기능을 하고 있다고 생각해서 추가적으로 분리하지 않았습니다.

2021-01-18 09:09 UTC, jeehoonkang requested changes
- `sys_*`와 `*`를 분리한다면, 분리된 `*`는 모두 safe로 만들어주세요.
- `sys_*` 중에서 safe해보이는 것도 있는데 그런건 safe로 만드는게 좋을까요? 확인 부탁들비니다 @efenniht

2021-01-18 09:09 UTC, jeehoonkang commented on kernel-rs/src/syscall.rs
> +        let num = (*data.trapframe).a7 as i32;
이것도 kernel.syscall()을 부르는 데에서 만들어서 `kernel.syscall(num)` 이런 식으로 부르는게 좋겠습니다.

2021-01-18 09:09 UTC, jeehoonkang commented on kernel-rs/src/sysfile.rs
> +    unsafe fn pipe(&self, fdarray: UVAddr) -> Result<(), ()> {
이렇게 sys_pipe에서 pipe를 뺀다면 unsafe를 떼는게 목적이어야할 것 같은데, 지금은 이거도 unsafe여서 약간 어중간한 것 같아요. safe하도록 리팩토링하는게 좋겠습니다. 다른 곳도 모두 마찬가지

2021-01-19 07:06 UTC, jeehoonkang requested changes

2021-01-19 07:06 UTC, jeehoonkang commented on kernel-rs/src/fs/inode.rs
> +    pub fn isdirempty(&mut self) -> bool {
naming convention이 약간 바뀐듯 한데 is_dir_empty 로 합시다

2021-01-19 07:06 UTC, jeehoonkang commented on kernel-rs/src/proc.rs
> +    pub unsafe fn fork(&self) -> Result<i32, ()> {
이게 proc id이죠? proc id 타입을 새로 만드는게 좋겠습니다. 이슈로 만들고 다음에 합시다.

2021-01-19 07:06 UTC, jeehoonkang commented on kernel-rs/src/sysfile.rs
> +    let ptr2 = unsafe { kernel().itable.alloc_inode(dp.dev, typ, tx) };
unsafe block을 introduce하신 곳에 모두 왜 safe한지 설명 남겨주세요.

2021-01-19 07:06 UTC, jeehoonkang commented on kernel-rs/src/sysfile.rs
> +        ip.dirlink(unsafe { FileName::from_bytes(b".") }, ip.inum, tx)
and_then이 이렇게 쓰이면 약ㄱ;ㅏㄴ 부자연스러운데 혹시 그냥 두줄로 나누는게 어떨까 합니다.

2021-01-19 07:06 UTC, jeehoonkang commented on kernel-rs/src/sysfile.rs
> +            // TODO: use other Result related functions => solved?
???

2021-01-19 07:06 UTC, jeehoonkang commented on kernel-rs/src/sysfile.rs
> +    /// Return a new file descriptor referring to the same file as given fd.
여기서 한번 impl을 끊어주면 좋겠습니다. sys_* 계열이 시작되는 곳이라서요

2021-01-19 07:18 UTC, efenniht requested changes

2021-01-19 07:18 UTC, efenniht commented on kernel-rs/src/pipe.rs
> +            *ptr = Pipe {
이 block 은 `page` 가 막 할당되었기 때문에 unique 한 access 가 보장되고, `Pipe` 의 크기와 alignment가 page 와 호환되므로 안전합니다.
 - 해당 argument 를 comment 로 남겨주세요.
 - `const_assert` 를 추가해서 `Pipe` 크기가 `Page` 보다 작거나 같고 `Pipe` 의 alignment 가 `Page` 의 alignment 에 맞음을 컴파일 시간에 확인하도록 해주세요.
 - `ptr::write` 을 사용해서 `Pipe` 을 ptr 에 써 주세요. `Pipe` 가 이후에 Drop 을 구현하면 이 코드는 해당 drop 을 호출할 수 있습니다.

2021-01-19 07:18 UTC, efenniht commented on kernel-rs/src/proc.rs
>          }
`?` 를 써서 간단하게 만들 수 있습니다.

2021-01-19 07:18 UTC, efenniht commented on kernel-rs/src/syscall.rs
> +/// Returns Ok(fetched address) on success, Err(()) on error.
```suggestion
/// Returns Ok(fetched integer) on success, Err(()) on error.
```

2021-01-19 07:18 UTC, efenniht commented on kernel-rs/src/sysfile.rs
> +    let ptr2 = unsafe { kernel().itable.alloc_inode(dp.dev, typ, tx) };
제 생각에 (최소한 create 에서 introduce한) unsafe 는 filesystem 의 safety 를 먼저 확인해야 이유를 설명할 수 있습니다.
 - TODO 로 남기거나
 - create을 unsafe 로 만들어야 하지 않을까요?

2021-01-19 07:20 UTC, efenniht commented
교수님께서 말씀하신대로 사실 safe한 sys_* 함수들은 unsafe 로 선언할 필요가 없는 것 같습니다. Rust typesystem이 safe fn 이 `unsafe` fn 의 subtype 이 되도록 지원하기만 하면 됩니다.

2021-01-19 11:16 UTC, anemoneflower reviewed
수정했습니다. :)
- safe한 sys_* 함수인 sys_uptime에서 unsafe를 지웠습니다.
- unsafe block에 TODO 또는 comment를 남겼습니다.

2021-01-19 11:16 UTC, anemoneflower commented on kernel-rs/src/proc.rs
> +    pub unsafe fn fork(&self) -> Result<i32, ()> {
#346

2021-01-19 11:16 UTC, anemoneflower commented on kernel-rs/src/sysfile.rs
> +    let ptr2 = unsafe { kernel().itable.alloc_inode(dp.dev, typ, tx) };
- 해당하는 부분에 TODO를 남겼습니다.
- `unsafe{ ip.update(tx) }`의 경우 ip가 inode에 lock이 걸려 있는 것을 guarantee하기 때문에 safe하다고 생각해서 TODO 대신에 comment를 남겼습니다.

2021-01-19 11:23 UTC, jeehoonkang approved these changes
저는 이제 리뷰 다 드린 것 같습니다. @efenniht 님이 review 해주시고 bors 해주세요.

2021-01-19 11:23 UTC, jeehoonkang commented on kernel-rs/src/sysfile.rs
> +    pub unsafe fn sys_dup(&self) -> Result<usize, ()> {
document why unsafe. ditto for every "new" unsafe funcitons.

2021-01-20 03:53 UTC, Medowhill commented on kernel-rs/src/proc.rs
>                              drop(np);
`drop(np)`는 없어도 되지 않나요?

2021-01-20 05:11 UTC, efenniht approved these changes
저도 다 된 것 같습니다. 아직 resolve 안 된 comment들만 반영해주시면 머지하도록 하겠습니다.

2021-01-20 10:10 UTC, anemoneflower commented on kernel-rs/src/pipe.rs
> +            *ptr = Pipe {
4ab2ef8  반영했습니다.

2021-01-20 12:03 UTC, efenniht commented
bors r+

2021-01-20 12:11 UTC, efenniht commented
bors retry

2021-01-20 13:35 UTC, efenniht commented
bors r+

2021-01-20 13:42 UTC, merged