[WIP] Refactoring VM
kaist-cp/rv6 pull request #334
Opened 2021-01-15 02:18 UTC by Medowhill

```rust
acquire("vm.rs")
```

제가 현재 VM 관련 코드를 리팩토링 중이라는 사실을 명시적으로 알려 드리기 위한 draft PR입니다. 앞으로 수정이 많이 이루어질 것 같으니 리뷰는 그 이후에 부탁드리겠습니다.

2021-01-15 13:28 UTC, jeehoonkang requested changes

2021-01-15 13:28 UTC, jeehoonkang commented on kernel-rs/src/kalloc.rs
> +// Internal safety invariant:
Rust doc을 쓰는 양식에 따라 아래와 같이 써주세요

```
/// # Safety
///
/// (invariants)
```

2021-01-15 13:28 UTC, jeehoonkang commented on kernel-rs/src/kernel.rs
> +    pub page_table: Option<PageTable<KVAddr>>,
주석으로 이게 runtime cost가 없다는 얘기를 써주면 좋을 것 같습니다.

2021-01-15 13:28 UTC, jeehoonkang commented on kernel-rs/src/vm.rs
> +    pub unsafe fn kvm_init_hart(&self) {
굳이 method를 만드는 이유는?

2021-01-15 13:28 UTC, jeehoonkang commented on kernel-rs/src/vm.rs
> +    unsafe fn as_table_mut(&mut self) -> Option<&mut RawPageTable> {
unsafe를 뗄수 있는지 궁금합니다

2021-01-15 13:28 UTC, jeehoonkang commented on kernel-rs/src/vm.rs
> +    pub fn uvm_walk_addr(&mut self, va: UVAddr) -> Option<PAddr> {
kernel page table에는 적용될 수 없는 함수인가요?

2021-01-15 13:28 UTC, jeehoonkang commented on kernel-rs/src/vm.rs
> +    pub unsafe fn uvm_init(&mut self, src: &[u8]) {
`uvm_new`처럼 만들 수도 있을까요?

2021-01-15 13:28 UTC, jeehoonkang commented on kernel-rs/src/vm.rs
> +    pub fn uvm_alloc(&mut self, mut oldsz: usize, newsz: usize) -> Result<usize, ()> {
함수 이름만 봐서는 kvm에도 적용될 수 있지 않을까 추측하는데 그러기 어려운 이유가 있나요? 이외에 모든 `uvm_*` 함수에 대해서도 같은 질문 드립니다

2021-01-15 13:28 UTC, jeehoonkang commented on kernel-rs/src/vm.rs
> +    pub fn kvm_make(&mut self) {
한번만 쓰이는 함수라면 kvm_new에 인라인 가능한가요?

2021-01-15 13:28 UTC, jeehoonkang commented on kernel-rs/src/vm.rs
> +    pub fn kvm_map(&mut self, va: KVAddr, pa: PAddr, sz: usize, perm: i32) {
마찬가지로 uvm_map과 통합 가능한지 궁금합니다

2021-01-15 13:40 UTC, Medowhill commented on kernel-rs/src/kalloc.rs
> +// Internal safety invariant:
혹시 Rust doc에 invariant를 작성한 예시가 있을까요? 제가 작성한 주석은 Rust 표준 라이브러리 구현에 있는 주석(<https://github.com/rust-lang/rust/blob/75042566d1c90d912f22e4db43b6d3af98447986/library/alloc/src/collections/vec_deque/iter_mut.rs#L14> 등)을 참고한 것이었습니다. 일반적으로 invariant를 doc에도 서술하는지, 아니면 이 프로젝트에서는 특히 unsafe에 대한 논증이 중요하므로 invariant를 doc에 서술하는 것인지 궁금합니다.

2021-01-15 13:53 UTC, Medowhill commented on kernel-rs/src/vm.rs
> +    pub fn kvm_map(&mut self, va: KVAddr, pa: PAddr, sz: usize, perm: i32) {
`kvm_init_hart`가 두 군데서 사용되는데 아래 코드를 두 번 작성하는 것보다 메서드로 정의하고 사용하는 편이 깔끔하다고 생각했습니다.

```rust
        self.page_table
            .as_ref()
            .expect("kernel page table must not be None")
            .kvm_init_hart();
```

메서드 없이 그냥 두 번 쓰는 편이 나을까요?

2021-01-15 13:53 UTC, Medowhill commented on kernel-rs/src/vm.rs
> +    pub unsafe fn kvm_init_hart(&self) {
`kvm_init_hart`가 두 군데서 사용되는데 아래 코드를 두 번 작성하는 것보다 메서드로 정의하고 사용하는 편이 깔끔하다고 생각했습니다.

```rust
        self.page_table
            .as_ref()
            .expect("kernel page table must not be None")
            .kvm_init_hart();
```

메서드 없이 그냥 두 번 쓰는 편이 나을까요?

2021-01-15 13:56 UTC, Medowhill commented on kernel-rs/src/vm.rs
> +    unsafe fn as_table_mut(&mut self) -> Option<&mut RawPageTable> {
이 메서드가 `unsafe`인 이유는 안전하게 사용하기 위해서 `RawPageTable`의 invariant가 필요하기 때문입니다. 같은 모듈 안에 있는 `RawPageTable` 안에서만 해당 메서드를 사용하고 이 메서드를 모듈 밖에서 사용할 수 없으므로 이 메서드가 `RawPageTable`의 invariant를 가정할 수 있다고 보고 `unsafe`를 그냥 없애도 될까요?

2021-01-15 14:32 UTC, Medowhill commented on kernel-rs/src/vm.rs
> +    pub unsafe fn uvm_init(&mut self, src: &[u8]) {
네. 그렇게 수정하겠습니다.

2021-01-15 14:33 UTC, Medowhill commented on kernel-rs/src/vm.rs
> +    pub fn kvm_make(&mut self) {
네. 그렇게 수정하겠습니다.

2021-01-15 14:36 UTC, Medowhill commented on kernel-rs/src/vm.rs
> +    pub fn uvm_alloc(&mut self, mut oldsz: usize, newsz: usize) -> Result<usize, ()> {
말씀하신 대로 kvm에도 적용할 수는 있습니다. 그러나 커널 페이지 테이블은 처음 부팅 시에 초기화되고 나서는 어떤 읽기나 쓰기가 이루어지지 않기 때문에 `uvm_*` 형태로 uvm에 대해 정의된 어떤 메서드도 필요하지 않습니다. 따라서 이런 메서드들은 유저 페이지 테이블에 대해서만 호출되어야 하기 때문에 kvm에 대해서 실수로 호출되는 일조차 없게끔 kvm에 대한 메서드(또는 두 형태 모두에 대해 일반화된 메서드)는 없는 것이 낫다고 생각합니다.

2021-01-15 14:38 UTC, Medowhill commented on kernel-rs/src/vm.rs
> +    pub fn uvm_walk_addr(&mut self, va: UVAddr) -> Option<PAddr> {
첫째, 이 메서드는 내부에서 PTE_U 플래그가 켜져 있는지 확인하는데 이를 커널 페이지 테이블의 엔트리에 대해 해서는 안되므로 uvm에 대한 메서드가 되어야 할 것 같습니다. 둘째, 나머지 `uvm_*` 메서드와 마찬가지로, kvm을 위한 유사한 메서드가 필요하지 않습니다.

2021-01-15 14:40 UTC, jeehoonkang commented
@Medowhill 혹시 코멘트들을 하나의 review로 묶어서 한꺼번에 주실 수 있으실까요? notification이 자주 와서 부득이 요청드립니다.

2021-01-15 16:13 UTC, Medowhill commented
## Invariant comment

> Rust doc을 쓰는 양식에 따라 아래와 같이 써주세요
```rust
/// # Safety
///
/// (invariants)
```

혹시 Rust doc에 invariant를 작성한 예시가 있을까요? 제가 작성한 주석은 Rust 표준 라이브러리 구현에 있는 주석(https://github.com/rust-lang/rust/blob/75042566d1c90d912f22e4db43b6d3af98447986/library/alloc/src/collections/vec_deque/iter_mut.rs#L14 등)을 참고한 것이었습니다. 일반적으로 invariant를 doc에도 서술하는지, 아니면 이 프로젝트에서는 특히 unsafe에 대한 논증이 중요하므로 invariant를 doc에 서술하는 것인지 궁금합니다.

## `Option`

> 주석으로 이게 runtime cost가 없다는 얘기를 써주면 좋을 것 같습니다.

> 굳이 method를 만드는 이유는?

`Kernel`이 가지고 있는 페이지 테이블은 `Option`이어도 큰 문제가 없지만 `Proc`이 가지고 있는 테이블도 `Option`을 사용하면 `Proc`에서 페이지 테이블에 접근할 때마다 `unwrap`/`expect`로 `Some`인지 확인해야 해서 런타임 비용이 증가할 수 있어 보입니다. 일관적으로 `Option`을 사용하지 않는 기존의 방식으로 되돌리도록 하겠습니다. 반복되는 코드를 줄이려고 `kvm_init_hart` 메서드를 정의했는데 `Option`을 사용하지 않으면 해당 메서드가 굳이 필요하지 않으므로 이 역시 없애겠습니다.

## Unsafe `as_table_mut`

> unsafe를 뗄수 있는지 궁금합니다

이 메서드가 `unsafe`인 이유는 안전하게 사용하기 위해서 `RawPageTable`의 invariant가 필요하기 때문입니다. 같은 모듈 안에 있는 `RawPageTable` 안에서만 해당 메서드를 사용하고 이 메서드를 모듈 밖에서 사용할 수 없으므로 이 메서드가 `RawPageTable`의 invariant를 가정할 수 있다고 보고 `unsafe`를 그냥 없애도 될까요?

## kvm과 uvm을 아우르는 일반적인 메서드

> 함수 이름만 봐서는 kvm에도 적용될 수 있지 않을까 추측하는데 그러기 어려운 이유가 있나요? 이외에 모든 uvm_* 함수에 대해서도 같은 질문 드립니다

말씀하신 대로 kvm에도 적용할 수는 있습니다. 그러나 커널 페이지 테이블은 처음 부팅 시에 초기화되고 나서는 읽기나 쓰기가 절대 이루어지지 않기 때문에 `uvm_*` 형태로 uvm에 대해 정의된 어떤 메서드도 필요하지 않습니다. 따라서 이런 메서드들은 유저 페이지 테이블에 대해서만 호출되어야 하기 때문에 kvm에 대해서 실수로 호출되는 일조차 없게끔 kvm에 대한 메서드(또는 두 형태 모두에 대해 일반화된 메서드)는 없는 것이 낫다고 생각합니다.

> kernel page table에는 적용될 수 없는 함수인가요?

첫째, 이 메서드는 내부에서 PTE_U 플래그가 켜져 있는지 확인하는데 이를 커널 페이지 테이블의 엔트리에 대해 해서는 안되므로 uvm에 대한 메서드가 되어야 할 것 같습니다. 둘째, 나머지 `uvm_*` 메서드와 마찬가지로, kvm을 위한 유사한 메서드가 필요하지 않습니다.

> 마찬가지로 `uvm_map`과 통합 가능한지 궁금합니다

`kvm_map`이 하는 일이 그냥 `map_pages`를 부르는 일이기 때문에 `kvm_map`을 없애고 항상 `map_pages`를 사용하도록 하겠습니다. 다만, 현재 `map_pages`가 `PAddr` 대신 `usize`를 인자로 받고 있는데, `PAddr`을 인자로 받는 것이 자연스러운 설계이므로 그렇게 하도록 `map_pages`와 이를 호출하는 부분을 수정하겠습니다.

## `uvm_init`

> `uvm_new`처럼 만들 수도 있을까요?

프로세스가 만들어질 때 `ProcessSystem::alloc()`을 호출해 페이지 테이블을 만든 뒤 페이지 테이블에 trampoline 등을 매핑합니다. 이 과정은 모든 프로세스를 만들 때 필요합니다. 첫 프로세스를 만들 때는 먼저 `user_proc_init`에서 `alloc`을 호출해 이미 페이지 테이블에 trampoline 등이 매핑된 상태로 만듭니다. 그 후에 `uvm_init`을 호출해 첫 프로세스의 코드를 복사하고 그에 대한 매핑을 페이지 테이블에 추가합니다. `alloc`을 재사용할 수 있는 현재의 코드가 좋은 설계 같기 때문에 `uvm_init`은 그대로 두어야 한다고 생각합니다. 다만, `alloc`에서 `proc_pagetable`을 호출해 페이지 테이블을 만들고 trampoline 등을 매핑하는데, `proc_pagetable`이 하는 작업이 `PageTable`에서 이루어지는 것이 바람직 해 보입니다. 따라서 `proc_pagetable`을 없애고 같은 기능을 하는 `uvm_new`를 추가하도록 하겠습니다.

## 반영 예정

> 한번만 쓰이는 함수라면 `kvm_new`에 인라인 가능한가요?

네. 그렇게 수정하겠습니다.

---

**위 내용 모두 반영되었습니다.**

2021-01-16 06:54 UTC, jeehoonkang commented
@Medowhill File changes > review changes 에서 코드에 직접 comment 다실 수 있습니다. 앞으로는 그렇게 답글 달아주시길 요청드립니다.

2021-01-16 07:06 UTC, jeehoonkang requested changes

2021-01-16 07:06 UTC, jeehoonkang commented on kernel-rs/src/vm.rs
> +    // Internal safety invariant:
(Rust doc에 관한 커멘트를 여기서 이어서 하겠습니다.)

검색해보니 struct invariant에 대해 딱히 정해진 관례는 없네요... 우리가 하나로 정하면 될듯 합니다.

저는 저번에 제안드린대로 struct의 doc comment로써 아래와 같이 쓰는걸 제안합니다:

```rust
/// # Safety
///
/// This struct's safety invariant is ...
struct foo {
}
```

- 각 field에 invariant를 쓰면 여러 field를 엮는 relational invariant를 쓰기 어려울 것 같습니다.
- "# Safety": "#Safety Invariant"와 같이 쓸 수도 있겠습니다만 (1) function에 대해서는 Safety라고 하기도 하고 또 더 짧기 때문에 Safety를 선호합니다.

2021-01-16 07:06 UTC, jeehoonkang commented on kernel-rs/src/vm.rs
> +    #[deny(unsafe_op_in_unsafe_fn)]
이걸 혹시 code base 전체에 적용할 수도 있을까요?

2021-01-16 07:06 UTC, jeehoonkang commented on kernel-rs/src/vm.rs
> +    pub unsafe fn uvm_init(&mut self, src: &[u8]) -> Result<(), ()> {
uvm_new도 있고 uvm_init도 있는데 혹시 통일 가능한가요? 아니면 두개가 필요한 이유는?

2021-01-16 07:06 UTC, jeehoonkang commented on kernel-rs/src/vm.rs
> +    pub fn uvm_alloc(&mut self, mut oldsz: usize, newsz: usize) -> Result<usize, ()> {
- xv6에 대해서는 말씀하신대로 kernel page table이 변화하지 않습니다만 앞으로 우리가 만들 kernel에서는 필요하게 될 것 같습니다.
- 만약에 logic이 거의 비슷하다면 kvm도 지원하는 `fn alloc()`으로 만들기를 제안합니다. (꼭 이번 PR일 필요는 없어보입니다. Issue raising 해주세요)
- 아니라면 지금 그대로 일단 uvm_alloc으로 놔두는게 좋겠습니다. @Medowhill 님이 판단 부탁드려요

2021-01-16 09:36 UTC, efenniht requested changes

2021-01-16 09:36 UTC, efenniht commented on kernel-rs/src/vm.rs
> +            (pte2pa(self.inner).into_usize() as *mut RawPageTable).as_mut()
이 지점에서 `as_mut()` 을 사용하면 PTE에 저장된 주소가 null 인 지 체크하는 로직이 추가되게 됩니다.

2021-01-16 09:36 UTC, efenniht commented on kernel-rs/src/vm.rs
> +    pub fn as_usize(&self) -> usize {
제 생각에 이 함수를 굳이 `PageTable` 의 method 로 제공할 필요는 없는 것 같습니다. 원래대로 `as_raw` 를 두는 게 어떨까요?

2021-01-16 09:36 UTC, efenniht commented on kernel-rs/src/vm.rs
> +        unsafe { self.ptr.as_mut() }.expect("ptr must not be null")
이렇게 하면 compiler 가 `PageTable` 의 invariant 를 알 수 없어서 `self.ptr` 이 null 인 지 체크하는 runtime cost 가 발생합니다.

2021-01-16 09:36 UTC, efenniht commented on kernel-rs/src/vm.rs
> +    fn as_raw_mut(&mut self) -> &mut RawPageTable {
이름이 convention 과 잘 맞지 않는 것 같습니다 (`as_raw_mut` 이면 `*mut T` 를 리턴할 것 같아요.)

2021-01-16 09:36 UTC, efenniht commented on kernel-rs/src/vm.rs
> +                PAddr::new(unsafe { trampoline.as_mut_ptr() as usize }),
이 `unsafe` 는 안전한가요? KVA <-> PA 의 identity map 에 의존하는 것 같은데 인자로 `trap_frame: UVAddr` 를 받는 게 더 바람직해 보입니다. 별개로 지금 디자인에서는 그렇게 해도 unsafe 인 것 같습니다.

2021-01-16 09:36 UTC, efenniht commented on kernel-rs/src/vm.rs
> +impl PageTable<UVAddr> {
이 타입의 메서드에서 `uvm_` 을 떼도 될 것 같습니다 (타입에 의해 자명하므로)

2021-01-18 05:14 UTC, Medowhill reviewed
.

2021-01-18 06:26 UTC, Medowhill commented on kernel-rs/src/vm.rs
> +    #[deny(unsafe_op_in_unsafe_fn)]
네. `lib.rs`에 `#![deny(unsafe_op_in_unsafe_fn)]`를 추가하면 프로젝트 전체에 적용할 수 있습니다. 그러나 지금 바로 적용하면 상당히 많은 unsafe 함수에서 컴파일 오류가 발생할 것이기 때문에, 일단은 그렇게 하지 않았습니다. 일단은 리팩토링 과정에서 파일 단위로 해당 어트리뷰트를 추가하고, 나중에 대부분의 파일에 해당 어트리뷰트가 적용되면 그때 프로젝트 전체에 적용하는 것은 어떻게 생각하시나요? 이 문제는 #335 에서 이야기하는 것이 더 좋을 것 같습니다.

2021-01-18 06:26 UTC, Medowhill commented on kernel-rs/src/vm.rs
> +    pub fn as_usize(&self) -> usize {
`RawPageTable`은 `PageTable`의 내부적인 구조이기 때문에 모듈 밖에서 접근할 수 없어야 한다고 생각했습니다. 따라서 `as_raw`는 `pub`이 붙지 않아야 하고, `as_raw` 없이도 페이지 테이블의 주소를 얻기 위해서는 `as_usize`가 필요합니다.

2021-01-18 06:26 UTC, Medowhill commented on kernel-rs/src/vm.rs
> +    fn as_raw_mut(&mut self) -> &mut RawPageTable {
무슨 이름이 가장 좋을지는 모르겠지만, 일단 `as_inner_mut`으로 바꾸어 두겠습니다.

2021-01-18 06:26 UTC, Medowhill commented on kernel-rs/src/vm.rs
> +                PAddr::new(unsafe { trampoline.as_mut_ptr() as usize }),
인자로 `trap_frame: &Page`을 받도록 하겠습니다. 나중에 `MemoryManager`를 추가하면 `MemoryManager`가 `PageTable`이 `UVAddr`에서 `Page`의 `PAddr`로 가는 매핑을 가지도록 invariant를 유지할 텐데, `uvm_new`가 임의의 `PAddr`을 받게 되면 그 invariant를 보장할 수 없어 `unsafe`가 되겠지만, `&Page`를 받아 그 주소를 사용하면 invariant를 항상 보장할 수 있습니다.

2021-01-18 06:26 UTC, Medowhill commented on kernel-rs/src/vm.rs
> +    pub unsafe fn uvm_init(&mut self, src: &[u8]) -> Result<(), ()> {
프로세스가 만들어질 때 `ProcessSystem::alloc()`을 호출해 페이지 테이블을 만든 뒤 페이지 테이블에 trampoline 등을 매핑합니다. 이 과정은 모든 프로세스를 만들 때 필요합니다. 첫 프로세스를 만들 때는 먼저 `user_proc_init`에서 `alloc`을 호출해 이미 페이지 테이블에 trampoline 등이 매핑된 상태로 만듭니다. 그 후에 `uvm_init`을 호출해 첫 프로세스의 코드를 복사하고 그에 대한 매핑을 페이지 테이블에 추가합니다. `alloc`을 재사용할 수 있는 현재의 코드가 좋은 설계 같기 때문에 `uvm_init`은 그대로 두어야 한다고 생각합니다. 다만, `alloc`에서 `proc_pagetable`을 호출해 페이지 테이블을 만들고 trampoline 등을 매핑하는데, `proc_pagetable`이 하는 작업이 `PageTable`에서 이루어지는 것이 바람직 해 보입니다. 따라서 `proc_pagetable`을 없애고 같은 기능을 하는 `uvm_new`를 추가했습니다.

2021-01-18 06:26 UTC, Medowhill commented on kernel-rs/src/vm.rs
> +    pub fn uvm_alloc(&mut self, mut oldsz: usize, newsz: usize) -> Result<usize, ()> {
kvm도 지원하도록 `alloc`으로 바꾸는 것은 가능해 보입니다. 이 PR에서 다룰 주제는 아닌 것 같기 때문에 말씀하신 대로 별도 이슈를 만들겠습니다.

2021-01-18 09:12 UTC, Medowhill commented on kernel-rs/src/vm.rs
> +                PAddr::new(unsafe { trampoline.as_mut_ptr() as usize }),
`&Page`를 인자로 받으려 하니 다른 문제가 생기기도 하고, 현재 해결하고자 하는 바가 명확하지 않기 때문에 `MemoryManager`를 추가한 후에 다시 이 이슈를 해결하겠습니다.

2021-01-18 12:30 UTC, jeehoonkang requested changes
- 감사합니다. 대체로 사소한 코멘트만 남겼습니다.
- 코멘트만 반영해주시면 바로 머지하겠습니다.

2021-01-18 12:30 UTC, jeehoonkang commented on kernel-rs/src/vm.rs
> +    unsafe fn as_table_mut(&mut self) -> Option<&mut RawPageTable> {
네... 어떤 고민인지 이해가 됩니다. 이 discussion을 주석으로 간단히 남겨주시겠어요? 추후에 어딜 unsafe로 만들지 결정합시다.

2021-01-18 12:30 UTC, jeehoonkang commented on kernel-rs/src/vm.rs
> +    pub fn as_usize(&self) -> usize {
전 큰 선호는 없습니다만 usize를 제공하는걸 조금이나마 더 선호합니다.

2021-01-18 12:30 UTC, jeehoonkang commented on kernel-rs/src/vm.rs
> +                PAddr::new(unsafe { trampoline.as_mut_ptr() as usize }),
@efenniht 님이 제기하신 issue를 comment로 남겨주시겠어요?

2021-01-18 12:30 UTC, jeehoonkang commented on kernel-rs/src/vm.rs
> +    pub fn guard(&mut self, va: UVAddr) {
혹시 이름을 바꾼 이유가 있나요? 걍 clear로 두는게 어덜가 해서요

2021-01-18 12:30 UTC, jeehoonkang commented on kernel-rs/src/vm.rs
> +    pub unsafe fn copy_out(&mut self, dstva: UVAddr, src: &[u8]) -> Result<(), ()> {
혹시 새로 생긴 함수인가요? 아니면 어디서 옮겨온 함수인가요?

2021-01-18 12:30 UTC, jeehoonkang commented on kernel-rs/src/vm.rs
> +        let mut page_table = Self::new_emtpy_table()?;
"emtpy" -> "empty"

2021-01-18 12:30 UTC, jeehoonkang commented
bors가 잘 도는지 확인차...

bors retry

2021-01-18 12:39 UTC, jeehoonkang commented
bors retry

2021-01-18 12:43 UTC, Medowhill commented on kernel-rs/src/vm.rs
> +    pub unsafe fn copy_out(&mut self, dstva: UVAddr, src: &[u8]) -> Result<(), ()> {
원래 `PageTable<A>`에 있었습니다. 인자로 `UVAddr`을 받는데 `PageTable<UVAddr>`이 아니라 `PageTable<A>`에 정의되어 있는 것은 이상하다고 생각해 위치를 옮겼습니다. `PageTable<UVAddr>`의 다른 메서드와 마찬가지로 나중에 일반화하면 될 것 같습니다. (#336)

2021-01-18 12:45 UTC, Medowhill commented on kernel-rs/src/vm.rs
> +    pub fn guard(&mut self, va: UVAddr) {
메서드가 하는 일은 `PTE_U`를 지워서 유저 프로세스의 접근을 막는 것인데, `clear`라고 하면 페이지의 데이터를 지우는 것 같은 느낌이 들어서 바꾸어 보았습니다. 무엇으로 하든 큰 상관은 없으니 다시 `clear`로 바꾸겠습니다.

2021-01-18 12:55 UTC, Medowhill commented on kernel-rs/src/vm.rs
> +                PAddr::new(unsafe { trampoline.as_mut_ptr() as usize }),
#338

2021-01-18 12:57 UTC, jeehoonkang commented
@Medowhill CI가 잘 안도는 것 같은데, (1) 코멘트 모두 반영해주시고 (2) PR close하고 (3) master에 rebase하고 (4) 새 PR로 만들어줄래요? CI가 잘 도는지 확인해보겠습니다.

2021-01-18 13:04 UTC, Medowhill commented on kernel-rs/src/vm.rs
> +    unsafe fn as_table_mut(&mut self) -> Option<&mut RawPageTable> {
주석 추가하고 이슈도 만들었습니다. #339

2021-01-18 13:04 UTC, closed without merging