[Closes #339] Exploit invariant of PageTableEntry
kaist-cp/rv6 pull request #342
Opened 2021-01-18 14:28 UTC by Medowhill

Closes #339

"V 플래그는 켜져 있지만 RWX 플래그는 꺼져 있는 엔트리는 페이지 테이블을 가리킨다"는 성질을 `PageTableEntry`의 invariant로 변경했습니다. `PageTableEntry`의 invariant가 엔트리 수정 시에도 유지될 수 있도록 `set_inner`와 같이 invariant를 깰 수 있는 메서드를 없애고 다음과 같은 메서드를 추가했습니다.

* `set_table`: 페이지 테이블을 가리키는 엔트리로 만듦
* `set_entry`: 데이터 페이지를 가리키는 엔트리로 만듦
* `make_user_inaccessible`: `PTE_U`를 지워 유저 프로세스의 접근을 막음
* `invalidate`: 유효하지 않은 엔트리로 만듦

더 나은 메서드 이름을 제안해 주시면 좋을 거 같습니다.

2021-01-18 19:08 UTC, jeehoonkang requested changes

2021-01-18 19:08 UTC, jeehoonkang commented on kernel-rs/src/vm.rs
> +    fn make_user_inaccessible(&mut self) {
단어가 약간 긴데 한단어로 가능할까요? `mask`?
한단어는 아니라도 `make_inaccessible`이 명확할 것 같기도 하네요.

2021-01-18 19:08 UTC, jeehoonkang commented on kernel-rs/src/vm.rs
> +/// The invariant of this struct is as follows:
아마 `# Safety`가 의미하는 바가 정확히 이거라서 굳이 매번 안써줘도 될거같습니다.

2021-01-19 06:01 UTC, Medowhill commented on kernel-rs/src/vm.rs
> +    fn make_user_inaccessible(&mut self) {
밑에 getter로 `is_user_accessible`이 있어서 두 메서드가 일관성 있는 이름을 가지도록 해야 할 것 같습니다. 또, `is_table`, `is_data`, `is_valid`와의 일관성도 유지되면 좋겠습니다.

`clear_user`와 `is_user`는 어떻게 생각하시나요?

2021-01-19 06:25 UTC, efenniht commented
bors retry

2021-01-19 06:26 UTC, efenniht commented
bors try

2021-01-19 06:27 UTC, jeehoonkang commented on kernel-rs/src/vm.rs
> +    fn make_user_inaccessible(&mut self) {
넵 좋은 것 같습니다.

2021-01-19 06:35 UTC, jeehoonkang commented
bors r+

2021-01-19 06:49 UTC, jeehoonkang commented
bors retry

2021-01-19 06:50 UTC, jeehoonkang commented
bors r=me

2021-01-19 06:55 UTC, merged