[Closes #341] Use bitflags
kaist-cp/rv6 pull request #347
Opened 2021-01-19 07:23 UTC by Medowhill

Closes #341

bitflags를 사용한 구현입니다.

2021-01-19 07:29 UTC, jeehoonkang requested changes

2021-01-19 07:29 UTC, jeehoonkang commented on kernel-rs/src/riscv.rs
> +pub const fn pte_flags(pte: PteT) -> PteFlags {
PteT를 그냥 없앨 수도 있을 것 같은데 가능하면 없앴으면 합니다.

2021-01-19 07:29 UTC, jeehoonkang commented on kernel-rs/src/riscv.rs
> +    PteFlags::from_bits_truncate(pte & 0x3FFusize)
혹시 bit masking 하지 않아도 원하는 효과를 얻지 않나요?

2021-01-19 07:29 UTC, jeehoonkang commented on kernel-rs/src/vm.rs
> +    fn check_flag(&self, flag: PteFlags) -> bool {
이제 굳이 함수로 안만들어도 될듯 합니다.

2021-01-19 07:29 UTC, jeehoonkang commented on kernel-rs/src/vm.rs
>          pte_flags(self.inner)
굳이 함수로 안만들어도 될듯 합니다.

2021-01-19 07:29 UTC, jeehoonkang commented on kernel-rs/src/vm.rs
>  }
inner: pteflags 를 두면 될듯 합니다.

2021-01-19 07:29 UTC, jeehoonkang commented on kernel-rs/src/vm.rs
> +        self.inner &= !(PteFlags::U.bits());
bits()를 없에도 혹시 되지 않나요?

2021-01-19 08:19 UTC, Medowhill commented on kernel-rs/src/vm.rs
>  }
`inner`는 flag뿐 아니라 `VAddr`에서 `PAddr`로 가는 매핑도 가지고 있는데 타입이 `PteFlags`인 것은 이상한 것 같습니다.

2021-01-20 14:14 UTC, jeehoonkang requested changes
재민님이 써주신 답글 보고 리뷰 재반영하여 보내드립니다.

2021-01-20 14:14 UTC, jeehoonkang commented on kernel-rs/src/riscv.rs
> +pub const fn pte_flags(pte: PteT) -> PteFlags {
paddr, vaddr 모두 vm.rs에서 정의되어 있는데, 여기서는 `PteT`은 여기서 정의된 것으로 보입니다.
제 생각에 layer를 맞춘다면 PteT를 없애고 그냥 usize를 쓰는게 맞지 않나 합니다. 어떻게 보시나요?

2021-01-20 14:14 UTC, jeehoonkang commented on kernel-rs/src/vm.rs
> +    fn check_flag(&self, flag: PteFlags) -> bool {
- 함수로 만드는 motivation은 이해했습니다.
- flag_intersects 정도로 이름을 바꾸면 어떨까요?

2021-01-20 14:26 UTC, Medowhill commented on kernel-rs/src/riscv.rs
> +pub const fn pte_flags(pte: PteT) -> PteFlags {
네. 그냥 `usize`를 사용해도 될 것 같습니다.

2021-01-20 14:32 UTC, Medowhill commented
리뷰해 주신 내용 반영했습니다. 확인해 주시면 rebase & squash 하겠습니다.

2021-01-20 14:40 UTC, jeehoonkang approved these changes

2021-01-20 14:40 UTC, jeehoonkang commented on kernel-rs/src/vm.rs
> +    fn flag_intersects(&self, flag: PteFlags) -> bool {
flag_intersects? flags_intersect? 뭐가 더 좋을지 모르겠네요...
재민님이 판단해서 결정해주시고 rebase/squash 해주시고 ping 주시면 머지하겠습니다.

2021-01-20 14:42 UTC, Medowhill commented on kernel-rs/src/vm.rs
> +    fn flag_intersects(&self, flag: PteFlags) -> bool {
어느 쪽이든 괜찮은 것 같은데, 개인적으로는 bitflags에 있는 `intersects`와 일관성 있는 지금이 좋은 것 같습니다.

2021-01-20 14:47 UTC, jeehoonkang commented
bors r+

2021-01-20 14:53 UTC, merged