Add `UserMemory` type to exploit invariant of user process memory
kaist-cp/rv6 pull request #352
Opened 2021-01-21 12:01 UTC by Medowhill

유저 프로세스 메모리를 관리하는 `UserMemory` 타입을 추가했습니다. `UserMemory`는 다음과 같은 invariant를 가집니다.

(For brevity, `pt` := `page_table`, and we treat `pt` as a function from `va` to `pa`.)

* `TRAMPOLINE` ∈ dom(`pt`) ∧ `pt(TRAMPOLINE)` = `trampoline`.
* `TRAPFRAME` ∈ dom(`pt`) ∧ `pt(TRAPFRAM)E` = `trap_frame`.
* If `va` ∈ dom(`pt`), `va` mod `PGSIZE` = 0 ∧ `pt(va)` mod `PGSIZE` = 0.
* If `va` ∈ dom(`pt`) where `va` ∉ { `TRAMPOLINE`, `TRAPFRAME` }, then `Page::from_usize(pt(va))` succeeds without breaking the invariant of `Page`.
* If `va` ∈ dom(`pt`) where `va` ∉ { 0, `TRAMPOLINE`, `TRAPFRAME` }, then `va - PGSIZE` ∈ dom(`pt`).
* `pgroundup(size)` ∉ dom(`pt`).
* If `size` > 0, then `pgroundup(size) - PGSIZE` ∈ dom(`pt`).
* `Page::from_usize(trap_frame)` succeeds without breaking the invariant of `Page`.

이제 `PageTable`은 단순히 `VAddr`에서 `PAddr`로 가는 맵 자료 구조로 취급됩니다.

2021-01-21 13:20 UTC, jeehoonkang requested changes

2021-01-21 13:20 UTC, jeehoonkang commented on kernel-rs/src/exec.rs
> +    pub fn exec(&self, path: &Path, argv: &[Page]) -> Result<usize, ()> {
이제 argv -> args로 이름을 바꿔도 되지 않을까 합니다.

2021-01-21 13:20 UTC, jeehoonkang commented on kernel-rs/src/vm.rs
> +        mem::swap(&mut self.trap_frame, &mut trap_frame);
try use mem::replace

2021-01-21 13:20 UTC, jeehoonkang commented on kernel-rs/src/vm.rs
> +    /// the return value of the very last remove_trap_frame call.
- "last remove_trap_frame": 같은 process에 대해 마지막 remove_trap_frame의 결과인거죠?
- 이 invariant를 자동으로 지키게하려면 trap frame 정보를 (user memory가 아니라) proc이 가지고 있어도 괜찮아보이는데 어떻게 보시나요?

2021-01-21 13:20 UTC, jeehoonkang commented on kernel-rs/src/vm.rs
> +        let size = pgroundup(self.size);
self.size가 pgsize의 배수가 아닐 수도 있나요? 맞다면 더 간단해질 거 같아서요

2021-01-21 13:20 UTC, jeehoonkang commented on kernel-rs/src/vm.rs
> +        self.page_table
error 처리를 먼저 하고 (map_err(...)?), 그 다음 self.size =... 코드를 실행하면 어떨까 합니다.

2021-01-21 13:20 UTC, jeehoonkang commented on kernel-rs/src/vm.rs
> +            .insert_multiple(
- 저는 원래 이름대로 가는게 어떨가 합니다. 충분히 의도하는 바를 잘 표현하는 것 같아서요
- 그래도 이름을 바꾼다면 multiple보단 pages 혹은 range 정도가 어떨까 합니다.

2021-01-21 13:20 UTC, jeehoonkang commented on kernel-rs/src/vm.rs
> +        assert_eq!(new.size, 0);
혹시 이렇다면 그냥 UserMemory를 return하는 것도 생각해봄직할 것 같은데 어떻게 보시나요?

2021-01-21 13:20 UTC, jeehoonkang commented on kernel-rs/src/vm.rs
> +            let mut new_umm = scopeguard::guard(new, |new| {
scopeguard를 loop 밖에서 만들 수도 있나요?

2021-01-21 13:20 UTC, jeehoonkang commented on kernel-rs/src/lib.rs
> +#[deny(unsafe_op_in_unsafe_fn)]
종국에는 모든 파일에 적용해야한다고 TODO 남겨주세요 (코멘트로)

2021-01-21 13:20 UTC, jeehoonkang commented on kernel-rs/src/exec.rs
> -        let p: *mut Proc = myproc();
이 지점에 diff가 많이 생겼는데 혹시 그 이유가 무엇인가요?

2021-01-21 13:20 UTC, jeehoonkang commented on kernel-rs/src/vm.rs
> +pub struct KernelMemory {
- kernel/user memory가 많이 다른가요? 합칠 수 있는 여지가 거의 없을까요?
- PR 본문에 써주신 invariant를 주석으로 기술해주시면 감사하겠ㅅ븐디ㅏ.

본문에 쓰신 invariant에 대해서는 아래와 같은 의견이 있습니다.
- 편의상 invariant를 1-8이라고 하겠습니다.
- 1,2는 pt(TRAMPOLINE) = trampoline 과 같이 simplify할 수 있어보입니다.
- 4,8은 합칠 수 있지 않나요?
- 6,7은 의미상 같이 제시되는게 좋을 것 같습니다.

2021-01-21 15:32 UTC, Medowhill commented on kernel-rs/src/vm.rs
> +        let size = pgroundup(self.size);
sbrk syscall을 통해 1바이트 단위로 size를 조절할 수 있어서 `PGSIZE`의 배수가 아닐 수 있습니다.

2021-01-21 16:31 UTC, Medowhill commented on kernel-rs/src/vm.rs
> +        assert_eq!(new.size, 0);
새로운 `Proc`을 `alloc`할 때 새로운 `UserMemory`를 만듭니다. 이때는 페이지 테이블에 `trampoline`과 `trapframe`만 추가하고, 이후에 만드는 프로세스가 첫 유저 프로세스라면 `init`을 호출해 `initcode`를 복사하고, 기존 프로세스에서 `fork`를 통해 만들어진 프로세스라면 `copy`를 호출해 기존 프로세스의 메모리를 복사합니다. 이처럼 `UserMemory`를 만드는 과정과 필요한 데이터를 복사해 오는 과정이 분리되어 있기 때문에 `UserMemory`를 return하기는 어려워 보입니다.

2021-01-21 16:31 UTC, Medowhill commented on kernel-rs/src/exec.rs
> -        let p: *mut Proc = myproc();
`exec`에서는 새로운 `UserMemory`를 만들되 기존 프로세스의 `trapframe`을 그대로 사용합니다. 그래서 `data.memory.remove_trap_frame()`을 통해 기존 프로세스의 `trapframe`을 꺼내 옵니다. 문제는 `exec`를 처리하던 도중에 실패할 수 있다는 것입니다. 이 경우 기존 프로세스의 `trapframe`이 다시 복원되어야 합니다. 이를 위해서는 새로 만든 `UserMemory`에서 `trapframe`을 꺼내 와 다시 기존 프로세스의 `UserMemory`에 넣어 주어야 하는데, `exec` 안에서 중간에 return 되는 곳이 굉장히 많기 때문에 모든 곳에 해당 코드를 넣을 수는 없습니다. 그래서 `scopeguard`를 사용함으로써 중간에 return이 일어나면 해당 과정이 진행되도록 만들었습니다.

2021-01-21 16:31 UTC, Medowhill commented on kernel-rs/src/vm.rs
> +pub struct KernelMemory {
`UserMemory`의 invariant는`trampoline`을 제외한 모든 `PAddr`이 `Page`로 부터 온 주소라는 것을 보장합니다. 이는 `UserMemory`가 제공하는 `copy_in`과 같이 메모리에 읽거나 쓰는 메서드의 안전성을 보장하는 데 핵심적인 성질입니다. 또한, 메모리의 크기를 줄이거나 `UserMemory`가 drop될 때 각 `PAddr`로 부터 `Page`를 만들어서 free하는 것이 안전하다는 것도 보장합니다.

반면, `KernelMemory`의 어떤 `PAddr`도 `Page`로부터 온 주소가 아닙니다. `KernelMemory`를 사용해 메모리에 읽거나 쓰거나 하지 않으며 `KernelMemory`는 drop되거나 메모리 크기가 줄어들지 않습니다. 따라서 `UserMemory`와 동일한 invariant를 찾기도 어렵고 굳이 invariant를 찾아서 보장해야 할 성질이 있지도 않습니다.

만약 나중에 커널을 수정/확장해서 `KernelMemory`의 동작이 달라지게 된다면 `KernelMemory`의 invariant가 필요할 수 있겠지만, 그 invariant가 무엇이며 `UserMemory`의 invariant와 통합할 수 있는지 알기 위해서는 `KernelMemory`의 동작이 먼저 정해져야 할 것 같습니다. 현재의 `KernelMemory`의 동작만 놓고 생각했을 때는 `UserMemory`와 `KernelMemory`가 가지는 성질이 상당히 다르기 때문에 두 개를 별개의 타입으로 두는 편이 낫다고 생각합니다.

2021-01-22 06:23 UTC, Medowhill commented on kernel-rs/src/exec.rs
> -        let p: *mut Proc = myproc();
다시 `trap_frame`을 `Proc`으로 옮기면서 원래와 비슷해졌습니다.

2021-01-22 06:23 UTC, Medowhill commented on kernel-rs/src/vm.rs
> +    /// the return value of the very last remove_trap_frame call.
다시 `trap_frame`을 `Proc`으로 옮겼습니다.

2021-01-22 06:24 UTC, Medowhill commented
다시 `trap_frame`을 `Proc` (정확히는 `ProcData`)로 옮겼습니다.

2021-01-22 08:02 UTC, jeehoonkang requested changes

2021-01-22 08:02 UTC, jeehoonkang commented on kernel-rs/src/vm.rs
> +            let mut s = scopeguard::guard(slf, |s| {
scopeguard를 while 밖에서 만들 수도 있나요?

2021-01-22 08:02 UTC, jeehoonkang commented on kernel-rs/src/vm.rs
> +        let mut slf = self;
이럴때 보통 `this`를 사용하는 것 같습니다 참고 요청드려요

2021-01-22 08:02 UTC, jeehoonkang commented on kernel-rs/src/vm.rs
> +pub struct KernelMemory {
잘 정리해주셔서 감사합니다. 해당하는 내용을 comment로 기술해주시면 나중에 context를 상기하는데 큰 도움이 될 것 같습니다. (지금 그대로 한국어로 써주셔도 됩니다.)

2021-01-25 05:52 UTC, efenniht requested changes
고생하셨습니다~

2021-01-25 05:52 UTC, efenniht commented on kernel-rs/src/vm.rs
> +    /// - All leaf mappings must already have been removed.
이 조건을 만족하지 않을 때, UB가 생기는 것은 아니므로 Safety 조건 밖에 있어도 될 듯 합니다.

2021-01-25 05:52 UTC, efenniht commented on kernel-rs/src/vm.rs
> +        assert!(!pte.is_valid(), "remap");
```suggestion
        assert!(!pte.is_valid(), "PageTable::insert");
```

2021-01-25 05:52 UTC, efenniht commented on kernel-rs/src/vm.rs
> +        if !self.ptr.is_null() {
Invariant 에 의해 항상 `self.ptr` 은 null pointer 가 아니지 않나요? 체크 안하거나 `debug_assert!(!self.ptr.is_null());` 로 바꾸는 것이 좋겠습니다.

2021-01-25 05:52 UTC, efenniht commented on kernel-rs/src/vm.rs
> +            .map_err(|page| kernel().free(page))
원래 uvminit 에서는 error 처리를 제대로 하지 않았군요!?

2021-01-25 05:52 UTC, efenniht commented on kernel-rs/src/vm.rs
> +    pub fn copy_from_file(
`read_from_file`가 더 나은 이름인 것 같습니다.

2021-01-25 05:52 UTC, efenniht commented on kernel-rs/src/vm.rs
> +    pub fn copy(&mut self, new: &mut UserMemory) -> Result<(), ()> {
```suggestion
    pub fn clone(&self) -> Result<Self, ()> {
```
새로운 UserMemory 를 만드는 것이니까 새 것을 직접 리턴하고, self 가 수정되지 않는 것을 보장하면 좋겠습니다.

2021-01-25 05:52 UTC, efenniht commented on kernel-rs/src/vm.rs
> +    pub fn copy(&mut self, new: &mut UserMemory) -> Result<(), ()> {
아 근데 `self.get_mut` 을 써야 하네요... ㅠㅠ `&mut self` 로 타협할까요?

2021-01-25 05:52 UTC, efenniht commented on kernel-rs/src/vm.rs
> +            (*new)
```suggestion
            page.copy_from_slice(src);
            new
```

2021-01-25 05:52 UTC, efenniht commented on kernel-rs/src/vm.rs
> +        // It is safe because pte.get_pa() is the address of a page.
여기서 안전한 이유는 `pte` 가 가리키고 있는 메모리를 usermemory 가 실제로 소유하고 있기 때문입니다. 예컨대 `TRAMPOLINE` 주소 또한 `pte.get_pa()` 로 얻을 수 있는 데 이 메모리는 `usermemory` 가 소유하지 않아서 앞의 if 문에서 걸러집니다. (`is_user` 가 그런 의도로 쓰이는 지는 잘 모르겠지만.) 해서 여기서의 safety argument 를 좀 더 보충해주셨으면 합니다.

2021-01-25 14:56 UTC, Medowhill commented on kernel-rs/src/vm.rs
> +    pub fn copy(&mut self, new: &mut UserMemory) -> Result<(), ()> {
https://github.com/kaist-cp/rv6/pull/352#discussion_r561998391

2021-01-25 14:58 UTC, Medowhill commented on kernel-rs/src/vm.rs
> +        if !self.ptr.is_null() {
https://github.com/kaist-cp/rv6/pull/352/files#diff-f657b36b5e7dd887fbabd44f2388caf5c4d926390caf4f72c1191acca76ea119R299

`uninit`에 의해 만들어진 `PageTable`이 사용되지는 않지만 `drop`될 수 있기 때문에 해당 조건이 필요합니다.

2021-01-25 15:24 UTC, Medowhill commented on kernel-rs/src/vm.rs
> +/// - If va ∈ dom(pt) ∧ va ∉ { TRAMPOLINE, TRAPFRAME },
`trap_frame`은 더 이상 `UserMemory`의 데이터가 아니긴 하지만, 위의 invariant가 요구하는 것은 `VAddr`인 `TRAPFRAME`에서 "어떤" `PAddr`로 가는 매핑이 페이지 테이블에 있다는 것뿐이고 해당 `PAddr`이 어떤 값인지는 표현하지 않습니다. 따라서 `trap_frame`이 `UserMemory`의 데이터가 아닌 것이 invariant의 유효함에 영향을 주지는 않을 것 같습니다.

2021-01-25 15:33 UTC, Medowhill commented on kernel-rs/src/proc.rs
> +    trap_frame: *mut TrapFrame,
`exec`에서는 `Proc`의 trap frame은 유지한 채로 페이지 테이블을 새로 만들고 페이지도 모두 새로 할당받습니다. 이는`Proc`의 trap frame은 유지하되 페이지 테이블 및 페이지만 교체해야 함을 뜻합니다. 만약 `UserMemory`가 trap frame까지 관리하게 되면 이전 commit의 코드처럼 `exec`가 다소 복잡해집니다. trap frame은 한번 `Proc`이 만들어지면 해당 `Proc`이 종료될 때까지 바뀌지 않지만, 페이지 테이블과 페이지는 `exec`가 호출되면 바뀌므로, trap frame은 페이지 테이블 및 페이지와 다소 다른 성격을 가진다고 보아야 할 것 같습니다. 그래서 trap frame은 `Proc`이 직접 소유하고, 페이지 테이블과 페이지의 관리는 `UserMemory`에 맡기는 것이 가장 자연스러운 설계라는 결론을 내렸습니다.

2021-01-26 04:27 UTC, efenniht requested changes

2021-01-26 04:27 UTC, efenniht commented on kernel-rs/src/vm.rs
> +        if !self.ptr.is_null() {
그렇다면 `PageTable` 의 safety invariant 인 'ptr uniquely refers to a valid 3-level RawPageTable.' 가 올바르지 않은 것 같습니다.

2021-01-26 04:27 UTC, efenniht commented on kernel-rs/src/vm.rs
> +    pub fn copy(&mut self, new: &mut UserMemory) -> Result<(), ()> {
앗 이미 리뷰한 내용이네요. 그럼 함수 signature 는 그대로 두되 이름만 바꾸면 좋겠습니다. `copy` 는 `copy_in` 과 `copy_out` 때문에 좀 헷갈리기 쉬운 이름인 것 같고, 비슷한 행동을 하는 함수가 standard library 에서는 [`clone_from`](https://doc.rust-lang.org/stable/std/clone/trait.Clone.html#method.clone_from) 이라는 이름을 가지고 있습니다.

2021-01-26 06:04 UTC, Medowhill commented on kernel-rs/src/vm.rs
> +        if !self.ptr.is_null() {
`uninit`으로 만들어진 `PageTable`이 invariant를 따르지 않기 때문에 `uninit`은 `unsafe` 함수이고 " Any page table returned by this method must not be used at all." 라는 주석이 붙어 있습니다. 다만 drop은 일어날 수 있기 때문에 예외적으로 `drop`에서만 null 검사를 합니다. 만약 invariant에서 null을 허용하게 되면 다른 모든 메서드에 null 검사가 추가되어야 하는 문제가 생깁니다.

가장 이상적인 방법은 `uninit` 자체를 없애는 것인데, 이는 `Proc` 리팩토링이 이루어져야 가능할 것 같아 지금 당장 하기는 어려워 보입니다.

임시로 해결하는 방법으로는 `uninit`으로 만들어진 `PageTable`은 drop조차 될 수 없고 항상 `mem::forget`에 인자로 넘기도록 수정함으로써 `drop`에서 null 검사를 안 해도 되게 바꾸는 것이 있을 것 같습니다.

2021-01-26 06:18 UTC, efenniht commented on kernel-rs/src/vm.rs
> +        if !self.ptr.is_null() {
논의한 대로 TODO 남깁시다 (Proc 을 리팩토링하면서 이 문제를 해결하는 것으로 합시다.)

2021-01-26 17:17 UTC, jeehoonkang requested changes
거의 다 온 것 같습니다-

2021-01-26 17:17 UTC, jeehoonkang commented on kernel-rs/src/kalloc.rs
> +            pa % PGSIZE == 0 && (pa as *mut _) >= unsafe { end.as_mut_ptr() } && pa < PHYSTOP,
포인터 비교 대신 usize로 옮겨와서 비교합시다. (포인터 비교는 이론적으로 컴파일러가 이상한 짓을 할 가능성이 있습니다.)

2021-01-26 17:17 UTC, jeehoonkang commented on kernel-rs/src/vm.rs
> +        assert_eq!(new.size, 0);
usermemory 만드는거랑 복사하는거랑 합칠순 없나요? proc 만들기 전에 usermemory를 먼저 만들면 되는 문제가 아닌가 해서요

2021-01-27 02:25 UTC, Medowhill commented on kernel-rs/src/vm.rs
> +        assert_eq!(new.size, 0);
아래 코드는 현재 상태입니다. `alloc`에서는 `UserMemory::new`를 통해 `trampoline`과 `trapframe`만 가지고 있는 `UserMemory`를 만듭니다. 이후 `user_proc_init`에서는 `INITCODE`에서 코드를 복사해 오고 `fork`에서는 기존 프로세스의 `UserMemory`에서 데이터를 복사해 옵니다.

```rust
pub unsafe fn user_proc_init(&mut self) {
  let mut guard = self.alloc().expect("user_proc_init");
  let data = &mut *guard.data.get();
  data.memory.init(&INITCODE).expect("init: failed");
  ...
}
pub unsafe fn fork(&self) -> Result<i32, ()> {
  ...
  let mut np = self.alloc()?;
  let mut npdata = &mut *np.data.get();
  pdata.memory.clone_into(&mut npdata.memory)?;
  ...
}
unsafe fn alloc(&self) -> Result<ProcGuard, ()> {
  ...
  let page = kernel().alloc().ok_or(())?;
  let pa = page.into_usize();
  data.trap_frame = pa as _;
  data.memory = UserMemory::new(PAddr::new(pa)).ok_or(())?;
  ...
}
```

만약 `clone_into`가 새로운 `UserMemory`를 만들도록 하면 다음과 같이 될 것 같습니다.

```rust
pub unsafe fn user_proc_init(&mut self) {
  let page = kernel().alloc().ok_or(())?;
  let pa = page.into_usize();
  let memory = data.memory.new(PAddr::new(pa), &INITCODE).expect("new: failed");
  let mut guard = self.alloc(Page::from_usize(pa), memory).expect("user_proc_init");
  let data = &mut *guard.data.get();
  ...
}
pub unsafe fn fork(&self) -> Result<i32, ()> {
  ...
  let page = kernel().alloc().ok_or(())?;
  let pa = page.into_usize();
  let memory = pdata.memory.clone(PAddr::new(pa))?;
  let mut np = self.alloc(Page::from_usize(pa), memory)?;
  let mut npdata = &mut *np.data.get();
  ...
}
unsafe fn alloc(&self, page: Page, memory: UserMemory) -> Result<ProcGuard, ()> {
  ...
  data.trap_frame = page.into_usize() as _;
  data.memory = memory;
  ...
}
```

이 경우 trap frame이 될 페이지를 만드는 과정이 `user_proc_init`과 `fork`에 중복되어 들어가게 되는데, 이것이 바람직한 리팩토링인지 잘 모르겠습니다.

2021-01-27 03:19 UTC, jeehoonkang commented on kernel-rs/src/vm.rs
> +        assert_eq!(new.size, 0);
저는 후자처럼 리팩토링하는게 바람직하다고 생각하긴 합니다. 간단히 통화나 online/offline 미팅으로 논의하면 좋겠습니다.

2021-01-27 04:57 UTC, jeehoonkang commented
bors r+

2021-01-27 04:59 UTC, Medowhill commented
rebase & squash 한 뒤 merge하겠습니다.

2021-01-27 04:59 UTC, jeehoonkang commented
bors r-

2021-01-27 06:27 UTC, efenniht commented
bors r+

2021-01-27 06:33 UTC, merged