Refactoring virtio_disk
kaist-cp/rv6 pull request #355
Opened 2021-01-25 14:27 UTC by Medowhill

* `Disk`가 `RawPage`를 받아 해당 페이지의 내부를 가리키는 포인터를 만드는 기존의 코드를 없애고, 처음부터 올바르게 align된 배열을 `Disk`가 가지고 있게 만들었습니다. 이를 통해 `Disk`가 자기 자신을 참조할 필요가 없게 되었습니다. 다만, 여전히 `Disk`의 배열의 주소를 MMIO 레지스터에 기록하기 때문에 이후에 가능하다면 `Disk`를 `Pin`으로 보호하는 것이 좋을 것 같습니다.
* `Descriptor`가 `Disk`에 있는 `desc` 배열의 특정 부분을 가리키는 포인터를 가지고 있던 것을 없애고, xv6 구현처럼 index를 나타내는 `usize`만 가지고 있도록 다시 바꾸었습니다. 
  * 포인터를 가지고 있는 경우 해당 포인터가 유효한지 보장할 수 없기 때문에 기존 구현에 있던 아래와 같은 `Deref` 및 `DerefMut` 구현은 올바르지 않습니다.
https://github.com/kaist-cp/rv6/blob/1afd6bfe99027e9e64b0c5d7c5d9d1ee9665be61/kernel-rs/src/virtio_disk.rs#L123-L135
 따라서 `Descriptor`가 가지고 있는 포인터를 사용하려면 반드시 `unsafe`가 필요하고 이는 `unsafe`를 불필요하게 늘립니다.
  * 반면 index만 가지고 있고 이 index를 사용해 `desc` 배열에 접근하는 것은 언제나 안전합니다. Rust에서는 배열에 접근할 때 index를 검사하므로 xv6에 비해 약간의 성능 손해가 발생할 수 있습니다. 그러나, 현실적으로 rv6 전체에서 배열 접근을 없앨 수 는 없기 때문에 굳이 배열에 접근하는 코드를 모두 없애려 할 필요는 없다고 생각하며, 무시할 수 있을 정도의 성능 손해라고 생각합니다.

2021-01-25 14:30 UTC, Medowhill commented on kernel-rs/src/virtio_disk.rs
> +        debug_assert!(!self.info.free[idx], "Disk::free");
이 줄은 `assert!(...)`가 되어야 합니다. 다른 리뷰 반영 시 함께 수정하겠습니다.

2021-01-25 14:44 UTC, jeehoonkang requested changes
제가 기력이 딸려서... 일단 superficial한거만 보고 디자인에 대해서는 다음 iteration에서 보겠습니다.

2021-01-25 14:44 UTC, jeehoonkang commented on kernel-rs/src/trap.rs
> -            kernel().file_system.disk.lock().virtio_intr();
혹시 파일 이름을 바꾼 이유가 있나요?

2021-01-25 14:44 UTC, jeehoonkang commented on kernel-rs/src/virtio.rs
> -/// a single descriptor, from the spec.
혹시 virtio_disk.rs로 옮겨간 이유가 있나요? 다른 struct도 마찬가지

2021-01-25 14:44 UTC, jeehoonkang commented on kernel-rs/src/virtio_disk.rs
> +const NUM: usize = 8;
power of two여야 하면 `1 << 3`과 같이 쓰면 어떨까 합니다.

2021-01-25 14:44 UTC, jeehoonkang commented on kernel-rs/src/virtio_disk.rs
> +                Some(desc) => descs.push(desc),
일반적으로 some은 match보다 if let Some(...) 을 선호합니다.

2021-01-25 14:44 UTC, jeehoonkang commented on kernel-rs/src/virtio_disk.rs
> +                - (VirtIOFeatures::BLK_F_RO
bitflag에 -가 있는게 다소 의아한데 혹시 의도를 설명해주실 수 있을까요?

2021-01-25 15:39 UTC, Medowhill commented on kernel-rs/src/virtio.rs
> -/// a single descriptor, from the spec.
모두 `virtio_disk.rs`에서만 사용되는 정의들이고 다른 모듈에서는 전혀 필요하지 않으므로, `virtio_disk.rs`로 옮겨서 불필요한 `pub`도 없애고 함께 필요한 정의(`Disk` 등)와 같은 파일에 있게 하는 편이 나을 것 같다고 생각했습니다. 사실 현재 `virtio.rs`에 남아 있는 정의들도 모두 `virtio_disk.rs`에서만 사용되는데, 아예 `virtio.rs`를 없애고 모두 `virtio_disk.rs`로 옮기는 것은 어떻게 생각하시나요?

2021-01-25 15:45 UTC, Medowhill commented on kernel-rs/src/virtio_disk.rs
> +                - (VirtIOFeatures::BLK_F_RO
https://github.com/kaist-cp/rv6/blob/1afd6bfe99027e9e64b0c5d7c5d9d1ee9665be61/kernel/virtio_disk.c#L96-L105

위의 C 코드에 해당하는 부분입니다. 기존 플래그를 읽어서 필요 없는 플래그를 지운 뒤 다시 쓰는 작업을 합니다.

2021-01-25 15:48 UTC, Medowhill commented on kernel-rs/src/trap.rs
> -            kernel().file_system.disk.lock().virtio_intr();
메서드 이름을 말씀하신 것 맞나요? 큰 이유는 없고 다른 메서드 이름 리팩토링과 마찬가지 이유로, C에서는 전역 함수이므로 `virtio_` 접두사가 붙는 것이 바람직하지만 지금은 `Disk`의 메서드이므로 굳이 `virtio_`가 필요 없다고 생각해 바꿨습니다. 윗줄에 있는 `kernel().uart.intr()`과의 일관성 측면에서도 더 나아 보입니다.

2021-01-26 03:20 UTC, jeehoonkang requested changes

2021-01-26 03:20 UTC, jeehoonkang commented on kernel-rs/src/virtio.rs
> -/// a single descriptor, from the spec.
저는 추후에 virtio 다른 device가 생길 가능성이 있으므로, virtio에 공통된거랑 disk에 specific한거랑 나누면 좋겠습니다.

2021-01-26 03:20 UTC, jeehoonkang commented on kernel-rs/src/virtio_disk.rs
> +                - (VirtIOFeatures::BLK_F_RO
`& ~(...)` 와 같이 되는게 좋겠습니다. bitflag다 보니 나중에 리팩토링하다가 -가 의도치 않은 동작을 일으킬 가능성이 있어보여서요

2021-01-26 03:49 UTC, Medowhill commented on kernel-rs/src/virtio_disk.rs
> +                - (VirtIOFeatures::BLK_F_RO
`& !`을 사용하면 `VirtIOFeatures`에 정의되어 있지 않은 비트들이 모두 지워지기 때문에 `-`를 사용해야 합니다. 이 설명을 주석으로  추가했습니다.

2021-01-26 04:38 UTC, efenniht commented on kernel-rs/src/virtio_disk.rs
> +                None => this.sleep(),
여기서 wakeup이 사라진 이유는 무엇인가요?

2021-01-26 05:42 UTC, Medowhill commented on kernel-rs/src/virtio_disk.rs
> +                None => this.sleep(),
https://github.com/kaist-cp/rv6/blob/1afd6bfe99027e9e64b0c5d7c5d9d1ee9665be61/kernel/virtio_disk.c#L216-L221

원래 xv6에 `sleep`밖에 없어서 지웠는데 지금 보니 `alloc_three_descriptors`에서 `free`를 하니 `wakeup`이 있는 것이 맞겠네요. 원래 `xv6`의 버그인 것 같습니다.

2021-01-26 05:55 UTC, efenniht commented on kernel-rs/src/virtio_disk.rs
> +                None => this.sleep(),
@jeehoonkang 이 코드에서 `wakeup` 을 추가하는 수정이 #240 에서 이루어졌습니다. 교수님께서도 여기 `wakeup` 이 없는 것은 버그라고 보신 건가요?

2021-01-26 06:12 UTC, Medowhill commented on kernel-rs/src/virtio_disk.rs
> +                None => this.sleep(),
@efenniht 님과 오프라인에서 의논한 내용입니다.

`wakeup`이 원래 `free` 안에서 호출되던 것을 #240 에서 지금의 위치로 옮긴 것을 확인했습니다. 따라서 `wakeup`이 있는 것이 원래 xv6 동작에 가장 가깝습니다.

다만, `alloc_three_descriptors`는 한번에 한 스레드에 의해서만 실행될 수 있습니다. 따라서 `alloc_three_descriptors`의 실행이 interleaving되는 경우를 고려할 필요는 없습니다.

또한, `alloc`을 시도했다가 실패하면 만든 `Descriptor`를 free할 뿐 기존에 남아 있던 `Descriptor`의 수보다 더 많은 `Descriptor`를 만들어 내는 것은 아닙니다. 그러므로 기존에 sleep 중이던 스레드 입장에서는 여전히 `alloc_three_descriptors`가 성공할 수 없으므로 `wakeup`이 호출되어도 아무 의미가 없습니다. 결론적으로, `wakeup`이 있어도 문제는 없지만, 불필요한 호출이므로 이를 빼는 것이 바람직해 보입니다.

2021-01-26 17:36 UTC, jeehoonkang requested changes

2021-01-26 17:36 UTC, jeehoonkang commented on kernel-rs/src/virtio_disk.rs
> +// It must be page-aligned. As used and info are page-aligned, it is guaranteed
명시적으로 여기도 align을 넣어주면 좋겠습니다. invariant가 약간 fragile 해보여서요

2021-01-26 17:36 UTC, jeehoonkang commented on kernel-rs/src/virtio_disk.rs
> +            desc: [VirtqDesc::zero(); 8],
8 -> NUM?

2021-01-26 17:36 UTC, jeehoonkang commented on kernel-rs/src/virtio_disk.rs
> +            Disk::rw(&mut self.lock(), &mut buf, false);
VirtioDisk라고 명명하는게 맞아보이기도 합니다. issue raising 해주시겠어요?

2021-01-26 17:36 UTC, jeehoonkang commented on kernel-rs/src/virtio_disk.rs
> +                - (VirtIOFeatures::BLK_F_RO
- bitflags에 `-`를 쓰는건 가능하면 피했으면 합니다. 다른 방법을 찾아봅시다... (datalab?)
- `&= ~(A | B | C | ...)` 이렇게 하면 되지 않나요?

2021-01-26 17:36 UTC, jeehoonkang commented on kernel-rs/src/virtio_disk.rs
> +    fn rw(this: &mut SleepablelockGuard<'_, Self>, b: &mut Buf<'static>, write: bool) {
disk i/o가 safe하다고 주장하는게 다소 radical해보이긴 하는데, 맞아보이기는 합니다... 다만 i/o가 safe하다는 argument가 어딘가에는 있어야할 것 같습니다.

2021-01-26 17:36 UTC, jeehoonkang commented on kernel-rs/src/virtio_disk.rs
> +                None => this.sleep(),
- 동의합니다.
- 이 내용을 코드에 주석으로 쓰는게 좋겠습니다. github discussion을 링크하는 것보다 코드에 이유를 써넣는게 더 직접적이어서요.

2021-01-26 17:36 UTC, jeehoonkang commented on kernel-rs/src/virtio_disk.rs
> +        let Descriptor { idx } = desc;
`let idx = desc.idx;` 가 더 낫지 않나 합니다-

2021-01-27 03:44 UTC, Medowhill commented on kernel-rs/src/virtio_disk.rs
> +                - (VirtIOFeatures::BLK_F_RO
https://docs.rs/bitflags/1.2.1/src/bitflags/lib.rs.html#783

2021-01-27 04:06 UTC, jeehoonkang commented on kernel-rs/src/virtio_disk.rs
> +                - (VirtIOFeatures::BLK_F_RO
usize로 가서 계산합시다-

2021-01-27 04:07 UTC, jeehoonkang commented on kernel-rs/src/virtio_disk.rs
> +                - (VirtIOFeatures::BLK_F_RO
주석... -의 의미가 set diff다...

2021-01-27 05:13 UTC, Medowhill commented on kernel-rs/src/virtio_disk.rs
> +            Disk::rw(&mut self.lock(), &mut buf, false);
#357

2021-01-27 07:08 UTC, jeehoonkang commented
bors r+

2021-01-27 08:05 UTC, efenniht commented
bors r+

2021-01-27 08:11 UTC, merged