Add Pipe::Drop
kaist-cp/rv6 pull request #362
Opened 2021-01-27 06:49 UTC by travis1829

* #356 에서의 변경사항 중 `Pin` API와 관련없는 내용만 따로 빼서 새롭게 PR을 만들었습니다. (주로 `Pipe`에 대한 변경사항입니다.)
* `Pipe`의 `Drop` trait을 추가했고 `Copy`, `Clone` trait을 없앴습니다.
* 추가로, `Pipe::copy`가 `unsafe`일 필요가 없는 것 같아서 없앴습니다. (혹시 `unsafe`이여야하는 이유가 있다면 말씀해주세요.)
* kernel.rs에 있던 주석을 일부 지웠습니다. (https://github.com/kaist-cp/rv6/pull/356#discussion_r564504081)

2021-01-27 07:29 UTC, Medowhill requested changes

2021-01-27 07:29 UTC, Medowhill commented on kernel-rs/src/pipe.rs
> +    pipe: &'static Pipe,
`Pipe`에 대한 reference의 lifetime이 `'static`일 수 있나요? 그러려면 이 reference가 가리키는 `Pipe`가 커널이 실행되는 내내 존재해야 하는데, `Pipe`는 만들어졌다 없어졌다 하니 `'static`을 사용할 수 없어 보입니다. Raw pointer를 사용한 원래 구현이 올바른 것 같습니다.

2021-01-27 07:29 UTC, Medowhill commented on kernel-rs/src/pipe.rs
> +                // Safe since this `self.pipe` is stored at a page
`AllocatedPipe`의 invariant로 `pipe`가 page로부터 만들어졌다는 내용이 명시되어야 할 것 같습니다.

2021-01-27 07:29 UTC, Medowhill commented on kernel-rs/src/pipe.rs
> +        let inner = self.inner.lock();
이렇게 되면 기존 구현에 비해 `lock`이 한 번 더 호출될 것 같습니다. `lock` 대신 `get_mut`을 사용하는 것은 어떨까요?

2021-01-27 07:29 UTC, Medowhill commented on kernel-rs/src/pipe.rs
> +    pub fn close(&self, writable: bool) {
`read`와 `write`의 `unsafe`도 없앨 수 있나요?

2021-01-27 07:43 UTC, travis1829 commented on kernel-rs/src/pipe.rs
> +    pipe: &'static Pipe,
`AllocatedPipe`에 lifetime identifier를 추가하고 싶지 않아서 `'static`을 추가하긴 했는데, 제 생각에도 `'static`이 말이 안되는 것 같긴 합니다.
그러면 그냥 `*const Pipe`로 바꿔보겠습니다!

2021-01-27 07:43 UTC, travis1829 commented on kernel-rs/src/pipe.rs
> +        let inner = self.inner.lock();
`get_mut`을 사용하면 race가 생길 수 있지 않나요? AllocatedPipe는 raw pointer를 저장하므로 &mut이 유일한 &mut reference라는 것을 보장할 수도 없을 것 같습니다.

2021-01-27 08:01 UTC, Medowhill commented on kernel-rs/src/pipe.rs
> +        let inner = self.inner.lock();
`&mut`은 해당 reference가 유일하다는 것을 보장합니다. 만약 raw pointer를 &mut으로 변환해서 그 가정이 깨졌다면 이는 raw pointer를 &mut으로 변환한 unsafe 코드의 문제이지, `&mut`이 유일하다고 가정한 코드가 잘못된 것은 아닙니다. 이 상황에서는 `closed`를 호출하기 전 raw pointer로부터 `&mut Pipe`를 만들 때 이 변환이 올바르다는 것을 `AllocatedPipe`의 invariant가 보장하도록 하면 될 것 같습니다.

2021-01-27 12:51 UTC, travis1829 commented
* `ptr: *mut Pipe` -> `ptr: NonNull<Pipe>`
* `AllocatedPipe`이 `&mut self`가 아니라 `self`를 받도록 바꿨습니다. `AllocatedPipe::Drop`은 없앴습니다. (Drop을 제대로 구현하려면 같은 값을 저장하는 readable/writable 변수를 `File`에도 저장하고 `AllocatedPipe`에도 중복해서 저장해야 합니다.)
* #354 를 고려하여 일단은 `Pipe::read()`와 `Pipe::write()`의 unsafe를 없앴습니다. myproc()부분을 제외하면, caller()가 추가로 고려해야 되는 사항은 딱히 없는 것으로 보입니다.
---
* 다만, 추가로 `AllocatedPipe`을 없애는게 어떨지 제안해봅니다.
	* 현재는 xv6의 `Pipe`이 rv6의 030fea5 에서 `PipeInner`, `Pipe`, `AllocatedPipe` 3가지로 나뉘어졌습니다. 여기서, `PipeInner`와 `Pipe`는 한개씩만 만들어지지만, `AllocatedPipe`만 두개가 만들어집니다. (하나는 read, 하나는 write). 또한 API의 경우도 `Pipe`꺼를 써야하는 경우와 `AllocatedPipe`을 써야하는 경우로 뒤섞여있습니다.
	* 차라리 `PipeInner`는 하나만 만들어지고 `Pipe`이 두개 만들어지도록 바꾸는게 나을 것 같습니다. 다만, 이러려면 `Pipe::inner`의 type을 `Spinlock<PipeInner>` -> `*const Spinlock<PipeInner>`로 바꿔야합니다. 또, `Pipe`의 `WaitChannel`들을 `inner`안으로 넣어야 합니다. (어차피 `WaitChannel`을 access할때는 항상 `Spinlock`을 lock()한 상태이니, 추가로 lock()을 할 필요는 없습니다.)

2021-01-27 12:51 UTC, travis1829 commented on kernel-rs/src/pipe.rs
> +    pub fn close(&self, writable: bool) {
바꿨습니다! (https://github.com/kaist-cp/rv6/pull/362#issuecomment-768264195)

2021-01-27 12:51 UTC, travis1829 commented on kernel-rs/src/pipe.rs
> +        let inner = self.inner.lock();
이 부분은 그냥 `closed()`를 없애는 걸로 바꿨습니다.

2021-01-27 12:52 UTC, travis1829 commented on kernel-rs/src/pipe.rs
> +    pipe: &'static Pipe,
`NonNull`로 바꿨습니다!

2021-01-27 13:09 UTC, Medowhill requested changes

2021-01-27 13:09 UTC, Medowhill commented on kernel-rs/src/pipe.rs
> +/// `ptr` always refers to a `Pipe`.
이와 동시에 `Page`를 가리킨다는 것도 명시되어 있어야 `close`의 안전성이 완전히 설명될 것 같습니다.

2021-01-27 13:40 UTC, Medowhill commented on kernel-rs/src/pipe.rs
> +/// `ptr` always refers to a `Pipe`.
코드를 더 보다 보니 위 조건을 추가해도 여전히 충분하지 않은 것 같습니다. `AllocatedPipe::close`에서 페이지를 free하면 같은 주소를 가리키던 다른 `AllocatedPipe`의 invariant가 깨질 수 있습니다. 물론 `Pipe::close`의 결과가 `true`일 때만 free하며, `Pipe::close`의 결과가 `true`라는 조건이 같은 주소를 가리키는 다른 `AllocatedPipe`가 존재하지 않는다는 사실을 보장하므로 구현은 안전한 것이 맞습니다.

`AllocatedPipe`의 invariant에 "`ptr`이 가리키는 `Pipe`의 `read_waitchannel`과 `write_waitchannel` 중 하나가 `false`라면 자기 자신이 아닌 다른 `AllocatedPipe`가 존재하지 않는다"는(또는 이와 유사한 형태의) 조건이 추가로 있어야 할 것 같습니다.

2021-01-27 13:41 UTC, Medowhill commented
> * 차라리 `PipeInner`는 하나만 만들어지고 `Pipe`이 두개 만들어지도록 바꾸는게 나을 것 같습니다. 다만, 이러려면 `Pipe::inner`의 type을 `Spinlock<PipeInner>` -> `*const Spinlock<PipeInner>`로 바꿔야합니다. 또, `Pipe`의 `WaitChannel`들을 `inner`안으로 넣어야 합니다. (어차피 `WaitChannel`을 access할때는 항상 `Spinlock`을 lock()한 상태이니, 추가로 lock()을 할 필요는 없습니다.)

저는 특별한 의견은 없습니다. 지금 상태도 크게 나쁘지는 않은 것 같은데, 바꿔서 더 간단해질 수 있다면 바꾸는 것도 좋다고 생각합니다.

2021-01-27 13:53 UTC, efenniht commented
`WaitChannel::sleep` 이 `&mut LockGuard` 를 필요로 하므로 `WaitChannel` 이 `Spinlock` 안에 있으면 안될 것 같습니다.

2021-01-27 13:57 UTC, travis1829 commented
> WaitChannel::sleep 이 &mut LockGuard 를 필요로 하므로 WaitChannel 이 Spinlock 안에 있으면 안될 것 같습니다.

그렇네요. 간단한 부분을 제가 놓쳤네요. 말씀해주셔서 감사합니다!

2021-01-28 05:38 UTC, efenniht requested changes

2021-01-28 07:38 UTC, travis1829 commented
* 홍재민님의 리뷰 내용을 반영했습니다. 리뷰해주셔서 감사합니다.
* 자잘한 주석을 좀 더 추가해봤습니다.
* 추가로 pipe.rs에 있던 TODO들에 대한 제 생각을 issue에 적어봤습니다 (#366, #367). 그리고 `n`을 `u32`로 바꿔야한다는 TODO는 없앴는데, 혹시 이거에 대한 생각이 따로 있으시면 말씀해주세요.

2021-01-28 07:41 UTC, travis1829 commented on kernel-rs/src/pipe.rs
> +            }
`self.ptr`가 `NonNull`이기는 하지만 그래도 raw pointer이므로 `self.ptr.as_ref()`이 unsafe 입니다.  unsafe block 두개를 써보는게 좋을까요?

2021-01-28 07:48 UTC, travis1829 commented on kernel-rs/src/pipe.rs
> +            }
반영했습니다!

2021-01-28 07:49 UTC, travis1829 commented on kernel-rs/src/pipe.rs
> +/// `ptr` always refers to a `Pipe`.
반영했습니다!

2021-01-29 08:36 UTC, Medowhill commented
bors r+

2021-01-29 08:39 UTC, Medowhill commented
bors retry

2021-01-29 09:34 UTC, Medowhill commented
bors retry

2021-01-29 09:41 UTC, merged