[WIP] unsafe reasoning in arena
kaist-cp/rv6 pull request #379
Opened 2021-01-27 14:09 UTC by Medowhill

* `Arena`의 unsafe reasoning을 위한 PR입니다.
* 일단 `ArrayPtr`과 `MruPtr`이 가지고 있는 포인터를 `*mut`에서 `NonNull`로 바꾸었습니다.
* 코드를 보다 보니 `Arena` 구현에 관련된 질문이 몇 가지 생겼는데 해당 위치에 comment로 달아 두겠습니다.

2021-01-27 14:14 UTC, jeehoonkang reviewed
전반적으로 좋은 것 같습니다. 제가 이해 안되는 부분(...) 하나만 찍어서 review드립니다.

2021-01-27 14:14 UTC, jeehoonkang commented on kernel-rs/src/arena.rs
> -        // Drop AFTER the arena guard is dropped, as dropping val may cause the current thread
음 이부분에 주석이 잘 이해가 안가는데 @efenniht 혹시 맥락이 기억나시나요?

2021-01-27 14:14 UTC, Medowhill commented on kernel-rs/src/arena.rs
> -        let entry = unsafe { &mut *handle.ptr };
`entry`를 다시 정의해야 하는 이유가 있나요? `handle.ptr`이 가리키는 주소는 바뀔 일이 없어 보입니다.

2021-01-27 14:14 UTC, Medowhill commented on kernel-rs/src/arena.rs
> -impl<A: Arena, T: Clone + Deref<Target = A>> Arena for T {
이 `impl`은 사용되고 있지 않기 때문에 지워도 문제가 없는 것 같습니다. 나중에 사용할 수도 있어 정의한 것인가요? 아니면 어딘가에서 사용되고 있거나, 사용되고 있어야 하는데 의도대로 되지 않은 것인가요?

2021-01-27 14:16 UTC, Medowhill commented on kernel-rs/src/arena.rs
>      fn unforget<C: Fn(&Self::Data) -> bool>(&self, c: C) -> Option<Self::Handle> {
`unforget`은 이 메서드를 통해 만들어진 `Handle`을 나중에 `dealloc`에 넘기지 않을 것을 가정해야 안전한 것 같은데, `unsafe`일 필요가 없나요?

2021-01-27 16:33 UTC, efenniht commented on kernel-rs/src/arena.rs
> -        // Drop AFTER the arena guard is dropped, as dropping val may cause the current thread
https://github.com/kaist-cp/rv6/pull/247#discussion_r508384013 file 을 drop할 때는 ftable 밖으로 file을 꺼내야 하기 때문에 해당 코멘트를 작성했습니다. 그런데 이후 리팩토링을 진행하면서 잘못된 곳에 주석이 남은 것 같습니다.

2021-02-01 15:31 UTC, jeehoonkang requested changes

2021-02-01 15:31 UTC, jeehoonkang commented on kernel-rs/src/arena.rs
> +        // It is safe becuase inner has been allocated from self.
- 이 safety는 혹시 어떻게 아나요?
- 혹시 unforget_handle에 unsafe를 mark해야할지도 모르겠습니다. 어떻게 생각하는지 궁금합니다.

2021-02-01 15:40 UTC, Medowhill commented on kernel-rs/src/arena.rs
> +        // It is safe becuase inner has been allocated from self.
* `find_or_alloc`과 `alloc`에서와 마찬가지로, `inner`는 `self.*`을 통해 얻은 핸들이며 이 조건이 `Rc::from_unchecked`가 요구하는 조건이므로 안전성이 보장됩니다.
* #386 이 merge되면 어차피 `unforget`이 지워지므로 굳이 고민하지 않아도 되는 문제라고 생각합니다. #386 에 대한 의견 있으신가요? 전에 주신 리뷰 반영하고 답글 달았습니다.

2021-02-02 08:51 UTC, jeehoonkang approved these changes
bors r+

2021-02-02 08:51 UTC, jeehoonkang commented on kernel-rs/src/arena.rs
> +        unsafe { (*handle.ptr.as_ptr()).refcnt += 1 };
아주 사소한건데 `... += 1;` 이렇게 가는게 어떨까 합니다

2021-02-02 08:56 UTC, merged