[WIP] Refactoring and Unsafe Reasoning in inode.rs
kaist-cp/rv6 pull request #388
Opened 2021-01-29 13:44 UTC by Medowhill

2021-01-29 13:53 UTC, jeehoonkang requested changes

2021-01-29 13:53 UTC, jeehoonkang commented on kernel-rs/src/exec.rs
> +                core::slice::from_raw_parts_mut(&mut elf as *mut _ as _, mem::size_of::<ElfHdr>())
혹시 이 로직을 아예 `ip.read()`에 넣는건 어떻게 보시나요? 지금 read()는 read_bytes()로 바꾸고

2021-01-29 13:53 UTC, jeehoonkang commented on kernel-rs/src/fs/inode.rs
> +    pub fn user_read(&mut self, dst: UVAddr, off: u32, n: u32) -> Result<usize, ()> {
- `read_user`는 어떨까 합니다. read가 더 중요한 것 같아서요
- `read_kernel`이 아니라 `read`인 이유는?

2021-01-29 13:53 UTC, jeehoonkang commented on kernel-rs/src/fs/inode.rs
> +        self.read_internal(off, n, |off, src| {
rust의 전통은 `read_inner`라고 이름짓는 것 같습니다

2021-01-29 13:53 UTC, jeehoonkang commented on kernel-rs/src/fs/inode.rs
> +    pub fn kwrite(&mut self, src: &[u8], off: u32, tx: &FsTransaction<'_>) -> Result<usize, ()> {
write_kernel, write_inner, write_user 제안합니다.

2021-01-29 13:53 UTC, jeehoonkang commented on kernel-rs/src/fs/inode.rs
> +        self.bmap_internal(bn, Some(tx))
아 일부러 이름 바꾼거군요. 혹시 internal이라는 이름을 더 많이 쓰나요?

2021-01-29 14:12 UTC, Medowhill commented on kernel-rs/src/fs/inode.rs
> +        self.bmap_internal(bn, Some(tx))
Rust의 convention은 잘 모르겠지만, rv6에서는 어떤 struct에 내부적인 데이터가 있을 때 해당 데이터에 접근하는 메서드에 주로 inner라는 이름을 사용하는 것 같습니다. 예를 들면, `Buf`의 `deref_inner`가 있습니다. 그러나, 이 파일의 `read_internal`, `write_internal`, `bmap_internal`은 `inode`의 내부적인 데이터에 접근하는 것이 아니라, 밖으로 공개된 비슷한 메서드 여럿에 대한 공통적인 구현을 제공하는 역할을 하기 때문에, inner를 이름에 넣는 것이 혼동을 줄 수 있으므로 다른 이름을 사용하는 편이 낫다고 생각했습니다.

2021-01-29 14:12 UTC, Medowhill commented on kernel-rs/src/fs/inode.rs
> +    pub fn kwrite(&mut self, src: &[u8], off: u32, tx: &FsTransaction<'_>) -> Result<usize, ()> {
네. `write_kernel`과 `write_user`(`read_*`도 마찬가지)로 수정하겠습니다. inner는 다른 코멘트에서 말씀드린 것처럼 혼동을 줄 수도 있다고 생각하는데, 어떤 이름이 좋다고 생각하시나요? inner, internal, common, helper 등이 가능할 것 같습니다.

2021-01-29 14:12 UTC, Medowhill commented on kernel-rs/src/exec.rs
> +                core::slice::from_raw_parts_mut(&mut elf as *mut _ as _, mem::size_of::<ElfHdr>())
네. 괜찮은 것 같습니다. `&T`를 `&[u8]`로 변환하는 것은 unsafe하므로 해당 로직과 Inode에서 `&[u8]`로 읽어 오는 로직을 분리해 두는 것이 낫다고 생각해서 합치지 않았었는데, 비슷한 패턴이 여러 곳에 등장하므로 `read_bytes`와 `read`를 모두 제공하되 `read`를 unsafe로 두는 것이 더 나은 것 같습니다.

2021-01-29 15:13 UTC, Medowhill reviewed
리뷰 내용을 반영하고, `Inode::lock`과 `Itable::alloc_inode`를 추가로 수정했습니다.

2021-01-29 15:22 UTC, jeehoonkang requested changes

2021-01-29 15:22 UTC, jeehoonkang commented on kernel-rs/src/fs/inode.rs
> +        mut f: F,
이건 주석이 필요할 것 같습니다. f의 역할에 대한..

2021-01-29 15:22 UTC, jeehoonkang commented on kernel-rs/src/fs/inode.rs
> +            // If t >= 4, UB will happen when we read dip.typ.
"4"가 magic인데 좀더 의미가 담긴 어구를 쓰면 어떨까 합니다.

2021-01-29 15:22 UTC, jeehoonkang commented on kernel-rs/src/vm.rs
> -            let pa = self
좀 곁ㅇ가지인데 이 함수의 이름은 `load_file`이 더 낫지 않나 합니다. read_file이면 읽은 값을 리턴해야할 것 같아서요.

2021-02-01 07:11 UTC, jeehoonkang requested changes

2021-02-01 07:11 UTC, jeehoonkang commented on kernel-rs/src/fs/inode.rs
> +    /// `f` takes an offset and a slice as arguments. `f(off, dst)` should copy
혹시 f를 function으로 받아야하는 이유가 있나요? 설명을 읽어보니 그냥 copy하는걸 write_internal 안에서 구현하면 되는 문제가 아닌가 해서요. function이 들어가는건 꽤 넉넉한 polymorphism을 허용하는건데 그렇게까지 필요한 이유를 잘 모르겠습니다-

(그리고 이 지점에서는 그런 이유가 있다면 document되어야할 것 같습니다.)

2021-02-01 07:42 UTC, Medowhill commented on kernel-rs/src/fs/inode.rs
> +    /// `f` takes an offset and a slice as arguments. `f(off, dst)` should copy
커널 메모리로 복사하는 것은 그냥 단순 복사이지만, 유저 메모리로 복사할 때는 해당 프로세스의 페이지 테이블을 확인하면서 주어진 virtual address에 해당하는 physical address를 구하고 그 위치로 복사하는 작업을 페이지 단위로 반복해야 합니다. 그래서 `write_internal` 안에 복사하는 로직이 바로 들어갈 수 없습니다.

2021-02-01 11:12 UTC, Medowhill commented on kernel-rs/src/fs/inode.rs
> +    /// `f` takes an offset and a slice as arguments. `f(off, dst)` should copy
해당 설명 주석으로 추가했습니다.

2021-02-01 12:13 UTC, jeehoonkang commented
bors r+

2021-02-01 12:14 UTC, jeehoonkang commented
@Medowhill ci fails due to lint: https://github.com/kaist-cp/rv6/pull/388/checks?check_run_id=1806072649#step:5:75

2021-02-01 12:23 UTC, Medowhill commented
bors retry

2021-02-01 15:43 UTC, Medowhill commented
bors retry

2021-02-01 16:00 UTC, Medowhill commented
bors retry

2021-02-01 16:07 UTC, merged