[Sub-issue of #378] Use `Pin` in `Spinlock`, `MruArena`, and `MruEntry`
kaist-cp/rv6 pull request #394
Opened 2021-02-02 15:49 UTC by travis1829

Partially resolves #378.
* `T: Unpin`인 경우에만 (즉, `T`가 move되어도 상관없는 경우에만) `Spinlock`, `SpinlockGuard`이 `get_mut()`, `get_mut_unchecked()`, `DerefMut`을 impl하도록 바꿨습니다. 그 대신, `get_pin()`을 추가했습니다.
* `ListEntry` API가 `Pin`을 사용하게끔 바꿨습니다.
* `MruArena`, `MruEntry`에서 mutable reference가 필요할 때는 항상 `Pin<&mut ...>`을 사용하게끔 바꿨습니다.
  * 편의를 위해 pin_project crate를 사용했습니다. move되선 안되는 field에는 #[pin]을 붙여서 `Pin`으로만 접근하도록 제한했습니다. 다만 pin_project가 procedural macro를 사용해서인지 dependency를 약 10개나 늘려버립니다. 참고로, procedural macro를 쓰지 않는 pin_project_lite도 있기는 한데 이건 기능이 제한적입니다.

2021-02-02 15:56 UTC, travis1829 commented
https://github.com/kaist-cp/rv6/blob/6fd7edc056630794fbccf04aa4478428b61655b3/kernel-rs/src/arena.rs#L118-L124
추가로, @Medowhill 님께서 여기에 TODO를 남기셨는데, "`ptr` is a valid pointer to `MruEntry<T>`" 정도로만 추가해도 될까요? 아니면 `ArrayPtr`처럼 lifetime을 추가하실 계획이시거나 다른 PR에서 작업하실 계획이신가요?

2021-02-03 03:56 UTC, Medowhill commented
`MruArena`의 안전성을 보장할 수 있는 올바른 invariant를 적어 달라는 의미였습니다.

2021-02-03 06:10 UTC, Medowhill requested changes
`pin_project`가 사용된 부분에서는 rust analyzer가 타입을 못 알아내서 다소 불편하네요... 다른 분들도 같은 문제가 있나요?

2021-02-03 06:10 UTC, Medowhill commented on kernel-rs/src/list.rs
>  pub struct ListEntry {
`prev`와 `next` 메서드의 안전성이 보장되려면 `next`와 `prev` 필드의 성질이 `ListEntry`의 invariant로 기술되어야 할 것 같습니다. `Pin`으로 `ListEntry`의 move를 막는다고 해도 lifetime 문제가 생길 수 있을 것 같은데, 그런 문제가 없다는 설명도 필요해 보입니다.

2021-02-03 06:44 UTC, travis1829 commented on kernel-rs/src/spinlock.rs
> +    pub fn get_pin(&mut self) -> Pin<&mut T> {
* 맞습니다. 그래서 제가 이전에 말씀드린 것처럼, 사실 `Spinlock`도 `Pin`으로 감싸고, 그 `Spinlock`을 들고있는 struct도 감싸고, 그 struct를 감싸고 있는 struct를 또 감싸고...를 반복해야 맞습니다.
* 다만, 현재 `kernel()`이 `&mut Kernel`이 아닌 `&Kernel`을 리턴하므로 `bufcache`에 한해서는 큰 문제는 없습니다.

2021-02-03 06:53 UTC, travis1829 commented
> pin_project가 사용된 부분에서는 rust analyzer가 타입을 못 알아내서 다소 불편하네요... 다른 분들도 같은 문제가 있나요?

저도 똑같은 문제가 발생합니다. 그래서 일단 pin_project 대신 pin_project_lite를 쓰면 문제가 해결되는지 알아보고 있습니다.

2021-02-03 09:01 UTC, travis1829 commented
* `SpinlockProtected`, `Sleeplock`, `Sleepablelock`도 `Pin`을 쓰도록 변경했습니다. (지금은 쓰이는 곳은 없습니다.)
* `ListEntry`에 safety invariant관련된 doc을 조금 추가했습니다.

2021-02-03 09:31 UTC, jeehoonkang requested changes

2021-02-03 09:31 UTC, jeehoonkang commented on kernel-rs/src/sleepablelock.rs
> +    pub fn get_pin(&mut self) -> Pin<&mut T> {
https://doc.rust-lang.org/std/pin/index.html naming convention에 따라 get_pin_mut이 어떨까 합니다.

2021-02-03 09:31 UTC, jeehoonkang commented on kernel-rs/src/arena.rs
> +        // TODO: Pin of array's element?
todo의 의미 = ?

2021-02-03 09:31 UTC, jeehoonkang commented on kernel-rs/src/arena.rs
> +                // Safe since `MruEntry` is accessed only through `Pin`.
좀더 자세히 적어주시면 좋을 것 같습니다.

2021-02-03 09:31 UTC, jeehoonkang commented on kernel-rs/src/list.rs
> +    // Add `PhantomPinned` to mark this struct as `!Unpin`, since `ListEntry`s must not move.
그냥 아래줄이랑 합치고 간단히 `ListEntry is !Unpin` 이라고만 적어도 될듯 해요

2021-02-03 09:31 UTC, jeehoonkang commented on kernel-rs/src/proc.rs
> +// TODO(travis1829): Change &mut Target -> Pin<&mut Target>
이 PR에서 되어야하지 않을까 생각합니다.

2021-02-03 10:07 UTC, travis1829 commented on kernel-rs/src/arena.rs
> +        // TODO: Pin of array's element?
사실 `MruArena::entries`를 접근할때도 `Pin`으로 접근해야하는데, 지금은 임시적으로 `&mut MruEntry`를 받아온 후 그걸로 `Pin`을 만들어냅니다. 이 부분을 곧 없앨 예정입니다. (미리 반영하지 않고 TODO로 표시했던 이유는, 어떻게 할지 조금 고민하느라 그랬습니다.)

2021-02-03 10:07 UTC, travis1829 commented on kernel-rs/src/proc.rs
> +// TODO(travis1829): Change &mut Target -> Pin<&mut Target>
현재 손서윤님께서 하고계신 PR이랑 겹치는 내용이 많을것 같아 보류하였습니다. 특히, PR #385 가 끝나고 나면 `Proc`의 내부를 접근하는 방법이 조금 바뀔 것 같아서 일단은 TODO로만 표시했습니다.

2021-02-03 11:55 UTC, travis1829 commented on kernel-rs/src/spinlock.rs
> +    pub fn get_pin(&mut self) -> Pin<&mut T> {
이 부분을 명시적으로 나타내기 위해 `unsafe` 함수인 `Spinlock::new_unchecked()`를 추가해봤습니다.

2021-02-03 11:56 UTC, travis1829 commented on kernel-rs/src/list.rs
>  pub struct ListEntry {
반영했습니다!

2021-02-03 11:56 UTC, travis1829 commented on kernel-rs/src/sleepablelock.rs
> +    pub fn get_pin(&mut self) -> Pin<&mut T> {
반영하였습니다!

2021-02-03 11:59 UTC, travis1829 commented
* `MruArena::get_entry()`를 추가했습니다. 배열의 index를 받은 후  `Pin<&mut [T]>`로부터 `Pin<&mut T>를 얻어낼 수 있는 함수입니다. 다만, 디자인이 그렇게 깔끔하지는 않은 것 같은데, 혹시 더 좋은 방법이 있으시면 말씀해주세요. (저도 고민 중입니다.)
> Spinlock이 move되면 그 안에 있는 data도 같이 move되지 않나요?
* 이 부분을 명시적으로 나타내기 위해서 unsafe 함수인 `Spinlock::new_unchecked()`를 추가했습니다.

2021-02-03 11:59 UTC, travis1829 commented on kernel-rs/src/list.rs
> +    // Add `PhantomPinned` to mark this struct as `!Unpin`, since `ListEntry`s must not move.
반영했습니다!

2021-02-03 11:59 UTC, travis1829 commented on kernel-rs/src/arena.rs
> +                // Safe since `MruEntry` is accessed only through `Pin`.
조금 더 자세하게 적어봤습니다!

2021-02-03 12:00 UTC, travis1829 commented on kernel-rs/src/arena.rs
> +        // TODO: Pin of array's element?
`MruArena::get_entry()`를 이용하도록 바꾼 후 TODO를 없앴습니다.

2021-02-03 12:57 UTC, Medowhill commented on kernel-rs/src/spinlock.rs
> +    pub const unsafe fn new_unchecked(name: &'static str, data: T) -> Self {
`Sleeplock`과 `Sleepablelock`도 동일한 설명이 들어가야 하지 않나요?

2021-02-03 12:57 UTC, Medowhill commented on kernel-rs/src/kernel.rs
> +            // Safe since the only way to access `bcache` is through `kernel()`, which is an immutable reference.
`bcache`가 move되면 안 된다는 invariant가 `Kernel`에 설명되면 좋을 것 같습니다.

2021-02-03 12:57 UTC, Medowhill commented on kernel-rs/src/arena.rs
`MruPtr`과 `MruArena`도 `ArrayPtr`과 `ArrayArena`와 동일하게 lifetime parameter 추가하고 invariant 주석 추가해 주시면 좋을 것 같습니다. `ArrayArena` 쪽 작업할 때는 list 때문에 `MruArena` 쪽은 다를 수도 있다고 생각했는데, 지금 보니까 그냥 똑같이 하는 것이 맞는 것 같네요.

2021-02-03 12:57 UTC, Medowhill commented on kernel-rs/src/list.rs
>  pub struct ListEntry {
지금의 invariant가 지켜질 수 있는지 잘 모르겠습니다. 현 상태에서 아래 코드를 막을 수 있나요?

```rust
let l = pin(ListEntry::new());
init(l);
foo(l);
let l2 = list_pop_front(l);
// use l2: safe?

fn foo(l1: Pin<&mut ListEntry>) {
    let l2 = pin(ListEntry::new());
    append(l1, l2)
}
```

`append`와 `prepend`는 unsafe가 되어야 맞는 것이 아닌가 싶기도 합니다.

2021-02-03 12:58 UTC, travis1829 commented
* `ListEntry`에 `PinnedDrop` trait을 추가했습니다. `Drop`과 매우 비슷한 trait이며, 마찬가지로 `ListEntry`가 drop될때 `fn drop()`이 실행됩니다.
  * 다만, 컴파일하는데는 문제가 없지만 어째서인지 rust-analyzer가 계속 `pin_project::pinned_drop`을 찾을 수 없다고 에러를 띄웁니다. `pin_project`와 rust-analyzer가 잘 안 맞는 것 같습니다.

2021-02-03 12:59 UTC, travis1829 commented on kernel-rs/src/spinlock.rs
> +    pub const unsafe fn new_unchecked(name: &'static str, data: T) -> Self {
https://github.com/kaist-cp/rv6/pull/394#issuecomment-772455953
맞습니다! 위 comment에 제 생각을 적어놨습니다.

2021-02-03 13:03 UTC, Medowhill commented on kernel-rs/src/spinlock.rs
> +    pub const unsafe fn new_unchecked(name: &'static str, data: T) -> Self {
아 그렇네요. 죄송합니다. 저는 `Lock` trait을 추가하는 것도 좋아 보입니다.

2021-02-03 13:04 UTC, Medowhill commented on kernel-rs/src/list.rs
>  pub struct ListEntry {
`PinnedDrop`이 추가되면서 이 문제가 사라진 것 같기도 한데, 맞나요?

2021-02-03 13:05 UTC, Medowhill commented
최종적으로는 `*lock` 타입들에서 unsafe를 없애고 해당 lock을 사용하는 쪽에서 적절히 pin을 하게 바꾸어야 할 것 같기는 한데, 이 PR에서 거기까지 할 필요는 없고 지금 상태 정도면 중간 과정으로서 괜찮은 것 같습니다.

2021-02-03 13:07 UTC, travis1829 commented
> 최종적으로는 *lock 타입들에서 unsafe를 없애고 해당 lock을 사용하는 쪽에서 적절히 pin을 하게 바꾸어야 할 것 같기는 한데, 이 PR에서 거기까지 할 필요는 없고 지금 상태 정도면 중간 과정으로서 괜찮은 것 같습니다.

이 부분은 TODO로 표시해두면 될 것 같습니다.

2021-02-03 13:12 UTC, travis1829 commented on kernel-rs/src/list.rs
>  pub struct ListEntry {
혹시 `ListEntry::PinnedDrop`을 추가한 이후에도 문제가 되나요? 이러면 `foo()`에서 `l2`가 drop될 자동으로 `l2.delete()`이 실행되는 것 같습니다.

2021-02-03 13:19 UTC, Medowhill commented on kernel-rs/src/list.rs
>  pub struct ListEntry {
네. 말씀하신 대로 `PinnedDrop`이 해결해 줄 것 같습니다.

2021-02-04 04:40 UTC, travis1829 commented
> 최종적으로는 *lock 타입들에서 unsafe를 없애고 해당 lock을 사용하는 쪽에서 적절히 pin을 하게 바꾸어야 할 것 같기는 한데, 이 PR에서 거기까지 할 필요는 없고 지금 상태 정도면 중간 과정으로서 괜찮은 것 같습니다.

실험적으로, 이걸 지금 미리 해봤습니다. (다만, *lock들의 API들은 아직은 그대로 놔뒀습니다.)
* `Bcache: Spinlock<MruArena<...>>`를 `BcacheInner: MruArena<...>`와 `Bcache: Spinlock<Pin<&mut MruArena<...>>>` 2개로 나누었습니다. `Kernel`은 이 두개를 모두 저장하지만, `Bcache`만을 밖으로 노출시키며 `BcacheInner`는 `kernel_main()` 이후에는 절대로 다시는 직접 access하지 않습니다.
  * `BcacheInner`를 다시는 access하면 안 되는 것을 나타내기 위해 `UnsafeCell`안에 넣었습니다. (즉, interior mutability때문에 넣은 건 아닙니다.)
  * 이 방법이 `Pin`을 제일 안전하게 사용하는 방법 같습니다. (`Kernel`이 `BcacheInner`만 노출시키지 않으면 내부 struct들을 safe하게 move할 방법이 없습니다.) 또, 이러면 *lock들이 내부 data가 `Unpin`인지를 신경쓸 필요가 없습니다.
  * 그러나, `Kernel`의 field를 두개로 나누어야되고, `Bcache`는 `BcacheInner`를 만든 후에만 initialize할 수 있으므로 const fn안에서 할 수 없습니다. 그래서 `MaybeUninit<Bcache>`이 필요합니다. 이 부분은 디자인이 조금 별로인 것 같습니다.

@Medowhill 혹시 어떻게 생각하시는지 말씀해주실 수 있으신가요?

2021-02-04 04:41 UTC, travis1829 commented on kernel-rs/src/arena.rs
반영했습니다!

2021-02-04 04:41 UTC, travis1829 commented on kernel-rs/src/kernel.rs
> +            // Safe since the only way to access `bcache` is through `kernel()`, which is an immutable reference.
반영하였습니다!

2021-02-04 05:24 UTC, Medowhill commented
정리해 보면 2가지 방법이 있는 것이 맞나요?

1. `Spinlock<Pin<&mut MruArena>>` 사용
현재 구현입니다. 이 경우 `MruArena`를 커널에 넣되 처음에 pin한 후에는 직접 접근하지 않습니다. Pin해서 만들어진 `Pin<&mut MruArena>`를 `Spinlock`에 넣으면 `Spinlock`의 구현에는 수정이 필요 없고, lock을 걸면 `Pin<&mut MruArena>`가 나오니 이를 사용하면 됩니다. 이 방법을 사용하면 2번처럼 커널 전체를 pin할 필요는 없고, 커널에서 pin해야 하는 부분만 별도의 필드로 선언하고 pin한 뒤에 사용하지 않으면 됩니다. 만약 이 방법을 선택한다면 `Kernel`에서 pin되어야 하는 부분은 따로 빼서 `PinnedKernel` 같은 것을 만드는 것은 어떨까 하는 생각도 듭니다.

2. `Pin<&mut Spinlock<MruArena>>` 사용
커널 전체를 pin합니다. 그러면 커널 안에 있는 `Spinlock<T>`는 `Pin<&mut Spinlock<T>>` 형태로 접근 가능합니다. `Spinlock`의 구현을 수정하여 `Pin<&mut Spinlock<T>>`의 lock을 걸면 `Pin<&mut T>`가 나오게 만들고 이를 사용합니다. 이 경우에는 1번처럼 필드를 분리해서 정의할 필요가 없습니다.

2가 좀 더 좋지 않을까 하는데, 2를 해보고 나면 그 쪽이 더 복잡해서 1이 나아 보일 수도 있을 것 같습니다. 둘 다 해 보고 결정하는 것이 좋아 보이지만, 지금 PR에서는 1로 해 두고 이후에 2를 시도해 본 뒤 괜찮으면 merge하고 별로면 그대로 두는 식으로 하는 것이 어떨까요?

2021-02-04 05:30 UTC, Medowhill requested changes

2021-02-04 05:30 UTC, Medowhill commented on kernel-rs/src/kernel.rs
> +    pub fn get_bcache(&self) -> &Bcache {
Safety condition이 붙는 메서드라면 unsafe로 정의하는 게 더 나을 것 같습니다.

2021-02-04 05:30 UTC, Medowhill commented on kernel-rs/src/kernel.rs
> +    _bcache_inner: UnsafeCell<BcacheInner>, // Never access this after initialization.
이 경우에 `UnsafeCell`을 사용하는 것이 좋은지 잘 모르겠습니다. `UnsafeCell`은 interior mutability를 나타내기 위해 사용되는 것인데, 이를 초기화 이후에 접근하면 안 된다는 것을 나타내는 용도로 사용하는 것이 자연스러워 보이지는 않습니다. 혹시 그런 용도로 사용하는 경우가 기존에 있었나요(rv6에서든 다른 Rust 프로젝트에서든)? 굳이 `UnsafeCell`을 사용하지 않더라도 어차피 `&Kernel`로 접근할 때는 `Kernel` 자체가 move되지 않는다는 가정하에서 `_bache_inner`가 move될 수 없을 텐데, `UnsafeCell`을 넣을 필요가 있는지도 잘 모르겠습니다.

2021-02-04 05:31 UTC, travis1829 commented
https://github.com/kaist-cp/rv6/pull/394#issuecomment-773023299
제가 위 comment에 EDIT2를 추가하느라 서로 약간 엇갈린 것 같은데, 제 의견은 @Medowhill 님과 비슷합니다.
* **1. Spinlock<Pin<&mut MruArena>> 사용**은 caller입장에서 신경써야되는 부분이 너무 많습니다. 지금은 `Bcache`에서만 이 방법을 쓰긴 하지만, 다른 곳에서도 똑같은 이런식으로 `T`는 안전하게 어딘가에 저장한 후 `Pin<&mut T>`만을 노출시키는 방법을 계속 사용해야됩니다.
* 적어도, `Bcache`에 대해서는 굳이 이렇게 할 필요가 없고, 오히려 약간 비직관적인 것 같습니다.
* 다만, 이거는 `Spinlock`이 알아서 `T: Unpin`과 `T: !Unpin`을 구별해주는 덕분에 이렇게 해도 되는 것 뿐이므로, `T`가 *lock으로 보호받지 못하는 type들에 대해서는 결국 https://github.com/kaist-cp/rv6/pull/394#issuecomment-773023299 에서 한 것과 비슷한 방법을 써야할 것 같습니다.

2021-02-04 05:35 UTC, travis1829 commented on kernel-rs/src/kernel.rs
> +    _bcache_inner: UnsafeCell<BcacheInner>, // Never access this after initialization.
> BcacheInner를 다시는 access하면 안 되는 것을 나타내기 위해 UnsafeCell안에 넣었습니다. (즉, interior mutability때문에 넣은 건 아닙니다.)

사실 저도 이게 별로 좋은 방법은 아닌 것 같습니다. 차라리 이런 경우만을 위해서 `OnceCell`같은 새로운 type을 만드는게 나을 것 같습니다.

2021-02-04 05:38 UTC, Medowhill commented on kernel-rs/src/kernel.rs
> +    _bcache_inner: UnsafeCell<BcacheInner>, // Never access this after initialization.
네. 타입으로 표현해야 한다면 새로운 타입을 만드는 것이 좋다고 생각합니다.

2021-02-04 05:43 UTC, travis1829 commented
> Spinlock의 구현을 수정하여 Pin<&mut Spinlock<T>>의 lock을 걸면 Pin<&mut T>가 나오게 만들고 이를 사용합니다.

조금 첨언을 하자면, 어차피 `Pin<&mut Spinlock<T>>`으로부터 `&Spinlock<T>`를 얻는 것은 legal하므로, 결국에는 `T: Unpin`인지 아닌지를 구분하는 방법으로 해야 합니다.

2021-02-04 07:22 UTC, travis1829 commented
* `PinnedKernel`을 추가해봤습니다.
* 제 생각에는 @Medowhill 께서 제안하신 `PinnedKernel`이 매우 좋은 방법 같습니다. `Pin<&mut T>`을 가장 이상적으로 쓰는 방법이 `T` 자체는 heap과 같이 외부에서 접근할 방법이 전혀 없는 안전한 곳에 저장하는 것인데, 여기서 `PinnedKernel` type의 static 변수를 만들어서 heap처럼 쓰면 이를 모방할 수 있습니다.
* 다만, 굳이 단점을 찾자면 이러면 `Kernel`의 field를 별도의 static한 변수에 저장하는 것이므로, `Kernel` 내부에서의 spatial locality가 아주 조금 안 좋아질 수도 있을 것 같습니다.

2021-02-04 08:16 UTC, Medowhill requested changes

2021-02-04 08:16 UTC, Medowhill commented on kernel-rs/src/kernel.rs
> +            KERNEL.bcache = MaybeUninit::new(Spinlock::new(
사소하긴 한데

```rust
KERNEL.bacache.write(Spinlock::new(...)).get_mut().as_mut().init()
```

로 하면 `assume_init_mut`을 한 번 줄일 수 있어서 조금 더 깔끔할 것 같습니다.

2021-02-04 08:26 UTC, travis1829 commented on kernel-rs/src/kernel.rs
> +            KERNEL.bcache = MaybeUninit::new(Spinlock::new(
반영하였습니다!

2021-02-04 08:27 UTC, Medowhill approved these changes
수고하셨습니다~

2021-02-04 08:29 UTC, travis1829 commented
감사합니다!
참고로 지금 아직 리뷰반영이 안 된 부분에 대해 말씀드리자면,
> Lock trait을 추가하는 것도 좋아 보입니다.
* *lock들을 trait로 정리하는 거는 바꿔야 하는 코드 양이 꽤 있는 것 같아 새로운 PR에서 하는게 좋을 것 같고
> 이 PR에서 되어야하지 않을까 생각합니다.
* `Proc`을 `Pin`하는 건 #385 가 끝난 후 하는 게 좋을 것 같습니다.

2021-02-04 11:53 UTC, jeehoonkang commented
- 이번주에 제가 review capacity가 안나올 것 같아서, 일단 한동안은 @Medowhill 님만 승인해주시면 머지하겠습니다.
- lock trait같이 반영 안된건 issue로 만들어주세요 @travis1829 

bors r+

2021-02-04 11:59 UTC, merged