[Closes #346, #363] Atomicpid, proc id type, state in procguard
kaist-cp/rv6 pull request #401
Opened 2021-02-05 07:12 UTC by anemoneflower

- closes #346 , closes #363 

주요 변경점입니다.
- prod id type인 `Pid`를 만들었습니다.
- `ProcInfo`에 있던 `pid`를 `AtomicI32`로 바꾸고 `Proc`으로 옮겼습니다.
- `Proc`에서 unsafe하게 정의되어 있던 `state()`함수를 `ProcGuard`로 옮겼습니다.
  - `ProcGuard`없이 `state`에 접근하지 않습니다.

2021-02-05 07:14 UTC, anemoneflower commented on kernel-rs/src/proc.rs
> +pub type Pid = i32;
`PID`가 더 좋을까요?

2021-02-05 07:17 UTC, coolofficials requested changes

2021-02-05 07:17 UTC, coolofficials commented on kernel-rs/src/proc.rs
> +pub type Pid = i32;
public으로 하신 이유가 있나요?
Global Pid가 proc.rs 말고 다른 모듈에서도 사용되나요? (몰라서 여쭤보는겁니다)

2021-02-05 07:29 UTC, coolofficials reviewed
https://github.com/kaist-cp/rv6/blob/9d0b25a83561f04e0d06b85a465b1080d99f154a/kernel-rs/src/proc.rs#L658
의 return type도 Pid가 되어야 할 것 같습니다.

https://github.com/kaist-cp/rv6/blob/9d0b25a83561f04e0d06b85a465b1080d99f154a/kernel-rs/src/proc.rs#L671
처럼 procinfo의 pid를 업데이트 해주기 때문에...

2021-02-05 07:55 UTC, coolofficials approved these changes
LGTM

2021-02-05 08:14 UTC, Medowhill commented on kernel-rs/src/proc.rs
> +            let guard = p.lock();
`dump`의 주석을 보면 디버깅을 위해 사용할 수 있도록 lock을 걸지 않는 것이 이 메서드의 원래 의도인 것 같습니다. 아마 lock이 걸려 있든 말든 그냥 읽은 다음에 지금 상태 그대로 출력하는 것이 원하는 동작인 것 같은데, 그냥 메서드 자체를 unsafe로 두는 게 나을 수도 있을 것 같습니다. ^P를 입력하지 않는 한 호출될 일도 없으니까요.

2021-02-05 08:14 UTC, Medowhill commented on kernel-rs/src/proc.rs
> +type Pid = i32;
`Pid` 타입을 정의해야 한다는 이야기가 나온 맥락을 정확히 모르겠는데, 이 타입을 추가하면 좋은 점이 무엇인가요?

2021-02-05 08:14 UTC, Medowhill commented on kernel-rs/src/proc.rs
> +    pid: AtomicI32,
지금 보니 `pid`에 접근하는 많은 경우에 이미 lock이 걸려 있거나 `CurrentProc`을 가지고 있는데, 굳이 atomic으로 할 필요가 있을까 고민이 됩니다. `pid`를 수정하는 곳이 `alloc`이랑 `clear`뿐이니 `CurrentProc`이 존재하는 동안은 `pid`에 쓰기가 일어나지 않을 것 같은데, `pid`를 원래대로 `ProcInfo`에 넣어 두고 `CurrentProc`의 메서드로 `pid`를 읽을 수 있게 하는 것은 어떨까요? 그렇게 바꾸면 `dump`만 문제가 될 것 같은데 `dump`는 그 의도 자체가 unsafe한 메서드인 것 같아서 `dump`는 신경쓰지 않아도 되는 것 같습니다.

2021-02-05 08:16 UTC, Medowhill commented on kernel-rs/src/proc.rs
> +    pid: AtomicI32,
덧붙이자면, xv6에서 `pid`에 접근할 때 특정 경우에 lock을 걸지 않는 이유도 위와 같은 reasoning 때문이 아닌가 싶습니다.

2021-02-05 09:05 UTC, coolofficials commented on kernel-rs/src/proc.rs
> +    pid: AtomicI32,
@Medowhill 굳이 atomic으로 할 필요가 있을까 고민이 된다고 하셨는데, 현재 PR의 수정이 있을 때의 단점은 어떤 것이 있나요? (xv6의 구현과 달라진다는 점 외에)

2021-02-05 09:09 UTC, coolofficials requested changes

2021-02-05 09:09 UTC, coolofficials commented on kernel-rs/src/proc.rs
> +            let guard = p.lock();
@Medowhill @anemoneflower 재민님 말씀이 맞습니다. dump는 lock과 상관 없이 동작해야 해서 `get_mut_unchecked`로 읽는 현재의 구현이 좋을 것 같습니다. #297 
메소드 자체를 unsafe로 두라는 말씀은 현재 `dump` 함수에 `unsafe` 마킹이 없는데 추가하는 수정도 필요하다는 말씀이시죠?

2021-02-06 16:00 UTC, Medowhill commented on kernel-rs/src/proc.rs
> +            let guard = p.lock();
네. `dump`를 `unsafe` 메서드로 만들자는 뜻이었습니다.

2021-02-06 16:10 UTC, Medowhill commented on kernel-rs/src/proc.rs
> +    pid: AtomicI32,
`pid`를 위해 atomic을 사용하는 것이 자연스러운 방법인지 잘 모르겠습니다. Atomic을 사용함으로써 lock이 사라져야 할 것 같은데 이 경우에는 그렇지 않아서요. xv6에서 lock을 사용하던 것을 atomic으로 바꾼 `killed`나 `nextpid` 같은 경우에는 접근할 때 lock이 필요 없어졌기에 잘 된 refactoring이라 생각합니다. 그러나 `pid`는 원래 lock을 걸고 접근하던 상황에, 이 PR에서도 여전히 lock을 걸고 접근하고 있습니다. 또한 원래 lock을 안 걸고 접근하던 상황은, 실제로 lock을 걸지 않아도 안전한 상황이기 때문에 굳이 atomic일 필요가 없습니다. 따라서 atomic을 추가함으로써 딱히 해결된 점이 있는 것이 아니므로 굳이 atomic을 사용하지 않아도 될 것 같습니다.

제 생각에는 `CurrentProc`이 존재하는 동안은 `pid`가 수정될 일이 없음을 명확히 주석으로 기술한 뒤, `CurrentProc`의 메서드로 `pid`에 lock을 걸지 않고 접근하는 (내부에서는 unsafe를 사용하지만) safe한 메서드를 추가하는 것이 xv6의 의도도 유지하고 더 자연스러운 해결책인 것 같습니다.

2021-02-06 16:24 UTC, Medowhill commented on kernel-rs/src/trap.rs
> +            if proc.lock().state() == Procstate::RUNNING {
여기서 `state`에 접근할 때 lock을 걸지 않던 것은 xv6의 버그일까요? 아니면 lock을 걸 필요가 없는 이유가 있는 것일까요?

2021-02-08 03:41 UTC, anemoneflower reviewed
리뷰 반영했습니다 :)
- `pid`를 `ProcInfo`에 그대로 유지
- `dump`를 unsafe하게 수정

2021-02-08 03:41 UTC, anemoneflower commented on kernel-rs/src/proc.rs
> +type Pid = i32;
https://github.com/kaist-cp/rv6/pull/333#discussion_r559951662

리턴되는 값이 `pid`임을 코드에 명확하게 드러내기 위해서라고 이해했습니다..!

2021-02-08 03:41 UTC, anemoneflower commented on kernel-rs/src/trap.rs
> +            if proc.lock().state() == Procstate::RUNNING {
`procdump`와 `kerneltrap`을 제외하고는 다 lock을 걸고 `state`에 접근하는데, `state`를 읽고, `proc`의 값을 수정하는 작업이 lock을 걸고 있는 동안 진행됩니다.

`kerneltrap()`의 경우에는 `yield`에서 lock을 걸기 때문에 `state`를 읽을 때는 lock없이 읽은 것 같습니다. `RUNNING`상태를 바꾸는 곳이 `yield`이고, `yield`에서 `sched`가 실행되면 context switch가 일어나기 때문에 lock을 걸지 않은 것이 아닐까요?

다시 생각해보니
1. 기존 코드처럼 unsafe하게 `state`를 읽거나
2. `proc_yield`를 `ProcGuard`의 함수로 만드는 것이 좋을 것 같습니다.

@Medowhill

2021-02-08 13:36 UTC, Medowhill requested changes

2021-02-08 13:36 UTC, Medowhill commented on kernel-rs/src/trap.rs
> +            if proc.lock().state() == Procstate::RUNNING {
제 생각에는 1을 선택하고 이 unsafe가 안전한 이유를 주석으로 설명하는 것이 좋은 것 같습니다. `proc_yield`는 현재 실행 중인 프로세스만 할 수 있는 일이니 지금처럼 `CurrentProc`의 메서드로 두는 것이 더 나아 보여서요.

2021-02-09 02:46 UTC, anemoneflower reviewed
코멘트 반영했습니다. :)

- `kerneltrap()` 에서 ProcInfo와 state에 접근해야 하기 때문에 관련된 field를 public으로 변경했습니다.

2021-02-09 03:33 UTC, Medowhill approved these changes

2021-02-09 03:34 UTC, Medowhill commented
bors r+

2021-02-09 03:40 UTC, merged