[Closes #402] Use `WeakPin<*mut T>` to reduce unsafe
kaist-cp/rv6 pull request #403
Opened 2021-02-06 14:12 UTC by travis1829

* `WeakPin<*mut T>`라는 실험적인 type을 만들어봤습니다.
  * `*mut T`와 많이 비슷하지만, `*mut T`보다 더 safe하게 사용할 수 있습니다.
  * `Pin<&mut T>`와 비슷하게 제한적인 API만을 사용해 `T`를 mutate할 수 있지만, `Pin<&mut T>`보다도 사용할 수 있는 API가 더 제한적입니다.
  * 더 자세한 내용은 https://docs.google.com/document/d/1CmlScyuRpprcw7bLL4GGdsPCGq_SfiUsGimFhKAjv0s/edit# 을 참고하면 좋을 것 같습니다.
    * 오류나 지적사항을 적극적으로 말씀해주시면 감사하겠습니다. 또, 가독성이 너무 안좋으면 말씀해주세요.
* `WeakPin<*mut T>`를 이용해서 list.rs에 있던 상당수의 unsafe부분을 제거했습니다.
  * 비슷한걸 `&T`나 `Pin<&mut T>`로 하려면 lifetime 표시 문제때문에 힘든 것 같습니다. (현재 rv6의 arena가 `'static` lifetime을 가지고 있긴 하지만, 이건 arena의 특수성때문에 그런 것이고, 일반적으로 intrusive linked list은 `ListEntry`의 lifetime을 compile time에 표현할 수 없습니다.)
  * 다만, `WeakPin<*mut T>`는 intrusive linked list보다는 `Proc::parent` field를 다룰 때 더 유용하게 사용할 수 있을 것 같습니다. (애초에, 과거의 `ListEntry`가 `*mut ListEntry`를 외부로 노출시키지 않았던 것처럼, 지금의 `ListEntry`도 `WeakPin<*mut T>`를 외부로 노출시키지 않습니다.)

2021-02-06 15:58 UTC, Medowhill requested changes
아직 자세히 보지는 못해서 코멘트는 하나만 남겼습니다. 추후에 의견 더 있으면 코멘트 추가하겠습니다.

2021-02-06 15:58 UTC, Medowhill commented on kernel-rs/src/pincell.rs
> +            ptr: pin.as_ref().get_ref() as *const _ as *mut _,
제가 알기로는 `&T`로부터 만들어진 `*mut T`에 쓰거나 해당 포인터를 `&mut T`로 변환하면 UB입니다. 따라서 `from_pin` 자체로는 UB를 발생시키지 않지만 `get_unchecked_pin_mut`이나 `get_unchecked_mut`이 호출되기만 해도 UB입니다. `WeakPin<*mut T>`의 목적이 제한된 형태로나마 데이터의 수정을 허용하는 것이라면 `Pin<&T>`로부터 만들어져서는 안 될 것 같습니다.

2021-02-06 17:36 UTC, travis1829 commented on kernel-rs/src/pincell.rs
> +            ptr: pin.as_ref().get_ref() as *const _ as *mut _,
사실 저도 이걸 고민하다가 `&mut T`에 `&T`로 바꾸긴 했었는데, 그냥 말씀해주신 내용을 반영한 후 `WeakPin<*const T>`를 추가해서 `Pin<&T>` <-> `WeakPin<*const T>`로 대응시켜야할 것 같습니다.

2021-02-08 13:14 UTC, travis1829 commented
* `&ListEntry`로부터 `&mut MruEntry<T>`를 얻던 부분을 변경하였습니다. 이제는 `MruEntry::from_list_entry()`를 이용하여 `&mut ListEntry`로부터 `&mut MruEntry<T>`를 얻습니다.
* 추가로 `WeakPin::get_unchecked_mut()`를 없앴습니다.
  * `T: !Unpin`에 대해서 `&mut T`를 얻을 수 있는 건 매우 위험하기 때문에, unsafe하게 `Pin::get_unchecked_mut()`나 `WeakPin::get_unchecked_mut()`를 사용하는 것, 또는 `*mut T`를 deref하는 것은 지양해야 합니다. 어차피 pin_project를 사용하면 `Pin<&mut T>`만을 가지고서도 `T`를 safe하게 mutate할 수 있습니다.
  * 마찬가지로, `*mut T` 대신 `WeakPin<*mut T>`를 사용하는게 더 안전할 것 같습니다.

2021-02-15 06:06 UTC, travis1829 commented
`Proc`, `ProcessSystem`에도 `WeakPin`을 적용해봤습니다.
https://docs.google.com/document/d/1CmlScyuRpprcw7bLL4GGdsPCGq_SfiUsGimFhKAjv0s/edit# 의 Section 4.1내용을 반영했습니다.

2021-02-16 09:40 UTC, Medowhill requested changes
`pincell.rs`만 보고 드리는 코멘트입니다.

2021-02-16 09:40 UTC, Medowhill commented on kernel-rs/src/pincell.rs
> +            ptr: pin.as_ref().get_ref() as *const _ as *mut _,
`.get_unchecked_mut()`을 사용해야 할 것 같습니다.

2021-02-16 09:40 UTC, Medowhill commented on kernel-rs/src/pincell.rs
> +    pub fn get_ref(&self) -> &T {
`get_ref`나 `deref`를 사용하면 `Pin<&mut T>`로부터 lifetime이 연관되어 있지 않은 `&T`를 만들 수 있어, `&mut T`가 해당 데이터를 유일하게 가리킨다는 stacked borrow의 가정을 깰 수 있어 보입니다. 예를 들면, 아래 코드는 `p`의 lifetime이 `q`의 lifetime과 겹치기 때문에 타입 검사를 통과하지 못해야 하지만, `WeakPin`을 거치는 과정에서 lifetime이 보존되지 않아 타입 검사를 통과합니다. 만약 둘째 줄이 `WeakPin`을 사용하지 않도록 주석처럼 고치면 올바르게 타입 오류가 발생합니다.

```rust
let mut x = 0;
let p = WeakPin::from_pin_mut(Pin::new(&mut x)); // let p = Pin::new(&mut x);
let p: &u32 = &p;
let q = Pin::new(&mut x);
let q: &mut u32 = q.get_mut();

println!("{}", *p);
*q = 1;
println!("{}", *p);
```

같은 맥락으로, `WeakPin<*const T>`의 `get_ref`와 `deref`도 문제가 있어 보입니다.

2021-02-16 09:40 UTC, Medowhill commented on kernel-rs/src/pincell.rs
> +            ptr: &self.data as *const _ as *mut _,
Immutable reference로부터 mutable raw pointer를 만들어 거기에 값을 써서는 안 됩니다.

2021-02-25 01:21 UTC, closed without merging