[Closes #404] Remove `PinnedKernel`
kaist-cp/rv6 pull request #405
Opened 2021-02-07 15:58 UTC by travis1829

Closes #404 
* `PinnedKernel`와 관련된 변화들을 revert했습니다.
* `Kernel::bcache`를 private field로 바꾼 후 unsafe 함수인 `Kernel::get_bcache()`를 추가했습니다.

2021-02-07 16:23 UTC, jeehoonkang requested changes

2021-02-07 16:23 UTC, jeehoonkang commented on kernel-rs/src/kernel.rs
> -/// If the `Cpu` executing the code has a non-null `Proc` pointer,
이건 지우면 안될듯 합니다

2021-02-07 16:23 UTC, jeehoonkang commented on kernel-rs/src/kernel.rs
> +    bcache: Bcache,
얘가 pin되어있어야 하는 아이디어가 여기 표현되어야 할거같은데, PinnedKernel에서 했던 것처럼 이 아이디어를 표현할 수 있을까요? 그렇게 되면 다른 곳은 어떻게 바뀌어야 하나요?

2021-02-07 16:59 UTC, travis1829 commented on kernel-rs/src/kernel.rs
> +    bcache: Bcache,
> 얘가 pin되어있어야 하는 아이디어가 여기 표현되어야 할거같은데, PinnedKernel에서 했던 것처럼 이 아이디어를 표현할 수 있을까요?

* `Kernel` struct를 `#[pin_project]`로 표시하고 `bcache`를 `#[pin]`으로 표시해야합니다. 이러면 `Kernel::bcache`를 접근할때는 `Pin<&mut Bcache>`로만 접근할 수 있게 됩니다.

> 그렇게 되면 다른 곳은 어떻게 바뀌어야 하나요?

* 이제는 `Kernel`이 `!Unpin`이므로, `Kernel`을 mutable하게 access하고 싶을 때는 `&mut Kernel`이 아니라 항상 `Pin<&mut Kernel>`의 형태로만 해야 합니다. 현재 `&mut Kernel`를 사용하는 곳이 `kernel_main()`뿐이므로, 이 부분을 바꿔야 합니다.
  * 다만, static 변수인 `KERNEL`이 같은 소스파일인 kernel.rs에 정의되어 있으므로, 지금은 `&mut Kernel`을 얻는 걸 원천적으로 차단할 수는 없고 프로그래머가 알아서 조심해야합니다. 변수 `KERNEL`을 별도의 소스파일에 정의한 후 이외의 소스파일들에서는 `Pin<&mut Kernel>`만 얻을 수 있도록 바꾸면 이걸 원천적으로 차단할 수 있습니다.

2021-02-07 16:59 UTC, travis1829 commented on kernel-rs/src/kernel.rs
> -/// If the `Cpu` executing the code has a non-null `Proc` pointer,
죄송합니다, 제가 실수했습니다. 적절히 편집한 후 복원시키겠습니다.

2021-02-08 03:13 UTC, travis1829 commented
* `Kernel`을 `Pin`시킨후, `kernel_main()`에서 pin projection을 사용하도록 변경했습니다.
-----
다만, 디자인 관련해서 아직 해결하지 않은 사항이 있습니다.
* 현재 `kernel_get_unchecked_pin()`을 여러번 부르면 `Pin<&mut Kernel>`을 여러개 얻을 수 있습니다. 그리고, 실제로 `kernel_main()`에서 어쩔 수 없이 그렇게 합니다.
* kernel_map()이라는 함수를 만든 후 이게 closure를 받게하면, 동일 thread 내에서는 `Pin<&mut Kernel>`이 하나만 존재하게 할 수는 있지만, 여러 thread가 동시에 부르는 걸 막지는 못합니다.
* 위와 같은 이유로 `kernel_get_unchecked_pin()`이 어쨌든 unsafe fn이므로, 아래의 내용을 적용하지는 않았습니다. 물론, 아래의 내용을 적용하게 되면 `kernel_get_unchecked_pin()`이 unsafe인 이유가 축소되게 되므로, code가 조금 더 safe해지긴 합니다.
> 변수 KERNEL을 별도의 소스파일에 정의한 후 이외의 소스파일들에서는 Pin<&mut Kernel>만 얻을 수 있도록 바꾸면 이걸 원천적으로 차단할 수 있습니다.

2021-02-08 03:29 UTC, jeehoonkang reviewed
잘 만들어주셔서 감사합니다. 몇개 사소한거만 해주시면 머지하겠습니다!

2021-02-08 03:29 UTC, jeehoonkang commented on kernel-rs/src/kernel.rs
> +unsafe fn kernel_get_unchecked_pin() -> Pin<&'static mut Kernel> {
inline

2021-02-08 03:29 UTC, jeehoonkang commented on kernel-rs/src/kernel.rs
> +/// The caller should make sure not to call this function multiple times.
newline above

2021-02-08 03:29 UTC, jeehoonkang commented on kernel-rs/src/kernel.rs
> +    let kernel = unsafe { kernel_get_unchecked_pin() }.project();
- 함수 이름을 `kernel_unchecked_pin`으로 하는게 어떨지 제안드립니다.
- 이거 저장 안하고 필요할때마다 함수 불러서 쓰는게 어떨까요?  굳이 저장하면 말씀하신 것처럼 여러개 생기는 문제가 있을지도 모르겠어서요

2021-02-08 03:29 UTC, jeehoonkang commented on kernel-rs/src/list.rs
> +    #[pin]
굳이 필요한가요?

2021-02-08 03:44 UTC, travis1829 commented on kernel-rs/src/kernel.rs
> +    let kernel = unsafe { kernel_get_unchecked_pin() }.project();
> 이거 저장 안하고 필요할때마다 함수 불러서 쓰는게 어떨까요? 굳이 저장하면 말씀하신 것처럼 여러개 생기는 문제가 있을지도 모르겠어서요

그렇다면 그렇게 바꿔보도록 하겠습니다!

다만, 제가 detail을 말씀드리지 않은 것 같은데, `kernel_main()`에서 `Pin<&mut Kernel>`이 두개가 필요한 이유는 `'static` borrow때문에 그런 것 같습니다.
https://github.com/kaist-cp/rv6/blob/4b1baac0567d99ad08c7fb23743b7a33810e3698/kernel-rs/src/kernel.rs#L226
여기서 `kernel.procs`를 `Pin<&'static mut ProcessSystem>`으로 borrow하게 되는데, (∵ `&'static ProcessSystem`으로부터 `&'static RawSpinlock`을 얻어야합니다.)
https://github.com/kaist-cp/rv6/blob/4b1baac0567d99ad08c7fb23743b7a33810e3698/kernel-rs/src/kernel.rs#L248
여기서 또 `kernel.procs`를 `Pin<&mut ProcessSystem>`으로 borrow해야 해서 그렇습니다.

결국, `kernel_main()`이 완료된 후에는 사실상 `&'static ProcessSystem` 하나만 남게 되지만, `kernel_main()`을 실행하던 도중에는 잠깐동안 `&'static ProcessSystem`과 `Pin<&mut ProcessSystem>`이 공존하게 되는 것 같습니다.

2021-02-08 03:44 UTC, travis1829 commented on kernel-rs/src/list.rs
> +    #[pin]
`#[pin_project]`이 `#[pin]`이 붙지 않은 field를 전부 `Unpin`으로 가정하므로 붙여야 합니다.

또는, `ListEntry`를 아래와 같이 바꿔도 되긴 하는데, 제 생각에는 지금 방법이 `ListEntry`가 `!Unpin`이라는 점을 더 잘 보여준다고 생각해서 이렇게 했습니다.
```Rust
#[pin_project(!Unpin, PinnedDrop)]
pub struct ListEntry {
    next: *mut ListEntry,
    prev: *mut ListEntry,
}
```

2021-02-08 04:03 UTC, travis1829 commented on kernel-rs/src/list.rs
> +    #[pin]
`Pin<&mut Kernel>`이 필요할때마다 `kernel_unchecked_pin()`을 부르도록 바꿨습니다.
* 참고로, 아쉽게도 `kernel_unchecked_pin().project()`을 하나로 합칠 수는 없습니다. `kernel_unchecked_pin().project()`의 return type이 `__KernelProjection<'_>`인데, 이게 pin_project이 macro로 정의하는 type이라서 그렇습니다.
* 이렇게 하고나니, code가 약간 길어지고 unsafe가 조금 늘어나지만, 어차피 `kernel_main()`에서는 `kernel_unchecked_pin()`을 여러번 불러야 하니 이렇게 하는것도 괜찮을 것 같습니다.

2021-02-08 04:04 UTC, travis1829 commented
`Pin<&mut Kernel>`이 필요할때마다 `kernel_unchecked_pin()`을 부르도록 바꿨습니다.
* 참고로, 아쉽게도 `kernel_unchecked_pin().project()`을 하나로 합칠 수는 없습니다. `kernel_unchecked_pin().project()`의 return type이 `__KernelProjection<'_>`인데, 이게 pin_project이 macro로 정의하는 type이라서 그렇습니다.
* 이렇게 하고나니, code가 약간 길어지고 unsafe가 조금 늘어나지만, 어차피 `kernel_main()`에서는 `kernel_unchecked_pin()`을 여러번 불러야 하니 이렇게 하는것도 괜찮을 것 같습니다.

2021-02-08 07:03 UTC, jeehoonkang approved these changes
bors r+

2021-02-08 07:04 UTC, jeehoonkang commented on kernel-rs/src/kernel.rs
> +    let kernel = unsafe { kernel_get_unchecked_pin() }.project();
@travis1829 이거는 issue로 만들어줄래요?

2021-02-08 07:09 UTC, merged