[Closes #398] use &mut CurrentProc, deref_data from CurrentProc
kaist-cp/rv6 pull request #407
Opened 2021-02-08 03:58 UTC by anemoneflower

- closes #398 

sync-up에서 논의했던 대로 `CurrentProc`을 사용하면, 관련 함수에 `CurrentProc`을 전달할때 move되는 문제가 있기 때문에 `deref_mut_data`를 사용하는 곳에 `&mut CurrentProc`을 전달했습니다.
- 기존에 `Proc`에 있던 `deref_mut_data`를 `CurrentProc`의 함수로 이동
- `ProcGuard`에 `deref_mut_data`함수 추가

2021-02-08 07:02 UTC, jeehoonkang requested changes

2021-02-08 07:02 UTC, jeehoonkang commented on kernel-rs/src/proc.rs
> +    #[allow(clippy::mut_from_ref)]
이건 없어져야하지 않나요? data가 current proc꺼면 proc guard에서는 접근 가능하면 안될 것 같습니다.

2021-02-08 07:02 UTC, jeehoonkang commented on kernel-rs/src/proc.rs
> +    pub fn deref_data_raw(&mut self) -> *mut ProcData {
raw 함수가 굳이 있어야 하나요?

2021-02-08 09:04 UTC, anemoneflower commented on kernel-rs/src/proc.rs
> +    #[allow(clippy::mut_from_ref)]
`ProcGuard`를 가지고 있을 때는 exclusive한 접근이 보장되기 때문에 guard를 통해 data에 접근할 수 있다고 생각합니다.
- Safety comment를 수정했습니다.

2021-02-08 13:42 UTC, jeehoonkang requested changes

2021-02-08 13:42 UTC, jeehoonkang commented on kernel-rs/src/proc.rs
> +    #[allow(clippy::mut_from_ref)]
current proc에서 (lock을 잡지 않아도) &mut data를 얻을 수 있으므로 여기서 또 &mut data를 얻을 수 있으면 안됩니다.

2021-02-08 13:42 UTC, jeehoonkang commented on kernel-rs/src/proc.rs
> +    pub fn deref_data_raw(&mut self) -> *mut ProcData {
deref_mut_data를 넣으면 왜 안되나요?

2021-02-09 02:29 UTC, anemoneflower commented on kernel-rs/src/proc.rs
> +    pub fn deref_data_raw(&mut self) -> *mut ProcData {
```
explicit lifetime required in the type of `proc`
lifetime `'static` required
```
reference를 사용하면 return되는 `RcFile`에 static lifetime이 붙어있어서, `CurrentProc`에도 static lifetime이 붙어야 한다는 에러가 뜹니다.
```
unsafe fn argfd(
    n: usize,
    proc: &mut CurrentProc<'_>,
) -> Result<(i32, &'static RcFile<'static>), ()> {
```

2021-02-09 02:33 UTC, anemoneflower commented on kernel-rs/src/proc.rs
> +    #[allow(clippy::mut_from_ref)]
`ProcGuard`의 함수들 중에 `ProcData`를 사용하는 함수들이 있습니다. (`sched`, `clear`, `alloc`등). 원래 의도대로는 `ProcData`는 current process에 private하기 때문에  lock을 잡지 않아도 사용할 수 있는데, `ProcGuard`에서 사용하는 것도 안전함을 어떻게 표현하는 것이 좋을까요?

2021-02-09 03:21 UTC, anemoneflower commented on kernel-rs/src/proc.rs
> +    #[allow(clippy::mut_from_ref)]
`// TODO(#407)` 로 `ProcGuard`에서 `deref_mut_data`가 사용되는 부분의 safety를 적어 두었습니다.

2021-02-09 03:45 UTC, Medowhill commented on kernel-rs/src/proc.rs
> +    pub fn deref_data_raw(&mut self) -> *mut ProcData {
`argfd`가 `&'static RcFile`을 반환하는 것부터 문제가 있는 것 같습니다. 이 PR에서는 `deref_data_raw`를 그대로 두고, `argfd` 리팩토링과 `deref_data_raw`를 없애는 것은 추후에 별도로 진행하면 어떨까요?

2021-02-09 09:16 UTC, Medowhill commented on kernel-rs/src/proc.rs
> +    #[allow(clippy::mut_from_ref)]
이 PR은 이 정도로 하고 별도 이슈로 해결해도 될 것 같습니다.

2021-02-15 06:10 UTC, Medowhill commented on kernel-rs/src/proc.rs
> +    pub fn deref_data_raw(&mut self) -> *mut ProcData {
#415

2021-02-15 06:40 UTC, Medowhill commented
bors r+

2021-02-15 06:46 UTC, merged