[Closes #408] Add `ProcessSystem::init_proc_parent()`.
kaist-cp/rv6 pull request #409
Opened 2021-02-08 09:06 UTC by travis1829

Closes #408
* `ProcessSystem`을 initialize하는 함수를 2개에서 3개로 늘렸습니다. 이유는 #408 과 같습니다.
* 이러면 `Pin<&'static mut ProcessSystem>`은 제일 마지막 함수에서만 필요하므로 mutable reference가 복수개 존재하는 문제는 생기지 않습니다. (이를 나타내기 위해, 일부러 `kernel`이라는 지역변수를 추가했습니다.)
* **다만, 이게 좋은 디자인인지는 잘 모르겠습니다.** xv6는 2개의 함수만으로 kernel을 initialize하는데, 이러면 rv6에서는 3개가 되기 때문입니다. 차라리 `ProcessSystem::user_proc_init()`과 `ProcessSystem::init_proc_parent()`를 합친 후 새로운 이름을 붙이는게 나을지도 모르겠습니다.

2021-02-08 13:45 UTC, jeehoonkang commented
음.. 제가 문제를 잘 이해 못하겠는데 내일 미팅 잡아주시겠어요? 저는 결론적으로 이렇게 수정하면 안된다고 생각합닏다 (복잡해져서)

2021-02-09 01:56 UTC, travis1829 commented
정리하면 다음과 같습니다.
**문제**: `Proc::parent` field를 init하기 위해서는 `&'static ProcessSystem`이 필요함
* **해결책** 1: `Proc::parent` field를 init하는 과정은 맨 마지막에 하기
	* **해결책** 1-1: 이걸 하는 새로운 함수를 만들어서, ProcessSystem initialization을 총 3단계로
	* **해결책** 1-2: 이걸 `ProcessSystem::user_proc_init()`안에서 같이 하기
* **해결책** 2: `ProcessSystem::wait_lock`을 `ProcessSystem` 밖으로 빼서 static variable로 바꾸기
	* 이러면 ProcessSystem과 wait_lock이 decouple됨.
* **해결책** 3: `SpinlockProtected`가 `&'static RawSpinlock`이 아니라 `*const RawSpinlock`을 받게 하기
	* 이러면 `SpinlockProtected` 내부에 unsafe를 추가해야하함

2021-02-09 05:03 UTC, travis1829 commented
오류 예시: https://github.com/kaist-cp/rv6/issues/408#issuecomment-775630199

2021-02-16 05:17 UTC, travis1829 commented
다른 방법을 시도해봤습니다. 이제 `user_proc_init()`은 `self: Pin<&mut Self>`가 아니라 `&self`를 받습니다.
* 기존에는, `ProcessSystem::initial_proc`을 `user_proc_init()`에서 write합니다.
* 변경 후에는,`ProcessSystem::initial_proc`을 `init()`에서 write하고 `user_proc_init()`에서는 read만 합니다.
  * 편의를 위해, `ProcessSystem`의 `initial_proc`은 `process_pool`의 첫번째 index에 저장되도록 했습니다. 이러면 굳이 `alloc()`을 `init()`에서 할 필요가 없습니다. (원하시지 않으시면, 이 부분은 `alloc()`을 사용하도록 변경 가능합니다.)

2021-02-16 07:33 UTC, Medowhill requested changes
그냥 `ProcessSystem::init`이랑 `ProcessSystem::user_proc_init`을 한 메서드로 합쳐서 이 문제를 해결하는 방향에 대해서는 어떻게 생각하시나요?

2021-02-16 07:33 UTC, Medowhill commented on kernel-rs/src/proc.rs
> +        assert!(info.state == Procstate::UNUSED);
이미 이 메서드의 safety condition이 `state`가 `UNUSED`라는 것을 가정하기 때문에 assert는 필요 없을 것 같습니다. 넣어야 한다면 `debug_assert!`를 사용하면 어떨까요?

2021-02-16 07:33 UTC, Medowhill commented on kernel-rs/src/proc.rs
> +    unsafe fn init(&mut self, pid: Pid, trap_frame: Page, memory: UserMemory) {
사용되지 않는 메서드 같은데 용도가 무엇인가요?

2021-02-16 07:33 UTC, Medowhill commented on kernel-rs/src/proc.rs
> +        this.process_pool[0].info.get_mut().state = Procstate::USED; // Temporarily set the state to `USED`.
여기서 `state`를 `USED`로 바꾸는 이유가 무엇인가요?

2021-02-16 07:53 UTC, travis1829 commented on kernel-rs/src/proc.rs
> +        assert!(info.state == Procstate::UNUSED);
`debug_assert!`로 바꾸겠습니다!

2021-02-16 07:53 UTC, travis1829 commented on kernel-rs/src/proc.rs
> +    unsafe fn init(&mut self, pid: Pid, trap_frame: Page, memory: UserMemory) {
필요없는 메서드입니다. 죄송합니다.
중간과정에서 추가했던 메서드인데, 지워도 무방해보이니 지우겠습니다.

2021-02-16 07:53 UTC, travis1829 commented on kernel-rs/src/proc.rs
> +        this.process_pool[0].info.get_mut().state = Procstate::USED; // Temporarily set the state to `USED`.
`process_pool`의 0번 자리를 reserve하고 싶어서입니다.
* 이렇게 하면 `ProcessSystem::alloc()`이 0번 자리를 skip하게 됩니다.
* 물론, 지금의 rv6에서는 `user_proc_init()`을 하기도 전에 `alloc()`을 실행하는 일도 없고 그래서 항상 `initial_proc`이 `process_pool`의 0번자리에 allocate되긴 하지만, 혹시라도 미래에 코드가 변경되는 상황을 대비하고 싶어서 이렇게 했습니다.
  * 너무 쓸데없는 고민일까요? 참고로, `alloc()` 자체를 `ProcessSystem::init()`에서 해버리면 `state`를 `UNUSED` -> `USED` -> `UNUSED`로 쓸데없이 바꿀 필요도 없어지지만, xv6와 달라지게 됩니다.

2021-02-16 07:54 UTC, travis1829 commented
> 그냥 ProcessSystem::init이랑 ProcessSystem::user_proc_init을 한 메서드로 합쳐서 이 문제를 해결하는 방향에 대해서는 어떻게 생각하시나요?

이 방법을 쓰면 확실히 `ProcessSystem`의 initialization이 깔끔해질 것 같습니다. (그리고, 실제로 가능합니다.) 다만, xv6와 달라진다는게 단점인 것 같습니다.

2021-02-17 06:24 UTC, travis1829 commented
이 PR은 우선순위가 낮고, 이렇게 되면 xv6와 달라지게 되므로, 이 PR은 일단 close하도록 하겠습니다.

2021-02-17 06:24 UTC, closed without merging