[Closes #410] Add `PinnedArray`
kaist-cp/rv6 pull request #411
Opened 2021-02-09 07:15 UTC by travis1829

Closes #410 
* `PinnedArray`라는 struct를 추가했습니다.
  * `pin_project`의 경우, struct A가 struct B를 own하고 있다면 `Pin<&mut A>` -> `Pin<&mut B>`로 **safe**하게 넘어가는 방법을 제공합니다.
  * 그러나, `Pin<&mut [A; N]>` -> `Pin<&mut A>`로 넘어가는 방법은 제공하지 않는 것으로 보입니다. 그러므로, 불필요하게 unsafe fn인 `Pin::get_unchecked_mut()`나 `Pin::new_unchecked()`를 사용해서 넘어가야 합니다.
  * `PinnedArray`는 위와 같은 불필요한 unsafe 과정을 type안에 가두고 **safe한 API만 제공**합니다. 또, `Index`, `IntoIterator` trait을 impl하며, 특히 `Pin<&mut [A; N]>`을 iterate하려고 하면 자동으로 `Pin<&mut A>`가 나옵니다.

2021-02-09 07:36 UTC, Medowhill approved these changes

2021-02-09 08:08 UTC, jeehoonkang commented
- 전 새로운 type 만드는데 반대합니다. 말씀하신 기능은 array가 자체적으로 지원해야할 기능인데 지금 std에서 빠졌다는게 제 인식입니다. 저는 이를 보완하기 위해 새로운 타입을 만드는게 아니라, `array_get_pin_mut` 과 같은 safe 함수를 unsafe하게 구현해서 가지고 있는게 어떨까 합니다.

- get_entry는 지우고 전역적으로 array_get_pin_mut 같은걸 만들어서 그걸 씁시다.

2021-02-09 08:10 UTC, travis1829 commented
알겠습니다. 그러면 전역 함수를 추가해겠습니다.

2021-02-10 13:41 UTC, travis1829 commented
* `PinnedArray`를 없앴고 `index_mut()`라는 전역함수를 추가했습니다. `index: usize`로 접근해야합니다.
* 굳이 index로만 접근할 필요가 없도록 하기 위해서 `IterMut`라는 iterator type은 그대로 놔뒀습니다. 이것도 없애는게 좋을까요? @jeehoonkang

2021-02-10 14:55 UTC, jeehoonkang requested changes

2021-02-10 14:55 UTC, jeehoonkang commented on kernel-rs/src/pinned_array.rs
> +pub struct IterMut<'s, T> {
- IterPinMut인게 더 나을 것 같습니다.
- `array.iter_pin_mut()` 이런 식으로 쓸 수 있도록 만들 수도 있을까요?

2021-02-10 14:55 UTC, jeehoonkang commented on kernel-rs/src/pinned_array.rs
> +pub fn index_mut<T, const N: usize>(arr: Pin<&mut [T; N]>, index: usize) -> Pin<&mut T> {
naming convention에 따른다면 `get_unchecked_pin_mut` 이어야할 것 같습니다.

2021-02-10 14:55 UTC, jeehoonkang commented on kernel-rs/src/proc.rs
> +        // TODO: Use pinned iteration instead.
이건 그냥 하면 되지 않나요? TODO로 남겨놓는이유 = ?

2021-02-10 18:49 UTC, travis1829 commented on kernel-rs/src/pinned_array.rs
> +pub struct IterMut<'s, T> {
* 이름은 바꿔보겠습니다!
* 그렇게 하려면 새로운 trait을 추가해야할 것 같습니다.
  * 참고로, 지금 상황에서도 `IterMut::from(array)` 대신 `array.into()`를 쓰는건 가능해보입니다.

2021-02-10 18:50 UTC, travis1829 commented on kernel-rs/src/proc.rs
> +        // TODO: Use pinned iteration instead.
* 다시보니 그냥 지금 해도 괜찮을 것 같습니다.
* 다만, `Proc`을 `Pin`하는 건 새로운 PR에서 할 계획입니다.

2021-02-10 18:50 UTC, travis1829 commented on kernel-rs/src/pinned_array.rs
> +pub fn index_mut<T, const N: usize>(arr: Pin<&mut [T; N]>, index: usize) -> Pin<&mut T> {
* `index_mut()`함수 unsafe일 필요가 없다고 생각되므로, unchecked라는 단어를 붙이지는 않아도 될 것 같습니다.
* 이 함수는 `struct`의 field를 projection하는게 아니고 배열의 몇번째 index를 indexing하는 것이므로, `get_pin_mut()`같은 이름보다는 `Index`/`IndexMut` trait에서 하는 것처럼 `index_mut()`함수로 이름 짓는게 괜찮을 것 같습니다.

2021-02-15 02:28 UTC, travis1829 commented on kernel-rs/src/pinned_array.rs
> +pub struct IterMut<'s, T> {
* 이름은 변경했습니다!
* 새로운 trait을 추가하기보다는, 일단은 `array.into()`를 사용하는 쪽으로 변경해봤습니다.

2021-02-15 02:28 UTC, travis1829 commented on kernel-rs/src/pinned_array.rs
> +pub fn index_mut<T, const N: usize>(arr: Pin<&mut [T; N]>, index: usize) -> Pin<&mut T> {
* `get_pin_mut()`라는 safe한 함수로 변경했습니다.
  * 기존의 경우, `index`이 out of bounds이면 panic했지만, 이제는 그냥 `None`을 리턴합니다.

2021-02-15 02:28 UTC, travis1829 commented on kernel-rs/src/proc.rs
> +        // TODO: Use pinned iteration instead.
* `pin_project`의 내부적인 문제때문에 지금 적용하기는 힘들 것 같습니다.
  * `self.project()`을 사용하게되면 compiler가 `'static` borrow를 인식하지 못하게 되어, `SpinlockProtected::new()`를 사용할 수 없습니다.
  * #408 이 끝난 후에는 변경할 수 있을 것 같습니다.

2021-02-15 08:16 UTC, Medowhill approved these changes
LGTM

2021-02-16 06:59 UTC, Medowhill commented
@travis1829 rebase 해 주시면 merge하겠습니다.

2021-02-16 07:01 UTC, Medowhill commented
bors r+

2021-02-16 07:07 UTC, merged