Closes #420
kaist-cp/rv6 pull request #424
Opened 2021-02-17 15:46 UTC by Medowhill

Closes #420

*설명 추가 예정*

2021-02-22 05:34 UTC, travis1829 reviewed
unsafe을 매우 많이 줄이신 것 같네요.
혹시, 비슷한 패턴을 적용할 수 있는 다른 struct들도 있나요?

지금 바로 떠오르는 건 `ListEntry`정도밖에 없긴 한데, 비슷한 패턴을 적용하면 여러 곳에서 unsafe을 줄일 수 있을 것 같아 문의드립니다.

2021-02-22 05:37 UTC, travis1829 reviewed
review내용이 날라가버려서 다시 추가합니다.

2021-02-22 05:37 UTC, travis1829 commented on kernel-rs/src/kernel.rs
> -// TODO: unsafe?
`Kernel`이 초기화가 안 된 상태에서 `kernel()`을 call해도 괜찮나요?

unsafe이여야할 것 같은데 저도 확실하지 않아서 일단은 TODO로 표시해놨었는데, 혹시 어떻게 생각하시는지 문의드립니다.

2021-02-22 05:37 UTC, travis1829 commented on kernel-rs/src/kernel.rs
> +pub struct InitializedKernel<'a> {
이러면 Kernel은 하는일이 builder랑 비슷한 것 같네요.
다만, `InitializedKernel`이라는 이름은 좋은 것 같은데, 이러면 혹시 `Kernel`의 이름을 `KernelBuilder`와 같은 형태로 바꾸는 건 어떨지 제안드립니다.

2021-02-22 05:37 UTC, travis1829 commented on kernel-rs/src/proc.rs
>  pub struct Proc {
마찬가지로, 혹시 `Proc`의 이름을 이제는 `ProcBuilder`와 같은 형태로 바꾸는건 어떻게 생각하시는지 문의드립니다.

2021-02-22 05:45 UTC, travis1829 commented on kernel-rs/src/proc.rs
> +        let mut guard = parent_guard;
변수명을 그냥 `parent_guard`로 하는 건 안되나요?

2021-02-22 05:49 UTC, jeehoonkang commented
- 따로 `Initialized...` 만들지 말고 Kernel, ProcessSystem, Proc 모두 init되었다고 가정할 순 없나요? init이 안되었을때 unsafe하게 접근하구요. `KERNEL: MaybeUninit<Kernel>`을 정의하고, `kernel()`을 init된 이후에만 호출하면 어떨까 합니다.
- `kernel_static()`은 약간 예감이 좋지 않습니다- 이게 safe한 invariant가 (있다면) 매우 복잡할 것 같아서요.

2021-02-22 05:50 UTC, coolofficials commented on kernel-rs/src/kernel.rs
> +pub struct InitializedKernel<'a> {
초기화 된 proc과 kernel을 type으로 표현하는 것은 좋은 것 같습니다. 기존의 Kernel&Proc을 Builder 혹은 그에 준하는 용어로 이름을 변경하는 것에 동의합니다. 다만 이렇게 변경하면 InitializedKernel과 InitializedProc을 Kernel과 Proc으로 이름을 되돌리면 어떨까요?

2021-02-22 06:10 UTC, Medowhill commented on kernel-rs/src/kernel.rs
> -// TODO: unsafe?
네. 저도 unsafe여야 한다고 생각합니다. 관련 논의는 https://github.com/kaist-cp/rv6/issues/267#issuecomment-783089931 에서 하려 했습니다.

주석은 다시 살려 놓겠습니다.

2021-02-22 06:13 UTC, Medowhill commented on kernel-rs/src/proc.rs
> +        let mut guard = parent_guard;
lifetime이 꼬여서 고치던 흔적이 남았네요..

2021-02-22 06:26 UTC, Medowhill commented
`ProcessSystem`을 초기화하려면 먼저 pin되어야 하기 때문에, 일단 `Kernel`을 만들고 이를 pin한 뒤 `ProcessSystem::init`을 호출하는 순서로 진행할 수밖에 없습니다.
https://github.com/kaist-cp/rv6/blob/2f8959ecaf27a98755d8c9f943e36d8eb42faf63/kernel-rs/src/kernel.rs#L238
https://github.com/kaist-cp/rv6/blob/2f8959ecaf27a98755d8c9f943e36d8eb42faf63/kernel-rs/src/proc.rs#L687-L696

---

`InitializedKernel::deref_static`은 이미 `&'static Kernel`이 있을 때 이를 그대로 제공할 뿐이므로 특별한 safety condition이 있다고 생각하지 않습니다. 처음에 `&'static Kernel`을 만드는 쪽이 unsafe일 것이고, 해당 부분에서 unsafe reasoning을 하면 될 것 같습니다.

2021-02-25 06:01 UTC, Medowhill commented
* `ProcessSystem` -> `Procs`
* `InitilializedKernel` -> `Kernel`
* `Kernel` -> `KernelBuilder`
* ...

2021-03-03 14:59 UTC, jeehoonkang commented
이거 @travis1829 님이 마무리해주실 수 있나요? 이름만 바꿔서 머지하기로 했던 것으로 기억해서 그렇습니다. (제가 잘못 기억하는 걸수도 있겠습니다... 확인 부탁드려요 @Medowhill)

2021-03-03 15:01 UTC, Medowhill commented
지난 미팅에서 `InitializedKernel`은 indirection을 한 단계 추가하기 때문에 이 방법은 바람직하지 않은 것 같고, async-book 등을 참고하여 이런 초기화 문제를 보통 어떻게 해결하는지 알아 보기로 한 것으로 기억합니다. 그래서 일단 PR은 merge하지 않고 그냥 두었습니다.

2021-03-08 14:49 UTC, Medowhill commented
`Kernel`이 `&KernelBuilder` 대신 `KernelBuilder`를 transparent memory layout으로 가지고 있도록 수정했습니다. `&KernelBuilder`를 `&Kernel`로 변환해서 써야 하므로 unsafe가 약간 필요하지만, indirection을 없앨 수 있습니다. `Procs`와 `ProcsBuilder`,  `Proc`과 `ProcBuilder`도 같은 방식으로 수정했습니다.

2021-03-09 12:33 UTC, jeehoonkang requested changes

2021-03-09 12:33 UTC, jeehoonkang commented on kernel-rs/src/kernel.rs
> +pub unsafe fn initialized_kernel() -> &'static Kernel {
저는 이름을 `kernel_builder()`, `kernel()`로 바꾸는게 어떨까 합니다. 타입 이름을 따라가서...

2021-03-09 12:33 UTC, jeehoonkang commented on kernel-rs/src/kernel.rs
> +pub unsafe fn initialized_kernel() -> &'static Kernel {
아래 kernel_unchecked_pin도 마찬가지

2021-03-09 12:33 UTC, jeehoonkang commented on kernel-rs/src/exec.rs
>      pub fn exec(
builder에서 exec을 할 수 있는게 다소 이상하게 느껴집니다. 이게 왜 safe한가요?

2021-03-09 12:33 UTC, jeehoonkang commented on kernel-rs/src/trap.rs
> +pub unsafe fn usertrapret(mut proc: CurrentProc<'_>) {
이제 move해도 괜찮나요? semantics가 달라지는 것 같아서요

2021-03-09 12:38 UTC, Medowhill commented on kernel-rs/src/exec.rs
>      pub fn exec(
`exec`에서 하는 일 중 커널의 초기화를 가정하는 것이 없기 때문에 안전하다고 생각합니다. `exec`에서 unsafe 블록은 세 번 사용되며, 세 개 모두 초기화와는 아무런 관련이 없습니다.

2021-03-11 06:26 UTC, Medowhill commented
`*Builder` -> `*`로 옮긴다.

2021-03-11 06:29 UTC, Medowhill commented on kernel-rs/src/trap.rs
> +pub unsafe fn usertrapret(mut proc: CurrentProc<'_>) {
`usertrap`과 `usertrapret`이 paring 되어있다는 것을 더 잘 표현할 수 있는지 별도 이슈에서 논의.

2021-03-11 10:36 UTC, Medowhill commented
`*Builder`에 있던 메서드를 대부분 `*`로 옮겼습니다. 또한, 필드의 타입도 `*Builder`에서 `*`로 바꿀 수 있는 경우 바꾸었습니다. `ProcGuard`가 `ProcBuilder`를 가지고 있는 것이 좀 걸리기는 하지만, `ProcGuard`를 사용하는 `wakeup_pull`이 `kernel_builder()`를 필요로 하기 때문에 `ProcsBuilder` 안에 남아 있어야 해서, `ProcGuard`는 지금 바꾸기는 어려워 보입니다. 이후에 `kernel_builder()`를 전체적으로 없애는 리팩토링을 진행한 후에 다시 봐야 할 것 같습니다.

2021-03-12 03:14 UTC, jeehoonkang approved these changes
- 이제 @Medowhill 님 재량하에 머지 요청드립니다.
- 조만간 kernel(), kernel_builder() 사용을 전반적으로 줄여야할 것 같긴 합니다...

2021-03-12 03:14 UTC, jeehoonkang commented on kernel-rs/src/fs/log.rs
> +            let lbuf = kernel_builder()
얘는 kernel()이 아니라 kernel_builder()여야 하는 이유가 있나요?  kernel_builder()를 사용하는 다른 모든 곳도 마찬가지 코멘트 드립니다.

2021-03-12 04:13 UTC, Medowhill commented
bors r+

2021-03-12 04:18 UTC, merged