[Sub-issue of #378] Pin `DiskInfo`
kaist-cp/rv6 pull request #427
Opened 2021-02-22 11:18 UTC by travis1829

Partially resolves # 378
* virtio_disk.rs에서 `VirtIOBlockOutHeader`, `InflightInfo`를 pin했습니다.
  * 추가적으로, 이를 own하는 `DiskInfo`, `Disk`, `FileSystem`까지 pin했습니다.
* Background: virtio_disk는 IO operation에 대한 정보가 담긴 부분의 address를 driver에게 전달한 후 waitchannel에 대해 sleep합니다. 이후, driver가 주어진 address에 있는 정보를 읽어서 operation을 수행합니다.
    * 이때, driver가 operation을 수행하기 전에 address에 있던 정보가 move되면 안되므로, 이 부분을 pin해야합니다.

2021-02-22 11:19 UTC, travis1829 commented
https://github.com/kaist-cp/rv6/blob/c183d8d51a49d1ae494cb36e1f3f32011aa6ac1b/kernel-rs/src/virtio_disk.rs#L421-L423
다만, 위 부분이 safe이여도 괜찮은지 의문입니다.
QueueNotify를 하게되면 driver가 주어진 address를 read/write하게 되는데, 만약 엉뚱한 address를 알려주었다면 잘못된 곳에 write를 하게될 수 있으므로 UB로 이어질 수 있습니다.

2021-02-23 01:41 UTC, Medowhill approved these changes

2021-02-23 01:58 UTC, Medowhill commented
저희가 원하는 것은 Rust의 메모리 모델 안에서의 메모리 안전성이기 때문에 unsafe일 필요가 없다고 생각합니다.

예를 들어, 커널 페이지 테이블이 잘못 만들어지면 unsafe가 하나도 없는 Rust 코드여도 실제로는 physical memory상에서 문제가 생길 수 있습니다. 하지만 커널 페이지 테이블을 install하는 것이 underlying machine의 동작에 영향을 준다는 것은 Rust 메모리 모델 바깥의 일입니다. 따라서 저희는 메모리 안전성을 위해 커널 페이지 테이블을 구성하는 struct가 메모리에 올바른 구조로 만들어졌다는 것만 확인하면 됩니다. 메모리 안전성을 위해 커널 페이지 테이블 엔트리 값까지 고려할 필요는 없습니다.

마찬가지로, `MmioRegs::QueueNotify.write(0);`이 Rust 메모리 모델 안에서 의미하는 것은 특정 메모리에 0이란 값을 쓰라는 것뿐입니다. 값을 썼을 때 device가 어떠한 동작을 해서 메모리에 변화가 일어나는 것은 메모리 모델 바깥의 일이기 때문에 고려 대상이 아닙니다.

물론 이후에 rv6를 검증하면서 functional correctness를 확인할 때는 page table을 install하면 어떻게 되는지, `QueueNotify.write`을 하면 device가 어떻게 동작하는지 등의 Rust 메모리 모델 바깥에 있는 HW의 동작을 고려해야 할 것입니다. 하지만 현 단계에서는 이들을 고려하지 않아도 됩니다.

제가 전에 @efenniht 님과 이야기할 때는 이렇게 정리했었는데, 교수님 의견도 확인해 보아야 할 것 같습니다. @jeehoonkang 어떻게 생각하시나요?

2021-02-24 08:01 UTC, travis1829 commented
`Disk` -> `VirtIODisk`으로 이름을 변경했습니다.
* rv6 내에서는 struct 이름을 항상 `Virtio*`가 아니라 `VirtIO*` 형태로 짓는 것으로 보여, `Disk`도 `VirtioDisk`가 아니라 `VirtIODisk`로 이름을 바꿨습니다.

2021-02-25 01:05 UTC, jeehoonkang commented
@Medowhill https://github.com/kaist-cp/rv6/pull/427#issuecomment-783808771 에 대해 의견 드립니다.

저는 unsafe여야할 것 같습니다. Rust에서 safe abstraction의 의미는 사용자가 어떻게 사용하는지와 상관 없이 안전해야한다는 규약인데요, 그 abstraction 안에서 machine configuration을 건드린다면 그 machine이 안전하게 동작한다는 보장이 되어야만 합니다.

만일 mmioregs의 spec에 비추어보았을 때 register에 0을 쓰는게 항상 안전하다면 safe인게 맞을 것 같고, 그게 아니라 상황에 따라 다르다면 unsafe인게 맞을 것 같습니다.

2021-02-25 10:38 UTC, travis1829 commented
일단 `MmioRegs::QueueNotify.write`는 unsafe이여야할 것 같지만, 대부분의 register들은 read/write이 safe이여도 괜찮을 것 같습니다. 다만, 이 부분을 고치는 건 새로운 PR에서 하는게 좋을 것 같습니다.

2021-03-03 15:02 UTC, jeehoonkang requested changes
전반적으로 pin을 통해 어떤걸 하고싶은지 명확하지 않은 것 같습니다. 이러한 PR을 만드는 이유를 먼저 제게 high-level에서 설명해주신 후에 코드 만들어서 리뷰하고 머지하기로 합시다.

2021-03-03 15:02 UTC, jeehoonkang commented on kernel-rs/src/fs/mod.rs
> +    pub disk: Sleepablelock<VirtIODisk>,
이렇게 인위적으로 pin을 하는게 다소 부자연스럽게 느껴집니다. VirtIoDisk가 !unpin이고 따라서 자연스럽게 FileSystem이 !unpin인 것으로 나오는게 맞을 것 같아서요

2021-03-03 15:02 UTC, jeehoonkang commented on kernel-rs/src/fs/mod.rs
> +            disk: Sleepablelock::new("virtio_disk", VirtIODisk::zero()),
VirtIoDisk라고 합시다 (대소문자)

2021-03-03 15:02 UTC, jeehoonkang commented on kernel-rs/src/proc.rs
> +    // Should be `!Unpin`, because of the `Proc::parent` pointer.
parent는 사실 !unpin이랑 별 상관 없지 않나요? 이유가 불충분한 것 같습니다.

2021-03-03 15:02 UTC, jeehoonkang commented on kernel-rs/src/virtio_disk.rs
> +    #[pin]
이게 자연스럽게 유추되지 않는게 다소 의아합니다...

2021-03-03 15:23 UTC, travis1829 commented on kernel-rs/src/fs/mod.rs
> +    pub disk: Sleepablelock<VirtIODisk>,
* 현재 교수님 말씀처럼 `VirtIODisk`가 `!Unpin`이라서 `FileSystem`도 자연스럽게 `!Unpin`이 되고있는게 맞습니다.
* `#[pin]`을 추가한 이유는 pin_project 매크로때문입니다. `#[pin]`으로 표시해놔야만 `Pin<&mut FileSystem>`으로부터 `Pin<&mut VirtIODisk>`만을 획득할 수 있으며, 표시하지 않으면 `&mut VirtIODisk`를 safe하게 획득할 수 있습니다.
* 혹시 제가 잘못 이해한 부분이 있으면 말씀해주세요.

2021-03-03 15:23 UTC, travis1829 commented on kernel-rs/src/fs/mod.rs
> +            disk: Sleepablelock::new("virtio_disk", VirtIODisk::zero()),
현재 `VirtIO`라는 접두사를 쓰는 type 이름이 많은 것으로 보이는데 (ex: `VirtIOStatus`, `VirtIOBlockOutHeader`, `VirtIOFeatures` 등), 이것들도 일괄적으로 `VirtIo*`로 바꾸는게 좋을지 문의드립니다.

2021-03-03 15:23 UTC, travis1829 commented on kernel-rs/src/proc.rs
> +    // Should be `!Unpin`, because of the `Proc::parent` pointer.
`Proc`은 항상 `Proc::parent` field를 통해 자신의 부모 `Proc`을 가리키고 있으므로, 부모 `Proc`은 move되어선 안됩니다. 그래서, `Proc`은 `!Unpin`이여야 합니다. 이 부분은 제가 comment를 더 추가하도록 하겠습니다.

2021-03-03 15:28 UTC, travis1829 commented
이 PR을 추가하게된 background에 대한 설명을 조금 변경해봤습니다. https://github.com/kaist-cp/rv6/pull/427#issue-577558626

2021-03-04 02:48 UTC, travis1829 commented on kernel-rs/src/proc.rs
> +    // Should be `!Unpin`, because of the `Proc::parent` pointer.
관련 comment를 추가해봤습니다.

2021-03-04 02:50 UTC, travis1829 commented on kernel-rs/src/virtio_disk.rs
> +    #[pin]
혹시 https://github.com/kaist-cp/rv6/pull/427#discussion_r586508244 와 관련이 있는 부분인지 문의드립니다.
일단, `!Unpin`은 자연스럽게 유추되고 있으며, `#[pin]`을 추가해야하는 이유는 pin_project와 관련이 있습니다.

2021-03-08 07:05 UTC, travis1829 commented
참고: @Medowhill 님께서 이 PR을 리뷰해주실 예정입니다. 이 PR이 굳이 필요하다고 생각되지 않는다면, 이 PR은 merge없이 close할 예정입니다.

2021-03-08 08:36 UTC, Medowhill commented on kernel-rs/src/fs/mod.rs
> +            disk: Sleepablelock::new("virtio_disk", VirtIODisk::zero()),
바꾼다면 일관적으로 다 바꾸는 것이 좋을 것 같습니다.

2021-03-08 09:15 UTC, jeehoonkang requested changes

2021-03-08 09:15 UTC, jeehoonkang commented on kernel-rs/src/fs/mod.rs
> +            disk: Sleepablelock::new("virtio_disk", VirtIODisk::zero()),
네 동의합니다. 일관적으로 다 바꿉시다.

2021-03-08 11:29 UTC, Medowhill commented
#432 가 merge되어야 Pin이 얼마나 `VirtIoDisk`의 unsafe reasoning에 도움이 되는지 구체적으로 보일 것 같아, #432 가 merge된 다음에 다시 리뷰하겠습니다.

2021-03-09 12:56 UTC, Medowhill commented
@travis1829 rebase 해 주시면 다시 리뷰하겠습니다.

2021-03-09 13:15 UTC, travis1829 commented on kernel-rs/src/fs/mod.rs
> +            disk: Sleepablelock::new("virtio_disk", VirtIODisk::zero()),
일괄적으로 변경했습니다!

2021-03-09 14:24 UTC, travis1829 commented
rebase 했습니다!

2021-05-21 02:25 UTC, closed without merging