Change `MmioRegs::{read, write}` into unsafe fn.
kaist-cp/rv6 pull request #432
Opened 2021-02-26 02:16 UTC by travis1829

### Context
`MmioRegs`를 `write`하게되면 side effect으로 인해 UB가 발생할 수 있으므로, unsafe이여야할 것 같습니다.
https://github.com/kaist-cp/rv6/pull/427#issuecomment-783301930
https://github.com/kaist-cp/rv6/pull/427#issuecomment-783808771
https://github.com/kaist-cp/rv6/pull/427#issuecomment-785499746

### Changes
* hafnium에서 했던 것과 비슷하게 바꿔봤습니다. (ex: https://github.com/kaist-cp/hafnium-verification/blob/hfo2/hfo2/src/cpu.rs)
  * `MmioRegs`를 write하는 것은 항상 unsafe입니다.
  * 다만, safe하게 write해도 되는 register는 따로 safe한 function으로 unsafe 부분을 감쌌습니다.

### Additional Suggestions
* 현재,
  * virtio.rs는 virtio_disk.rs에서만 사용되며,
  * virtio_disk.rs는 fs/mod.rs에서만 사용됩니다.
* 이러면, 그냥
  * virtio.rs와 virtio_disk.rs를 합쳐서 virtio module을 만들고, (그리고 virtio.rs는 private으로 한 후)
  * 이 virtio module을 fs의 sub module로 만드는 건 어떻게 생각하시는지 문의드립니다.

2021-03-03 15:08 UTC, jeehoonkang requested changes

2021-03-03 15:08 UTC, jeehoonkang commented on kernel-rs/src/virtio/mod.rs
> +        // Usually, this is safe because
- 이런 말은 굳이...
- 이 함수를 안전하게 사용하기 위한 규약이 뭔지 함수 doc comment로 나와야 합니다 (`# Safety`). 규칙에 맞게 문서화 부탁드려요
- 규약만 지키면 왜 안전한지에 관한 설명이 unsafe block의 주석으로 나와야 합니다.

2021-03-03 15:08 UTC, jeehoonkang commented on kernel-rs/src/virtio/mod.rs
> +        assert!(
assert_eq! 4개로 바꿉시다. 그게 더 가독성이 높아서요

2021-03-03 15:08 UTC, jeehoonkang commented on kernel-rs/src/virtio/mod.rs
> +        // However, the caller should be aware of the side effects caused by the driver.
"should be aware of": 너무 불명확합니다. 좀더 명확하게 뭘 알아야 하는지, 규약이 뭔지 적어야 합니다

2021-03-03 15:08 UTC, jeehoonkang commented on kernel-rs/src/virtio/mod.rs
> +        unsafe {
왜 사실 safe한지 모두 주석 남겨주세요

2021-03-04 07:54 UTC, travis1829 commented
관련 comment를 추가해봤습니다.

2021-03-08 10:38 UTC, Medowhill requested changes

2021-03-08 10:38 UTC, Medowhill commented on kernel-rs/src/virtio/mod.rs
> +    fn set_pg_size(size: u32) {
Safety condition이 붙어 있는데, unsafe 함수일 필요는 없나요?

2021-03-08 10:38 UTC, Medowhill commented on kernel-rs/src/virtio/mod.rs
> +    fn select_and_init_queue(queue_num: u32, queue_size: u32, queue_pg_num: u32) {
Unsafe 함수일 필요는 없나요?

2021-03-08 10:38 UTC, Medowhill commented on kernel-rs/src/virtio/mod.rs
> +    unsafe fn notify_queue(num: u32) {
Physical disk를 하나의 타입으로 생각하면, 해당 타입의 invariant가 위 조건을 보장하고, 그 invariant를 깰 수도 있는 `set_pg_size`와 `select_and_init_queue`는 unsafe로 하되 invariant에 의해 안전성을 보장받을 수 있는 `notify_queue`는 unsafe가 아니게 하는 것이 Rust의 다른 타입의 설계와 더 유사한 것 같습니다. 어떻게 생각하시나요?

2021-03-08 10:54 UTC, travis1829 commented on kernel-rs/src/virtio/mod.rs
> +    unsafe fn notify_queue(num: u32) {
그렇게 생각하면 `set_pg_size()`와 `select_and_init_queue()`는 unsafe으로 바꿔도 될 것 같습니다.
다만, 두 함수가 unsafe이더라도 `notify_queue()`는 여전히 unsafe이여야할 것 같습니다.

위에 적어놓은 comment를 보시면 `notify_queue()`가 unsafe인 이유가 3가지인데,
`set_pg_size()`와 `select_and_init_queue()`를 unsafe로 바꾸면 1, 2번째 이유는 무시해도 되지만, 여전히 3번째(* The descriptors were well set and contains correct addresses.)는 caller가 manual하게 조심해야 합니다.

2021-03-08 11:27 UTC, Medowhill commented on kernel-rs/src/virtio/mod.rs
> +    unsafe fn notify_queue(num: u32) {
네. 말씀하신 것이 맞는 것 같습니다.

2021-03-08 11:33 UTC, Medowhill commented on kernel-rs/src/virtio/virtio_disk.rs
> +        // Safe since the all three descriptors' fields are well set.
여기서도 `ProcessSystem` 등에서 보였던, 안전성이 초기화에 의존하는 상황이 벌어지는 것 같습니다. `rw`의 안전성이 보장되려면 `init`이 이미 호출된 상태여야 하고, 현재 상태에서는 `rw`가 unsafe 메서드가 되어야 올바른 것으로 보입니다.

2021-03-08 13:12 UTC, travis1829 commented on kernel-rs/src/virtio/virtio_disk.rs
> +        // Safe since the all three descriptors' fields are well set.
네, 맞는 말씀인것 같습니다. `Disk`도 `Disk::zero()`와 `Disk::init()`이 나눠져있고, `init()`전에는 `rw`를 하면 안 되는 것 같습니다. 이런 형태의 struct들을 issue로 정리해놓는 것도 좋을 것 같습니다.

2021-03-09 03:13 UTC, travis1829 commented on kernel-rs/src/virtio/mod.rs
> +        // Usually, this is safe because
comment를 조금 변경해봤습니다.

2021-03-09 03:13 UTC, travis1829 commented on kernel-rs/src/virtio/mod.rs
> +        assert!(
반영했습니다!

2021-03-09 03:13 UTC, travis1829 commented on kernel-rs/src/virtio/mod.rs
> +        // However, the caller should be aware of the side effects caused by the driver.
이것도 마찬가지로 comment를 조금 변경해봤습니다.

2021-03-09 03:13 UTC, travis1829 commented on kernel-rs/src/virtio/mod.rs
> +        unsafe {
comment 모두 추가했습니다!

2021-03-09 03:22 UTC, travis1829 commented on kernel-rs/src/virtio/mod.rs
> +    fn set_pg_size(size: u32) {
unsafe로 바꾸겠습니다! (참고: https://github.com/kaist-cp/rv6/pull/432#discussion_r589324877)

2021-03-09 03:22 UTC, travis1829 commented on kernel-rs/src/virtio/mod.rs
> +    fn select_and_init_queue(queue_num: u32, queue_size: u32, queue_pg_num: u32) {
이것도 unsafe로 바꾸겠습니다! (참고: https://github.com/kaist-cp/rv6/pull/432#discussion_r589324877)

2021-03-09 03:42 UTC, travis1829 commented on kernel-rs/src/virtio/virtio_disk.rs
> +        // Safe since the all three descriptors' fields are well set.
다만 이렇게 되면 `rw()` 뿐만 아니라 다른 함수들 (`intr()`, `alloc()` 등)도 unsafe로 표시해야할 것 같습니다.

2021-03-09 04:56 UTC, Medowhill commented on kernel-rs/src/virtio/virtio_disk.rs
> +        // Safe since the all three descriptors' fields are well set.
일단 모두 safe로 두고 이후에 별도 PR에서 `Kernel`과 `Procs`에 사용한 방법을 동일하게 적용하는 것이 어떨까요?

2021-03-09 05:05 UTC, travis1829 commented on kernel-rs/src/virtio/virtio_disk.rs
> +        // Safe since the all three descriptors' fields are well set.
그러면 일단은 그렇게 하도록 하겠습니다.

2021-03-09 05:22 UTC, travis1829 commented on kernel-rs/src/virtio/mod.rs
> +    unsafe fn notify_queue(num: u32) {
반영했습니다!

2021-03-09 05:24 UTC, Medowhill approved these changes

2021-03-09 12:45 UTC, jeehoonkang approved these changes
bors r+

2021-03-09 12:45 UTC, jeehoonkang commented on kernel-rs/src/virtio/virtio_disk.rs
> +        // Safe since the all three descriptors' fields are well set.
두분 논의에 동의합니다. issue 만들어서 tracking 해줄래요?

2021-03-09 12:51 UTC, merged

2021-03-09 12:56 UTC, travis1829 commented on kernel-rs/src/virtio/virtio_disk.rs
> +        // Safe since the all three descriptors' fields are well set.
https://github.com/kaist-cp/rv6/issues/437 를 추가했습니다!