[Sub-issue of #378] Pin `ArrayArena` and `RawPageTable`.
kaist-cp/rv6 pull request #433
Opened 2021-03-02 11:23 UTC by travis1829

Partially resolves # 378.
* Pinned `ArrayArena`.
* Pinned `RawPageTable`.

2021-03-03 14:56 UTC, jeehoonkang requested changes

2021-03-03 14:56 UTC, jeehoonkang commented on kernel-rs/src/file.rs
> +            Spinlock::new_unchecked(
왜 unchecked가 되었나요?

2021-03-03 14:56 UTC, jeehoonkang commented on kernel-rs/src/pipe.rs
> +    _marker: PhantomPinned,
이게 safety reasoning에 어떤 도움이 되는지 잘 모르겠습니다.

2021-03-03 14:56 UTC, jeehoonkang commented on kernel-rs/src/vm.rs
> +/// Also, it is always pinned.
왜 pin되어야 하나요?

2021-03-03 14:56 UTC, jeehoonkang commented on kernel-rs/src/arena.rs
> +    _marker: PhantomPinned,
왜 pin되어야 하나요?

2021-03-03 15:07 UTC, travis1829 commented on kernel-rs/src/arena.rs
> +    _marker: PhantomPinned,
`ArrayPtr`가 `ArrayEntry<T>`를 가리키는 ptr를 들고 있고, `ArrayPtr`가 언제 drop될지 static하게 알 수 없기 때문에 `ArrayEntry<T>`를 항상 pin해야 합니다. 마찬가지로, `ArrayArena`도 pin해야 합니다.

2021-03-03 15:07 UTC, travis1829 commented on kernel-rs/src/file.rs
> +            Spinlock::new_unchecked(
`ArrayArena`가 이제 `!Unpin`이므로 `Spinlock::new_unchecked`를 사용해야 합니다.

2021-03-03 15:07 UTC, travis1829 commented on kernel-rs/src/pipe.rs
> +    _marker: PhantomPinned,
지금 단계에서는 `&mut Pipe`로 사용하는 곳이 없고 항상 `&Pipe`로만 사용하므로, 의미가 없는게 맞습니다. 다만, 사용하는 경우가 없더라도 어쨌든 `Pipe`를 `!Unpin`으로 표시하기 위해서 이걸 추가했습니다.

2021-03-03 15:07 UTC, travis1829 commented on kernel-rs/src/vm.rs
> +/// Also, it is always pinned.
`PageTable`이 `RawPageTable`을 가리키는 ptr를 들고 있기 때문에, `RawPageTable`이 pin되어야 합니다.

2021-03-03 15:07 UTC, travis1829 commented
교수님께서 남겨주신 리뷰에 답변을 달았습니다. 특히, pin되어야 하는 이유 및 unsafe인 이유 등과 관련해서 comment를 추가하도록 하겠습니다.

2021-03-04 02:43 UTC, travis1829 commented
관련 comment를 조금 추가했습니다.

2021-03-08 07:05 UTC, travis1829 commented
참고: @Medowhill 님께서 이 PR을 리뷰해주실 예정입니다. 이 PR이 굳이 필요하다고 생각되지 않는다면, 이 PR은 merge없이 close할 예정입니다.

2021-03-08 11:38 UTC, Medowhill commented
아직까지는 해당 타입들을 Pin했을 때 얻는 것이 정확히 무엇인지 잘 모르겠어, 우선 닫은 뒤 이후에 리팩토링하다가 필요성이 명확해지면 다시 열도록 하겠습니다.

2021-03-08 11:38 UTC, closed without merging