[Closes #434] Use `StaticRefCell` in `ArrayArena`/`MruArena`
kaist-cp/rv6 pull request #435
Opened 2021-03-06 10:58 UTC by travis1829

Closes #434 
-----
### Background
TODO

-----
### Changes
TODO

2021-03-08 06:10 UTC, Medowhill commented
타입 이름에 reference counting이라는 아이디어가 드러나야 합니다.

2021-03-08 12:34 UTC, travis1829 commented
혹시 그냥 `StaticRefCell<T>`이라는 이름을 사용하시는 것에 대해서는 어떻게 생각하시는지 문의드립니다.
* 저희의 상황에서는 `T`의 owner가 정해져있습니다. 즉, `Rc<T>`처럼 ownership을 공유하는 상황이 아닙니다.
* 일반적인 `RefCell<T>`처럼 1)`RefMut`이 한개만 존재하거나 2)`Ref`만 여러개가 존재할 수 있으며, runtime check로 이걸 보장합니다.

참고로, `Rc<RefCell<T>>` (더 정확히는 `Pin<Rc<RefCell<T>>>`)를 사용하는 방법도 있겠지만, 이러면 runtime 비용을 중복해서 사용하게 됩니다.

2021-03-08 13:19 UTC, travis1829 commented
추가로, `ArrayArena`/`MruArena`에 synchronization 관련해서 문제가 있는 것 같습니다. (#393)
이 부분은 `find_or_alloc_handle()`함수를 살짝 바꾸면 해결되는 것 같지만, 이러면 xv6와 조금 달라지게 됩니다. https://github.com/kaist-cp/rv6/issues/393#issuecomment-792750363

2021-03-10 03:16 UTC, travis1829 commented
추가적으로, https://github.com/kaist-cp/rv6/commit/7b493ce35f8165bd92775d070a551d86f589bb9d 관련해서 의문이 있습니다.
이 commit으로 `ArrayArena::find_or_alloc()`에 break이 추가되었습니다. 즉, 비여있는 entry를 찾았다면 나머지 entry들은 모두 skip한후, 그냥 첫번째로 비여있는 entry에 alloc을 하게 되는데, 이러면 혹시 나머지 entry중 하나에 동일한 inode가 이미 alloc되었더라도 다른 entry에 중복해서 alloc을 하게되는게 아닌지 의문입니다.

2021-03-10 03:34 UTC, Medowhill commented
말씀하신 것처럼 `break`가 없는 것이 올바른 것 같습니다. 기존 코드가 잘못된 것이 맞다면, 테스트가 실패하지 않았다는 것이 신기하긴 하네요..

2021-03-10 04:51 UTC, travis1829 commented
> 말씀하신 것처럼 break가 없는 것이 올바른 것 같습니다. 기존 코드가 잘못된 것이 맞다면, 테스트가 실패하지 않았다는 것이 신기하긴 하네요..
혹시 issue #393 에서 test linkunlink가 실패했던게 이거랑 관련이 있는 건 아닐지 조심스럽게 추측해봅니다.

2021-03-10 05:03 UTC, coolofficials commented
> > 말씀하신 것처럼 break가 없는 것이 올바른 것 같습니다. 기존 코드가 잘못된 것이 맞다면, 테스트가 실패하지 않았다는 것이 신기하긴 하네요..
> 
> 혹시 issue #393 에서 test linkunlink가 실패했던게 이거랑 관련이 있는 건 아닐지 조심스럽게 추측해봅니다.

이상하네요... 애초에 해당 commit에서 break이 추가된 맥락이 무엇일까요?

2021-03-12 09:08 UTC, travis1829 commented
`Arena`의 synchronization 관련 문제들이 좀 정리가 된 것 같습니다.
* `Arena::find_or_alloc_handle()`에 대한 설명 : https://github.com/kaist-cp/rv6/issues/393#issuecomment-797347862
* `ArrayArena`의 early break에 대한 설명 : https://github.com/kaist-cp/rv6/issues/393#issuecomment-796525781

2021-03-17 05:02 UTC, travis1829 commented
이러면 arena.rs의 unsafe이 줄어드는 것 같습니다. 그리고, 제 생각으로는 readability도 더 좋아진 것 같습니다.
다만, `Arena::find_or_alloc_handle()`와 같은 함수가 계속 잠깐동안만 `StaticRefCell`을 borrow()했다가 drop하기를 반복하기 때문에 (즉, refcnt를 잠깐동안 늘렸다 줄이므로), 혹시 runtime cost가 생기지는 않는지 살펴보고 있습니다.

2021-03-17 07:11 UTC, Medowhill reviewed
우선 `static_refcell.rs`만 확인한 뒤 작성하는 리뷰입니다. 나중에 더 추가하겠습니다.

Raw pointer의 유효함을 보장하기 위해서는 `try_borrow` 등이 `&Self`가 아니라 `Pin<&Self>`를 인자로 받아야 하지 않나요? Borrow된 상태에서 drop될 때는 panic하지만, swap은 막을 수 없어 문제가 생길 것 같습니다.

```rust
let mut src1 = StaticRefCell::new(None);
let mut src2 = StaticRefCell::new(Some(Box::new(0)));

let r1 = src1.borrow();
core::mem::swap(&mut src1, &mut src2);
let mut r2 = src1.borrow_mut();

if let Some(b) = r1.as_ref() {
    drop(r2.take());
    println!("{}", *b);
}
```

2021-03-17 07:11 UTC, Medowhill commented on kernel-rs/src/static_refcell.rs
> +                self.refcnt.set(self.refcnt.get() + 1);
`usize::MAX`번 borrow하면 실제로는 mutably borrow한 적이 없지만 `is_borrowed_mut`이 `true`를 반환하지 않나요? `self.refcnt`가 `usize::MAX - 1`일 때는 `try_borrow`가 실패해야 할 것 같습니다.

2021-03-17 07:11 UTC, Medowhill commented on kernel-rs/src/static_refcell.rs
> +                    ptr: self as *const _ as *mut _,
`RefMut::ptr`을 `*const`로 바꾸면 `*mut`으로 캐스트하는 부분을 없앨 수 있어 문제가 해결될 것으로 보입니다.

2021-03-17 07:11 UTC, Medowhill commented on kernel-rs/src/static_refcell.rs
> +    fn deref_mut(&mut self) -> &mut Self::Target {
`T: !Unpin`일 때는 왜 하면 안 되나요?

2021-03-17 07:11 UTC, Medowhill commented on kernel-rs/src/static_refcell.rs
> +        unsafe { Pin::new_unchecked(&mut *(*self.ptr).data.get()) }
왜 안전한가요?

2021-03-17 07:23 UTC, travis1829 commented on kernel-rs/src/static_refcell.rs
> +                self.refcnt.set(self.refcnt.get() + 1);
맞습니다.
다만, 이렇게 되면 runtime 비용이 늘어날 것 같아서, 혹시 다른 방법이 있나 생각해보고 있었습니다.

2021-03-17 07:32 UTC, travis1829 commented on kernel-rs/src/static_refcell.rs
> +                    ptr: self as *const _ as *mut _,
다만, `RefMut`이 `DerefMut` trait을 impl하므로, `*mut T`를 저장하는게 적합할 것 같아 고민 중입니다.

2021-03-17 07:38 UTC, Medowhill commented on kernel-rs/src/static_refcell.rs
> +                    ptr: self as *const _ as *mut _,
`self.ptr.data`가 `UnsafeCell`이고 어차피 `&UnsafeCell`로부터 `*mut`을 얻을 수 있으므로 `self.ptr`이 `*mut`일 필요는 없다고 생각합니다.

2021-03-17 08:01 UTC, Medowhill requested changes

2021-03-17 08:01 UTC, Medowhill commented on kernel-rs/src/arena.rs
> +    pub fn get_list_entry(r: &mut RefMut<T>) -> Pin<&mut ListEntry> {
unsafe가 되어야 하지 않나요?

2021-03-18 02:57 UTC, travis1829 commented on kernel-rs/src/static_refcell.rs
> +                self.refcnt.set(self.refcnt.get() + 1);
말씀해주신 내용을 반영했습니다.

2021-03-18 02:57 UTC, travis1829 commented on kernel-rs/src/static_refcell.rs
> +                    ptr: self as *const _ as *mut _,
반영했습니다!

2021-03-18 02:57 UTC, travis1829 commented on kernel-rs/src/static_refcell.rs
> +    fn deref_mut(&mut self) -> &mut Self::Target {
관련 comment를 추가했습니다.
참고로, `T: !Unpin`일때는 하면 안되는 이유는 `Guard`의 경우와 매우 비슷합니다.

2021-03-18 02:57 UTC, travis1829 commented on kernel-rs/src/static_refcell.rs
> +        unsafe { Pin::new_unchecked(&mut *(*self.ptr).data.get()) }
> Raw pointer의 유효함을 보장하기 위해서는 try_borrow 등이 &Self가 아니라 Pin<&Self>를 인자로 받아야 하지 않나요? Borrow된 상태에서 drop될 때는 panic하지만, swap은 막을 수 없어 문제가 생길 것 같습니다.

엄밀히 말하자면, 위에서 말씀해주신 부분때문에 아직은 safe하지 않은 것 같습니다.
일단은 이 부분을 TODO로만 표시한 후, 윗 부분을 해결하고나서 나중에 comment를 추가해보도록 하겠습니다.

2021-03-18 02:57 UTC, travis1829 commented
> Raw pointer의 유효함을 보장하기 위해서는 try_borrow 등이 &Self가 아니라 Pin<&Self>를 인자로 받아야 하지 않나요? Borrow된 상태에서 drop될 때는 panic하지만, swap은 막을 수 없어 문제가 생길 것 같습니다.

말씀해주신 내용이 맞는 것 같습니다.
다만, 이 부분을 해결하기 위해서는 https://github.com/kaist-cp/rv6/pull/430#discussion_r591188577 와 마찬가지로 사소하게 바꾸어야하는 부분이 매우 많이 생기므로, 이 부분을 #439 와 함께 해결하는 것이 좋을 것 같습니다.

2021-03-18 05:59 UTC, travis1829 commented on kernel-rs/src/arena.rs
> +        unsafe { &*ptr }
혹시, 주어진 `ListEntry`가 `MruEntry<T>`안에 들어있는 `ListEntry`가 아닐 수 있으므로 unsafe이어야 한다는 말씀이신가요? 그런거라면 맞는 말씀이신 것 같습니다.

* 이 부분은 `ListEntry`를 `ListEntry<T>`로 바꾸면 해결할 수 있을 것 같습니다.
* 또는, tock이나 https://rust-unofficial.github.io/too-many-lists/index.html 에서 한 것과 비슷하게, `ListEntry`를 저장하는게 아니라 `Link<T>`를 저장하는 방식으로 해도 될 것 같습니다. 이러면, `from_list_entry()`함수 자체가 필요 없어지게 됩니다.

2021-03-18 05:59 UTC, travis1829 commented on kernel-rs/src/arena.rs
> +    pub fn get_list_entry(r: &mut RefMut<T>) -> Pin<&mut ListEntry> {
말씀해주신 것처럼, 이건 unsafe로 바꾸는게 맞는 것 같습니다.

다만, 이와는 별개로, 사실 `get_list_entry`같은 함수를 추가하는게 좋은 디자인인지는 잘 모르겠습니다.
* 이런 함수를 추가해야하는 이유가 `StaticRefCell`안에는 `data`만을 저장하고 `ListEntry`는 저장하지 않아서입니다.
* 만약 `ListEntry`도 함께 저장한다면 `get_list_entry`같은 함수가 필요없어지지만, 그 대신 `MruArena`가 intrusive linked list를 iterate할때마다 `StaticRefCell`안에 저장되어있는 `ListEntry`를 접근해야하게 됩니다. 이러면, 현재 이미 borrow_mut된 `StaticRefCell`들(ex: finalize되고있는 경우)도 강제로 내부를 immutable deref해야하게 됩니다.
* 추가로, `get_list_entry`는 `StaticRefCell`이 `data`를 첫번째 field로 저장한다는 assumption을 하고 있습니다. 만약 이게 아니라면 (ex: refcnt가 첫번째 field라면) `get_list_entry`는 틀리게 됩니다.
  * 다만, 이건 `RefMut::get_refcell()`같은 함수를 추가하면 되긴 합니다.

2021-03-18 06:34 UTC, travis1829 commented on kernel-rs/src/arena.rs
> +    pub fn get_list_entry(r: &mut RefMut<T>) -> Pin<&mut ListEntry> {
EDIT: https://github.com/kaist-cp/rv6/pull/435/commits/e41223f654308dc478e1037bf100786ae70528d2 에서 그냥
`unsafe fn get_list_entry(r: &mut RefMut<T>) -> Pin<&mut ListEntry>`를
`fn finalize_entry(r: RefMut<T>, head: Pin<&mut ListEntry>)`로 바꿔버렸습니다.

2021-03-18 06:35 UTC, travis1829 commented on kernel-rs/src/arena.rs
> +        let mut empty: *const MruEntry<T> = ptr::null();
반영했습니다!

2021-03-18 06:37 UTC, travis1829 commented on kernel-rs/src/arena.rs
> +    const DATA_OFFSET: usize = mem::size_of::<ListEntry>();
저도 동의합니다. 더 좋은 해결책은, 아마 https://github.com/kaist-cp/rv6/pull/435/commits/586d2647660dea71cf59b9bfa7894491c25c1a4a#diff-1143f439dea5787b579c41d95de49a8cc7abf5acc965fc98dd2c7a6dc904ee65R252 에서 한것처럼, offset_of!를 사용하는 방법일 것 같습니다.

다만, 현재 offset_of!를 사용할 수 없는 것 같으므로, 지금으로써는 일단 관련 주석만 추가하는 것에 대해서는 어떻게 생각하시는지 문의드립니다.

2021-03-19 13:04 UTC, travis1829 commented
@Medowhill 
말씀해주신 리뷰사항을 반영했습니다. 리뷰해주셔서 감사합니다.
추가로, list.rs를 많이 손봤습니다.
* 기존 `ListEntry`의 경우, `prev()`, `next()` 함수나 `list_pop_front()`등의 함수가 `&ListEntry`를 리턴하는데, 사실 이건 `ListEntry`가 언제 drop될지를 lifetime등으로 표현할 수 없으므로 unsound합니다. 그러므로, `&ListEntry`가 아니라 `*const ListEntry`를 리턴하도록 변경했습니다.
* 기존 `MruEntry::from_list_entry()`의 경우, 주어진 `list_entry`가 사실 `MruEntry` 내부에있던 ` list_entry`가 아닐 수 있으므로 unsafe했습니다. 이 부분을 해결하기 위해, `List<T>`를 추가했습니다.
  * `List<T>`는 `head`을 제외하고서는, 연결된 모든 `ListEntry`가 `MruEntry` 내부에 있던 `ListEntry`입니다. 그러므로, `head`를 제외하고선 `MruEntry::from_list_entry()`를 safe하게 사용해도 됩니다.
  * `List<T>`의 iterator는 `&T`를 제공합니다. 다만, intrusive collection의 특성상, `T`가 언제 drop/remove 될지 알 수 없으므로, 이 iterator는 unsafe iterator입니다.
* 추가로, 오늘 sync up에서 `ListEntry`에 interior immutability를 강제하는 것은 다른 PR에서 하자고 하였으므로, 이 PR에서는 적용하지 않았습니다. 다만, 이 부분을 추가하게 되면 위에서 설명한 문제점이 대부분 해결될 것 같습니다.

2021-03-19 13:05 UTC, travis1829 commented on kernel-rs/src/arena.rs
> +        unsafe { &*ptr }
다른 방법으로 해결해봤습니다.
https://github.com/kaist-cp/rv6/pull/435#issuecomment-802818538 를 참고해주시면 감사드리겠습니다.

2021-03-22 10:49 UTC, Medowhill requested changes

2021-03-22 10:49 UTC, Medowhill commented on kernel-rs/src/static_refcell.rs
> +// fn main() {
지워도 될 것 같습니다.

2021-03-22 13:49 UTC, travis1829 commented on kernel-rs/src/static_refcell.rs
> +        match refcnt == BORROWED_MUT - 1 || refcnt == BORROWED_MUT {
반영했습니다!
다만, list.rs에 있는 match들은 그대로 놔두었는데, 혹시 이 부분도 바꾸기를 원하시는지 문의드립니다.

2021-03-22 13:49 UTC, travis1829 commented on kernel-rs/src/list.rs
> +    /// # Safety
그렇다면 `# Note`로 바꾸도록 하겠습니다!

2021-03-22 13:49 UTC, travis1829 commented on kernel-rs/src/list.rs
> +    /// This raw pointer is valid only until `T` gets dropped.
포인터가 가리키는 데이터의 **lifetime**을 주석으로라도 표현해주고 싶어서였습니다.
즉, 이 ptr를 immutable dereference하게 된다면, 그 `&T`의 lifetime이 이 함수를 부른 순간부터 `T`가 drop될때까지라는 점을 나타내고 싶었습니다. 다만, 이를 explicit한 lifetime parameter로 표현할 수 없으므로, 주석으로 표현해준 것입니다.

설명이 부족한 것 같아서, 설명을 보충해봤습니다!

2021-03-22 13:49 UTC, travis1829 commented on kernel-rs/src/list.rs
> +            // Safe since `head.prev()` is a `ListEntry` contained in a `T`.
원래는 self.head.prev() 포인터가 `T`안에 들어있는 `ListEntry`를 가리키는게 맞으므로, pointer arithmetic을 통해 `*const ListEntry`를 `*const T`로 바꾸는게 말이 된다는 뜻이였습니다.

다만, 말씀해주신 것처럼, 굳이 주석으로 이런 설명을 달 필요는 없을 것 같아서 그냥 지웠습니다!

2021-03-22 13:49 UTC, travis1829 commented on kernel-rs/src/static_refcell.rs
> +// fn main() {
반영했습니다!

2021-03-23 05:09 UTC, Medowhill commented on kernel-rs/src/static_refcell.rs
> +        match refcnt == BORROWED_MUT - 1 || refcnt == BORROWED_MUT {
저는 bool에 대한 match는 다 if로 바꾸어도 된다고 생각합니다.

2021-03-23 05:17 UTC, Medowhill commented on kernel-rs/src/list.rs
> +    /// This raw pointer is valid only until `T` gets dropped.
`*const T`를 `&T`로 바꾸었을 때 그 `&T`는 가리키는 데이터가 수정되거나 drop되지 않은 동안만 사용되어야 하는 것은 모든 raw pointer에 대해 성립하는 말 아닌가요? 언제나 성립하는 사실을 굳이 주석으로 또 적어야 하는 이유가 무엇인지 잘 모르겠습니다.

2021-03-23 05:22 UTC, travis1829 commented on kernel-rs/src/arena.rs
> +    pub fn get_list_entry(r: &mut RefMut<T>) -> Pin<&mut ListEntry> {
다시보니, 위처럼 하더라도 문제가 생길 수 있어, 그냥 말씀해주신 내용을 반영해서 raw pointer를 리턴하도록 바꿨습니다!

2021-03-23 05:41 UTC, Medowhill commented
제 리뷰는 거의 끝난 것 같은데, rebase하고 교수님께 리뷰 부탁드려도 될 것 같습니다.

2021-03-23 05:44 UTC, travis1829 commented on kernel-rs/src/static_refcell.rs
> +        match refcnt == BORROWED_MUT - 1 || refcnt == BORROWED_MUT {
말씀해주신 것처럼 match들을 전부 if로 변경했습니다!

2021-03-23 05:44 UTC, travis1829 commented on kernel-rs/src/list.rs
> +    /// This raw pointer is valid only until `T` gets dropped.
네, 말씀해주신 것처럼 사실 당연한 내용을 주석으로 또 써놓은게 맞습니다.
이 부분은 어차피 list.rs의 최상단에 documentation으로도 적어놨으므로, 그냥 이런 주석들을 전부 없애도록 하겠습니다.

2021-03-24 08:22 UTC, Medowhill commented on kernel-rs/src/arena.rs
> +    unsafe fn finalize_entry(r: RefMut<T>, head: Pin<&mut ListEntry>) {
* 메서드로 따로 빼서 정의하면 어떤 점이 좋나요?
* 왜 unsafe 메서드인가요?

2021-03-24 10:44 UTC, travis1829 commented on kernel-rs/src/arena.rs
> +    unsafe fn finalize_entry(r: RefMut<T>, head: Pin<&mut ListEntry>) {
> * 메서드로 따로 빼서 정의하면 어떤 점이 좋나요?

`RefMut<T>`로 부터 pointer arithmetic을 사용해서 `*mut MruEntry`를 얻고 또 `Pin<&mut ListEntry>`를 얻는 과정이 조금 비직관적이고 너무 `MruEntry<T>`만의 low level detail이 많이 사용되는 것 같아서, 이를 함수로 감싸면 좋을 것 같았습니다.

> * 왜 unsafe 메서드인가요?

생각해보니까, `RefMut<T>`가 `MruEntry<T>`로부터 얻은 게 아닐수도 있어서 이렇게 바꿨습니다.
즉, 예를 들면, `RefMut<usize>`가 그냥 다른 곳에 있던 `StaticRefCell<usize>`로 부터 얻은 것일 수도 있으므로, 이 함수를 unsafe로 바꿔야 했습니다.

2021-03-26 06:44 UTC, Medowhill approved these changes

2021-03-26 06:47 UTC, coolofficials approved these changes
논문을 위해 comment를 더 면밀히 검토할 필요가 있다는 issue raising 해주세요 :)

2021-03-26 15:10 UTC, jeehoonkang requested changes

2021-03-26 15:10 UTC, jeehoonkang commented on kernel-rs/src/arena.rs
> +    pub unsafe fn from_list_entry(list_entry: &ListEntry) -> &Self {
얼마전 merge된 ListNode를 써야하는 대목이 아닌가 생각합니다.

2021-03-26 15:10 UTC, jeehoonkang commented on kernel-rs/src/arena.rs
> +impl<'s, T> MruPtr<'s, T> {
이제 ArrayPtr, MruPtr의 내부 데이타가 같은 것으로 보이는데 혹시 둘을 구분해야할 필요가 있나요?

2021-03-26 15:10 UTC, jeehoonkang commented on kernel-rs/src/list.rs
> +    pub fn next_mut(self: Pin<&mut Self>) -> Pin<&mut Self> {
pin mut self를 가지고 있다고 해서 next를 pin mut으로 얻을 수 있나요? 왜 safe?

2021-03-26 15:10 UTC, jeehoonkang commented on kernel-rs/src/rc_cell.rs
> +//! Similar to `RefCell<T>`, but provides lifetime-less `Ref<T>` and `RefMut<T>`.
newline above

2021-03-26 15:10 UTC, jeehoonkang commented on kernel-rs/src/rc_cell.rs
> +//! `RcCell<T>`.
여기선 보통 영어로 RcCell을 설명하는 구절이 나옵니다.

2021-03-26 15:10 UTC, jeehoonkang commented on kernel-rs/src/rc_cell.rs
> +        if self.is_borrowed() {
`assert!(!self.is_borrowed(), ...);`

2021-03-26 15:10 UTC, jeehoonkang commented on kernel-rs/src/rc_cell.rs
> +    pub fn try_borrow_mut(&self) -> Option<RefMut<T>> {
혹시 이 API 대신에 (1) Pin<&mut self>를 받고 (2) Pin<&mut T>를 반환할 수도 있을까요? 그러면 refcnt를 굳이 set하지 않아도 안전할 것 같아서요. runtime cost도 줄이고...

2021-03-29 05:42 UTC, travis1829 commented on kernel-rs/src/arena.rs
> +                    // runtime cost?
이 TODO는 제가 작업중에 임시로 추가했던 것들인데, 지금은 없애도 될 것 같습니다.
주석을 제때 처리하지 못하여 죄송합니다.

2021-03-29 05:42 UTC, travis1829 commented on kernel-rs/src/arena.rs
> +                    if let Some(r) = entry.try_borrow() {
> try_borrow_mut을 하고 다시 try_borrow를 하는게 다소 의아합니다.

다른 방법으로 해결했습니다!

> 혹시 두 api call을 하나로 합칠 방법이 있을까요?

합칠 수는 있을 것 같습니다! 다만, 이미 다른 방법으로 해결했고, 또, 이미 `RcCell::{is_borrowed, is_borrowed_mut}`이 public API로 노출되어 있으므로, 지금 상황에서는 합치지 않아도 될 것 같습니다.

2021-03-29 05:42 UTC, travis1829 commented on kernel-rs/src/arena.rs
> +    pub unsafe fn from_list_entry(list_entry: &ListEntry) -> &Self {
upstream rebase 했습니다!

2021-03-29 05:42 UTC, travis1829 commented on kernel-rs/src/arena.rs
> +impl<'s, T> MruPtr<'s, T> {
`ArrayPtr`, `MruPtr` struct를 아예 없애버린후, `Ref`로 대체했습니다!

2021-03-29 05:42 UTC, travis1829 commented on kernel-rs/src/list.rs
> +    pub fn next_mut(self: Pin<&mut Self>) -> Pin<&mut Self> {
safe하지 않으며, 이 부분은 이미 PR #451 에서 해결되었습니다.
upstream rebase 하면서 해결되었습니다.

2021-03-29 05:42 UTC, travis1829 commented on kernel-rs/src/rc_cell.rs
> +//! `RcCell<T>`.
```Rust
//! `RcCell<T>`.
```
위 줄을 없앴습니다!

2021-03-29 05:42 UTC, travis1829 commented on kernel-rs/src/rc_cell.rs
> +//! Similar to `RefCell<T>`, but provides lifetime-less `Ref<T>` and `RefMut<T>`.
https://github.com/kaist-cp/rv6/pull/435#discussion_r603025641

2021-03-29 05:42 UTC, travis1829 commented on kernel-rs/src/rc_cell.rs
> +        if self.is_borrowed() {
반영했습니다!

2021-03-29 05:42 UTC, travis1829 commented on kernel-rs/src/rc_cell.rs
> +    pub fn try_borrow_mut(&self) -> Option<RefMut<T>> {
* `Pin<&mut T>`를 반환하는 건 안 될 것 같습니다. `Pin<&mut Self>`을 가지고 있다는 것이 `RefMut<T>`이 없다는 것을 보장하지 못하기 때문입니다.
* 그 대신, `Option<Pin<&mut T>>`를 반환하는 건 가능할 것 같습니다. 다만, 이러면 `Option<RefMut<T>>`와 큰 차이가 없고, API가 복잡해질 수 있을 것 같습니다.

2021-03-29 05:42 UTC, travis1829 commented
교수님 리뷰사항을 반영했습니다!
추가로, `Arena` trait을
* private한 `ArenaInner` trait와
* public한 `Arena` trait으로 나누었습니다.
이렇게 하면 `Arena::{dup, dealloc}`이 밖으로 노출되지 않으며, user가 항상 `Rc`만을 이용해서 내부 data를 접근하도록 강제할 수 있습니다. 이에 대해서 어떻게 생각하시는지 문의드립니다.

2021-03-29 12:23 UTC, jeehoonkang requested changes

2021-03-29 12:23 UTC, jeehoonkang commented on kernel-rs/src/rc_cell.rs
> +    pub fn try_borrow_mut(&self) -> Option<RefMut<T>> {
저는 `Pin<&mut Self>`를 받고 `Option<Pin<&mut T>>`를 반환하도록 API를 변경하는게 어떨지 제안드립니다. 그러면 refcnt를 set하지 않고도 safe api를 제공할 수 있습니다. API complexity는 크게 차이 없어보입니다.

2021-03-29 12:23 UTC, jeehoonkang commented on kernel-rs/src/arena.rs
> +    pub trait ArenaInner: Sized {
ArenaInner, Arena를 나누는 motivation을 잘 모르겠습니다. 일전에 말씀드렸다시피 각 PR은 쉬운 리뷰를 위해 가능한 작게 쪼갰으면 합니다. 이건 revert 해주시고, 이 변화가 왜 필요한지 motivation을 새로운 issue로 정리해주세요.

2021-03-29 12:23 UTC, jeehoonkang commented on kernel-rs/src/arena.rs
> +    pub trait ArenaInner: Sized {
일반적으로 리뷰 후에 feature 추가하는건 하지 말아주세요. 리뷰에 불필요한 노력이 들어갑니다.

2021-03-29 12:25 UTC, travis1829 commented on kernel-rs/src/arena.rs
> +    pub trait ArenaInner: Sized {
이 feature를 추가했던 이유는 `RcCell`을 추가하면서 `ArrayPtr`/`MruPtr`를 아예 없애버렸기 때문입니다.
* 기존에는 `ArrayPtr`/`MruPtr`가 dealloc되지 않고 drop되면 panic!이 일어났습니다.
* 이 PR로 인해 `ArrayPtr`/`MruPtr`가 아예 없어져버렸으므로 이를 막을 방법이 없어졌습니다. 그러므로, API를 변경해야 했습니다.

다만, 말씀하신 것처럼, 이는 다른 PR에서 하도록 하겠습니다.

2021-03-29 12:37 UTC, travis1829 commented on kernel-rs/src/rc_cell.rs
> +    pub fn try_borrow_mut(&self) -> Option<RefMut<T>> {
그러면 `RefCell::get_mut`와 비슷하게 `RcCell`에
```Rust
fn get_pin_mut(self: Pin<&mut Self>) -> Option<Pin<&mut T>>
```
를 추가하도록 하겠습니다.
위 method는, refcnt가 0인 경우에만 Some을 리턴하고 refcnt != 0이면 None을 리턴합니다.

다만, 교수님께서 원하시는게,
* `RcCell::{try_borrow_mut, borrow_mut}`는 그대로 두고, `RcCell::get_pin_mut`을 추가하는 것이신지,
* 아니면 `RcCell::{try_borrow_mut, borrow_mut}`를 전부 없애고 `RcCell::get_pin_mut`를 추가하자는 것이신지 문의드립니다.

2021-03-29 12:49 UTC, travis1829 commented on kernel-rs/src/rc_cell.rs
> +    pub fn try_borrow_mut(&self) -> Option<RefMut<T>> {
* 일단은 전자로 생각하고 작업했습니다. 이제, `RcCell::get_pin_mut`을 이용하면 write instruction없이도 내부 data를 읽을 수 있을 것 같습니다.
* 혹시 후자를 원하시면 말씀해주세요. 이 경우, `RcCell`을 크게 바꾸어야할 것으로 보이며, `RefCell`과는 semantics가 크게 바뀔 것 같습니다.

2021-03-29 13:50 UTC, travis1829 commented on kernel-rs/src/rc_cell.rs
> +    pub fn try_borrow_mut(&self) -> Option<RefMut<T>> {
교수님께서 후자를 원하신다는 것과, 그 이유가 runtime 비용때문이라는 것도 이해했습니다.
다만, runtime비용을 줄이는 것은 1) `RcCell::get_mut`을 추가해서 해결할 수도 있지만, 2) `Ref::get_mut`을 추가해서도 해결할 수 있을 것 같습니다.
* 두 개를 비교하자면, 1)의 경우 말씀드린 것처럼 불필요하게 unsafe이 늘어나고 `Pin`때문에 readability가 안 좋아질 것 같습니다.
* 참고로, `RcCell::{try_borrow_mut, borrow_mut}`을 없애느냐 마느냐는 이와 독립인 것 같습니다. (없애게되면, `refcnt == BORROWED_MUT`를 할 필요가 없어지므로, runtime 비용이 아주 조금 줄어들 것 같습니다.)
혹시 이에 대해서 어떻게 생각하시는지 문의드립니다.

2021-03-30 03:15 UTC, travis1829 commented on kernel-rs/src/rc_cell.rs
> +    pub fn try_borrow_mut(&self) -> Option<RefMut<T>> {
`RcCell::as_ptr`를 이용해서 해결해보았습니다. de8f2795aa6b71c36192613b00681d680605640a

2021-03-30 03:23 UTC, jeehoonkang approved these changes
bors r+

2021-03-30 03:30 UTC, merged