Partially resolves #267
kaist-cp/rv6 pull request #441
Opened 2021-03-17 15:12 UTC by Medowhill

#267 을 부분적으로 해결하는 PR입니다. 다음 파일에 있는 `kernel_builder` 호출을 없앴습니다.

* fs/path.rs
  * `Path::root`를 `Itable::root`로 옮김. 이에 따라 `ProcsBuilder::user_proc_init`이 init 프로세스의 초기 cwd를 인자로 받음.
  * `Path::namei`와 `Path::nameiparent`가 `&Itable`을 인자로 받음.
* fs/log.rs
  * `Log`의 대부분 메서드가 `&Disk`를 인자로 받음.
* fs/inode.rs (partial)
  * `InodeGuard::dirlink`와 `InodeGuard::dirlookup`이 `&Itable`을 인자로 받음.
* file.rs (partial)
  * `FileType::Device`가 `major`로 `u16` 대신 `&Devsw`를 가짐.
  * `File::write`이 `&FileSystem`을 인자로 받음.
* sysfile.rs
  * `create`을 전역 함수에서 `Kernel`의 메서드로 바꿈.
* pipe.rs
  * `AllocatedPipe::alloc`을 `Kernel::allocate_pipe`로 옮김.
  * `AllocatedPipe::close`가 `Page`를 직접 free하는 대신 그냥 반환.

`'b: 'a`일 때 `Rc<'b, T, S>`를 `Rc<'a, T, S>`의 서브타입으로 취급하기 위해 `arena.rs`에 `narrow_lifetime`을 정의했습니다. 알아서 서브타입으로 간주가 되면 좋겠는데, 이유는 잘 모르겠지만 그렇게는 되지 않습니다. 실질적으로 `narrow_lifetime`이 하는 일이 없으므로 최적화가 잘 된다면 overhead를 추가하지는 않을 것 같습니다.

2021-03-18 07:43 UTC, jeehoonkang requested changes

2021-03-18 07:43 UTC, jeehoonkang commented on kernel-rs/src/arena.rs
> +    mut rc: Rc<'b, Spinlock<ArrayArena<T, CAPACITY>>, S>,
- Rc의 method로 만드는게 어떨지?
- narrow lifetime은 그냥 자동으로 되어야 할 것처럼 보이는데 그게 아닌 이유가 있나요? 주석으로 이 함수의 motivation에 대해 간단히 남겨주시면 좋겠습니다.

2021-03-18 07:43 UTC, jeehoonkang commented on kernel-rs/src/exec.rs
> +        let ptr = path.namei(proc, &self.itable)?;
얘를 누구의 method로 넣을지 좀 고민이 됩니다... itable의 member function으로 이해하는게 더 자연스럽지 않나 하는 생각이 드는데요 혹시 어떻게 보시나요?

만일 바꾼다고 해도 다음 PR에서 하기로 합시다. issue raising 해주세요

2021-03-18 07:43 UTC, jeehoonkang commented on kernel-rs/src/file.rs
> +        fs: &FileSystem,
얘도 path.namei와 비슷한 느낌으로 FileSystem의 멤버 함수가 되어야 하지 않나 생각했ㅅ브니다.

2021-03-18 07:43 UTC, jeehoonkang commented on kernel-rs/src/file.rs
> +                        kernel_builder().free(page);
- 얘는 free가 추가된 것 같은데 맞나요? rv6 버그였던건가요?
- kernel_builder()를 호출하는 지점에 모두 // TODO 남기면 어떨까 합니다

2021-03-18 07:43 UTC, jeehoonkang commented on kernel-rs/src/fs/log.rs
> +    pub fn new(dev: u32, start: i32, size: i32, disk: &Sleepablelock<Disk>) -> Self {
아래 보니 Log의 member function에서 각기 disk를 또 받는데, 사실 Log가 생성될때 받은 disk를 계속 써야하지 않나요? 그 invariant가 API에 더 잘 드러나도록 만드는게 어떨까 합니다. 가령 new에서 disk 한번 받고 기억했다가 나중에 그걸 다시 쓴다던지...

2021-03-22 03:50 UTC, Medowhill commented on kernel-rs/src/arena.rs
> +    mut rc: Rc<'b, Spinlock<ArrayArena<T, CAPACITY>>, S>,
* `Rc`의 메서드로 바꾸겠습니다.
* 왜 서브타입으로 취급되지 않는지는 잘 모르겠습니다. 주석으로 간단하게 써 두겠습니다.

2021-03-22 03:52 UTC, Medowhill commented on kernel-rs/src/file.rs
> +                        kernel_builder().free(page);
`pipe.close`가 원래는 스스로 페이지를 free했는데 지금은 페이지를 return하도록 수정했습니다. 이에 따라 `pipe.close`를 호출하는 쪽에서 페이지를 free해야 합니다.

2021-03-22 03:54 UTC, Medowhill commented on kernel-rs/src/exec.rs
> +        let ptr = path.namei(proc, &self.itable)?;
`Itable`의 메서드로 해도 될 것 같습니다.

2021-03-22 03:56 UTC, Medowhill commented on kernel-rs/src/file.rs
> +        fs: &FileSystem,
만약 `File::write`을 `FileSystem`의 메서드로 만든다면 `File::read`도 옮겨야 할까요?

2021-03-22 06:34 UTC, Medowhill commented on kernel-rs/src/file.rs
> +                        kernel_builder().free(page);
TODO 추가했습니다.

2021-03-22 06:35 UTC, Medowhill commented
`Log`가 `&Sleepablelock<Disk>`를 가지고 있도록 수정했습니다. 이로 인해 `Log`와 `FileSystem`에 lifetime parameter가 추가되었습니다.

2021-03-22 13:42 UTC, jeehoonkang requested changes
꼼꼼하게 작업해주셔서 감사합니다!  몇몇 사소한 코멘트 남겼습니다.  조만간 머지할 수 있으리라 기대합니다.

2021-03-22 13:42 UTC, jeehoonkang commented on kernel-rs/src/proc.rs
> +    pub fn user_proc_init(self: Pin<&mut Self>, cwd: RcInode<'static>) {
- 이제 RcInode를 받아야하는 이유가 궁금합니다.
- 만일 user_proc_init에서 이 kernel과 상관없는 다른 kernel의 RcInode를 받으면 어떻게 되나요?

2021-03-22 13:42 UTC, jeehoonkang commented on kernel-rs/src/sysfile.rs
> +            if typ == InodeType::File {
typ != InodeType::File 이면 early return 하는 방식으로 작성하면 어떨까 제안드립니다.

2021-03-22 13:42 UTC, jeehoonkang commented on kernel-rs/src/sysfile.rs
> +                    InodeType::File | InodeType::Device { .. } => {
문법을 잘 모르겠습니다만 여기도 혹시 early return이 가능한지 궁금합니다.

2021-03-22 13:42 UTC, jeehoonkang commented on kernel-rs/src/sysfile.rs
> +    fn chdir(&'static self, dirname: &CStr, proc: &mut CurrentProc<'_>) -> Result<(), ()> {
kernel method에 붙은 &'static은 나중에 완화 가능한가요? 지금은 왜 필요한지 궁금합니다

2021-03-22 14:10 UTC, Medowhill commented on kernel-rs/src/sysfile.rs
> +    fn chdir(&'static self, dirname: &CStr, proc: &mut CurrentProc<'_>) -> Result<(), ()> {
chdir syscall을 처리하려면 프로세스의 cwd를 바꾸어야 합니다. 현재는 `ProcData`의 `cwd`의 타입이 `RcInode<'static>`이기 때문에 새로운 `cwd` 역시 `RcInode<'static>` 타입이어야 하고, 이를 위해서는 `&'static Itable`이 필요하므로 `&'static Kernel`을 인자로 받아야 합니다. 이를 완화하려면 `ProcData`에 lifetime parameter를 추가하고 `RcInode<'static>` 대신 `RcInode<'s>`를 가지게 만들어야 할 것 같습니다.

2021-03-22 14:15 UTC, Medowhill commented on kernel-rs/src/proc.rs
> +    pub fn user_proc_init(self: Pin<&mut Self>, cwd: RcInode<'static>) {
* 원래는 `user_proc_init`에서 cwd를 만들기 위해 `Path::root`를 호출했는데, `Path::root`가 `Itable`에 접근하기 위해 `kernel_builder`를 호출하기 때문에 `Path::root`를 아예 없애고 `root`를 `Itable`의 메서드로 만들었습니다. 따라서 `user_proc_init`에서 `Itable`이 필요한데, `user_proc_init`에서 `kernel_builder`를 호출하는 대신 cwd를 인자로 받도록 수정했습니다.
* 커널이 여러 개가 되었을 때 어떤 식으로 동작할지 명확하지 않아 구체적으로 대답하기는 어렵지만, 논리적으로 바람직한 일은 아닌 것 같습니다.

2021-03-22 14:45 UTC, Medowhill commented on kernel-rs/src/arena.rs
> +// When 'b: 'a, we want Rc<'b, A, T> <: Rc<'a, A, T>. However, Rc is currently invariant to its
* 현재 `Rc`의 구현은 다음과 같습니다.
```rust
pub struct Rc<'s, A: Arena, T: Deref<Target = A>> {
    tag: T,
    inner: ManuallyDrop<A::Handle<'s>>,
}
```
이때, `A::Handle`은 `Arena`의 generic associated type으로 정의된 임의의 타입이므로 `Rc`가 `'s`에 대해 invariant인 것이 합리적입니다.

그러나, `A` = `Spinlock<ArrayArena<T, CAPACITY>>`인 경우에는 `A::Handle<'s>` = `ArrayPtr<'s, T>`이므로 `Rc`가 `'s`에 대해 covariant가 될 수 있습니다. 어떤 parametric type을 invariant로 취급하다가 특정 방식으로 instantiate된 경우에만 covariant로 취급하는 것은 Rust 타입 체계에서 허용하지 않는 것 같습니다. 만약 `Arena::Handle`이 covariant type constructor라는 것을 `Arena`의 정의에 명시해 줄 수 있으면 해결되겠지만, Rust의 higher-kinded type에 대한 지원이 부실하다 보니 그런 방법은 아마 현재로서는 없는 것 같습니다.

(답글을 작성하다 보니 이 문제에 대해 드디어 이해를 한 것 같은데 주석을 수정해 두겠습니다.)
* 해당 upcast가 필요한 이유는 커널에 `RcInode<'static>`와 `RcFile<'static>` 타입의 필드가 있기 때문입니다. 대부분의 메서드가 `'static`을 사용하지 않도록 일반화되어 있으므로 `&'s Kernel`로부터 `RcInode<'s>`를 만들어 리턴해야 하는데, 필드에서 값을 가져 오면 `RcInode<'static>` 타입의 값이 나오기 때문에 upcast가 필요합니다.

2021-03-22 14:51 UTC, Medowhill commented on kernel-rs/src/fs/mod.rs
> +pub struct FileSystem<'s> {
`Log`가 `&Disk`를 가지고 있게 수정했고, `FileSystem`이 원래 `Log`를 가지고 있었기 때문에, `FileSystem`이 실질적으로 `Disk`와 이 디스크에 대한 참조인 `&Disk`를 모두 가지고 있는 상황입니다. 이런 self-referential struct를 Rust에서 만들 수 있는 제가 아는 두 가지 방법은 (1) 지금처럼 `FileSystem`이 lifetime parameter를 가지고 있는 것과 (2) raw pointer를 사용한 뒤 `FileSystem`을 pin하는 것뿐인데, 더 좋은 방법이 있을까요? 저도 `FileSystem`이 lifetime parameter를 가지고 있지 않는 것이 더 나은 설계라고 생각합니다.

2021-03-22 15:14 UTC, Medowhill commented on kernel-rs/src/fs/log.rs
>      bufs: ArrayVec<[BufUnlocked<'static>; LOGSIZE]>,
`Log::install_transaction`에서 `bufs`에서 `Buf`를 꺼내 `Disk::write`에 전달합니다. `Disk::write`은 `Disk::rw`를 호출하고 `Buf`를 `InflightInfo::b`에 저장하는데 `InflightInfo::b`의 타입이 `*mut Buf<'static>`입니다. `bufs`가 `BufUnlocked<'a>`를 가지고 있게 하려면 `Disk`와 `InflightInfo` 등에 lifetime parameter를 추가해야 할 것으로 보입니다. 만약 그렇게 한다면 별도 이슈로 해결하는 것이 좋을 것 같습니다.

2021-03-22 15:30 UTC, Medowhill commented on kernel-rs/src/fs/mod.rs
> +    fs: &'s FileSystem<'t>,
`Sleepablelock<T>`는 `UnsafeCell<T>`를 가지고 있으므로 `T`에 대해 invariant입니다. 따라서 `FileSystem<'s>`는 `Sleepablelock<Log<'s>>`를 가지고 있기 때문에 `'s`에 대해 invariant입니다. 그러므로 `'t: 's`이더라도 `FsTransaction<'s, 't>` <: `FsTransaction<'s, 's>`가 성립하지 않습니다. 만약 lifetime parameter를 하나로 합치면, `&'s FileSystem<'t>`로부터는 `FsTransaction`을 만들 수 없고 `&'s FileSystem<'s>`로부터만 `FsTransaction`을 만들 수 있는 문제가 생깁니다.

2021-03-22 18:20 UTC, jeehoonkang commented
bors retry

2021-03-22 18:22 UTC, jeehoonkang commented
bors ping

2021-03-22 18:25 UTC, jeehoonkang commented
bors ping

2021-03-22 19:41 UTC, jeehoonkang commented
bors try

2021-03-23 04:33 UTC, Medowhill commented on kernel-rs/src/arena.rs
> +// When 'b: 'a, we want Rc<'b, A, T> <: Rc<'a, A, T>. However, Rc is currently invariant to its
#444 `Rc`의 lifetime을 없애 해결 가능.

2021-03-23 04:33 UTC, Medowhill commented on kernel-rs/src/fs/log.rs
>      bufs: ArrayVec<[BufUnlocked<'static>; LOGSIZE]>,
#444 `Rc`의 lifetime을 없애 해결 가능.

2021-03-23 04:33 UTC, Medowhill commented on kernel-rs/src/sysfile.rs
> +    fn chdir(&'static self, dirname: &CStr, proc: &mut CurrentProc<'_>) -> Result<(), ()> {
#444 `Rc`의 lifetime을 없애 해결 가능.

2021-03-23 04:39 UTC, Medowhill commented on kernel-rs/src/fs/mod.rs
> +pub struct FileSystem<'s> {
#445 를 통해 lifetime을 없앨 수 있음.

2021-03-23 04:39 UTC, Medowhill commented on kernel-rs/src/fs/mod.rs
> +    fs: &'s FileSystem<'t>,
#445 를 통해 `FileSystem`의 lifetime을 없앨 수 있음.

2021-03-23 04:44 UTC, Medowhill commented on kernel-rs/src/proc.rs
> +    pub fn user_proc_init(self: Pin<&mut Self>, cwd: RcInode<'static>) {
`user_proc_init`에서 `kernel_builder`를 호출하도록 수정.

2021-03-23 04:48 UTC, Medowhill commented on kernel-rs/src/file.rs
> +        fs: &FileSystem,
일단 이대로 두고 #446 의 고려 사항들을 고민하여 함께 해결.

2021-03-23 05:22 UTC, jeehoonkang approved these changes
bors r+

2021-03-23 05:31 UTC, merged