[Closes #450] Fix unsoundness in list.rs.
kaist-cp/rv6 pull request #451
Opened 2021-03-24 07:28 UTC by travis1829

Closes #450

### Background
기존의  intrusive linked list에는 unsound한 부분들이 있습니다.
* 예를 들어, `ListEntry::prev`나 `ListEntry::next`는 `Pin<&mut Self>`를 리턴하는데, 사실 node가 언제 mutate/drop될지 알 수 없으므로 이런 type을 리턴하는게 unsound 합니다.
* `ListEntry`의 API를 잘못 사용하면, linked list 구조를 망가뜨릴 수 있습니다. 이를 막기 위하여, `List`와 같은 type을 추가하는 것이 좋을 것 같습니다.

### Changes
* `List`와 `ListEntry`의 API들이 `&Self`나 `Pin<&mut Self>`와 같은 type이 아닌, `*const Self`을 리턴하도록 변경했습니다.
* 항상 linked list 구조를 가지는 `List`라는 type을 추가했습니다.

2021-03-24 08:06 UTC, coolofficials requested changes
High-level 아이디어 위주로 살펴봤습니다.
코드를 아직 자세히 보지는 않았고, 다시 살펴보겠습니다.

구두로 말씀드린 것 포함하여 comment에 대한 몇 가지 아주 사소한 의문과 제안을 드립니다/

2021-03-24 08:13 UTC, jeehoonkang requested changes

2021-03-24 08:13 UTC, jeehoonkang commented on kernel-rs/src/list.rs
> +pub struct ListEntry<T: ListNode> {
여기에 T가 없도록 디자인할 수도 있을까요?

2021-03-24 08:13 UTC, jeehoonkang commented on kernel-rs/src/list.rs
> +    /// * If the item gets removed, the iterator will loop forever.
이건 unsafe는 아닌듯 합니다

2021-03-24 08:13 UTC, jeehoonkang commented on kernel-rs/src/list.rs
> +    /// The caller must make sure that the iterator's **current** items does not get removed, mutated, or dropped.
"current"가 강조되는 이유를 잘 모르겠습니다.

2021-03-24 08:13 UTC, jeehoonkang commented on kernel-rs/src/list.rs
> +    /// * If the item gets mutated/dropped, using the iterator may lead to undefined behavior.
혹시 예제가 있나요?

2021-03-24 08:13 UTC, jeehoonkang commented on kernel-rs/src/list.rs
> +    pub unsafe fn unsafe_iter(&self) -> Iter<'_, T> {
method 이름을 `unsafe_***`라고 짓기도 하는지 궁금합니다. 보통 이럴때 어떻게 이름 짓는지...

2021-03-24 11:11 UTC, travis1829 commented on kernel-rs/src/list.rs
> +//! On contrast, this list does not use lifetimes and allows nodes from being mutated or dropped
> 추가로, this list라고 하는게 위에 말한 일반적인 rust의 list 구현이 아닌 rv6의 list를 지칭한다는 것이 명확하지 않은 것 같습니다.. our 정도로?

[`List`]로 바꾸면 될 것 같습니다.

2021-03-24 11:11 UTC, travis1829 commented on kernel-rs/src/list.rs
> +/// Use only after initialization.
User가 조심해야 하는 부분이 맞는 것 같습니다!

2021-03-24 11:12 UTC, travis1829 commented on kernel-rs/src/list.rs
> +pub struct ListEntry<T: ListNode> {
`ListEntry`에 `ListEntry::{push_back, push_front}`와 같은 method이 있으므로, 이렇게 되면 `List`안에 들어있는 node들의 type들이 뒤죽박죽이 될 수 있을 것 같습니다.

차라리 `T`를 없앤 후 `ListEntry::{push_back, push_front}` method들을 private API로 옮겨버리면 괜찮을 것 같은데, 이에 대해서는 어떻게 생각하시는지 문의드립니다.

2021-03-24 11:12 UTC, travis1829 commented on kernel-rs/src/list.rs
> +    /// * If the item gets removed, the iterator will loop forever.
네, 사실 semantics가 이상해지는 것이지, memory safety 관점에서 문제가 생기는 건 아닌 것 같습니다.
이 부분은 # Note 같은 곳으로 옮기도록 하겠습니다!

2021-03-24 11:12 UTC, travis1829 commented on kernel-rs/src/list.rs
> +    /// The caller must make sure that the iterator's **current** items does not get removed, mutated, or dropped.
`Iter`가 현재 접근하고 있지 않은 `ListNode`는 mutated되거나 drop되더라도 문제가 생기지 않기 때문입니다.

2021-03-24 11:55 UTC, travis1829 commented on kernel-rs/src/list.rs
> +    /// * If the item gets mutated/dropped, using the iterator may lead to undefined behavior.
```Rust
static list: List = List::new();

fn thread1() {
    let mru_entry = MruEntry::new();
    mru_entry.data = 10;
    list.push_front(node);
    drop(mru_entry);
}

fn thread2() {
    for entry in unsafe { list.unsafe_iter() } {
        // do something with entry's data before thread1 drops `mru_entry`
        // thread1 drops `mru_entry`
        // do something with entry's data after thread1 drops `mru_entry`
    }
}
```

2021-03-24 12:09 UTC, travis1829 commented on kernel-rs/src/list.rs
> +    pub unsafe fn unsafe_iter(&self) -> Iter<'_, T> {
어차피 지금은 따로 safe iterator가 존재하지는 않으므로, method의 이름을 그냥 `iter()`로 바꾸는 것에 대해서는 어떻게 생각하시는지 문의드립니다. 적어도 공식 crate들 내에서는, function이나 method의 이름을 `unsafe_***`형태로 짓는 경우는 없는 것으로 보입니다.

다만, 나중에 #443 을 해결하게되면, safe iterator와 unsafe iterartor를 구별해야하게 될 수는 있습니다.

2021-03-24 15:08 UTC, jeehoonkang requested changes

2021-03-24 15:08 UTC, jeehoonkang commented on kernel-rs/src/list.rs
> +pub struct ListEntry<T: ListNode> {
네- 저도 ListEntry에서는 list operation만 수행하고, List에서 Listentry들이 같은 T 안에 있음을 확인하는게 맞는 방향이 아닌가 생각합니다.

2021-03-24 15:08 UTC, jeehoonkang commented on kernel-rs/src/list.rs
> +    pub unsafe fn unsafe_iter(&self) -> Iter<'_, T> {
https://rust-lang.github.io/api-guidelines/naming.html#getter-names-follow-rust-convention-c-getter 이 가이드라인에서 정확히 우리 상황에 대한 얘기를 하고 있는 것같지 않긴 합니다만 `iter_unchecked`가 어떨지 제안드립니다.

2021-03-25 05:51 UTC, travis1829 commented on kernel-rs/src/list.rs
> +pub struct ListEntry<T: ListNode> {
`ListEntry<T>`를 `ListEntry`로 바꾼 후, 말씀드린대로 `ListEntry::{push_back, push_front}`를 private API로 옮겼습니다!
추가로, `ListNode` trait을 없애고, `ListNode<T>`를 추가했습니다.

2021-03-25 05:51 UTC, travis1829 commented on kernel-rs/src/list.rs
> +    pub unsafe fn unsafe_iter(&self) -> Iter<'_, T> {
`iter_unchecked`로 이름을 변경했습니다!

2021-03-25 08:09 UTC, jeehoonkang requested changes
메시지에 더해-

https://github.com/kaist-cp/rv6/pull/451#discussion_r600409813 : 예제가 주석으로 달리면 좋을듯 합니다. 아울러 thread1이 mutate하는 경우에도 문제가 생기나요?

2021-03-25 08:09 UTC, jeehoonkang commented on kernel-rs/src/list.rs
> +/// Intrusive linked list nodes that can be inserted into a `List`.
이건 기존대로 trait으로 하면 안되나요?

2021-03-25 08:21 UTC, travis1829 commented on kernel-rs/src/list.rs
> +/// Intrusive linked list nodes that can be inserted into a `List`.
* 기존에는 `ListNode`가 *unsafe* trait이였으므로, 이렇게 바꾸면 unsafe를 조금 줄일 수 있습니다.
* 또, 이렇게 `ListNode`를 struct로 바꾸면 `ListNode::{push_back, push_front}`를 safe한 public API로 제공할 수 있습니다. (물론, 지금 rv6에서 사용되는 곳은 없긴 합니다.)
* 추가로, 나중에 #443 을 고치기 위해서는 어차피 언젠가는 이렇게 바꾸긴 해야할 것 같습니다.

2021-03-25 08:30 UTC, travis1829 commented
> 메시지에 더해-
> 
> #451 (comment) : 예제가 주석으로 달리면 좋을듯 합니다. 아울러 thread1이 mutate하는 경우에도 문제가 생기나요?

* 예제를 주석으로 추가하겠습니다!
* 네, thread1이 mutate을 하게되면 mut ref와 immut ref가 공존할 수 있을 것 같습니다. 이것도 주석으로 추가하겠습니다.

2021-03-26 04:15 UTC, jeehoonkang requested changes

2021-03-26 04:15 UTC, jeehoonkang commented on kernel-rs/src/list.rs
> +/// Intrusive linked list nodes that can be inserted into a `List`.
- 알겠습니다. 다만 이렇게 하면 더이상 intrusive list라고 하긴 어렵습니다. 왜냐하면 node 안에 entry가 있는 디자인이라고 볼 수 잇으므로... 실제 intrusive list를 쓰면 한 data type 안에 이런 entry가 여럿 있고 다양한 data structure에 동시에 들어있는 형태로 사용됩니다.
- #443 은 왜?

2021-03-26 04:39 UTC, travis1829 commented on kernel-rs/src/list.rs
> +/// Intrusive linked list nodes that can be inserted into a `List`.
> 다만 이렇게 하면 더이상 intrusive list라고 하긴 어렵습니다. 왜냐하면 node 안에 entry가 있는 디자인이라고 볼 수 잇으므로... 

* 저는 `ListEntry`가 `T`를 가리키는 pointer를 가지고 있는 경우 non-intrusive list이고, `ListEntry`가 `T` 자체에 저장되어있으면 intrusive list라고 생각했는데, 혹시 제가 잘못알고 있는 부분이 있는지 문의드립니다.

> 실제 intrusive list를 쓰면 한 data type 안에 이런 entry가 여럿 있고 다양한 data structure에 동시에 들어있는 형태로 사용됩니다.

* 말씀해주신 것처럼, 이렇게 되면 한 node안에 entry가 여러개 있는 형태로는 사용할 수 없게 되는게 맞긴 하지만, 이건 `ListNode`가 unsafe trait이였을때도 비슷한 것 같습니다. 과거의 `ListNode` trait은 node 하나에 `ListEntry`는 한개뿐이라고 가정하고 있었으며, 이건 tock의 intrusive list도 비슷한 것 같습니다.
* 추가로, `ListNode<ListNode<T>>`와 같은 형태로 사용하면, entry가 여러개인 효과를 낼 수 있지 않은지 문의드립니다.

2021-03-26 05:52 UTC, travis1829 commented on kernel-rs/src/list.rs
> +/// Intrusive linked list nodes that can be inserted into a `List`.
제 생각에는, `ListEntry`에 다시 generic을 추가하면, `ListNode`를 다시 trait로 변경하거나 아예 없애도 될 것 같습니다.

2021-03-26 07:18 UTC, travis1829 commented on kernel-rs/src/list.rs
> +/// Intrusive linked list nodes that can be inserted into a `List`.
* 그냥 commit 7b00985 를 revert하겠습니다! (즉, `ListNode`를 다시 trait로 변경하겠습니다!)
  * commit f10070d 는 revert하지 않겠습니다. (즉, `ListEntry`는 여전히 generic parameter가 없는 상태로 두겠습니다)
* 이후, `ListNode` trait에 usize const generic을 추가해서, 여러개의 `ListEntry`를 가지고 있는 `ListNode`도 잘 표현할 수 있도록 해보겠습니다!

2021-03-26 13:02 UTC, jeehoonkang requested changes

2021-03-26 13:02 UTC, jeehoonkang commented on kernel-rs/src/list.rs
> +pub struct List<T: ListNode<ENTRY_INDEX>, const ENTRY_INDEX: usize> {
`ENTRY_INDEX`가 다소 이상한 디자인인 것 같긴 합니다... 지금은 빼고, 나중에 여러 list에 들어갈때 어떻게 할지 생각해보는게 어떨지 제안드립니다.

2021-03-26 13:14 UTC, travis1829 commented
59cfe85 를 revert했습니다.
다만, `ListEntry`를 복수개 가지고 있는 `ListNode`를 이외의 방법으로 잘 표현할 수 있는지 잘 모르겠습니다. 일단 지금까지의 선택지는
* `ListNode<ListNode<T>>`의 형태를 사용하는 것
* `ListNode<0>`, `ListNode<1>`, ...의 형태를 사용하는 것
* runtime 비용을 추가해서 해결하는 것
이 정도인 것 같은데, 제 생각에는 두번째께 제일 괜찮을 것 같습니다.

물론, 아직 rv6에는 이런 형태의 `ListNode`가 필요하지는 않으므로, 일단은 그냥 revert했습니다.

2021-03-26 13:16 UTC, travis1829 commented on kernel-rs/src/list.rs
> +pub struct List<T: ListNode<ENTRY_INDEX>, const ENTRY_INDEX: usize> {
말씀대로 일단은 뺐습니다. https://github.com/kaist-cp/rv6/pull/451#issuecomment-808205386

2021-03-26 13:18 UTC, jeehoonkang approved these changes
bors r+

나중에 필요하면 ENTRY_INDEX보다 차라리 EntryTag를 받는게 좋겠습니다 (타입으로). 필요하게 되면 다시 논의합시다.

2021-03-26 13:24 UTC, merged