Closes #344: add Allocator
kaist-cp/rv6 pull request #458
Opened 2021-03-26 08:10 UTC by Medowhill

* `Allocator` 타입을 추가
  * zero-sized struct
  * unsafe 메서드인 `new_unchecked`를 통해 새 `Allocator`를 만들 수 있음
  * `alloc` 메서드는 `kernel_builer().alloc()`을 호출
  * `free` 메서드는 `kernel_builer().free()`를 호출
* `UserMemory`와 `PageTable`이 각각 `Allocator`를 가짐
  * `UserMemory`의 `Allocator`는 유저 프로세스가 사용할 페이지를 제공
  * `PageTable`의 `Allocator`는 페이지 테이블 자기 자신이 사용할 페이지를 제공
  * 두 `Allocator`의 역할이 분명히 구분되므로 `UserMemory` 안에 있는 `PageTable`이 자신만의 `Allocator`를 가진다고 해도 크게 이상하지 않음. 어차피 `Allocator`는 zero-sized struct이므로 runtime overhead도 없음.
  * Alternative designs:
    * `UserMemory`는 `Allocator`를 가지되 `PageTable`은 가지지 않음: `PageTable`의 많은 메서드가 `UserMemory`로부터 게속 `Allcoator`를 인자로 받아야 해서 코드가 장황해짐. `PageTable`의 auto drop도 불가능해짐.
    * `PageTable`은 `Allocator`를 가지되 `UserMemory`는 가지지 않음: `PageTable`은 페이지 테이블 자료 구조만을 나타내는 타입이고 `UserMemory`는 유저 프로세스의 메모리를 관리하는 타입인데, 유저 프로세스가 사용할 페이지를 구하기 위해 `PageTable`의 `Allocator`를 필요로 하는 것은 논리적으로 이상한 설계라 생각됨.

2021-03-26 12:55 UTC, jeehoonkang requested changes

2021-03-26 12:55 UTC, jeehoonkang commented on kernel-rs/src/kernel.rs
> +    pub fn allocator(&self) -> Allocator {
- &Allocator가 나오도록 할 수는 없나요?
- Kernel 안에 member로 allocator가 있으면 어떨까 합니다.

2021-03-26 12:55 UTC, jeehoonkang commented on kernel-rs/src/kernel.rs
> +        kernel_builder().alloc()
음.. 이걸 보니 kmem 자체가 allocator로 기능하는 것으로 보이는데요, 이렇다면 굳이 새롭게 allocator type을 만들 필요가 있을까 합니다. 어떻게 보시나요?

2021-03-29 00:35 UTC, Medowhill commented on kernel-rs/src/kernel.rs
> +    pub fn allocator(&self) -> Allocator {
`Allocator`가 zero-sized struct라는 이점을 살리기 위해 `&Allocator` 대신  `Allocator`가 나오게 했습니다.

2021-03-29 00:39 UTC, Medowhill commented on kernel-rs/src/kernel.rs
> +        kernel_builder().alloc()
현재는 `Kmem`에서 페이지를 할당/해제하고 `KernelBuilder`에서 페이지를 특정 바이트로 채우기 때문에 `Kmem`만으로 allocator라고 보기 어려운 부분이 있기는 하지만, 어차피 항상 `KernelBuilder`를 거쳐 페이지를 할당/해제하므로 페이지를 특정 바이트로 채우는 부분을 `Kmem`으로 옮기면 그 문제는 해결되기는 합니다. `UserMemory` 등이 `&Kmem`을 가지고 있으려면 lifetime parameter를 추가해야 할 텐데 이 점에 대해서는 어떻게 생각하시나요?

2021-03-30 15:32 UTC, Medowhill commented
`Allocator`를 없애고 페이지를 할당/해제하는 메서드들이 `&Spinlock<Kmem>`을 인자로 받도록 했습니다.

2021-03-30 17:01 UTC, jeehoonkang approved these changes
bors r+

2021-03-30 17:08 UTC, merged