Use `List` for `Kmem`
kaist-cp/rv6 pull request #468
Opened 2021-03-31 05:30 UTC by Medowhill

원래 `Kmem`은 자체적인 intrusive linked list를 사용하도록 구현되어 있었는데, 이를 이미 rv6가 가지고 있는 instrusive linked list 타입인 `List`를 사용하도록 수정했습니다. 원래 `Kmem`에서는 singly linked list를 사용하지만 `List` 타입은 doubly linked list인 것 등의 사소한 차이가 있고, 이로 인해 약간의 runtime overhead가 추가될 수는 있겠으나 무시할 수 있을 정도라고 생각합니다. 어차피 핵심은 `Kmem`이 intrusive linked list로 구현되어야 한다는 점이니, `Kmem`을 이미 존재하는 `List` 타입을 사용해 구현하는 것이 더 바람직한 방향인 것 같습니다.

2021-03-31 06:33 UTC, travis1829 approved these changes

2021-03-31 06:37 UTC, travis1829 commented on kernel-rs/src/kalloc.rs
> +        const_assert!(mem::size_of::<Run>() <= PGSIZE);
rv6에 여기처럼 `debug_assert!`를 `const_assert!`로 바꾸면 좋을 곳이 많을 것 같네요.

2021-03-31 07:04 UTC, jeehoonkang requested changes

2021-03-31 07:04 UTC, jeehoonkang commented on kernel-rs/src/kalloc.rs
> +        const_assert!(mem::size_of::<Run>() <= PGSIZE);
@travis1829 이슈로 만들어주세요-

2021-03-31 07:04 UTC, jeehoonkang commented on kernel-rs/src/kalloc.rs
> +    runs: List<Run>,
SList를 만드는건 어떨지? singly linked list

2021-03-31 07:04 UTC, jeehoonkang commented on kernel-rs/src/page.rs
> +    /// * `mem::size_of::<T>() <= PGSIZE`
얘는 걍 const_assert로 만들어도 괜찮을 것 같습니다.

2021-03-31 07:39 UTC, Medowhill commented on kernel-rs/src/page.rs
> +    /// * `mem::size_of::<T>() <= PGSIZE`
저도 그러고 싶었지만 아쉽게도 컴파일 오류가 발생합니다.

```
error[E0401]: can't use generic parameters from outer function
  --> src/page.rs:82:38
   |
81 |     pub unsafe fn as_uninit_mut<T>(&mut self) -> &mut MaybeUninit<T> {
   |                                 - type parameter from outer function
82 |         const_assert!(mem::size_of::<T>() <= PGSIZE);
   |                                      ^ use of generic parameter from outer function
```

`mem::size_of::<T>()`의 결과를 `const` 변수에 저장하는 것이 불가능한 것 같습니다.

2021-03-31 07:56 UTC, Medowhill commented on kernel-rs/src/kalloc.rs
> +    runs: List<Run>,
현재의 `List`와 비슷한 방식으로 `SList`를 만들려 해 보았는데, 쉽게 되지는 않을 것 같습니다.

`List`는 원소의 lifetime에 대한 어떤 정보도 없기 때문에, 리스트가 drop되기 전에 원소가 먼저 drop될 수 있습니다. 이 경우에도 UB가 발생하지 않도록 원소가 drop될 때 자기 자신을 리스트에서 제거합니다. 이는 `List`가 doubly-linked list이므로 각 원소가 자신의 이전/다음 원소를 가리키는 포인터를 가지고 있어 가능합니다.

같은 방법으로 `SList`를 만들면 문제가 생깁니다. Singly-linked list에서는 각 원소가 자신의 이전 원소를 가리키는 포인터를 가지고 있지 않으므로 drop될 때 리스트에서 자신을 제거할 방법이 없습니다. 각 원소가 reference count를 해서 drop될 때 rc가 0이 아니면 panic하는 방법이 있겠지만, rc를 추가하면 `List` 대신 `SList`를 써서 overhead를 줄이겠다는 목표에도 어긋나고 panic이 일어나는 것이 그다지 좋은 해결 방법은 아닌 것 같습니다.

2021-03-31 08:11 UTC, travis1829 commented on kernel-rs/src/kalloc.rs
> +    runs: List<Run>,
네, 맞는 것 같습니다. 혹시 `SListEntry`를 추가하게 된다면, 위 부분을 user가 manual하게 조심해야할 것 같습니다.
즉, `SListEntry`는 drop되기 전에 `SList::{pop_front, pop_back}`을 꼭 실행해야만 한다고 적어놔야할 것 같습니다.

2021-03-31 12:01 UTC, jeehoonkang commented on kernel-rs/src/page.rs
> +    /// * `mem::size_of::<T>() <= PGSIZE`
만일 그렇다면 debug_assert로 하고 safety documentation을 지우는게 어떨지 제안드립니다.

2021-03-31 12:03 UTC, jeehoonkang commented on kernel-rs/src/kalloc.rs
> +    runs: List<Run>,
> drop될 때 리스트에서 자신을 제거할 방법이 없습니다.

혹시 doubly linked list에서는 이게 어떻게 잘 되나요? 특히 두 thread가 동시에 consecutive node를 linked list에서 제거하려고 한다면, 뭔가 꼬여서 invariant을 깨게 될 것 같은데, 이런 경우는 어떻게 방지되나요?

2021-03-31 14:39 UTC, travis1829 commented on kernel-rs/src/page.rs
> +    /// * `mem::size_of::<T>() <= PGSIZE`
추가로, 조금 더 조사를 해봤는데,
* `#![feature(const_generics)]`와 `#![feature(const_evaluatable_checked)]`를 추가하면, 다음과 같은 방법으로 const assertion을 할 수 있는 것으로 보입니다.
```rust
    /// # Safety
    ///
    /// * `mem::size_of::<T>() <= PGSIZE`
    /// * `PGSIZE % mem::align_of::<T>() == 0`
    pub unsafe fn as_uninit_mut<T>(&mut self) -> &mut MaybeUninit<T>
    where
        Assert<{ mem::size_of::<T>() <= PGSIZE }>: True
    {
        unsafe { &mut *(self.inner.as_ptr() as *mut MaybeUninit<T>) }
    }
}

struct Assert<const EXPR: bool>;
trait True {}
impl True for Assert<true> {}
```
  * 참고:
    * https://github.com/rust-lang/rust/issues/68436#issuecomment-710312762
    * https://github.com/rust-lang/rust/issues/68436#issuecomment-711068069
* 다만, 어째서인지 rv6에서는 위 코드를 사용하면 ICE (internal compiler error)가 발생합니다.
```
error: internal compiler error: compiler/rustc_middle/src/ich/impls_ty.rs:94:17: StableHasher: unexpected region '_#3r

thread 'rustc' panicked at 'Box<Any>', compiler/rustc_errors/src/lib.rs:958:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

note: the compiler unexpectedly panicked. this is a bug.
```
  * `#![feature(const_evaluatable_checked)]` 가 아직 unstable해서 이러는 것 같습니다. 비슷한 증상이 많이 일어나는 것 같습니다.

2021-04-01 05:03 UTC, travis1829 commented on kernel-rs/src/kalloc.rs
> +    runs: List<Run>,
> 혹시 doubly linked list에서는 이게 어떻게 잘 되나요?

* doubly linked list의 경우, 노드의 `fn drop`에서 자신의 왼쪽 노드의 `next` ptr가 자신의 오른쪽 노드를 가리키도록 바꾸고, 자신의 오른쪽 노드의 `prev` ptr가 자신의 왼쪽 노드를 가리키도록 변경합니다.
* singly linked list의 경우, 노드에 `prev` ptr 자체가 없으므로, 자신의 왼쪽 노드의 `next` ptr를 업데이트 해줄수가 없습니다.

> 특히 두 thread가 동시에 consecutive node를 linked list에서 제거하려고 한다면, 뭔가 꼬여서 invariant을 깨게 될 것 같은데, 이런 경우는 어떻게 방지되나요?

* 방지할 수 없습니다. rv6의 doubly linked list는 tock등에서와 마찬가지로 single thread에서만 제대로 작동하며, multi thread에서는 `Spinlock`으로 감싸서 사용해야 합니다.
* 다만, 문제는 singly linked list의 경우, single thread에서도 문제가 일어난다는 것입니다.

2021-04-01 05:39 UTC, Medowhill commented on kernel-rs/src/page.rs
> +    /// * `mem::size_of::<T>() <= PGSIZE`
`assert!`를 사용하고 최적화되기를 기대하기 + 주석으로 추후 컴파일러가 업데이트되면 수정할 수 있음을 적어 두기

2021-04-01 05:40 UTC, Medowhill commented on kernel-rs/src/kalloc.rs
> +    runs: List<Run>,
일단 이 PR은 merge하고 doubly instrusive linked list의 sharing pattern부터 정리하자: 두 주체(list와 node)가 두 영역(entry와 entry를 제외한 node의 데이터)에 어떻게 접근하는지

2021-04-01 12:51 UTC, jeehoonkang approved these changes
bors r+

2021-04-01 13:01 UTC, merged