[Closes #371] Use `const Default` trait in arena.
kaist-cp/rv6 pull request #469
Opened 2021-03-31 06:15 UTC by travis1829

Closes #371 
### Changes
`ArrayArena`/`MruArena`의 `new` method를 변경했습니다.
기존:
```Rust
pub const fn new(entries: [RcCell<T>; CAPACITY]) -> Self; // ArrayArena
pub const fn new(entries: [MruEntry<T>; CAPACITY]) -> Self; // MruArena
```

변경 후:
```Rust
pub const fn new_locked<D: Default>(name: &'static str) -> Spinlock<Self>; // ArrayArena
pub const fn new_locked<D: Default>(name: &'static str) -> Spinlock<Self>; // MruArena
```
-----
* 기존에는 caller가 직접 초기화된 배열을 제공하는 형태였기 때문에, caller가 malicious한 배열을 제공하게 되면 문제가 생길 수 있었습니다.
* 변경 후에는 `ArrayArena`/`MruArena`가 직접 배열을 초기화합니다.
  * 이를 위해서, `Default` trait을 요구하도록 변경했습니다.
  * 특히, `Default` trait을 `const fn`안에서 사용하기 위해서, `#![feature(const_impl_trait)]`을 사용했습니다.

2021-03-31 07:24 UTC, travis1829 commented on kernel-rs/src/arena.rs
> +    pub const fn new_locked<D: Default>(name: &'static str) -> Spinlock<ArrayArena<D, CAPACITY>> {
아쉽게도 그런 형태의 syntax는 아직 지원하지 않는 것으로 보입니다. 현재로서는, `T: const Default`을 시도하면 syntax error가 발생합니다.

참고로, 아직은 `const_trait_impl` feature가 uncomplete한 것 같습니다.
(https://github.com/oli-obk/rfcs/blob/const_generic_const_fn_bounds/text/0000-const-generic-const-fn-bounds.md) 위 RFC에서는 propose되었지만 실제로는 아직 지원되지 않는 기능이 많습니다.

2021-03-31 07:24 UTC, travis1829 commented on kernel-rs/src/arena.rs
> +    pub const fn new_locked<D: Default>(name: &'static str) -> Spinlock<ArrayArena<D, CAPACITY>> {
* `...Arena` 자체를 접근하는건 arena.rs 내부에서만 해야하고, 외부에서는 항상 `Spinlock`에 감싸진 형태로 접근해야합니다.
* 추가로, 외부에서는 `...Arena`를 가지고서는 할 수 있는게 없습니다. (사용할 수 있는 API가 없습니다.)

`new`가 `Self`를 리턴하는 것보다 `Spinlock<Self>`를 리턴하는게 이걸 더 잘 나타낸다고 생각하여 변경했습니다.
다만, 혹시 이전으로 다시 되돌리기를 원하시면 말씀해주세요.

2021-03-31 07:24 UTC, travis1829 commented on kernel-rs/src/bio.rs
> +#[rustfmt::skip] // Need this to use #![feature(const_trait_impl)]
네, 1.4.34 이상 버전이면 되는 것으로 보입니다.

2021-03-31 07:29 UTC, Medowhill approved these changes

2021-03-31 09:09 UTC, travis1829 commented on kernel-rs/src/bio.rs
> +#[rustfmt::skip] // Need this to use #![feature(const_trait_impl)]
참고로 rustup update를 하더라도 rustfmt 1.4.32를 사용하는 것으로 보입니다.

2021-03-31 11:55 UTC, jeehoonkang requested changes

2021-03-31 11:55 UTC, jeehoonkang commented on kernel-rs/src/arena.rs
> +    pub const fn new_locked<D: Default>(name: &'static str) -> Spinlock<ArrayArena<D, CAPACITY>> {
>     * 외부에서는 항상 `Spinlock`에 감싸진 형태로 접근해야합니다.

왜 그런가요?  Arena 자체는 spinlock 없이도 API를 잘 만들 수 있는게 아닌가 싶어서 질문드립니다.

2021-03-31 11:55 UTC, jeehoonkang commented on kernel-rs/src/arena.rs
> +    pub const fn new_locked<D: Default>(name: &'static str) -> Spinlock<ArrayArena<D, CAPACITY>> {
관련 사안을 주석으로 남겨주세요

2021-03-31 11:55 UTC, jeehoonkang commented on kernel-rs/src/bio.rs
> +#[rustfmt::skip] // Need this to use #![feature(const_trait_impl)]
관련 사안을 주석으로 남겨주세요

2021-03-31 15:15 UTC, travis1829 commented on kernel-rs/src/arena.rs
> +    pub const fn new_locked<D: Default>(name: &'static str) -> Spinlock<ArrayArena<D, CAPACITY>> {
다시 `new`로 변경했습니다.

지금의 `ArrayArena`/`MruArena`는 multi thread에서는 사용할 수 없으므로, 항상 `Spinlock`에 감싸져있어야해서 이렇게 생각했는데, 말씀하신것처럼 arena를 single thread에서 사용할 수도 있고 이미 `MruArena::init`같은 API가 존재하므로, 다시 변경했습니다.

2021-03-31 15:15 UTC, travis1829 commented on kernel-rs/src/arena.rs
> +    pub const fn new_locked<D: Default>(name: &'static str) -> Spinlock<ArrayArena<D, CAPACITY>> {
추가했습니다!

2021-03-31 15:15 UTC, travis1829 commented on kernel-rs/src/bio.rs
> +#[rustfmt::skip] // Need this to use #![feature(const_trait_impl)]
추가했습니다!
```
// Need this if lower than rustfmt 1.4.34
```

2021-04-01 12:54 UTC, jeehoonkang approved these changes
bors r+

2021-04-01 13:01 UTC, merged