[Partially resolves #400] `SpinlockProtected` 정리
kaist-cp/rv6 pull request #472
Opened 2021-04-01 09:05 UTC by travis1829

Partially resolves #400 

### Background
PR #430 에서 해결하지 않고 넘어갔던 부분을 이 PR에서 고쳤습니다. (https://github.com/kaist-cp/rv6/pull/430#discussion_r592155440)
Issue #400 을 해결하려면 먼저 이 PR이 merge되어야할 것으로 보입니다.

### Changes
* `SpinlockProtected<T>`를 `SpinlockProtected<T, &Spinlock<U>>`로 변경했습니다. 이러면, 굳이 `Spinlock<()>`를 받지 않아도 됩니다.
이전:
```Rust
pub const fn new(lock: &'static Spinlock<()>, data: T) -> Self
```
이후:
```Rust
pub const fn new(lock: &'static Spinlock<U>, data: T) -> Self
```
* `SpinlockProtectedGuard`를 없애고, 그냥 `SpinlockGuard`를 사용하도록 변경했습니다.

2021-04-01 12:50 UTC, jeehoonkang requested changes

2021-04-01 12:50 UTC, jeehoonkang commented on kernel-rs/src/lock/spinlock_protected.rs
> +impl<T, U> SpinlockProtected<T, &'static Spinlock<U>> {
SpinlockProtected도 lifetime을 갖도록 하는건 어떨가요? 'static 강제하지 말고

2021-04-01 12:50 UTC, jeehoonkang commented on kernel-rs/src/lock/spinlock_protected.rs
> +    lock: P,
여기선 spinlock protected가 이름인데 P가 spinlock이 아닐 수도 있어서 다소 의아합니다.
`LockProtected<L: Lock, T>` 와 같이 정의하는건 어떤가요?

2021-04-02 02:37 UTC, travis1829 commented on kernel-rs/src/lock/spinlock_protected.rs
> +impl<T, U> SpinlockProtected<T, &'static Spinlock<U>> {
반영했습니다!

2021-04-02 02:37 UTC, travis1829 commented on kernel-rs/src/lock/spinlock_protected.rs
> +    lock: P,
반영했습니다!

2021-04-02 03:04 UTC, jeehoonkang requested changes

2021-04-02 03:04 UTC, jeehoonkang commented on kernel-rs/src/lock/lock_protected.rs
> +pub struct LockProtected<T, P> {
`LockProtected<'s, R, U, T>` 이런 식으로 정의하는건 어떨지 제안드립니다.

2021-04-02 03:04 UTC, jeehoonkang commented on kernel-rs/src/lock/lock_protected.rs
> +pub struct LockProtected<T, P> {
아울러- U는 없어도 되지 않나 생각합니다. 걍 raw lock이 일치하면 T를 얻을 수 있다고 보면 될거 같아서요. 최종적으로 `LockProtected<'s, R, T>` 제안드립니다.

이렇게 놓고 보니 이름을 `RemoteLock<'s, R, T>` 정도도 괜찮아보입니다.

2021-04-02 04:24 UTC, travis1829 commented on kernel-rs/src/lock/lock_protected.rs
> +pub struct LockProtected<T, P> {
> LockProtected<'s, R, U, T> 이런 식으로 정의하는건 어떨지 제안드립니다.

`R`을 추가하게 되면, `lock` module의 `RawLock`들 (ex: `RawSpinlock`, `RawSleeplock`, `RawSleepablelock`)을 user에게 노출시켜야만 할것 같습니다. 예를 들어, user가 `LockProtected`의 type을 적고 싶을 때,
* 이전에는 `LockProtected<T, &'s Spinlock<U>>`로 하면 되는데 (또는 `LockProtected<'s, T, Spinlock<U>>`)
* 이후에는 `LockProtected<'s, RawSpinlock, U, T>` 형태로 써야합니다.

> 아울러- U는 없어도 되지 않나 생각합니다.

`U`가 없으면 `LockProtected::get_lock`을 구현할 수 없을 것 같습니다.
```Rust
/// Returns a reference to the `Lock` that `self` borrowed from.
pub fn get_lock(&self) -> &'s Lock<R, U>;
```
* 참고로, 지금은 `get_lock`을 사용하는 곳이 없지만, #400 을 해결하기 위해서는 필요할 것으로 보입니다.

2021-04-02 05:25 UTC, jeehoonkang commented on kernel-rs/src/lock/lock_protected.rs
> +pub struct LockProtected<T, P> {
- RawSpinlock을 노출하는게 의도에 부합할 것 같습니다. Lock, LockProtected는 같은 수준에 있는 abstraction이라고 봐서요.
  SpinlockProtected를 spinlock.rs에서 정의하는 방법도 있겠습니다.

- get_lock: 왜 필요하게 되나요? 만일 필요하다면 Spinlock<U>, SpinlockProtected<T>를 둘다 들고 있는게 맞지 않나 해서 질문드립니다.

2021-04-02 06:07 UTC, travis1829 commented on kernel-rs/src/lock/lock_protected.rs
> +pub struct LockProtected<T, P> {
* 알겠습니다. 그럼 말씀하신 방법을 사용하되, type alias를 이용해보도록 하겠습니다.
* `get_lock` 함수를 추가하지 않게되면, arena.rs에 정의되어 있는 `Rc`가 field를 하나 더 가지고 있어야 됩니다.
1) `LockProtected::get_lock`이 존재하는 경우:
```Rust
pub struct Rc<A: Arena> {
    inner: SpinlockProtected<ManuallyDrop<Ref<A::Data>>, &A>,
}
```
2) `LockProtected::get_lock`이 존재하지 않는 경우:
```Rust
pub struct Rc<A: Arena> {
    arena: *const A, // *const Spinlock<...>
    inner: SpinlockProtected<ManuallyDrop<Ref<A::Data>>, &A>,
}
```
이런식으로, `Rc`에 field를 추가해야되서 runtime cost가 조금 늘어날 것 같습니다.

2021-04-02 07:22 UTC, travis1829 commented on kernel-rs/src/lock/lock_protected.rs
> +pub struct LockProtected<T, P> {
리뷰 반영했습니다!
* `LockProtected<T, &'s Lock<R, U>>` -> `RemoteLock<'s, R, U, T>`.

2021-04-02 07:31 UTC, jeehoonkang approved these changes
bors r+

2021-04-02 07:38 UTC, merged