[Closes #479] Use `Branded` to remove (potential) unsafe in `Procs`
kaist-cp/rv6 pull request #481
Opened 2021-04-11 09:01 UTC by travis1829

Partially resolves #479 

#479 에서 설명한 것처럼, `Procs::{fork, wait, exit_current}`와 같은 method들은 여러개의 `Procs`가 존재할 수 있다면 문제가 생길 수 있습니다. 그러므로, `Branded`을 사용하여, 인자로 주어진 `proc`이 `self`의 process들 중 하나여야만 한다는 것을 표현하였습니다.

* 참고: `RemoteLock`의 runtime cost를 없애는 것은 먼저 이 PR이 끝난 후 하면 좋을 것 같아, 아직 하지 않았습니다.

2021-04-11 09:16 UTC, travis1829 commented on kernel-rs/src/trap.rs
> +    kernel.brand(|kernel| {
아래 코드는 기존 코드의 왼쪽에 indentation을 추가한 것 뿐인 부분이 대부분입니다.
실질적으로 뭐가 바뀐 line은
* L60~L64 (기존: L59~61)
* L74~L75 (기존: L71)
* L96~L99 (기존: L91~93)

정도입니다.

2021-04-22 13:56 UTC, travis1829 commented on kernel-rs/src/trap.rs
> +    kernel.brand(|kernel| {
Outdated

2021-04-22 14:42 UTC, travis1829 commented on kernel-rs/src/syscall/file.rs
> +        let tx = self.kernel.fs().begin_transaction();
참고: 이전처럼 `self.kernel.file_system`을 시도하면 lifetime error가 발생하게 됩니다.
* 우리가 원하는건 `&'s Kernel`로부터 `&'s FileSystem`을 borrow하는 것인데, `self.kernel.file_system`을 하게되면 `&'s KernelCtx`로부터 `&'s FileSystem`을 borrow해버리게 됩니다.
* 장기적으로는, `KernelBuilder::file_system` field를 private field로 변경한 후, 항상 `KernelRef::fs()`와 같은 getter function을 쓰도록 변경해야할 것 같습니다.
  * 이 PR에서는 하지 않았습니다.

2021-04-26 07:39 UTC, Medowhill approved these changes

2021-04-26 07:44 UTC, Medowhill commented
아직 `fork`, `wait`, `exit_current`가 `Branded`가 없으면 정말 unsafe한지 확인된 바는 없지만, `Branded`를 넣음으로써 functional correctness를 논증하는 데 도움이 되는 것은 사실이므로, 이 PR은 그대로 merge하고 이후에 unsafe하다는 증거를 찾으면 주석으로 추가해도 될 것으로 보입니다.

2021-04-26 07:46 UTC, travis1829 commented
@Medowhill 
제 생각에는 memory safety bug가 일어날 수도 있는 것 같습니다. 혹시 https://github.com/kaist-cp/rv6/pull/481#issue-613037244 의 "Motivation" section을 읽어주시면 감사드리겠습니다.

2021-04-26 07:51 UTC, jeehoonkang requested changes

2021-04-26 07:51 UTC, jeehoonkang commented on kernel-rs/src/kernel.rs
> +pub unsafe fn kernel_ref<'s, F: for<'new_id> FnOnce(KernelRef<'new_id, 's>) -> R, R>(f: F) -> R {
safety condition이 문서화되면 좋겠습니다.

2021-04-26 07:51 UTC, jeehoonkang commented on kernel-rs/src/kernel.rs
> +pub unsafe fn kernel<'s>() -> &'s Kernel {
safety condition이 문서화되면 좋겠습니다.

2021-04-26 07:51 UTC, jeehoonkang commented on kernel-rs/src/kernel.rs
> +    pub fn get_inner(&self) -> &Branded<'id, &'s Kernel> {
inner를 access할 수 있다면 kernelref를 굳이 정의할 필요가 있나요?

2021-04-26 07:51 UTC, jeehoonkang commented on kernel-rs/src/proc.rs
> +    pub fn procs_ref<'id, 's>(self: &KernelRef<'id, 's>) -> ProcsRef<'id, 's> {
KernelRef에 정의하지 않고 Kernel에 정의하는 까닭은?

2021-04-26 07:51 UTC, jeehoonkang commented on kernel-rs/src/proc.rs
> +pub unsafe fn kernel_ctx<'s, F: for<'new_id> FnOnce(KernelCtx<'new_id, 's>) -> R, R>(f: F) -> R {
걍 `'id`라고만 해도 될듯 합니다.

2021-04-26 07:51 UTC, jeehoonkang commented on kernel-rs/src/kernel.rs
> +    Branded::new(kernel, |bkernel| f(KernelRef(bkernel)))
bkernel: 그냥 `k`라고만 해도 될듯 합니다.

2021-04-26 07:51 UTC, jeehoonkang commented on kernel-rs/src/syscall/file.rs
> +        let tx = self.kernel.fs().begin_transaction();
지금 KernelCtx의 두번째 lifetime 인자와, &mut self의 lifetime이 두가지가 있어서 좀 헷갈리는 것 같습니다. 혹시 둘중 하나만 쓰도록 변경은 어렵나요?

2021-04-26 07:51 UTC, jeehoonkang commented on kernel-rs/src/syscall/proc.rs
> +        self.kernel.procs_ref().exit_current(n, self);
걍 `procs()`로 이름붙이는건 어떨까요? `_ref`가 굳이 정보를 주지 않는 것 같아서요. 다른 곳도 마찬가지

2021-04-26 07:55 UTC, Medowhill commented
ex1: `RemoteLock`을 수정해야 runtime cost가 없어지므로, 이 PR의 motivation이라고 하기에는 적절하지 않은 것 같습니다. 그래도 `RemoteLock`을 수정하게 되면 결국은 `wait`이 `'id`를 필요로 하게 될 것이므로, 나중에 해야 할 일을 지금 미리 해 두는 정도로 이해할 수는 있겠습니다.
ex2: 좋은 설명인 것 같습니다. `fork`의 주석에 설명을 추가해 주세요.
ex3: `Kmem`이 소유한 페이지의 reference를 받아서 가지고 있는 것이 아니라, 페이지의 소유권 자체를 넘겨 받는 것이므로 `Kmem`이 먼저 drop되어도 문제가 있을 것 같지는 않습니다.

2021-04-26 08:00 UTC, travis1829 commented on kernel-rs/src/proc.rs
> +    pub fn procs_ref<'id, 's>(self: &KernelRef<'id, 's>) -> ProcsRef<'id, 's> {
cargo doc을 할 때 차이가 생깁니다.
* `Kernel`에 정의하게 되면, `Kernel`문서와 `KernelRef` 문서 모두에 이 함수가 나타나게 됩니다.
* `KernelRef`에 정의하게 되면, `KernelRef` 문서에만 이 함수가 나타납니다.

사실 큰 차이는 없습니다. 혹시 `KernelRef`로 옮기기를 원하시면 말씀해주세요.

2021-04-26 08:00 UTC, travis1829 commented on kernel-rs/src/proc.rs
> +pub unsafe fn kernel_ctx<'s, F: for<'new_id> FnOnce(KernelCtx<'new_id, 's>) -> R, R>(f: F) -> R {
저도 동의합니다.
다만, 다른 곳들(ex: [GhostCell](https://gitlab.mpi-sws.org/FP/ghostcell/-/blob/master/ghostcell/src/lib.rs#L118), [LCell](https://docs.rs/qcell/0.4.1/qcell/struct.LCellOwner.html#method.scope))은 굳이 `'id`라고만 하지 않고 `'new_id` 또는 `'scope_id`를 사용한 것으로 보이는데, 이 부분에 대해서는 어떻게 생각하시는지 문의드립니다.

2021-04-26 08:06 UTC, travis1829 commented on kernel-rs/src/kernel.rs
> +    pub fn get_inner(&self) -> &Branded<'id, &'s Kernel> {
`Branded`에는 concrete한 의미가 주어져있지 않으므로, https://github.com/kaist-cp/rv6/issues/479#issuecomment-818762919 에서 discuss했던 대로 `Branded`는 항상 wrap해서 사용해야할 것 같습니다.

또 다른 방법으로는, 그냥 type alias를 사용해도 될 것 같습니다.
* 다만, 이렇게 되면 어떠한 경우에는 `Branded`를 wrap하지 않고 사용하고, 어떠한 경우에는 `Branded`를 wrap해서 사용하므로 조금 혼란스러울 수도 있을 것 같습니다.

2021-04-26 08:11 UTC, Medowhill commented on kernel-rs/src/kernel.rs
> +    pub fn get_inner(&self) -> &Branded<'id, &'s Kernel> {
덧붙이자면, 다음과 같이 `u32` + invariant의 형태로 이루어진 타입에서 getter를 제공하는 것이 이상하지 않듯,
```rust
// Invariant: self.0 must be an even integer.
pub struct A(u32);
impl A { pub fn get_inner(&self) -> &u32 { ... } }
```
`KernelRef`의 경우에도 문제될 것은 없어 보입니다. `Branded<T>`는 `T`와 Id의 product, `KernelRef`는 `Branded<Kernel>` + invariant로 이해할 수 있습니다.

2021-04-26 10:06 UTC, travis1829 commented on kernel-rs/src/syscall/proc.rs
> +        self.kernel.procs_ref().exit_current(n, self);
`KernelRef`로 옮긴 후, 함수명을 `procs()`로 바꾸었습니다.
(이전에는, 이미 `Kernel`에 `procs()`라는 함수명이 있어서 `procs()`를 사용할 수 없었습니다.

2021-04-26 11:01 UTC, travis1829 commented on kernel-rs/src/syscall/file.rs
> +        let tx = self.kernel.fs().begin_transaction();
항상 `KernelCtx`, `KernelRef`의 두번째 lifetime인자를 사용하도록 변경했습니다.

이를 위해, 추가적으로,
* `KernelBuilder::{ticks, devsw}` field를 private field로 변경했고,
* `kernelRef::{ticks, devsw}`라는 getter 함수를 추가했습니다.

2021-04-26 11:04 UTC, travis1829 commented on kernel-rs/src/kernel.rs
> +pub unsafe fn kernel_ref<'s, F: for<'new_id> FnOnce(KernelRef<'new_id, 's>) -> R, R>(f: F) -> R {
추가했습니다!

2021-04-26 11:04 UTC, travis1829 commented on kernel-rs/src/kernel.rs
> +pub unsafe fn kernel<'s>() -> &'s Kernel {
추가했습니다!

2021-04-26 17:12 UTC, jeehoonkang requested changes
좀만 더 보고 머지합시다- branded가 중요한 변화다보니 앞으로의 PR에도 영향을 많이 끼칠 것 같아 가장 꼼꼼하게 살펴봤습니다.

2021-04-26 17:12 UTC, jeehoonkang commented on kernel-rs/src/kernel.rs
> +    pub fn get_inner(&self) -> &Branded<'id, &'s Kernel> {
좀 다른 식으로 질문해보겠습니다. get_inner()가 필요한 이유가 궁금합니다. Branded<Kernel>이 외부에서 사용되는 곳이 있나요? 저는 가능하면 그런게 없었으면 해서 질문드립니다.

2021-04-26 17:12 UTC, jeehoonkang commented on kernel-rs/src/kernel.rs
> +    pub fn ticks(&self) -> &'s Sleepablelock<u32> {
- 이런 accessor가 LCell에서도 도입되었었나요?
- 일반적으로 field 접근하는 것보다 type checking이 좀 덜되긴 할텐데 괜찮나요?

2021-04-26 17:12 UTC, jeehoonkang commented on kernel-rs/src/proc.rs
> +pub unsafe fn kernel_ctx<'s, F: for<'new_id> FnOnce(KernelCtx<'new_id, 's>) -> R, R>(f: F) -> R {
넵.. lcell을 따라갑시다 그렇다면

2021-04-27 05:41 UTC, travis1829 commented on kernel-rs/src/kernel.rs
> +    pub fn get_inner(&self) -> &Branded<'id, &'s Kernel> {
* `Branded::brand` method이 "src/proc.rs"에서 사용됩니다.
  ex)
  ```Rust
  impl<'id, 's> KernelRef<'id, 's> {
      /// Returns a `ProcsRef` that points to the kernel's `Procs`.
      pub fn procs(&self) -> ProcsRef<'id, 's> {
          ProcsRef(self.get_inner().brand(self.get_inner().procs()))
      }
  }
  ```
* 저도 이 부분을 없애고 싶었는데, `KernelRef`는 "src/kernel.rs"에 정의되어있고, `ProcsRef`는 "src/proc.rs"에 정의되어 있어서, 없애기 힘들 것 같습니다. (즉, 서로 다른 module에 정의되어 있어서 힘들 것 같습니다.)
  * `ProcsRef`의 정의를 "src/kernel.rs"로 옮기면 가능은 할 것 같은데, 좋은 방법인지 잘 모르겠습니다. 또, 지금은 `Branded`를 `Procs`의 method들에서만 사용하니까 상관없지만, 나중에 다른곳에서도 사용하게되면 비슷한 wrapper들을 또다시 "src/kernel.rs"에 저장해야할 수 있습니다.

2021-04-27 05:51 UTC, travis1829 commented on kernel-rs/src/kernel.rs
> +    pub fn get_inner(&self) -> &Branded<'id, &'s Kernel> {
그냥 `KernelRef::get_inner`함수를 없앤 후 `KernelRef::brand`를 추가해보았습니다. e62b781

2021-04-27 06:10 UTC, travis1829 commented on kernel-rs/src/kernel.rs
> +    pub fn ticks(&self) -> &'s Sleepablelock<u32> {
* 그렇지는 않은 것 같습니다.
  * 애초에, 이 부분은 `Branded`와는 상관이 없는 것 같고, `&'s Kernel`을 그대로 쓰지 않고 `KernelRef<'_, 's>`형태로 wrap해서 사용하게 되면서 나타난 변화인 것 같습니다. 이러면
    * `&'s KernelRef<'_, '_>` -> `&'s Sleeplock<u32>`를 원하는 건지,
    * `&'_ KernelRef<'_, 's>` -> `&'s Sleeplock<u32>`를 원하는 건지
  
    이를 명확히 나타내야 하는데, 그걸 나타내기 위해서 추가한 함수입니다.
* 일단 현재 rv6에서는 문제가 없는 것 같습니다.
  * 애초에, `KernelRef`가 `impl Copy`이므로, field를 직접 접근하는 방법이나 이렇게 getter를 사용하는 방법이나 대부분의 경우는 큰 차이가 없을 것 같습니다.
  * 추가적으로, 이런 getter 함수를 추가하게 되면 `Kernel::ticks` field를 private field로 변경할 수 있으므로, 개인적으로는 이렇게 하는게 장기적으로 더 좋을 것 같습니다.

2021-04-27 14:57 UTC, jeehoonkang approved these changes
고생하셨습니다-

bors r+

2021-04-27 15:03 UTC, merged

2021-04-28 05:40 UTC, travis1829 commented on kernel-rs/src/kernel.rs
> +    pub fn get_inner(&self) -> &Branded<'id, &'s Kernel> {
참고: https://github.com/kaist-cp/rv6/issues/498