[Partially resolves #483] Make only one `CurrentProcMut` exist
kaist-cp/rv6 pull request #488
Opened 2021-04-14 08:31 UTC by travis1829

Partially resolves #483 

# Motivation
current cpu가 `Kernel::current_proc`을 사용하면 current cpu의 `Proc`을 가리키는 `CurrentProc`을 얻을 수 있습니다. 이때,
* `Kernel::current_proc`을 여러번 사용하면 동일한 `Proc`을 가리키는 `CurrentProc`을 여러개 얻을 수 있습니다.
* `CurrentProc::deref_mut_data`를 사용하면 `&mut ProcData`를 얻을 수 있습니다.

결과적으로, current cpu가 위 API를 악용하면 동일한 `ProcData`를 가리키는 `&mut ProcData`를 여러개 얻을 수 있게 됩니다.

# Changes
### 이 부분을 고치기 위해 `CurrentProc`을 1) `CurrentProc`와 2) `CurrentProcMut`로 나누었습니다.
* `CurrentProc`은 `&mut ProcData`를 얻을 수 없지만, `CurrentProcMut`는 가능합니다.
* `CurrentProc`은 여러개 존재해도 되지만, `CurrentProcMut`은 단 한개만 존재해야 합니다.
  * 참고로, `CurrentProc`와 `CurrentProcMut`은 공존할 수 있습니다.

### 또, `CurrentProcMut`이 하나만 존재하도록 하기 위해 `CpuToken`이라는 type을 추가했습니다.
* 하나의 cpu는 딱 하나의 `CpuToken`만을 가질 수 있습니다.
* `CurrentProcMut`을 얻기위해서는 `&mut CpuToken`을 제공해야 합니다.
  * 이렇게 변경하면, 하나의 cpu가 딱 하나의 `CurrentProcMut`만을 가질 수 있게 할 수 있습니다.
* `CpuToken`은
  * cpu가 user mode -> kernel mode로 진입할 때 1개 제공되며, (`usertrap`의 argument 형태 등으로 제공)
  * cpu가 다시 kernel mode -> user mode로 되돌아갈 때 반환해야 합니다.

이렇게 하면, device interrupt와 관련된 부분을 제외하면, 굳이 unsafe를 사용할 필요가 없습니다.

# Problems
다만, 아쉽게도 device interrupt과 관련된 code는 `CpuToken`을 제공받지 않도록 하였습니다.
* cpu가 `usertrap`에 의하여 kernel mode로 진입한 후에도, `devintr`는 갑자기 언제든지 발생할 수 있습니다.
* 만약 `devintr`도 `usertrap`과 비슷하게 `CpuToken`을 argument형태로 제공하게 한다면, 하나의 cpu가 여러개의 `CpuToken`을 가지게될 수 있습니다.
* 결국, device interrupt와 관련된 code는 이 점을 manual하게 조심해야하므로, 이 부분만 유일하게 unsafe fn인 `Kernel::current_proc_mut_unchecked`를 사용하도록 하였습니다.

2021-04-14 08:37 UTC, travis1829 commented on kernel-rs/src/proc.rs
> +pub struct CurrentProcMut<'p> {
`CurrentProcMut`라는 이름이 너무 길다면,
* `CurrentProc` -> `CurrProc`
* `CurrentProcMut` -> `CurrProcMut`

로 줄이는 것도 좋을 것 같습니다.

2021-04-14 10:14 UTC, Medowhill requested changes
`CurrentProc`을 사용하는 곳이 모두 `kernel_builder`를 호출하는 곳이기 때문에 추후에 없어질 것 같은데, 굳이 `CurrentProc`과 `CurrentProcMut`을 구분하기보다는 `CurrentProcMut`을 그냥 `CurrentProc`으로 두고 `current_proc`을 호출하는 곳에서 `current_proc_unchecked`을 호출하도록 하는 것이 나을 것 같습니다.

2021-04-14 10:23 UTC, travis1829 commented
@Medowhill https://github.com/kaist-cp/rv6/pull/488#pullrequestreview-635449695
* 알겠습니다. 이 경우, commit b927438 만 revert하면 될 것 같습니다.
* 다만, 그러면 혹시 `CpuToken`에 대해서는 어떻게 생각하시는지 문의드립니다. (지금은 `KernelBuilder::current_proc`에서만 사용되지만, PR #476 이 끝나고 나면 `KernelBuilder::current_cpu`도 `CpuToken`을 받도록 변경할 생각입니다.)

2021-04-14 10:34 UTC, Medowhill commented
* `usertrap`과 `forkret`은 실제로는 인자를 받지 않는데, 코드 상으로 `CpuToken`을 받도록 되어 있는 것이 바람직한지는 잘 모르겠습니다. 전에 말씀하신 것처럼 ZST이니 괜찮을 것 같기는 한데, ZST의 정확한 의미를 바탕으로 판단하는 것이 좋을 것 같습니다. 일단 교수님 의견을 확인해 보면 좋겠습니다.
* 교수님께서 전에 `&mut CurrentProc`에서 `&mut Cpu`를 얻도록 하는 것이 좋겠다고 말씀하셨는데, 이를 따르는 편이 더 나을 것 같기는 합니다. `&mut Cpu`를 얻는 곳까지 `&mut CpuToken`을 전달하는 것이 별로인 것 같아서요.
* `CpuToken`이 좋은 이름인지는 잘 모르겠습니다. 특히 `&mut Cpu`를 얻을 때 `CpuToken`을 사용하지 않게 된다면요.

2021-04-14 10:40 UTC, travis1829 commented
그렇게 되면, (좀 더 고민이 필요하겠지만), `CpuToken`을 그냥 없애든가 한 후,
* `usertrap()`을 1) `usertrap()`와 2) `usertrapproc()` (가칭)으로 나누고, `usertrapproc()`은 `CurrentProc`의 method이도록 하거나
* 비슷하게 `usertrap()`을 `usertrap()`와 `usertrapkernel()` (가칭)으로 나누고, 후자는 `Kernel`의 method이도록 하거나

기타 비슷한 방법을 대신 사용할 수도 있을 것 같습니다.

2021-04-21 11:59 UTC, travis1829 commented
Resolved in #490

2021-04-21 11:59 UTC, closed without merging