[Closes #471] Add `const_assert_generics` module
kaist-cp/rv6 pull request #489
Opened 2021-04-15 13:03 UTC by travis1829

Partially resolves #471 

# Changes
* `fn`이나 `impl`의 `where` clause에서 compile-time assertion을 할 수 있게 해주는 `const_assert_generics` module을 추가했습니다.
  * 특히, 이러면 input generics에 대하여 compile-time assert을 할 수 있게 됩니다.
* ICE가 일어나지 않도록 하기 위해서 `incremental = false`로 세팅했습니다.
* 아쉽게도, 이를 `const_assert_generics!`와 같은 형태의 macro로 만들 수는 없는 것으로 보입니다.

참고: 기존에는 ICE가 일어나서 이를 못했었는데, https://github.com/rust-lang/rust/issues/77708 에 의하면 incremental=false로 해놓고 compile을 하거나, release mode에서 compile을 하면 ICE가 일어나지 않는다고 합니다.

2021-04-15 13:06 UTC, Medowhill approved these changes

2021-04-15 13:09 UTC, travis1829 commented on kernel-rs/src/page.rs
> +        Assert2<{ mem::size_of::<T>() <= PGSIZE }, { PGSIZE % mem::align_of::<T>() == 0 }>: True,
참고: 이 줄을 `Assert({mem::size_of::<T>() <= PGSIZE && PGSIZE % mem::align_of::<T>() == 0}>: True`로 변경하면, const expression이 너무 복잡하니 const fn으로 대체하라는 에러가 발생하게 됩니다.
그래서, 부득이하게 `Assert2`를 추가했습니다.

2021-04-15 15:33 UTC, jeehoonkang requested changes

2021-04-15 15:33 UTC, jeehoonkang commented on kernel-rs/Cargo.toml
> +incremental = false
why?

2021-04-15 15:33 UTC, jeehoonkang commented on kernel-rs/src/util/const_assert_generics.rs
> +impl True for Assert2<true, true> {}
- 저는 Assert 하나만 남기는게 어떨까 합니다. 두번 쓰면 되니까...
- 혹시 error message도 넣을 수 있을까요?
- 이 기능을 제공하는 혹시 별도 crate이 있나요? 있으면 그걸 쓰는게 좋을 것 같아서요.

2021-04-15 15:49 UTC, travis1829 commented on kernel-rs/Cargo.toml
> +incremental = false
아직 `const_evaluatable_check` feature가 unstable해서, 이걸 끄지 않고 debug mode로 컴파일하면 ICE가 발생합니다. (rust-lang/rust#77708)

2021-04-15 15:49 UTC, travis1829 commented on kernel-rs/src/util/const_assert_generics.rs
> +impl True for Assert2<true, true> {}
* https://github.com/kaist-cp/rv6/pull/489#discussion_r614054166 에서 말씀드렸다싶이, `Assert` 하나로만 하려고 하면 const expression이 너무 복잡하다고 compile error가 발생합니다.
* 아쉽지만, error message를 넣는건 안 될것 같습니다. macro를 쓰면 가능할지도 모르겠는데, `where` clause에서는 macro자체를 쓸 수 없는 것 같습니다.
  * 참고로, 지금은 이런 에러 메세지를 띄웁니다.
  ```
  mismatched types
  expected type `false`
     found type `true`
  ```
* 따로 이런 crate가 존재하지는 않는 것 같습니다.

2021-04-15 17:38 UTC, jeehoonkang commented
저는 close를 제안합니다. (1) 새 solution이 다소 복잡하고, (2) assert가 asm에서 사라지는 것을 확인했습니다.

2021-04-15 17:46 UTC, travis1829 commented
* 알겠습니다.
* 네, 아마 일반적인 경우, assert이 지워지긴 할 것 같습니다.

2021-04-16 04:30 UTC, travis1829 commented on kernel-rs/src/util/const_assert_generics.rs
> +impl True for Assert2<true, true> {}
EDIT: 다만, 이런 방식으로 사용하자는 discussion들이 있기는 합니다.
* https://www.reddit.com/r/rust/comments/gt067a/implementing_a_trait_only_for_types_satisfying_a/
* https://internals.rust-lang.org/t/const-generics-where-restrictions/12742

2021-04-16 06:34 UTC, closed without merging