Add `KernelCtx`
kaist-cp/rv6 pull request #490
Opened 2021-04-16 09:15 UTC by Medowhill

현재의 커널 스레드가 어떤 커널의 스레드이며 어떤 유저 프로세스를 위한 것인지 나타내는 `KernelCtx` 타입을 추가했습니다.

```rust
pub struct KernelCtx<'p> {
    pub kernel: &'p Kernel,
    pub proc: CurrentProc<'p>,
}
```

`CurrentProc`은 mutable하게 접근하면서 `Kernel`에는 immutable하게 접근해야 하는 경우가 꽤 있기 때문에, lifetime 문제가 생기지 않도록 두 필드를 각각 접근해야 합니다. 그래서 `CurrentProc` 안에 `&Kernel`을 넣는 대신 `&Kernel`과 `CurrentProc`을 모두 가지고 있는 타입인 `KernelCtx`를 새로 만들고, 기존에 `CurrentProc`을 전달하던 곳에서 `KernelCtx`를 전달하도록 수정했습니다.

2021-04-16 10:30 UTC, travis1829 requested changes
`KernelCtx`라는 아이디어는 좋은 것 같습니다.
다만, 몇 가지 문의사항이 있는데, 이것만 확인해주시면 감사드리겠습니다.

2021-04-16 10:30 UTC, travis1829 commented on kernel-rs/src/proc.rs
> +    pub fn current_ctx(&self) -> Option<KernelCtx<'_>> {
일반적인 경우 `KernelCtx`는 하나만 존재해야하는 것 같은데, 혹시 `current_ctx`가 `unsafe fn`이여야하는 건 아닌지 문의드립니다.

2021-04-16 10:30 UTC, travis1829 commented on kernel-rs/src/proc.rs
> +pub struct KernelCtx<'p> {
`KernelCtx`의 `kernel`와 `proc` field를 pub으로 해놓으면,
* `ctx.kernel = other_kernel` 이라든가,
* `ctx.proc = other_current_proc` 이라든가,
위와 같은 방식으로 field의 값 자체를 아예 바꿀수도 있을 것 같은데,
혹시 `kernel`, `proc` field를 private으로 바꾸고 `KernelCtx::kernel()`이나 `KernelCtx::proc()`을 추가하는 건 어떻게 생각하시는지 문의드립니다.

2021-04-16 10:45 UTC, Medowhill commented on kernel-rs/src/proc.rs
> +    pub fn current_ctx(&self) -> Option<KernelCtx<'_>> {
네. 말씀하신 내용이 맞습니다. `CurrentProc`의 유일성을 보장하려는 PR #488 이 이미 존재해서, 이 PR에서는 관련된 내용은 다루지 않는 것이 맞다고 생각해서 unsafe로 바꾸지 않았습니다. 일단 이 PR에서 unsafe로 바꿔 둘까요?

2021-04-16 10:54 UTC, Medowhill commented on kernel-rs/src/proc.rs
> +pub struct KernelCtx<'p> {
* `ctx.proc`과 `ctx.kernel`을 접근할 때는 `proc`과 `kernel`을 각각 접근하므로 `proc`을 mutably borrow한 상태에서 `kernel`을 또 mutably borrow할 수 있습니다. 그러나 `ctx.proc_mut()`과 `ctx.kernel_mut()`을 통해 해당 필드에 접근할 때는 두 메서드 모두 `ctx`를 mutably borrow하게 되어 `proc`과 `kernel`을 동시에 사용할 수 없습니다. 그래서 어쩔 수 없이 두 필드를 `pub`으로 두었습니다.
* `CurrentProc`을 만들려면 무조건 unsafe 블록이 필요하므로, `proc`이 `pub`이어도 `proc`을 수정하려면 unsafe 블록을 열어야만 하기 때문에, `proc`이 `pub`인 것은 별로 위험해 보이지 않습니다. `kernel`을 외부에서 수정하는 것은 가능할 텐데, 이것이 위험한지는 아직 잘 모르겠습니다. 어차피 `kernel`은 immutable하게만 사용하니까요. 다만 `KernelCtx`의 invariant가 `proc`이 `kernel`의 프로세스여야 함을 규정한다고 생각해 볼 수는 있을 텐데, 그 경우에는 각 필드에서 `pub`을 떼서 해결할 문제라기보다는 branded 타입을 사용해 해결할 문제가 아닐까 합니다.

2021-04-16 10:59 UTC, travis1829 commented on kernel-rs/src/proc.rs
> +    pub fn current_ctx(&self) -> Option<KernelCtx<'_>> {
* 제 생각에, #488 은 그냥 close하면 될 것 같습니다.
  * 이전 논의에서 이야기한대로, `CpuToken`이라는 type을 굳이 추가하지 말고 그냥 `KernelCtx`가 하나만 존재하도록 하면 될 것 같습니다.
* 위 함수를 unsafe fn으로 변경하는 것은 이 PR에서 하셔도 되고, 아니면 다른 PR에서 하셔도 될 것 같습니다.

2021-04-17 08:32 UTC, jeehoonkang requested changes

2021-04-17 08:32 UTC, jeehoonkang commented on kernel-rs/src/console.rs
> +                .current_ctx()
kernel()에서 current_ctx()를 뽑아내기보다는, `kernel_ctx()` 를 부르는 API를 노출하면 어떨까 합니다. 표현하고 싶은 아이디어는 kernel init한느 곳을 제외하고는 모두 kernel에 직접 접근하면 안됩니다.

2021-04-17 08:32 UTC, jeehoonkang commented on kernel-rs/src/file.rs
> +    pub fn stat(&self, addr: UVAddr, ctx: &mut KernelCtx<'_>) -> Result<(), ()> {
이 PR은 아니고 나중에 생각해볼 수도 있는데: KernelCtx의 메서드인 것도 말이 되보이는데 어떻게 보시나요?

2021-04-17 08:32 UTC, jeehoonkang commented on kernel-rs/src/proc.rs
> +    pub unsafe fn yield_cpu(&self) {
걍 yield인건 어떨지? (강한 의견은 아닙니다.)

2021-04-17 08:32 UTC, jeehoonkang commented on kernel-rs/src/proc.rs
> +    pub fn current_ctx(&self) -> Option<KernelCtx<'_>> {
위에서 `unsafe fn kernel_ctx()`를 제안드렸습니다. 검토 부탁드립니다.

2021-04-17 08:32 UTC, jeehoonkang commented on kernel-rs/src/syscall/proc.rs
> +        self.kernel.procs().kill(pid)?;
이거 혹시 자기 자신도 kill할 수 있나요? 그런 경우 ok가 나올 수 있나요?
질문드리는 까닭은 `&self` 외에 `&mut self`가 필요하진 않은지 궁금해서요

2021-04-17 08:32 UTC, jeehoonkang commented on kernel-rs/src/syscall/proc.rs
> +    pub fn sys_poweroff(&self) -> Result<usize, ()> {
좀 애매하긴 한데 의미상으로는 &mut self가 맞아보이긴 합니다. 다만 어차피 꺼지는 명령 내린 후에는 다 같이 손잡고 망하는거라 &self로만 해도 컴파일이 잘 되는 것 같고...

혹시 어떻게 생각하는지 궁금합니다.

2021-04-17 08:32 UTC, jeehoonkang commented on kernel-rs/src/trap.rs
> +    unsafe { usertrapret(ctx) };
`fn KernelCtx::usertrapret(self)`는 어떨지 궁금합니다.  비슷한 함수에 대해서도 가능하면 KernelCtx 안으로 보내면 좋을 것 같습니다.

2021-04-17 08:32 UTC, jeehoonkang commented on kernel-rs/src/trap.rs
> -        if let Some(proc) = kernel.current_proc() {
위 174 라인에서부터 걍 `kernel_ctx()`를 부를 수도 있을가요?

2021-04-17 08:32 UTC, jeehoonkang commented on kernel-rs/src/proc.rs
> +    pub proc: CurrentProc<'p>,
currentproc은 이제 아예 없앨 수도 있나요?
 굳이 없어도 되는 abstraction인 것 같아서요

2021-04-19 08:56 UTC, Medowhill commented on kernel-rs/src/proc.rs
> +    pub unsafe fn yield_cpu(&self) {
<https://github.com/kaist-cp/rv6/pull/385/files#r569951090> 예전에 관련 논의가 있었는데 yield가 reserved keyword라 사용하지 못한다고 합니다. 주석으로 yield가 reserved keyword라는 설명을 추가하겠습니다.

2021-04-19 09:05 UTC, Medowhill commented on kernel-rs/src/syscall/proc.rs
> +        self.kernel.procs().kill(pid)?;
가능하고 ok가 나오는 것 같습니다. `self.kernel.procs().kill(pid)`을 하면 주어진 pid의 프로세스를 찾아 `killed`를 `true`로 바꾸는데, `killed`가 `AtomicBool`이기 때문에 수정할 때 shared reference만 필요합니다. 프로세스의 데이터 중 `info`는 락으로 보호받고 `killed`는 atomic이기 때문에, 수정할 때 mutable reference가 필요한 경우는 `data`(페이지 테이블, 열려 있는 file descriptor, cwd 등)에 접근할 때뿐입니다.

2021-04-19 11:52 UTC, Medowhill commented on kernel-rs/src/syscall/proc.rs
> +    pub fn sys_poweroff(&self) -> Result<usize, ()> {
`&mut KernelCtx`가 필요한 경우는 현재 프로세스의 데이터(`ProcData`)를 수정하려는 경우입니다. 커널의 대부분이 락으로 보호받고 있기 때문에 그 이외의 경우에는 데이터를 수정할 때도 `&KernelCtx`로 충분합니다. 또한, 어차피 `KernelCtx`는 `&Kernel`을 가지고 있기 때문에 `&mut KernelCtx`가 있어도 `&mut Kernel`을 의미하는 것이 아닙니다.

`sys_poweroff`가 하는 일은 MMIO 레지스터에 값을 쓰는 것인데, 위 사실을 바탕으로 보면 그냥 `&KernelCtx`를 받아도 의미상으로 큰 문제는 없다고 생각합니다. 어차피 poweroff가 실행되는 순간 이 스레드가 종료되는 것이니 `panic!()`을 호출하는 것과 비슷하다고 이해하는 방법도 있을 것 같습니다.

2021-04-19 14:00 UTC, Medowhill commented on kernel-rs/src/proc.rs
> +    pub proc: CurrentProc<'p>,
`CurrentProc`은 `Proc`의 `data`와 `MaybeUninit`으로 정의되어 있는 필드에 안전하게 접근할 수 있는 메서드를 제공하기 때문에 `Proc`에 비해 추가적인 능력을 가집니다. 지금은 `CurrentProc`이 `KernelCtx`의 필드이기 때문에 `CurrentProc`을 mutable하게 빌린 상태에서 `&Kernel`을 사용할 수 있지만, `CurrentProc`의 메서드들을 `KernelCtx`로 옮기게 되면 해당 메서드를 사용하는 중에 `&Kernel`을 사용할 수 없게 되는 문제가 있습니다.

2021-04-19 14:02 UTC, Medowhill commented on kernel-rs/src/trap.rs
> -        if let Some(proc) = kernel.current_proc() {
`kerneltrap`은 커널 모드에서 발생한 인터럽트를 처리하기 때문에 실행 중인 유저 프로세스가 없는 상태에서도 호출될 수 있습니다. 이 경우 `CurrentProc`이 존재하지 않으므로 `KernelCtx`를 만들 수 없습니다. `CurrentProc`이 없는 경우에도 `&Kernel`을 사용해야 하기 때문에 `kernel_ctx`를 호출해서는 안 됩니다.

2021-04-19 14:04 UTC, Medowhill commented on kernel-rs/src/console.rs
> +                .current_ctx()
아래 `kerneltrap`에서 설명한 것처럼, `KernelCtx` 없이 `&Kernel`을 사용해야 하는 경우가 있습니다. `kernel_ctx`와 `Kernel::current_proc`을 둘 다 유지해야 할 것 같습니다.

2021-04-19 14:06 UTC, Medowhill commented on kernel-rs/src/file.rs
> +    pub fn stat(&self, addr: UVAddr, ctx: &mut KernelCtx<'_>) -> Result<(), ()> {
`KernelCtx`의 메서드로 바꿔도 되기는 하는데, `File::read`와 `File::write`은 `File`의 메서드인데 `File::stat`만 `KernelCtx`로 옮기는 것이 자연스러운지는 잘 모르겠습니다. 참고로 `File::read`와 `File::write`도 `KernelCtx`를 인자로 받습니다.

2021-04-19 14:07 UTC, Medowhill commented on kernel-rs/src/file.rs
> +    pub fn stat(&self, addr: UVAddr, ctx: &mut KernelCtx<'_>) -> Result<(), ()> {
만약 `File::read`와 `File::write`까지 `KernelCtx`로 옮기려면, `File`의 `readable`과 `writable` 필드를 `pub`으로 바꿔야 합니다.

2021-04-19 15:18 UTC, jeehoonkang requested changes

2021-04-19 15:18 UTC, jeehoonkang commented on kernel-rs/src/proc.rs
> +    pub proc: CurrentProc<'p>,
이 디자인 고려사항을 주석으로 남겨주시기 부탁드려요

2021-04-19 15:18 UTC, jeehoonkang commented on kernel-rs/src/lock/sleeplock.rs
> +        *guard = unsafe { kernel_ctx() }.proc.pid();
얘도 kernel mode에서 acquire 함수가 불릴 수 있으므로 `kernel_ctx()` 호출이 위험하지 않은지 궁금합니다.

2021-04-19 15:18 UTC, jeehoonkang commented on kernel-rs/src/trap.rs
> +    // SAFETY: usertrap can be reached only after the initialization of the kernel
kernel_ctx()를 부르는 곳에 safety condition이 추가되어야 하지 않나요? 한번에 2개가 생기면 안된다던지...

2021-04-19 15:18 UTC, jeehoonkang commented on kernel-rs/src/virtio/virtio_disk.rs
> +                &unsafe { kernel_ctx() },
마찬가지로 위험하지 않은지?

2021-04-20 12:40 UTC, Medowhill commented on kernel-rs/src/lock/sleeplock.rs
> +        *guard = unsafe { kernel_ctx() }.proc.pid();
Current proc이 없으면 `kernel_ctx`가 panic하므로 위험하지는 않습니다. 이 PR 이전에도 current proc이 없을 때 sleep lock을 acquire하려고 시도하면 panic했고, sleep lock의 의미는 lock을 바로 얻을 수 없으면 현재 프로세스를 sleep하는 것이니 current proc이 없으면 panic하는 것이 올바른 것 같습니다.

2021-04-20 12:43 UTC, Medowhill commented on kernel-rs/src/virtio/virtio_disk.rs
> +                &unsafe { kernel_ctx() },
마찬가지로 위험하지 않습니다. `sleep` 역시 현재 프로세스를 sleep시키는 것이니 current proc이 없으면 panic하는 것이 합당하다고 생각합니다.

2021-04-20 13:15 UTC, jeehoonkang requested changes
current_proc()이 필요한 경우가 언제 있나요? 가능하면 그런 경우는 없도록 디자인할 수 있으면 좋을 것 같아 제안들비니다.

2021-04-20 13:15 UTC, jeehoonkang commented on kernel-rs/src/lock/sleeplock.rs
> +        *guard = unsafe { kernel_ctx() }.proc.pid();
제 의견은- SAFETY condition으로 unsafe가 사실 safe한 이유를 적어야 하는거 아닌가 합니다. 그 이유는 바로 concurrent currentproc, kernelctx가 없기 때문에... kernelctx()를 호출하는 모든 곳에 같은 코멘트 드립니다.

2021-04-20 13:15 UTC, jeehoonkang commented on kernel-rs/src/virtio/virtio_disk.rs
> +                &unsafe { kernel_ctx() },
위와 같은 comment 드립니다.

2021-04-20 13:18 UTC, Medowhill commented on kernel-rs/src/lock/sleeplock.rs
> +        *guard = unsafe { kernel_ctx() }.proc.pid();
`KernelCtx`가 존재하지 않는다는 것을 보장할 수 없기 때문에 (더 정확히는 `usertrap`에서 `KernelCtx`를 만들었으니 `KernelCtx`가 사실은 존재할 테니) 해당 unsafe가 safe하다고 주장할 수 없습니다. TODO에 적힌 대로, 나중에 `kernel_ctx` 호출을 없애야지만 안전함이 보장되는 코드라고 생각합니다.

2021-04-20 13:26 UTC, Medowhill commented
`riscv` 브랜치에서 `current_proc`이 안전하지 않은 방식으로 사용되는 경우는
* `console.rs`
* `lock/sleeplock.rs`의 `acquire`와 `holding`, `lock/sleepablelock.rs`의 `sleep`
* `virtio/virtio_disk.rs`의 `Disk::rw`
* `proc.rs`의 `Procs::wakeup_pool`

입니다.

말씀하신 것처럼 모두 `current_proc`을 없애야 하며, 이미 TODO로 표시되어 있습니다.

2021-04-20 14:33 UTC, jeehoonkang commented
bors r+

2021-04-20 14:40 UTC, merged