Make `KernelCtx::{kernel, proc}` fields into private
kaist-cp/rv6 pull request #493
Opened 2021-04-23 06:33 UTC by travis1829

참고: https://github.com/kaist-cp/rv6/pull/490#discussion_r614735246

* `KernelCtx`의 `kernel`와 `proc` field를 private field로 변환했습니다.
  ```Rust
  pub struct KernelCtx<'p> {
      kernel: &'p Kernel,
      proc: CurrentProc<'p>,
  }
  
  impl<'p> KernelCtx<'p> {
      pub fn kernel(&self) -> &'p Kernel {
          &self.kernel
      }
  
      pub fn proc(&self) -> &CurrentProc<'p> {
          &self.proc
     }
  
      pub fn proc_mut(&mut self) -> &mut CurrentProc<'p> {
          &mut self.proc
      }
  }
  ```
* 이외에는, 그저 기계적으로
  * `self.kernel` -> `self.kernel()`로
  * `self.proc` -> `self.proc()` (또는 `self.proc_mut()`)
로 변환한 것 뿐입니다.

2021-04-23 06:42 UTC, travis1829 commented on kernel-rs/src/proc.rs
> +    pub fn kernel(&self) -> &'p Kernel {
이렇게 리턴 타입을 `&'p Kernel`으로 하게되면, `self`를 borrow하지 않고 그냥 `&'p Kernel`을 copy하게 되므로 문제가 생기지 않는 것 같습니다.

2021-04-26 06:09 UTC, Medowhill requested changes
~~`KernelCtx` 외부에서는 `kernel()`, `proc()` 등을 통해 접근한다 하더라도, `KernelCtx` 내부에서는 그냥 `kernel`, `proc`을 사용하는 것이 나아 보입니다.~~

2021-04-26 08:18 UTC, Medowhill requested changes
`proc.rs`의 `proc()`들만 `proc`으로 바꿔 주시면 merge하겠습니다. 사소한 PR이니 빨리 merge해 버립시다.

2021-04-26 08:26 UTC, Medowhill commented
bors r+

2021-04-26 08:33 UTC, merged