[Closes #443] Safe list that does not own its nodes
kaist-cp/rv6 pull request #495
Opened 2021-04-23 13:21 UTC by travis1829

Closes #443 

#443 을 `Branded`를 사용하지 않는 다른 방법으로 해결해보았습니다.
핵심은 다음과 같습니다.
* `NodeRef`, `NodeMut`는 `Node`가 `List` 안에 있는 동안에만 존재합니다.
* `Node`를 immutably access하려면, 항상 1) `NodeRef`와 2) `ListRef`가 둘다 필요합니다.
* `Node`를 mutably access하려면, 항상 1) `NodeMut`와 2) `ListMut`가 둘다 필요합니다.
* 하나의 `List`에 대해, `NodeMut`는 항상 단 한개만 존재합니다.
* `Node`가 `List`안에 있는 상태에서 drop되면 panic합니다. (유일한 runtime cost)

이렇게 하면, lifetime 제한이나 functionality 제한 등을 걸지 않더라도 linked list를 safe하게 구현할 수 있습니다.

2021-04-28 12:35 UTC, jeehoonkang requested changes

2021-04-28 12:35 UTC, jeehoonkang commented on kernel-rs/src/util/list2.rs
> +    pub unsafe fn as_ref_unchecked<'s>(&'s self, _list_ref: &'s ListRef<'_, T>) -> NodeRef<'s, T> {
branded를 쓰면 이 함수를 safe로 만들 수 있지 않나요? safety invariant를 static하게 보장할 수 있을 것 같아서요.

2021-04-28 13:20 UTC, travis1829 commented on kernel-rs/src/util/list2.rs
> +    pub unsafe fn as_ref_unchecked<'s>(&'s self, _list_ref: &'s ListRef<'_, T>) -> NodeRef<'s, T> {
저도 이 부분에 대해서 고민을 많이 해봤는데, 결론만 말씀드리자면 **이 함수는 그대로 unsafe로 두고, 이 함수를 safe한 함수로 감싸는 건 user에게 맡겨야 할 것 같습니다.**

말씀하신 것처럼 `BrandedNode<'id, '_>`같은 걸 추가하면 `BrandedNode`로부터 `NodeRef`를 얻는 건 safe하게 가능할 것 같습니다. 다만, 문제는, 이러면 `BrandedNode`를 얻는 함수가 어차피 unsafe이여야할 것 같습니다. 즉, **`unsafe`이 다른 함수로 옮겨지는 것 뿐이지, `unsafe`를 한번도 통과하지 않고 `NodeRef`를 얻을 수 없을 것 같습니다.**
* 참고로, `ListRef`/`ListMut`의 method들 중에는 `BrandedNode`가 필요한 method이 없으며, `Node`의 method들 중에서도 `BrandedNode`가 필요한 method는 `as_ref_unchecked, as_mut_unchecked`뿐입니다.
* `ListRef`/`ListMut`의 method들이 `NodeRef`/`NodeMut`가 아니라 `BrandedNode`를 리턴하게끔 할 수는 있겠지만, 이렇게 할 이유가 없습니다.
  * `BrandedNode<'id, '_>`는 `Node`가 `List<'id, '_>`내에 존재하는 동안에만 존재해야 합니다. 즉, `NodeRef`/`NodeMut`와 마찬가지로 어차피 계속 `List`를 borrow해야 하므로 `NodeRef`/`NodeMut`와 `BrandedNode`사이의 차이가 사실상 없습니다. 또, `BrandedNode`를 가지고서는 할 수 있는 일이 `BrandedNode`를 `NodeRef`/`NodeMut`로 변환하는 것 뿐인데, 이럴바에는 `List`의 method들이 처음부터  `NodeRef`/`NodeMut`를 리턴하도록 하는게 낫습니다.

2021-04-28 13:52 UTC, jeehoonkang commented on kernel-rs/src/util/list2.rs
> +    pub unsafe fn as_ref_unchecked<'s>(&'s self, _list_ref: &'s ListRef<'_, T>) -> NodeRef<'s, T> {
list<'id>에서 파생한 iterator<'id>를 돌다가 node<'id>를 safe하게 얻을 수 있지 않을까요?

2021-04-28 14:00 UTC, travis1829 commented on kernel-rs/src/util/list2.rs
> +    pub unsafe fn as_ref_unchecked<'s>(&'s self, _list_ref: &'s ListRef<'_, T>) -> NodeRef<'s, T> {
아쉽게도 `Branded`는 closure안에서만 사용될 수 있으므로, `List`/`Node` 자체에 `'id` tag를 붙여버리게 되면 stack이외의 곳에서는 사용하기 매우 까다로울 것 같습니다. 현재 `Kernel`이나 `Procs`같은 곳들에 `'id` tag를 붙이지 않은 것도 비슷한 이유입니다.
* 사실, 이 부분은 Rust의 한계라고 보는게 맞을 것 같습니다.

2021-04-28 16:12 UTC, Medowhill requested changes
태우님께서 이 PR의 리스트 역시 stacked borrow를 어기는 것 같다고 전에 말씀해 주시긴 했는데, 실제로도 그런 것 같습니다.


```rust
let mut node = unsafe { Node::new(0u32) };
let mut node = unsafe { Pin::new_unchecked(&mut node) };
node.as_mut().init();

let mut list = unsafe { List::<u32>::new() };
let mut list = unsafe { Pin::new_unchecked(&mut list) };
list.as_mut().init();
let mut list = list.as_list_mut();

list.push_front(node.as_mut());
println!("{}", node.as_mut().get_mut_inner().is_some());
list.pop_front();
println!("{}", node.as_mut().get_mut_inner().is_some());
```

`node`는 `&mut`이므로 exclusive access가 보장됩니다. 따라서 `node.as_mut().get_mut_inner()`의 결과는 `list.pop_front();` 전후에 바뀌지 않아야 합니다. 그러나 `list.pop_front()` 전에는 `false`, 후에는 `true`가 출력됩니다.

해결 방법은 아직 잘 모르겠습니다..

2021-04-29 10:43 UTC, travis1829 commented
* `Cursor`, `CursorMut`를 추가했습니다.
* `ListRef`, `ListMut`, `NodeRef`, `NodeMut`를 모두 없앴습니다.

2021-04-29 10:45 UTC, travis1829 commented on kernel-rs/src/util/list2.rs
> +    pub unsafe fn as_ref_unchecked<'s>(&'s self, _list_ref: &'s ListRef<'_, T>) -> NodeRef<'s, T> {
오늘 회의에서 이야기한대로, `Cursor`, `CursorMut`를 추가했습니다.

2021-04-29 13:15 UTC, travis1829 commented
module이름을 변경했습니다.
* list.rs -> intrusive_list.rs
* list2.rs -> list.rs

2021-04-30 02:34 UTC, Medowhill commented
bors r+

2021-04-30 02:47 UTC, merged