[Closes #298] Uart & Console refactoring
kaist-cp/rv6 pull request #503
Opened 2021-04-28 16:45 UTC by Medowhill

`Uart`와 `Console`을 리팩토링하는 PR입니다.

* `Uart`와 `Console`이 상호 의존적이기 때문에 어느 한쪽이 다른 하나를 소유한다고 보기 어려운 것 같아, 구조는 그대로 두고 대부분의 메서드가 `KernelRef`나 `KernelCtx`를 받도록 만들었습니다.
* `Uart`가 MMIO 레지스터를 소유하는 개념을 명확히 했습니다. 여러 `Uart`가 동시에 존재할 수 있으므로, `Uart`는 만들어질 때 MMIO 레지스터의 위치를 인자로 받습니다.

2021-04-28 16:58 UTC, jeehoonkang requested changes

2021-04-28 16:58 UTC, jeehoonkang commented on kernel-rs/src/console.rs
> +            kernel.uart.putc_sync(c, kernel);
console에서 uart에 접근할때 kernel을 통해서 하는데, 혹시 console이 uart를 소유하는 방식으로도 가능할지 궁금합니다.

2021-04-28 16:58 UTC, jeehoonkang commented on kernel-rs/src/console.rs
> +pub struct Printer;
Printer는 혹시 없어도 되지 않나 하는 생각이 좀 드는데 어떻게 보시나요? Console과 분리한 motivation이 무엇인지 궁금합니다.

2021-04-28 16:58 UTC, jeehoonkang commented on kernel-rs/src/trap.rs
> +                // SAFETY: it's unsafe only when ctrl+p is pressed.
이게 의도적인 race임을 본 기억이 나네요. 혹시 문제가 되진 않을까요?

2021-04-28 17:06 UTC, coolofficials commented on kernel-rs/src/console.rs
> +pub struct Printer;
https://github.com/kaist-cp/rv6/pull/297#issue-529656664

제가 기억하기로는 자세하지는 않지만 console과 printer가 특정 상황에서 서로 다른 lock으로 보호되어야 하는 경우가 있었습니다. 그 이후로 많은 수정이 있어서 현재는 어떤지 잘 모르겠습니다.

2021-04-28 17:11 UTC, Medowhill commented on kernel-rs/src/console.rs
> +pub struct Printer;
사실 safety 관점에서는 `Printer`가 굳이 필요하지 않습니다. 커널 모드에서 콘솔에 출력할 때는 volatile write을 하기 때문에 동기화 없이 그냥 MMIO 레지스터에 값을 쓰면 됩니다. 하지만, 여러 스레드에서 동시에 콘솔에 출력을 시도하면, 일반적으로 한 스레드에서 한 문자만 출력하는 것이 아니라 문자열을 출력하기 때문에, 여러 스레드의 문자열이 interleaving된 형태로 출력될 수 있습니다. 이는 safety 문제는 아니지만 기능적으로는 문제입니다. 그래서 xv6에서는 한번에 한 스레드만 출력하도록 printf를 락으로 보호하고, 마찬가지로 rv6에서도 print할 때 보호해 주는 락이 필요합니다. 이 락을 `Console`에 걸 수는 없으므로, print를 하기 위한 타입인 `Printer`를 추가하고 `Printer`를 락으로 보호하는 것입니다.

2021-04-28 17:12 UTC, Medowhill commented on kernel-rs/src/console.rs
> +pub struct Printer;
저도 `Printer`를 없애고 싶기는 한데 지금까지 시도해 봤을 때는 `Printer`가 있는 쪽이 구현이 더 깔끔한 것 같습니다.

2021-04-28 17:16 UTC, Medowhill commented on kernel-rs/src/trap.rs
> +                // SAFETY: it's unsafe only when ctrl+p is pressed.
ctrl+p를 눌렀을 때 프로세스 리스트를 dump하는 기능은 디버깅을 위해서 안전성을 무시하고 존재하는 기능이니, rv6 안전성을 이야기할 때는 해당 기능은 배제하고 이야기해야 할 것 같습니다. 즉, "rv6는 ctrl+p를 누르지 않으면 안전하다" 또는 "ctrl+p를 눌렀을 때 dump를 호출하는 줄만 지우면 안전하다"라고 주장해야 합니다. dump 자체가 OS의 기능이라기보다는, 디버깅을 위해 의도적으로 안전성을 포기한 것이니 저희의 contribution에 지장이 되지는 않을 것 같습니다.

2021-04-28 17:16 UTC, Medowhill commented on kernel-rs/src/console.rs
> +            kernel.uart.putc_sync(c, kernel);
한번 시도해 보겠습니다.

2021-04-29 08:49 UTC, Medowhill commented
* `Uart`에는 실제 하드웨어랑 상호작용하는 부분만 남겼습니다.
* `Console`이 output buffer와 input buffer를 가지고 있고, 각 buffer를 별개의 sleepablelock으로 보호합니다.
* `Console`이 `Uart`를 가지고 있습니다.

2021-04-29 12:42 UTC, jeehoonkang approved these changes
bors r+

2021-04-29 12:49 UTC, merged