Easy 2021 05 01
kaist-cp/rv6 pull request #524
Opened 2021-04-30 16:23 UTC by jeehoonkang

D-easy 다 해결했습니다

2021-04-30 17:24 UTC, coolofficials requested changes
AsBytes와 FromBytes를 제가 주말에 하려고 했는데 해주셨길래 리뷰 남겨봅니다.

2021-04-30 17:24 UTC, coolofficials commented on kernel-rs/src/vm.rs
>              unsafe { core::slice::from_raw_parts_mut(src as *const _ as _, mem::size_of::<T>()) },
여기도 AsBytes의 API를 사용하여
```
pub fn copy_out<T: AsBytes>(&mut self, dstva: UVAddr, src: &T) -> Result<(), ()> {
        self.copy_out_bytes(dstva, src.as_bytes())
    }
```

표현할 수 있을 것 같습니다.

2021-04-30 17:24 UTC, coolofficials commented on kernel-rs/src/fs/inode.rs
> +    pub fn write_kernel<T: AsBytes>(
AsBytes의 API를 사용하여
```
pub fn write_kernel<T: AsBytes>(
        &mut self,
        src: &T,
        off: u32,
        tx: &FsTransaction<'_>,
    ) -> Result<(), ()> {
        let bytes = self.write_bytes_kernel(src.as_bytes(), off, tx)?;
        if bytes == mem::size_of::<T>() {
            Ok(())
        } else {
            Err(())
        }
    }
```

와 같이 사용할 수 있을 것 같습니다. https://docs.rs/zerocopy/0.3.0/zerocopy/trait.AsBytes.html

2021-04-30 17:24 UTC, coolofficials commented on kernel-rs/src/fs/inode.rs
> +    pub fn read_kernel<T: FromBytes>(
AsBytes의 API를 사용하여 다음과 같이 사용할 수 있을 것 같습니다.
```
    pub fn read_kernel<T: AsBytes + FromBytes>(&mut self, dst: &mut T, off: u32) -> Result<(), ()> {
        let bytes = self.read_bytes_kernel(dst.as_bytes_mut(), off);
        if bytes == mem::size_of::<T>() {
            Ok(())
        } else {
            Err(())
        }
    }
```

2021-04-30 17:26 UTC, coolofficials commented on kernel-rs/src/vm.rs
> +    pub unsafe fn copy_in<T: FromBytes>(&mut self, dst: &mut T, srcva: UVAddr) -> Result<(), ()> {
```  
  pub fn copy_in<T: AsBytes + FromBytes>(
        &mut self,
        dst: &mut T,
        srcva: UVAddr,
    ) -> Result<(), ()> {
        self.copy_in_bytes(dst.as_bytes_mut(), srcva)
    }
```

2021-04-30 17:43 UTC, coolofficials approved these changes
좋은 것 같습니다.

2021-05-01 05:19 UTC, Medowhill approved these changes

2021-05-01 05:19 UTC, Medowhill commented
bors r+

2021-05-01 05:25 UTC, merged