1
kaist-cp/rv6 pull request #549
Opened 2021-05-27 08:44 UTC by Medowhill

2021-05-27 08:57 UTC, Medowhill commented
* `SharedMut<T>` 추가
  * `*mut T`를 가지고 있음.
  * 하나만 존재 가능. (`&mut`과 동일)
  * `*mut`과 공존 가능. (`&mut`과 다름)
* `RcCell<T>`
  * 수정을 위해서는 `SharedMut<RcCell<T>>`가 필요.
  * Interior mutability가 필요하지 않으므로 `struct RcCell<T>(T, usize)`로 정의됨.
* `Ref<T>`, `RefMut<T>`
  * `*mut RcCell<T>`을 가지고 있음.
  * Reference count를 수정하려면 `SharedMut<RcCell<T>>` 필요.
  * **각 메서드에서 가지고 있는 포인터와 인자로 주어진 `SharedMut<RcCell>`이 같은지 확인하는 runtime cost 발생.** `Arena`에서 `RcCell`을 사용할 것을 생각하면, 한 `Arena`에 `RcCell`이 여럿 있기 때문에 branded type을 사용해서 해결할 수 없음.
* `Arena`
  * **`dup`/`dealloc`에서 주어진 `Ref<T>`를 복사/제거하려면 그 `Ref<T>`와 같은 `RcCell`을 가리키는 `SharedMut<RcCell<T>>`를 찾기 위해 `RcCell` 리스트를 탐색해야 하므로 runtime cost 발생(시간 복잡도가 `O(1)`에서 `O(n)`이 됨).** `ArrayArena`라면 포인터 연산을 사용하여 `O(1)`으로 줄일 수도 있겠지만, `ListArena`에서는 그럴 수 없음.

2021-05-27 15:14 UTC, jeehoonkang requested changes

2021-05-27 15:14 UTC, jeehoonkang commented on kernel-rs/src/file.rs
> -            unsafe { A::reacquire_after(guard, cleanup) };
이제 reacquire_after가 필요없게 되었나요?

2021-05-27 15:14 UTC, jeehoonkang commented on kernel-rs/src/fs/ufs/inode.rs
> +                drop(ip);
이거 drop 명시적으로 안해도 되나요?

2021-05-27 15:14 UTC, jeehoonkang commented on kernel-rs/src/fs/ufs/inode.rs
> -                    A::reacquire_after(guard, cleanup);
여기도 reacquire_after가 없어지는군요... 왜 이런 좋은(?) 일이 일어났는지 궁금합니다.

2021-05-27 15:14 UTC, jeehoonkang commented on kernel-rs/src/util/rc_cell.rs
> -//! Similar to `RefCell<T>`, but provides lifetime-less `Ref<T>` and `RefMut<T>`.
주석을 없앴는데, 내용이 많이 바뀌어서 그런지 궁금합니다.
혹시 내용이 바뀌었다면 비슷한 주석을 남길 수 있으면 좋겠습니다

2021-05-27 15:14 UTC, jeehoonkang commented on kernel-rs/src/util/rc_cell.rs
> +        Self::rc(this).load(Ordering::SeqCst) > 0
acquire로도 될겁니다.

2021-05-27 15:14 UTC, jeehoonkang commented on kernel-rs/src/util/rc_cell.rs
> +        let refcnt = Self::rc(this.as_shared_mut());
이게 pointer를 들고있는 셈인데, 그냥 refcnt 변수 안만들고 바로 load하는게 어떨까 합니다.

2021-05-27 15:14 UTC, jeehoonkang commented on kernel-rs/src/util/rc_cell.rs
> +            let r = refcnt.load(Ordering::SeqCst);
early return으로 control flow를 바꾸면 좋겠습니다.

```
if (...) return None;

if (...) return Some;

refcnt.cmpxchg(...);
```

2021-05-27 15:14 UTC, jeehoonkang commented on kernel-rs/src/util/rc_cell.rs
> +                    refcnt.compare_exchange(r, r + 1, Ordering::SeqCst, Ordering::SeqCst),
둘다 relaxed로도 됩니다.

2021-05-27 15:14 UTC, jeehoonkang commented on kernel-rs/src/util/rc_cell.rs
> +            .compare_exchange(0, BORROWED_MUT, Ordering::SeqCst, Ordering::SeqCst)
질문: 이 API가 쓰이나요? get_mut으로 커버되지 않는 use case가 있나요

2021-05-27 15:14 UTC, jeehoonkang commented on kernel-rs/src/util/rc_cell.rs
> +        let _ = ok_or!(
`if ....is_err() { return Err(self); }`는 어떨까요?

2021-05-27 15:14 UTC, jeehoonkang commented on kernel-rs/src/util/rc_cell.rs
> +                .compare_exchange(1, BORROWED_MUT, Ordering::SeqCst, Ordering::SeqCst),
둘다 relaxed여도 됩니다.

2021-05-27 15:14 UTC, jeehoonkang commented on kernel-rs/src/util/rc_cell.rs
> +        let _ = self.rc().fetch_add(1, Ordering::SeqCst);
relaxed

2021-05-27 15:14 UTC, jeehoonkang commented on kernel-rs/src/util/rc_cell.rs
> +        let _ = self.rc().fetch_sub(1, Ordering::SeqCst);
**release** (not relaxed)

2021-05-27 15:14 UTC, jeehoonkang commented on kernel-rs/src/util/rc_cell.rs
> +        self.rc().store(0, Ordering::SeqCst);
release

2021-05-27 15:14 UTC, jeehoonkang commented on kernel-rs/src/util/shared_mut.rs
> +/// `SharedMut` can coexist with `*const` and `*mut`.
이게 pin2같은 건지 궁금합니다. 이 module의 safety를 좀더 면밀하게 검토해야하지 않을까해서 질문드려요

2021-05-29 05:16 UTC, Medowhill commented on kernel-rs/src/file.rs
> -            unsafe { A::reacquire_after(guard, cleanup) };
기존에는 `Rc`를 드롭할 때 `RcCell`의 rc를 수정해야 하므로 `Arena`의 락을 acquire해야만 했습니다. 하지만 `finalize` 안에서 해당 락을 잠시 release해야 하는 경우가 있어 `reacquire_after`를 사용했습니다. 이제는 rc가 `AtomicUsize`이므로 rc를 수정할 때 락을 acquire할 필요가 없고, 따라서 `finalize` 안에서 락을 잠시 release할 필요도 없습니다.

2021-05-29 05:24 UTC, Medowhill commented on kernel-rs/src/util/rc_cell.rs
> -//! Similar to `RefCell<T>`, but provides lifetime-less `Ref<T>` and `RefMut<T>`.
`Arc`와 비슷하지만 heap을 사용하지 않으며 드롭될 때 패닉할 수 있다는 주석을 추가했습니다. 그 이외의 기존 주석은 모두 `RcCell`과 `RefCell`과의 연관성에 대한 것이었는데, 이제는 `RefCell`과의 연관성이 없기 때문에 지우도록 하겠습니다.

2021-05-29 05:27 UTC, Medowhill commented
`RcCell`에는 더 이상 interior mutability가 없으니 다른 이름을 붙여야 할 것 같습니다. Standard library의 `Arc`와 거의 유사(<https://doc.rust-lang.org/src/alloc/sync.rs.html#302-312>)하지만 힙에 할당되지 않는다는 점이 가장 큰 차이입니다. 이름에 `Arc`를 포함하되 이 차이점을 드러낼 수 있는 이름이 좋을 것 같습니다.

2021-05-29 05:31 UTC, jeehoonkang commented
ArcCell? 모종의 int. mut.이 있는건 맞아보이긴 합니다 pin2<&mut>을 가지고 data에 mutably 접근할 수 있으니...

2021-05-29 05:34 UTC, Medowhill commented
해당 능력은 `Arc`에도 동일하게 있습니다.

`pub fn get_mut(this: &mut Arc<T>) -> Option<&mut T>`

<https://doc.rust-lang.org/std/sync/struct.Arc.html#method.get_mut>

Mutable reference(또는 그와 유사한 스마트 포인터)를 받아 rc를 검사하여 유일한 접근이 보장되면 내부 데이터에 대한 mutable reference를 제공하는 기능은 `UnsafeCell`을 필요로 하지도 않고 shared reference를 받아 데이터를 수정하는 것도 아니므로 interior mutability라고 볼 필요는 없는 것 같습니다.

2021-05-31 08:31 UTC, Medowhill commented
bors r+

2021-05-31 08:37 UTC, merged