Closes #539
kaist-cp/rv6 pull request #554
Opened 2021-05-31 16:04 UTC by Medowhill

Closes #539

`RawSleeplock`이 `acquire`와 `release`할 때 `KernelCtx`를 인자로 받습니다. 이제 `RawSleeplock`이 `RawLock`을 구현하지 않습니다. 이렇게 해도 코드 중복이 많아 보이지는 않습니다.

2021-05-31 18:48 UTC, jeehoonkang requested changes

2021-05-31 18:48 UTC, jeehoonkang commented on kernel-rs/src/bio.rs
> +    pub fn free(self, ctx: &KernelCtx<'_, '_>) {
name: free는 약간 C스러운데(..) 다른 이름이 혹시 있나요? rv6 내 다른 곳에서 이런 경우 어떤 이름을 썼느닞 궁금합니ㅏㄷ.

2021-05-31 18:48 UTC, jeehoonkang commented on kernel-rs/src/fs/ufs/inode.rs
> +            match f(tot, &bp.deref_inner().data[begin..end], k) {
여기서 코드의 느낌적 느낌이 별로 안좋은데 혹시 좀더 ergonomic하게 쓸 수 있는 방법이 있을까요? 가령 f가 bp를 받아서 free하는건 어떨지 궁금합니다.

2021-06-01 02:31 UTC, Medowhill commented on kernel-rs/src/bio.rs
> +    pub fn free(self, ctx: &KernelCtx<'_, '_>) {
기존에 존재하던 auto drop을 하지 않는 타입인 `UserMemory`, `PageTable`, `Descriptor`, `Page`의 경우 모두 `free`라는 이름을 사용하고 있습니다.

2021-06-01 02:39 UTC, Medowhill commented on kernel-rs/src/fs/ufs/inode.rs
> +            match f(tot, &bp.deref_inner().data[begin..end], k) {
`f`가 `Result<K, K>` 대신 `(K, bool)`을 반환하도록 수정했습니다.

2021-06-01 02:52 UTC, jeehoonkang requested changes

2021-06-01 02:52 UTC, jeehoonkang commented on kernel-rs/src/fs/ufs/inode.rs
> +        F: FnMut(u32, &[u8], K) -> (bool, K),
이렇게되면 걍 &mut K를 받는게 어떤가요?

2021-06-01 03:23 UTC, Medowhill commented on kernel-rs/src/fs/ufs/inode.rs
> +        F: FnMut(u32, &[u8], K) -> (bool, K),
그렇게 할 수는 있지만, 그러면 `&KernelCtx` 대신 `&&KernelCtx`가 인자로 넘어가게 돼 indirection이 추가됩니다.

2021-06-01 03:30 UTC, Medowhill commented
bors r+

2021-06-01 03:36 UTC, merged