Arm
kaist-cp/rv6 pull request #568
Opened 2021-07-19 05:47 UTC by Gabriel4256

* architecture dependent한 부분들 분리하고 Makefile에서 옵션에 따라 다른 architecture로 실행하도록 했습니다.
* linker script (kernel.ld) 수정
* ARM 버전은 현재 딱 booting만 됩니다. (command: `TARGET=arm make qemu`)

2021-07-19 12:48 UTC, jeehoonkang requested changes

2021-07-19 12:48 UTC, jeehoonkang commented on Makefile
> +ifeq ($(TARGET),riscv)
Arm에는 trampoline, kernelvec이 필요 없나요? 궁금해서 질문드립니다.

2021-07-19 12:48 UTC, jeehoonkang commented on Makefile
> +ifeq ($(ARCH),aarch64)
Architecture-dependent 상수들이 좀 있는데 위에서 한꺼번에 정의해도 될듯 합니다.

2021-07-19 12:48 UTC, jeehoonkang commented on Makefile
> +KERNELLD = $K/$(TARGET)/kernel.ld
제 느낌에 얘는 굳이 변수로 안만들어도 될듯 한데 혹시 어떻게 보시나요?

2021-07-19 12:48 UTC, jeehoonkang commented on Makefile
> +	*/*.o */*/*.o */*.d */*.asm */*.sym \
혹시 `**/*.o`도 되나요? 잘 몰라서 질문드립니다...

2021-07-19 12:48 UTC, jeehoonkang commented on Makefile
> +QEMUOPTS += -cpu cortex-a72
- RISC-V에서는 굳이 -cpu가 없는데 그래도 괜찮나요? Arm에선 없으면 문제가 되나요? (이 asymmetry는 좀의아해서 그 이유가 주석으로 남으면 좋겠습니다.)
- bios none에 대한 asymmetry도 주석으로 남겨주시면 좋겠습니다./

2021-07-19 12:48 UTC, jeehoonkang commented on README-rv6.md
> +- Run rv6 on qemu (ARM).
일반적으로 `ARM` 대신 `Armv8`이라고 합시다 (적절한 경우).

2021-07-19 12:48 UTC, jeehoonkang commented on README-rv6.md
> +- Run rv6 on qemu (riscv).
`RISC-V`

2021-07-19 12:48 UTC, jeehoonkang commented on kernel-rs/src/arch/arm/arm.rs
> +//! ARM instructions.
`arm.rs`: 혹시 `arch.rs` 정도가 어떨까 제안드립니다. `riscv.rs`도 `arch.rs`...

2021-07-19 12:48 UTC, jeehoonkang commented on kernel-rs/src/arch/arm/arm.rs
> +    unimplemented!()
요즘 더 많이 쓰이는 `todo!()`로 합시다 ㅎㅎ 나중에 채워 넣을 예정인거죠?

2021-07-19 12:48 UTC, jeehoonkang commented on kernel-rs/src/arch/arm/cpu.rs
> +use core::{
일반적으로 이 파일이 arch 폴더에 있어야할 이유가 있나요? 대부분 riscv, arm에 공통된 코드인 것 같아서요.

2021-07-19 12:48 UTC, jeehoonkang commented on kernel-rs/src/arch/arm/kernel.rs
> +use core::fmt::{self, Write};
cpu.rs와 마찬가지로 이것도 가능하면 공통된 코드로 뺐으면 합니다.

2021-07-19 12:48 UTC, jeehoonkang commented on kernel-rs/src/proc/mod.rs
> +#[cfg(target_arch = "riscv64")]
제 생각에 이 dispatch는 한꺼번에 한 파일에서만 다 일어나면 좋겠습니다. 가령 `lib.rs`에서...

2021-07-19 12:48 UTC, jeehoonkang commented on kernel/arm/swtch.S
> +
- 여기 원래 newline이 있나요?
- 이 코드는 어디서 가져온건지 궁금합니다. 주석으로 출처를 적어주면 좋겠습니다.

2021-07-19 12:48 UTC, jeehoonkang commented on kernel/arm/kernel.ld
> +OUTPUT_FORMAT("elf64-littleaarch64")
혹시 이 파일은 RISC-V와 많이 다른가요? 다르면 얼마나 다른가요?

2021-07-19 12:48 UTC, jeehoonkang commented on kernel/arm/entry.S
> +.equ _EL2, 0x8
역시 출처가 궁금합니다. 주석으로 써주시면 감사하겠습니다.

2021-07-23 03:38 UTC, Gabriel4256 commented on Makefile
> +ifeq ($(TARGET),riscv)
필요합니다. 추후 작성 예정입니다.

2021-07-23 03:51 UTC, Gabriel4256 commented on Makefile
> +	*/*.o */*/*.o */*.d */*.asm */*.sym \
실험해보니 안 되는 것 같습니다.

2021-07-23 04:31 UTC, Gabriel4256 commented on kernel-rs/src/arch/arm/arm.rs
> +//! ARM instructions.
해당 파일들의 parent module 이름이 `arch`라서 좀 중복되는 느낌이 있는 것 같은데, 혹시 `asm.rs`는 어떤가요?

2021-07-23 04:41 UTC, Gabriel4256 commented on Makefile
> +QEMUOPTS += -cpu cortex-a72
### CPU
* riscv qemu에서는 machine을 virt로 설정하면 자동으로 default cpu가 자동으로 설정이 됩니다. (rv64g)
  * https://qemu.readthedocs.io/en/latest/system/riscv/virt.html#supported-devices 
* 하지만 aarch64에서는 cpu를 무조건 지정해줘야 합니다. default cpu인 cortex-a15가 64bit 환경을 지원하지 않기 때문에
  * https://qemu.readthedocs.io/en/latest/system/arm/virt.html#supported-devices
  * > Note that the default is cortex-a15, so for an AArch64 guest you must specify a CPU type.

### bios
* riscv qemu에서는 machine을 `virt`로 설정할 시 boot option 중 하나로 `-bios none` option을 제공합니다.
  * https://qemu.readthedocs.io/en/latest/system/target-riscv.html#risc-v-cpu-firmware
* 반면에 aarch64에서는 해당 option에 대한 명확한 설명을 찾지 못했습니다. `-bios none` 옵션이 특정 environment에서만 사용 가능한 것으로 보입니다.

2021-07-23 04:45 UTC, Gabriel4256 commented on kernel/arm/kernel.ld
> +OUTPUT_FORMAT("elf64-littleaarch64")
거의 비슷합니다. 두 가지 차이점이 있습니다.
* 시작 주소가 다름 (`0x80000000` -> `0x40010000`)
* `trampoline` 파일의 위치를 고정하지 않음: 이건 나중에 다시 필요할 수도 있습니다.

2021-07-23 04:51 UTC, Gabriel4256 commented on kernel/arm/entry.S
> +.equ _EL2, 0x8
이 부분의 초기화가 OS 디자인에 따라서 달라지는 듯하여, 최대한 기존의 `entry.S` (RISC-V의)를 그대로 arm 버전으로 옮기면서 universal하게 적용될 것 같은 코드만 가져왔습니다. 일단 참조 정도로만 적어놓을까요?

2021-07-24 07:36 UTC, Gabriel4256 commented on Makefile
> +ifeq ($(ARCH),aarch64)
반영했습니다.

2021-07-24 07:36 UTC, Gabriel4256 commented on Makefile
> +KERNELLD = $K/$(TARGET)/kernel.ld
반영했습니다.

2021-07-24 07:37 UTC, Gabriel4256 commented on Makefile
> +QEMUOPTS += -cpu cortex-a72
주석으로 간단하게 설명과 링크 남겼습니다.

2021-07-24 07:42 UTC, Gabriel4256 commented on kernel/arm/swtch.S
> +
* newline 삭제했습니다.
* 주석으로 출처 추가했습니다.

2021-07-24 07:44 UTC, Gabriel4256 commented on README-rv6.md
> +- Run rv6 on qemu (ARM).
반영했습니다.

2021-07-24 07:45 UTC, Gabriel4256 commented on kernel-rs/src/arch/arm/arm.rs
> +    unimplemented!()
해당 부분의 코드를 추가하고, 다른 모든 `unimplemented!` 를 `todo!`로 바꿨습니다.

2021-07-24 07:45 UTC, Gabriel4256 commented on kernel-rs/src/arch/arm/cpu.rs
> +use core::{
반영했습니다.

2021-07-24 07:46 UTC, Gabriel4256 commented on kernel-rs/src/arch/arm/arm.rs
> +//! ARM instructions.
일단은 `asm.rs`로 하여 수정했습니다. 혹시 더 좋은 이름이 있다면 제안해주시면 감사하겠습니다.

2021-07-24 08:04 UTC, Gabriel4256 commented on kernel-rs/src/proc/mod.rs
> +#[cfg(target_arch = "riscv64")]
`lib.rs`에서만 일어나도록 수정했습니다.

2021-07-24 08:16 UTC, Gabriel4256 commented
지금까지 작성한 코드들 같이 정리해서 올렸습니다.

2021-07-26 09:56 UTC, jeehoonkang requested changes

2021-07-26 09:56 UTC, jeehoonkang commented on kernel-rs/Cargo.toml
> +tock-registers = { version = "0.7.x", default-features = false, features = ["register_types"]}
- tock-registers에 혹시 RISC-V는 없나요?
- 보다 일반적으로, 이런것들을 처리해주는 일반적인 라이브러리가 있으면 (지금은 꼭 아니더라도 나중에) 사용할 수 있으면 좋겠습니다.

2021-07-26 09:56 UTC, jeehoonkang commented on kernel-rs/src/arch/arm/addr.rs
> +pub trait Addr: Copy + From<usize> + Add<usize, Output = Self> {
이건 혹시 arm, riscv 공통된 코드 아닌가 싶은데 혹시 dedup할 수 있을까요?

2021-07-26 09:56 UTC, jeehoonkang commented on kernel-rs/src/arch/arm/memlayout.rs
> +pub const UART0: usize = 0x09000000;
- 혹시 (숫자는 다르더라도) UART0 이런 변수들은 arch 상관없이 공통적으로 등장하는 코드들인가요?
- 만약 그렇다면 더 generic하게 표현할 수 있지 않을까 해서요... 한번 확인/고민 부탁드립니다.

2021-07-26 09:56 UTC, jeehoonkang commented on kernel-rs/src/arch/arm/poweroff.rs
> +pub fn machine_poweroff(_exitcode: u16) -> ! {
위의 코멘트의 연장선상인데, `trait Arch` 와 같은걸 정의해서 이와 같은 method를 다 정의하고, RiscV, Armv8이 Arch를 impl하도록 구성할 순 있을지 궁금합니다.

2021-07-26 09:56 UTC, jeehoonkang commented on kernel-rs/src/arch/arm/vm.rs
> +    pub unsafe fn init_hart(&self) {
- "hart"는 RISC-V-specific한 단어일거에요
- vm.rs은 arch별로 나눠야만 하는 상황인가요? 적어도 interface라도 generic하게 (trait 등으로) 합칠 수 있는지 궁금합니다.

2021-07-26 09:56 UTC, jeehoonkang commented on kernel-rs/src/lib.rs
> +#[cfg(target_arch = "riscv64")]
혹시 `cfg_if` 라는 crate이 도움이 될지도 모르겠습니ㅏㄷ. 한번 확인 부탁드려ㅑ요

2021-07-26 09:56 UTC, jeehoonkang commented on kernel-rs/src/lib.rs
> +#[cfg(target_arch = "riscv64")]
아니면- 지금 cfg로 arch에 따라 분기하는 코드가 많은데 이 분기를 한번만 할 수도 있지 않을까 하는데 혹시 확인/고민 부탁드리겠습니다.

2021-07-26 09:56 UTC, jeehoonkang commented on user/usertests.c
>  #include "kernel/riscv.h"
`kernel/arch.h`로 바꿀 수도 있을까요? 이 안에서 `#if defined`로 분기하구요...

2021-07-28 02:18 UTC, Gabriel4256 commented on kernel-rs/Cargo.toml
> +tock-registers = { version = "0.7.x", default-features = false, features = ["register_types"]}
tock-registers를 사용하는 것은 아니지만 이런 것을 찾았습니다. 필요한 register 관련 기능들은 잘 구현되어 있는 것 같습니다. 일단은 TODO로 남겨놓겠습니다.
https://crates.io/crates/riscv/0.6.0

2021-07-29 01:04 UTC, Gabriel4256 commented on kernel-rs/src/lib.rs
> +#[cfg(target_arch = "riscv64")]
`cfg-if`을 사용해서 한번만 하도록 수정했습니다.

2021-07-29 01:05 UTC, Gabriel4256 commented on kernel-rs/src/arch/arm/addr.rs
> +pub trait Addr: Copy + From<usize> + Add<usize, Output = Self> {
공통된 부분은 빼내고, 다른 부분들만 남겨놓았습니다.

2021-07-29 03:11 UTC, Gabriel4256 commented on user/usertests.c
>  #include "kernel/riscv.h"
반영했습니다.

2021-07-29 06:22 UTC, Gabriel4256 commented on kernel-rs/src/arch/arm/vm.rs
> +    pub unsafe fn init_hart(&self) {
* 좀 더 general한 용어(core)로 대체했습니다.
* arch dependent한 부분들을 분리해서 이것들을 위한 trait들(`PageTableEntry`, `PageInit`, `PteFlags`)을 만들어 해당 부분들을 분리했습니다. common한 부분들은 `src/vm.rs`에, arch dependent한 부분들은 `src/arch/{target_arch}/vm.rs`로 옮겼습니다.
* 분리하는 방식에 대해 고민을 좀 했었는데, 너무 많은 부분을 건드리려다 보니 시간이 너무 오래 걸릴 것 같아, 일단은 이 정도에서 마무리 지었습니다. 혹시 분리 방식에 대해서 좋은 아이디어가 있으면 말씀해주시면 감사하겠습니다.

2021-07-29 06:27 UTC, Gabriel4256 commented on kernel-rs/src/arch/arm/memlayout.rs
> +pub const UART0: usize = 0x09000000;
* memlayout 안에서 arch 상관없이 등장하는 부분들을 모아 하나의 trait (`Memlayout`)으로 만들었습니다. trait 정의는 `src/memlayout.rs`에 있고, `src/arch/{target_arch}/memlayout.rs`에서 trait implementation을 정의합니다. 
* 이것을 외부에서 사용할 때 어떤 방식으로 인터페이스를 제공해야할지에 대한 고민이 있습니다. 지금 방식이 그리 좋은 것 같지는 않지만 이미 너무 많은 시간을 써버려서 일단은 여기서 stop하겠습니다.

2021-07-29 06:58 UTC, Gabriel4256 commented on kernel-rs/src/arch/arm/poweroff.rs
> +pub fn machine_poweroff(_exitcode: u16) -> ! {
아이디어 자체에는 동의합니다. 다만 현재로서는 제가 rv6에서 architecture dependent한 부분들에 대해 정확히 파악이 완료되지 않은 부분들이 많아서 추상화 단위 설정이 쉽지 않습니다. 제가 생각하기에는 조금 장기적으로 architecture dependent한 부분들을 작성하면서 파악이 완료된 부분들에 한해 조금씩 진행하는 것이 나을 것이라고 보는데 어떻게 생각하시나요?

대략적인 process는 일단 파일 단위로 구분된 각 part별로 먼저 추상화 단위를 결정하고 trait을 정의한 뒤, 나중에 그 모든 trait들을 super trait으로 가지는 `trait Arch` 같은 것을 만드는 식으로 진행할 생각입니다.

2021-07-29 12:24 UTC, jeehoonkang requested changes

2021-07-29 12:24 UTC, jeehoonkang commented on kernel-rs/src/addr.rs
>  pub const PGSHIFT: usize = 12;
이건 architecture-dependent한게 아닌가 합니다. 혹시 `src/addr.rs`에 놓은 이유가 있나요? 있다면 주석으로 논의되면 좋겠습니다.

2021-07-29 12:24 UTC, jeehoonkang commented on kernel-rs/src/addr.rs
>  pub const PLNUM: usize = 3;
이건 architecture-dependent한게 아닌가 합니다. 혹시 `src/addr.rs`에 놓은 이유가 있나요? 있다면 주석으로 논의되면 좋겠습니다.

2021-07-29 12:24 UTC, jeehoonkang commented on kernel-rs/src/arch/arm/vm.rs
> +        if f.intersects(AccessFlags::R) {
`let mut ret` 없이 value-oriented로 작성할 수도 있을까요?

2021-07-29 12:24 UTC, jeehoonkang commented on kernel-rs/src/arch/arm/vm.rs
> +pub struct PageInitImpl {}
이런 struct가 있는게 다소 의아합니다. `PageTable`의 method로 들어가야하는 내용인 것 같아서요.

2021-07-29 12:24 UTC, jeehoonkang commented on kernel-rs/src/hal.rs
> +    arch::memlayout::MemLayoutImpl,
`Impl`이 다소 low-level인 것처럼 느껴지는데 다른 이름도 가능할지 궁금합니ㅏㄷ.

2021-07-29 12:24 UTC, jeehoonkang commented on kernel-rs/src/lib.rs
> +        mod arch;
이렇게 하지 말고 `pub use riscv::*;` 이런 식으로도 가능할까요? 그러면 4번 반복해서 mod 정의 안해도 될거 같아서요

2021-07-29 12:24 UTC, jeehoonkang commented on kernel-rs/src/vm.rs
> +        const R = 1 << 0;
숫자가 바뀐 이유가 있나요?

2021-07-29 12:24 UTC, jeehoonkang commented on kernel-rs/src/vm.rs
> +    ) -> Option<&mut PageTableEntryImpl> {
여기도 비슷하게 `PageTableEntry` 라는 타입 이름은 보존할 수 있을지 궁금합니다.

2021-08-17 06:58 UTC, Gabriel4256 commented on kernel-rs/src/vm.rs
> +    ) -> Option<&mut PageTableEntryImpl> {
다음과 같이 변경했습니다.
`PageTableEntry` -> `PageTableEntryDesc ` (trait)
`PageTableImpl` -> `(RiscV | ArmV8)PageTable` (struct)

2021-08-17 07:28 UTC, Gabriel4256 commented on kernel-rs/src/lib.rs
> +        mod arch;
반영했습니다.

2021-08-17 14:33 UTC, Gabriel4256 commented on kernel-rs/src/arch/arm/memlayout.rs
> +pub const UART0: usize = 0x09000000;
공통적으로 나타나는 것들을 `IrqNumbers`, `DeviceMappingInfo` 등의 trait으로 만들어 각 arch의 file에서 구현하도록 했습니다.

2021-08-17 14:35 UTC, Gabriel4256 commented on kernel-rs/src/arch/arm/vm.rs
> +    pub unsafe fn init_hart(&self) {
기존의 `vm.rs`에서 공통되는 부분들은 분리하여 `PageInitiator`, `PageTableEntryDesc` 등의 trait으로 만들어 각 arch에서 구현하도록 했습니다.

2021-08-17 14:35 UTC, Gabriel4256 commented on kernel-rs/src/addr.rs
>  pub const PGSHIFT: usize = 12;
삭제했습니다.

2021-08-17 15:20 UTC, Gabriel4256 commented on kernel-rs/src/arch/arm/vm.rs
> +        if f.intersects(AccessFlags::R) {
반영했습니다.

2021-08-17 15:22 UTC, Gabriel4256 commented on kernel-rs/src/hal.rs
> +    arch::memlayout::MemLayoutImpl,
trait을 `DeviceMappingInfo`와 `IrqNumbers`로 나누고, 이 trait들의 구현체는 `MemLayoutImpl`에서 `Memlayout`으로 수정했습니다.

2021-08-17 15:30 UTC, Gabriel4256 commented on kernel-rs/src/arch/arm/poweroff.rs
> +pub fn machine_poweroff(_exitcode: u16) -> ! {
architecture dependent한 함수들을 모두 하나의 trait에 정의하는 것은 덩어리가 너무 커질 것 같다는 생각이 듭니다. 현재는 기능(파일) 단위로 그런 함수들을 포함하는 trait들을 정의하여 각 architecture에서 구현하도록 하고 있고, 저는 이렇게 하는 것이 모듈화 측면에서 좋다고 생각하는데 의견 주시면 감사하겠습니다.

2021-08-17 15:37 UTC, Gabriel4256 commented on kernel-rs/src/vm.rs
> +        const R = 1 << 0;
원래 버전에서는 riscv의 page table entry flag bit를 나타내는 것이었지만, arm을 지원하는 과정에서 접근 권한을 추상화한 type을 만들 필요가 있었습니다. Arm의 pte flag는 riscv처럼 R,W,X,U를 각각 다른 하나의 bit로 나타내는 것이 아니라 여러 개의 권한을 하나로 나타내거나 bit가 0일 때 권한이 생기는 등 기존 riscV를 사용하던 방식을 그대로 사용하는 것이 어려워 접근 권한을 나타내는 추상화 계층을 만들게 되었습니다.

각 arch의 파일에서는 이 접근 권한을 나타내는 `AccessFlags`를 받아서 그에 대응하는 자신의 pte flag를 만들어 냅니다. (`src/arch/riscv/vm.rs`의 `RiscVPteFlags`, `src/arch/arm/vm.rs`의 `ArmV8PteFlags`)

2021-08-17 15:43 UTC, Gabriel4256 commented on kernel-rs/src/arch/arm/vm.rs
> +pub struct PageInitImpl {}
page table 초기화 시에 arch-dependent한 부분들만을 모아 `PageInitiator` trait으로 만들고, 각 arch에서 이것을 구현하도록 했습니다. (`RiscVPageInit`, `ArmPageInit`)

2021-08-17 15:46 UTC, Gabriel4256 commented on kernel-rs/src/addr.rs
>  pub const PLNUM: usize = 3;
`src/arch/addr.rs`로 옮겼습니다.

2021-08-18 00:10 UTC, jeehoonkang requested changes

2021-08-18 00:10 UTC, jeehoonkang commented on kernel-rs/src/arch/mod.rs
> +cfg_if! {
- 깔끔하게 정리된 것 같습니다!
- 혹시 한가지 더: `trait Arch`를 정의하고 `Armv8, RiscV` 를 만들어서 `Arch`를 impl한 뒤, Kernel이 `A: Arch`에 dependent하게 만들 수도 있을 것 같습니다. 그러면 type system level에서 arch-dependent code를 인식하고 다룰 수 있게 됩니다.

2021-08-18 00:10 UTC, jeehoonkang commented on kernel-rs/src/lib.rs
> +// TODO: remove this
remove 가능?

2021-08-18 00:10 UTC, jeehoonkang commented on kernel-rs/src/page.rs
> +pub fn getpagesize() -> usize {
`PGSIZE를 그냥 pub으로 노출하는 것도 좋을 것 같습니다.

2021-08-18 00:10 UTC, jeehoonkang commented on kernel-rs/src/proc/procs.rs
> +                    havekids = true;
이 로직을 loop 밖에서 하거나, 아니면 loop 밖에 있는 logic을 여기로 옮길 수 있나요? 지금 로직이 분산된 것 같아서요

2021-08-18 00:10 UTC, jeehoonkang commented on kernel-rs/src/proc/procs.rs
> +    pub fn getppid(&mut self, ctx: &mut KernelCtx<'id, '_>) -> Pid {
`get_parent_pid`?

2021-08-18 18:21 UTC, Gabriel4256 commented on kernel-rs/Cargo.toml
> +opt-level = 3
찾아보니 맞네요. 원래대로 복원했습니다.

2021-08-18 18:21 UTC, Gabriel4256 commented on kernel-rs/src/arch/arm/intr/gicv2.rs
> +    fn ptr(&self) -> *const GicDistributorBlock {
반영했습니다.

2021-08-18 18:21 UTC, Gabriel4256 commented on kernel-rs/src/arch/arm/intr/gicv2.rs
> +    fn init(&self) {
명백하게 unsafe인 것 같습니다. 반영했습니다.

2021-08-18 18:21 UTC, Gabriel4256 commented on kernel-rs/src/arch/arm/proc.rs
> +impl UserProcInitiator for ArmV8UserProcInit {
반영했습니다.

2021-08-18 18:21 UTC, Gabriel4256 commented on kernel-rs/src/arch/arm/start.rs
> +fn _puts(s: &str) {
반영했습니다. 그냥 `Uart`에 `fn puts`를 추가해서 사용하도록 했습니다.

2021-08-18 18:21 UTC, Gabriel4256 commented on kernel-rs/src/arch/arm/start.rs
> +pub fn launch_other_cores(kernel_entry: usize) {
반영했습니다.

2021-08-18 18:22 UTC, Gabriel4256 commented on kernel-rs/src/proc/procs.rs
> +                    havekids = true;
반영했습니다. 또한 의미를 좀 더 명확하게 하기 위해 `havekids` -> `found`로 변수명을 변경했습니다.

2021-08-18 18:22 UTC, Gabriel4256 commented on kernel-rs/src/proc/procs.rs
> +    pub fn getppid(&mut self, ctx: &mut KernelCtx<'id, '_>) -> Pid {
반영했습니다.

2021-08-22 18:21 UTC, Gabriel4256 commented on kernel-rs/src/arch/arm/start.rs
> +fn uart_putc(c: u8) {
둘 다 반영했습니다. unsafe block은 trivial case를 제외하고는 제가 작성한 부분들에 대해서는 설명을 추가했습니다.

2021-08-22 18:21 UTC, Gabriel4256 commented on kernel-rs/src/arch/arm/trap.rs
> +    unsafe fn user_trap(mut self, etype: ExceptionTypes) -> ! {
반영하여 구조 수정했습니다.

2021-08-22 18:22 UTC, Gabriel4256 commented on kernel-rs/src/arch/arm/vm.rs
> +pub type PageInit = ArmV8PageInit;
`Arch` trait 만들어서 모두 하나로 합쳤습니다.

2021-08-22 18:29 UTC, Gabriel4256 commented on kernel-rs/src/arch/mod.rs
> +cfg_if! {
* `src/arch/interface`에 각 arch에서 구현해야 하는 trait들을 정의하고 모두 모아 `Arch`로 만든 뒤, 각 arch에서 구현하도록 했습니다.
* Kernel이 `A:Arch`에 dependent하게 만드는 작업
  * `Kernel`은 depend하도록 수정했습니다만, 아래의 subcomponent들도 `Arch`에 의존하도록 만드는 것이 쉽지 않았습니다. `hal()`, `kernel()` 등의 함수로 static variable(`static mut KERNEL`, `static mut HAL`) 을 참조하는 경우에 generic한 부분과 충돌이 생겨서 이 부분을 처리하는 것이 쉽지 않았습니다.
  * 일단은 적은 수정으로 변경이 가능한 부분들은 변경하고, 그렇지 않은 부분들은 기존의 방식처럼 구현체(`TargetArch`)를 import하여 사용하도록 했습니다.

2021-08-22 18:29 UTC, Gabriel4256 commented on kernel-rs/src/arch/arm/timer.rs
> +    fn spin_for<'id, 's>(kernel_ctx: &KernelCtx<'id, 's>, duration: usize) -> Result<(), ()> {
반영했습니다.

2021-08-22 18:30 UTC, Gabriel4256 commented on kernel-rs/src/arch/arm/vm.rs
> +pub struct PageInitImpl {}
구조가 완전히 변경되었습니다.

2021-08-22 19:00 UTC, jeehoonkang requested changes

2021-08-23 03:26 UTC, Gabriel4256 commented on kernel-rs/src/arch/arm/mod.rs
> +    fn cpu_id() -> usize {
현재 Arch는 kernel이 필요로하는 모든것을 다 가지도록 설계했습니다. `src/arch/interface.rs`에 구현해야 하는 모든 trait들(e.g., `MemLayout`, `TimeManager`,...)정의되어있고, `Arch`는 이것들을 super trait으로 가집니다.

2021-08-23 04:29 UTC, Gabriel4256 commented on kernel-rs/src/arch/arm/mod.rs
> +pub type TargetArch = ArmV8;
반영했습니다.

2021-08-23 04:29 UTC, Gabriel4256 commented on kernel-rs/src/arch/arm/mod.rs
> +    type Uart = uart::ArmUart;
반영했습니다.

2021-08-23 04:29 UTC, Gabriel4256 commented on kernel-rs/src/arch/arm/intr/mod.rs
> +use crate::arch::ArmV8;
반영했습니다.

2021-08-23 04:30 UTC, Gabriel4256 commented on kernel-rs/src/arch/arm/start.rs
> +pub unsafe fn start() {
반영했습니다.

2021-08-23 04:30 UTC, Gabriel4256 commented on kernel-rs/src/arch/arm/timer.rs
> +impl ArmV8 {
`Armv8` 밖으로 뺐습니다.

2021-08-23 04:30 UTC, Gabriel4256 commented on kernel-rs/src/arch/arm/vm.rs
> +    pub struct ArmV8PteFlags: usize {
반영했습니다. `riscv`에 대해서도 똑같이 적용했습니다.

2021-08-23 04:30 UTC, Gabriel4256 commented on kernel-rs/src/arch/interface.rs
> +pub trait Arch:
반영했습니다.

2021-08-23 04:30 UTC, Gabriel4256 commented on kernel-rs/src/file.rs
> +    _Write,
select system call이 아직은 read event만 지원해서 그런 것인데, used 되도록 수정했습니다.

2021-08-23 04:30 UTC, Gabriel4256 commented on kernel-rs/src/timer.rs
> +
반영했습니다.

2021-08-23 04:30 UTC, Gabriel4256 commented on kernel-rs/src/arch/interface.rs
> +pub trait PageTableEntryDesc: Default {
일단은 `IPageTableEntry`로 변경했습니다. 더 좋은 이름이 생각나면 변경하겠습니다.

2021-08-23 04:30 UTC, Gabriel4256 commented on kernel-rs/src/arch/interface.rs
> +    fn cpu_id() -> usize;
반영했습니다.

2021-08-23 07:36 UTC, Gabriel4256 commented on kernel-rs/src/arch/arm/uart.rs
> +    pub fn puts(&self, s: &str) {
`arm/start.rs` 파일에서 아래와 같이 Uart 객체를 생성하고 그 객체를 이용하여 `puts` 함수를 호출합니다. 그렇기에 `puts`와 같은 함수들이 `Uart` 안에 존재하는 것이 낫다고 생각했습니다. 
```rust
let uart = Uart::new();
uart.puts("sdfsfsf");
```

물론 외부의 함수로 만드는 것이 가능하기는 하지만 어차피 `Uart` 객체를 인자로 받아야 하기에 내부에 정의하는것이 더 깔끔하다고 생각했는데 어떻게 생각하시나요?

2021-08-23 07:46 UTC, jeehoonkang requested changes

2021-08-23 07:46 UTC, jeehoonkang commented on kernel-rs/src/arch/interface.rs
> +    PageTableManager + MemLayout + TimeManager + TrapManager + InterruptManager + ProcManager + PowerOff
이렇게 나눈 디자인에 대해 한번 리뷰하는게 좋을 것 같습니다. 꼭 이번 PR이 아니어도 될 것 같고 TODO만 남기고 머지해도 좋을 것 같습니다.

- start(), poweroff를 하나로 합치는건 어떨지 제안드립니다. 의미상 가까워 보여서요
- proc, trap, interrupt도 비슷해 보이는데 어떻게 보시나요? 나누는 기준이 명확하게 있을지 궁금합니다. 그리고 그러한 기준이 있다면 문서화되면 좋겠습니다.
- PageTableManager, MemLayout도 의미상 비슷해보이는데 어떻게 보시나요? 명확한 기준 = ?

2021-08-23 07:46 UTC, jeehoonkang commented on kernel-rs/src/arch/mod.rs
> +cfg_if! {
다음 PR에서 다룹시다. TODO로 남겨주세요

2021-08-23 07:46 UTC, jeehoonkang commented on kernel-rs/src/interface.rs
> +pub trait Arch:
`src/arch/interface.rs`와 같은 파일인가요?

2021-08-23 07:47 UTC, jeehoonkang commented on kernel-rs/src/console.rs
> +    fn putc_spin<A: Arch>(&self, c: u8, kernel: Pin<&Kernel<A>>) {
다음 PR에서 다룹시다 TODO comment...

2021-08-23 07:56 UTC, Gabriel4256 commented on kernel-rs/src/interface.rs
> +pub trait Arch:
삭제했습니다.

2021-08-23 07:58 UTC, Gabriel4256 commented on kernel-rs/src/arch/interface.rs
> +    PageTableManager + MemLayout + TimeManager + TrapManager + InterruptManager + ProcManager + PowerOff
작성할 때는 기존 코드의 파일 단위(`vm.rs`, `memlayout.rs`, `trap.rs`, `proc.rs`, `intr.rs`)를 기준으로 하였습니다. 일단 TODO로 남겨놓았습니다.

2021-08-23 08:02 UTC, Gabriel4256 commented on kernel-rs/src/arch/mod.rs
> +cfg_if! {
TODO로 남겨놓았고, 작은 example이 완성되어 공유드립니다.  `Component` 의 `do_something`이 호출될 때 전역 static 변수인 `Kernel`의 reference를 얻어오는 `kernel` 함수를 호출하여 사용하는데, 전역변수의 generic type은 고정되어 있기에 호출 과정에서 type 문제가 발생합니다.
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=b6c41f22f19f37ad054a7ff858d07b96

2021-08-23 08:02 UTC, Gabriel4256 commented on kernel-rs/src/console.rs
> +    fn putc_spin<A: Arch>(&self, c: u8, kernel: Pin<&Kernel<A>>) {
남겨놓았습니다.

2021-08-23 11:53 UTC, Gabriel4256 commented
rustc가 1.56.0-nightly 버전으로 올라감에 따라 빌드 시 발생하는 문제가 있어 issue로 남겨놓았습니다. 그래서 일단 MakeFile에서는 arm 버전 build시 build-specification JSON file이 아니라 target name으로 지정하도록 하여 실행되도록 했습니다.
https://github.com/kaist-cp/rv6/issues/573

2021-08-23 11:58 UTC, jeehoonkang commented
bors r+

2021-08-23 12:04 UTC, merged