add clock-cycle benchmark
kaist-cp/rv6 pull request #578
Opened 2021-08-24 03:51 UTC by Gabriel4256

* #574 해결했습니다.

* 실험에 필요한 기능들을 추가했습니다 (`clock` system call, usertests 코드 약간 수정)
* 실험 시 사용했던 benchmark 코드를 bench.py에 추가했습니다. `--timemode` 옵션에 따라 기존 벤치마크(measuring in wall clock)도 실행이 가능합니다.

* 벤치마크를 돌려본 결과 이전 실험때보다 결과가 많이 안좋아서 원인 파악 중입니다.

Closes #574

2021-08-24 04:44 UTC, jeehoonkang requested changes

2021-08-24 04:44 UTC, jeehoonkang commented on Makefile
> +OPTFLAGS = -O2
`-O3`는 안되나요?

2021-08-24 04:44 UTC, jeehoonkang commented on Makefile
> +ifeq ($(ISBENCH), yes)
Flag 이름이 아래는 `USERTEST`이므로, 여기는 `BENCH`면 어떨까 합니다.

2021-08-24 04:44 UTC, jeehoonkang commented on Makefile
> +# $U/usertests.o: $U/usertests.c
굳이 없어진 이유는?

2021-08-24 04:44 UTC, jeehoonkang commented on lmbench/lib_mem.c
> +	double	baseline = 0.0f, max_par, par = 0.0f;
별건 아니지만 `0.0f`가 아니라 `0.0`이 어떨까 합니다. `0.0f`는 제가 알기로 `float` 타입이어서요. 확인 요청드려요

2021-08-30 06:52 UTC, Gabriel4256 commented on Makefile
> +ifeq ($(ISBENCH), yes)
반영 후 LMBench에서 해당 이름의 macro를 사용하고 있어 같이 수정했습니다.

2021-08-30 06:53 UTC, Gabriel4256 commented on Makefile
> +OPTFLAGS = -O2
이유를 주석으로 추가했습니다.

2021-08-30 06:54 UTC, Gabriel4256 commented on lmbench/lib_mem.c
> +	double	baseline = 0.0f, max_par, par = 0.0f;
반영했습니다.

2021-08-30 06:54 UTC, Gabriel4256 commented on Makefile
> +# $U/usertests.o: $U/usertests.c
usertest 컴파일 시 옵션으로 넘겨주는 macro이름을 LMBench에서 사용하고 있어서 두 파일에 다른 compile rule을 적용하려 했었는데, 더 좋은 방법을 찾아서 없앴습니다.

2021-08-30 06:58 UTC, Gabriel4256 commented
주신 review들 반영하고, 성능 향상을 위해 rustc 버전을 nightly-2021-08-18 -> nightly-2021-06-19로 다시 되돌렸습니다.

2021-08-30 07:42 UTC, merged