Bugfix
kaist-cp/rv6 pull request #580
Opened 2021-09-04 15:58 UTC by Gabriel4256

지금까지 발견한 성능 저하 요인들 중 해결할 수 있는 것들을 해결했습니다. refactoring 과정 중에 생긴 overhead는 모두 해결한 것 같고, 1월 21자 커밋을 기준으로 봤을 때는 https://github.com/kaist-cp/rv6/commit/a975176671c78db223909df0c503543e231e56ab 만 해결하면 될 것 같습니다.

* `printf`: 기능을 줄이고, lightweight하게 동작하도록 수정
* C opt level 변경: C 코드 컴파일 시 optimize하지 않는 것이 더 좋은 성능이 나옵니다. 원인은 모르겠습니다.

이 버전과 xv6, 실험에 사용한 commit, 1월 21일자 commit들을 비교한 데이터입니다. 
https://docs.google.com/spreadsheets/d/1qFx7DbCXJAELuup9i-pWZLrHzqArVGBVBC4wDVjzZJM/edit?usp=sharing

그 외 자잘한 버그들 수정했습니다.

2021-09-05 07:41 UTC, Gabriel4256 commented
추가로 lmbench 실행 스크립트 이름을 `script.c` -> `lmbench.c` 로 변경하고, 실행 방법을 README-rv6에 추가했습니다.

2021-09-06 03:21 UTC, jeehoonkang requested changes
감사합니다!

2021-09-06 03:21 UTC, jeehoonkang commented on README-rv6.md
> +Test=createdelete, Iter=0, ExecCount=10, Mean=16921060c81.6, Standard Deviation=43254490.91422707
"c"?

2021-09-06 04:09 UTC, jeehoonkang commented
bors r+

2021-09-06 04:16 UTC, merged