Lfs initialize
kaist-cp/rv6 pull request #587
Opened 2022-01-13 16:07 UTC by yj-han

- Commit 순서

2022-01-17 06:40 UTC, jeehoonkang requested changes

2022-01-17 06:40 UTC, jeehoonkang commented on kernel-rs/src/fs/lfs/inode.rs
> +pub enum DInodeType {
혹시 ufs랑 공통되는 사안인가요? 만일 그렇다면 합치는게 어떨까 합니다.

2022-01-17 06:40 UTC, jeehoonkang commented on kernel-rs/src/fs/lfs/inode.rs
> +    pub nlink: i16,
아래 애들도 간단히만 주석 남겨주시면 감사하겠습니다.

2022-01-17 06:40 UTC, jeehoonkang commented on kernel-rs/src/fs/lfs/inode.rs
> +/// On-disk inode structure
`cargo doc`으로 예쁘게 나오기 위해서는 아마 아래에 newline을 하나 넣어야할 겁니다.

2022-01-17 06:40 UTC, jeehoonkang commented on kernel-rs/src/fs/lfs/inode.rs
> +struct DirentIter<'id, 's, 't> {
id, s, t의 의미를 주석으로 남겨주실 수 있으실까요?

2022-01-17 06:40 UTC, jeehoonkang commented on kernel-rs/src/fs/lfs/inode.rs
> +// Directories
주석이 inode guard에 대한게 아닌듯 한데 확인 요청드려요. 아니면 좀더 자세히 주석을 남겨주시면 좋을듯 합니다.

2022-01-17 06:40 UTC, jeehoonkang commented on kernel-rs/src/fs/lfs/inode.rs
> +impl Itable<Lfs> {
혹시 ufs와 달라진 부분이 있는지 궁금합다. 만일 나중에 tree로 바꿀 예정이라면 그렇다고 주석으로 남기면 좋을 것 같습니다.

2022-01-19 04:39 UTC, jeehoonkang requested changes

2022-01-19 04:39 UTC, jeehoonkang commented on kernel-rs/src/fs/lfs/inode.rs
> +/// `'id` and `'t` are current lifetime of context that stores information about current thread
둘이 같으면 하나만 있어도 되지 않나요?

2022-01-19 04:40 UTC, yj-han commented on kernel-rs/src/fs/lfs/inode.rs
> +/// `'id` and `'t` are current lifetime of context that stores information about current thread
넵 하나로 합치겠습니다

2022-01-19 04:55 UTC, yj-han commented on kernel-rs/src/fs/lfs/inode.rs
> +/// `'id` and `'t` are current lifetime of context that stores information about current thread
그런데 지금 합치려고 보니까 DirentIter가 사용하는 Dirent가 Lfs, Ufs로 각각 구현되어 있어서 합치려면 코드 수정이 많이 들어갈 것 같습니다. 혹시 다음 PR에서 Dirent, DirentIter 등의 코드를 하나로 합치는 작업을 진행해도 될까요?

2022-01-19 04:57 UTC, jeehoonkang commented on kernel-rs/src/fs/lfs/inode.rs
> +/// `'id` and `'t` are current lifetime of context that stores information about current thread
ㅇㅋ

2022-01-19 05:03 UTC, yj-han commented on kernel-rs/src/fs/lfs/inode.rs
> +/// `'id` and `'t` are current lifetime of context that stores information about current thread
주석 남겼습니다!

2022-01-19 05:05 UTC, jeehoonkang commented
bors r+

2022-01-20 02:14 UTC, yj-han commented
bors r+

2022-01-20 02:20 UTC, jeehoonkang commented
bors retry

2022-01-20 02:21 UTC, jeehoonkang commented
bors r+

2022-01-20 02:31 UTC, jeehoonkang commented
bors r+

2022-01-20 02:39 UTC, merged