Added new code to Itable and set DefaultFs as Lfs
kaist-cp/rv6 pull request #588
Opened 2022-01-25 10:12 UTC by yj-han

2022-01-26 02:40 UTC, jeehoonkang requested changes

2022-01-26 02:40 UTC, jeehoonkang commented on kernel-rs/src/fs/mod.rs
>  pub type DefaultFs = Ufs;
일단 defaultfs는 놔둡시다

2022-01-26 02:40 UTC, jeehoonkang commented on kernel-rs/src/fs/mod.rs
>  pub type DefaultFs = Ufs;
https://docs.rs/cfg-if/latest/cfg_if/

2022-01-26 02:41 UTC, jeehoonkang commented on kernel-rs/src/fs/mod.rs
>  pub type DefaultFs = Ufs;
https://cp-git.kaist.ac.kr/persistent-mem/rdtsc_test

2022-01-26 06:23 UTC, yj-han commented
@jeehoonkang cfg_if 적용하였습니다

2022-01-26 12:12 UTC, jeehoonkang requested changes

2022-01-26 12:12 UTC, jeehoonkang commented on kernel-rs/src/fs/lfs/inode.rs
> +    pub const fn new_itable() -> Self {
`fn new()`는 안되나요?

2022-01-26 12:12 UTC, jeehoonkang commented on kernel-rs/src/fs/lfs/mod.rs
> +    imap: Itable<Lfs>,
Self가 더 어울리는 것 같긴 한데 바꾼 이유가 궁금합니다.

2022-01-26 12:36 UTC, yj-han commented on kernel-rs/src/fs/lfs/mod.rs
> +    imap: Itable<Lfs>,
코드 수정 중 컴파일 에러를 잡는 시도로 바꿔보았던 것인데, 불필요한 코드 변화였었습니다. 수정하겠습니다.

2022-01-26 12:38 UTC, yj-han commented on kernel-rs/src/fs/lfs/inode.rs
> +    pub const fn new_itable() -> Self {
기존 `Itable<Ufs>`와 인터페이스 모양을 맞추기 위해 `fn new_itable()`로 했었습니다. 둘 다 `fn new()`로 고쳐도 상관없어 보여서 수정하겠습니다.

2022-01-27 02:34 UTC, yj-han commented
@jeehoonkang 리뷰 반영하였습니다.

2022-01-27 02:51 UTC, jeehoonkang commented
bors r+

2022-01-27 02:58 UTC, merged