[Closes #471] Use `where` bound to const check at compilation time
kaist-cp/rv6 pull request #592
Opened 2022-02-04 10:31 UTC by travis1829

Partially resolves #471 
https://github.com/kaist-cp/rv6/issues/471#issuecomment-1024471179

기존에 [PR#489](https://github.com/kaist-cp/rv6/pull/489)를 close without merge했던 [이유](https://github.com/kaist-cp/rv6/pull/489#issuecomment-820610286)를 완전히 해결하기는 아직 힘들어보입니다.
다만, 이전보다 훨씬 깔끔하게는 할 수 있을 것 같습니다.

```Rust
pub fn as_uninit_mut<T>(&mut self) -> &mut MaybeUninit<T>
where
	[u8; PGSIZE - mem::size_of::<T>()]:,                // We need mem::size_of::<T>() <= PGSIZE
        [u8; PGSIZE % mem::align_of::<T>() + usize::MAX]:   // We need PGSIZE % mem::align_of::<T> == 0
{
	//...
}
```

[Rust blog](https://blog.rust-lang.org/inside-rust/2021/09/06/Splitting-const-generics.html) 등을 확인해보면, 아직은 위 예처럼 array length부분 등을 이용해 검사를 해보기를 권고하는 것 같습니다.
(추후에 훨찐 직관적인 syntax를 제공하겠다고는 했으나, 아직 안 나온 것 같습니다.)

2022-02-04 10:31 UTC, travis1829 commented
또는 다음과 같이 자동으로 impl되는 trait을 추가해서 해결할수도 있습니다.
ex)
```Rust
pub fn as_uninit_mut<T: FromPage>(&mut self) -> &mut MaybeUninit<T> {
	//...
}

/// This trait is auto-implemented for types that suffice the following.
/// * mem::size_of::<T>() <= PGSIZE
/// * PGSIZE % mem::align_of::<T>() == 0
pub trait FromPage {}
impl<T> FromPage for T
where
	[u8; PGSIZE - mem::size_of::<T>()]:,                // We need mem::size_of::<T>() <= PGSIZE
        [u8; PGSIZE % mem::align_of::<T>() + usize::MAX]:   // We need PGSIZE % mem::align_of::<T> == 0
{}
```

2022-02-08 05:30 UTC, jeehoonkang requested changes

2022-02-08 05:30 UTC, jeehoonkang commented on kernel-rs/src/page.rs
> +        [u8; PGSIZE - mem::size_of::<T>()]: , /* We need mem::size_of::<T>() <= PGSIZE */
/* */ 대신 // 로 해주시겠어요?

2022-02-08 05:30 UTC, jeehoonkang commented on kernel-rs/src/page.rs
> +        [u8; PGSIZE % mem::align_of::<T>() + usize::MAX]: , /* We need PGSIZE % mem::align_of::<T> == 0 */
약간 anti-pattern이 아닌가 생각하긴 합니다 ㅎㅎ 그냥 원래 코드에 비해 어떤 장점이 있을까요?

2022-02-08 09:32 UTC, travis1829 commented on kernel-rs/src/page.rs
> +        [u8; PGSIZE % mem::align_of::<T>() + usize::MAX]: , /* We need PGSIZE % mem::align_of::<T> == 0 */
* `assert`을 compile time check으로 대체한 것 뿐이므로, runtime 비용이 없어진다는 장점 정도만 있는 것 같습니다. (다만, [이걸](https://github.com/kaist-cp/rv6/pull/489#issuecomment-820610286) 참고하면 이미 runtime 비용이 없던 상황일 수도 있습니다.)

일단은 위 expression은 다른곳들([예시](https://hackmd.io/OZG_XiLFRs2Xmw5s39jRzA?view), [Rust blog 예](https://blog.rust-lang.org/inside-rust/2021/09/06/Splitting-const-generics.html#featuregeneric_const_exprs))에서도 사용하는 방법이긴 하지만, 제 생각에도 syntax가 별로인 것 같습니다. 좀 걸리겠지만 차라리 [Rust blog](https://blog.rust-lang.org/inside-rust/2021/09/06/Splitting-const-generics.html#featuregeneric_const_exprs)에서 약속한대로 더 깔끔한 syntax를 정식으로 지원할때까지 기다리는게 나을수도 있을 것 같습니다.

2022-02-08 09:32 UTC, travis1829 commented on kernel-rs/src/page.rs
> +        [u8; PGSIZE % mem::align_of::<T>() + usize::MAX]: , /* We need PGSIZE % mem::align_of::<T> == 0 */
추가 : 61a7a43 에서 `u8`을 `()`로 변경했습니다.

2022-04-21 03:15 UTC, travis1829 commented
아직까지는 `const_evaluatable_checked` 및 `generic_const_exprs` feature가 unstable하므로 버그 등을 일으킬 수 있고 syntax가 깔끔하지 못한 것 같으므로, 이 문제는 추후에 rustc version을 올린 후 revisit하는게 좋을 것 같습니다. 일단은 close합니다.

2022-04-21 03:15 UTC, closed without merging