Implemented Lfs
kaist-cp/rv6 pull request #602
Opened 2022-02-21 22:28 UTC by yj-han

Done
- Dinode
- Inode
- FileSystem

Todo
- fix params, match blockno and segment offset

2022-02-21 22:29 UTC, yj-han commented
@jeehoonkang

2022-02-22 12:52 UTC, jeehoonkang commented on kernel-rs/src/fs/lfs/inode.rs
> +                        dip.minor = minor
`;`를 넣어주면 좋을듯 합니다.

2022-02-22 12:55 UTC, jeehoonkang commented on kernel-rs/src/fs/lfs/mod.rs
> +        panic!("balloc: out of blocks");
마찬가지로 cur_segment를 증가시켜서 다시 search해야할 것 같습니다.

2022-02-22 14:14 UTC, travis1829 commented on kernel-rs/src/fs/lfs/inode.rs
> +        (*dip).addr_indirect = inner.addr_indirect;
[lfs 논문](https://www.google.com/url?sa=t&source=web&rct=j&url=https://web.stanford.edu/~ouster/cgi-bin/papers/lfs.pdf&ved=2ahUKEwimgJ2VvZP2AhWmGKYKHfj7ByIQFnoECEkQAQ&usg=AOvVaw2_BTCofWCj5hAXZCnsuqfK)의 3.1절을 보면, inode의 구조 자체는 lfs와 ufs가 거의 같은 것 같습니다.

2022-02-22 14:40 UTC, travis1829 requested changes
수고 너무 많으십니다. 몇가지 문의사항이 있는데, 해결이 너무 복잡하거나 오래걸릴것 같으면 나중으로 미루셔도 될 것 같습니다.

2022-02-22 14:40 UTC, travis1829 commented on kernel-rs/src/fs/lfs/segment.rs
> +}
block type을 이렇게 정의하면 `Segment`의 크기가 너무 커질 것 같습니다. 제 생각에 `Segment`에 들어가야하는 내용의 경우,
* `Inode`의 in-memory buffer : `Itable`
* `Data`의 in-memory buffer : `Buf` (어차피 데이터를 디스크에서 먼저 읽은 후 써야하므로, Buf에 캐시될 것 같습니다.)

이므로, `Imap`은 `LFS`에 in-memory buffer형태로 저장하게 하면,
실제로 `Segment`에는 segment summary만 저장하게 하고 나중에 segment를 commit할때만 in-memory buffer의 내용을 보고 commit하도록 하면 어떨까 조심히 제안합니다.

참고로 다음 draft pr에서 위 내용을 구현하려고 하고 있습니다.
https://github.com/kaist-cp/rv6/pull/601

2022-02-22 14:40 UTC, travis1829 commented on kernel-rs/src/fs/lfs/mod.rs
> +        panic!("balloc: out of blocks");
죄송하지만 제가 지금 제대로 확인할 수 없는 상황이라 그런데, 이게 disk의 모든 block usage table을 읽은 후 iterate하여 안 쓰는 블럭을 찾는게 맞나요?
* 맞다면, LFS에도 이런 table을 놓는게 맞는지 문의드립니다. 어차피 LFS에 나중에 cleaner를 추가해야하기도 하고, 이런 table이 LFS에는 안 맞는것 같습니다.
* 빈 block을 찾는건, 그냥 current segment의 맨 뒤를 할당해주는걸로 대신할 수 있는게 아닌지 문의드립니다.

2022-02-23 01:00 UTC, travis1829 requested changes

2022-02-23 01:00 UTC, travis1829 commented on kernel-rs/src/fs/lfs/segment.rs
> +    Inode { inner: RcInode<Lfs> },
`RcInode`는 일종의 reference counted smart pointer이므로, 이렇게 되면 inode와 관련한 작업이 모두 끝나더라도 `Segment` 가 `RcInode`를 가지고 있으므로 `Segment`가 이를 drop하기 전까지는 [`FS::inode_finalize`](https://github.com/yj-han/rv6/blob/e37fa8b51f25fbc8d3f1b232ceee6530bc0e9da6/kernel-rs/src/fs/lfs/mod.rs#L525)가 실행되지 못할 것 같습니다. `Inode` (no fields)로 바꾸는 걸 제안드립니다.

2022-02-23 08:42 UTC, reverofx commented on kernel-rs/src/fs/lfs/inode.rs
> +        tx.write(bp, ctx);
I think that the `InodeGuard::update` method, as implemented here, is used to commit one inode update to disk. However, in LFS, shouldn't the updated inode be buffered in the segment buffer first before being flushed to the disk.

2022-02-23 08:48 UTC, reverofx commented on kernel-rs/src/fs/lfs/inode.rs
> +                tx.write(bp, ctx);
Shouldn't this write be buffered in Lfs::segments.

2022-02-23 12:32 UTC, yj-han commented on kernel-rs/src/fs/lfs/inode.rs
> +        let segment = tx.fs.segments[cur_segment as usize];
현재는 dram이 모든 정보를 들고 있는데, 지금 param으로는 (segment 개수 10) * (block 수 200) * (block size 1024) byte = 2.048 MB입니다. segment를 한 개로 바꾸면 달라질 것 같습니다.

2022-02-23 12:32 UTC, yj-han commented on kernel-rs/src/fs/lfs/inode.rs
> +            let mut bp = hal().disk().read(dev, segment.offset, ctx);
아 네넵 for문 밖으로 옮길 수 있습니다.

2022-02-24 01:40 UTC, closed without merging