Implemented LFS: basic structs
kaist-cp/rv6 pull request #603
Opened 2022-02-25 01:04 UTC by yj-han

- Added comments for upcoming updates

2022-02-25 07:03 UTC, jeehoonkang requested changes

2022-02-25 07:03 UTC, jeehoonkang commented on kernel-rs/src/arch/arm/start.rs
> +    // TODO: If device memory is needed for some attribute,
- 이 변화가 이 PR에서 필요한 건가요? cc: @junsooo
- 혹시 concurrent PR에 있던 내용이 여기에 들어온거라면 rebase해서 diff를 깔끔하게 만들어주시면 감사하겠습니다.

2022-02-25 07:03 UTC, jeehoonkang commented on kernel-rs/src/fs/lfs/mod.rs
> +        panic!("balloc: out of blocks");
- 제가 했던 comment들이 없어진 것 같은데 확인해주세요.
- 여기서 segment가 꽉찼다고 하더라도 panic하면 안되고 다른 segment를 찾아서 alloc해야하지 않나요?

2022-02-25 07:08 UTC, yj-han commented on kernel-rs/src/fs/lfs/mod.rs
> +        panic!("balloc: out of blocks");
맞습니다. 코멘트 반영해서 올려놓겠습니다.

2022-02-25 18:47 UTC, jeehoonkang requested changes

2022-02-25 18:47 UTC, jeehoonkang commented on kernel-rs/src/fs/lfs/inode.rs
> +                break;
segment를 다 쓰면 alloc에 실패하는게 아니라 처음부터 다시 돌아가서 gc를 하면서 빈 공간을 찾아야 합니다. 주석으로 남겨주세요.

2022-02-25 18:47 UTC, jeehoonkang commented on kernel-rs/src/fs/lfs/inode.rs
> +        }
break하면 리턴을 아무것도 안하는 건가요? 컴파일이 안될 것 같은데...

2022-02-25 18:47 UTC, jeehoonkang commented on kernel-rs/src/fs/lfs/mod.rs
> +    fn balloc(&self, dev: u32, ctx: &KernelCtx<'_, '_>) -> u32 {
- lfs/inode.rs 에서와 똑같은 코멘트 드립니다.
- logic이 중복되는 것 같은데 통합 가능한가요?

2022-02-25 18:47 UTC, jeehoonkang commented on kernel-rs/src/fs/lfs/superblock.rs
>      /// Checkpoint region
pair의 의미를 주석으로 남기면 좋겠습니다.

2022-02-26 05:49 UTC, jeehoonkang commented
bors r+

2022-02-26 05:55 UTC, merged