[Closes #614] Implement the segment cleaner
kaist-cp/rv6 pull request #627
Opened 2022-06-12 08:02 UTC by travis1829

Closes #614 

* Implemented the segment cleaner
  * Only implemented basic functionality. We may want to choose a better way to select segments and when to run the cleaner.
* Passes all usertests

2022-06-12 16:10 UTC, jeehoonkang requested changes

2022-06-12 16:10 UTC, jeehoonkang commented on kernel-rs/src/fs/lfs/cleaner.rs
> +                0 => false,
혹시 magic number 대신에 constant 정의된걸 쓸 수도 있나요?

2022-06-12 16:10 UTC, jeehoonkang commented on kernel-rs/src/fs/lfs/cleaner.rs
> +                0 => false,
아울러 liveness 체크하는 로직을 함수로 빼면 어떨가 합니다. 그럼 false에 대해 early return을 할 수도 있겠네요.

2022-06-12 16:10 UTC, jeehoonkang commented on kernel-rs/src/fs/lfs/cleaner.rs
> +                0 => (), //empty
역시 마찬가지로 constant 사용하면 더 좋을듯 합니다.

2022-06-12 16:10 UTC, jeehoonkang commented on kernel-rs/src/fs/lfs/cleaner.rs
> +                    // 3. If the segment does not have a lot of live blocks,
이 코멘트를 if 위에 쓰는게 어떨까 합니다. 큰 단락으로 구별된다면 enter 하나 넣으면 좋을 것 같습니다.

2022-06-12 16:10 UTC, jeehoonkang commented on kernel-rs/src/fs/lfs/cleaner.rs
> +            if !is_free {
is_free면 continue라고 쓰면 어떨까 합니다.

2022-06-12 16:10 UTC, jeehoonkang commented on kernel-rs/src/fs/lfs/imap.rs
> +        if let Some((mut buf, addr)) = seg.get_or_add_updated_imap_block(block_no, ctx) {
none인 케이스에 대해 early return으로 하면 더 좋을 것 같습니다.

2022-06-12 16:10 UTC, jeehoonkang commented on kernel-rs/src/fs/lfs/inode.rs
> +        match self.read_addr(bn, ctx) {
`let addr = self.read_addr(bn, ctx).expect("bmap: out of range");` 가 어떨까 합니다.

2022-06-12 16:10 UTC, jeehoonkang commented on kernel-rs/src/fs/mod.rs
> +    /// Called for each FS system call that may cause a disk write..
`..`?

2022-06-13 10:59 UTC, travis1829 commented on kernel-rs/src/fs/lfs/cleaner.rs
> +                0 => false,
clippy가 에러를 내지 않는 선에서 반영하였습니다!

2022-06-13 10:59 UTC, travis1829 commented on kernel-rs/src/fs/lfs/cleaner.rs
> +                0 => (), //empty
마찬가지로 반영했습니다!

2022-06-13 10:59 UTC, travis1829 commented on kernel-rs/src/fs/lfs/imap.rs
> +        if let Some((mut buf, addr)) = seg.get_or_add_updated_imap_block(block_no, ctx) {
`Option::map`을 사용하는 형태로 바꾸었습니다!

2022-06-13 10:59 UTC, travis1829 commented on kernel-rs/src/fs/mod.rs
> +    /// Called for each FS system call that may cause a disk write..
오타 수정하였습니다!

2022-06-13 11:27 UTC, jeehoonkang commented
bors r+

2022-06-13 11:34 UTC, merged